### ISSUE TITLE
PaddleOCR slow download

### ISSUE THREAD

**Issue by raymondlo84** [openvinotoolkit/openvino_notebooks#1000]
@OpenVINO-dev-contest  and @zhuo-yoyowz, do we have alternative download links for them? They are pretty slow and may worth rehosting them maybe on huggingface or similar?

```
rec_model_url = "https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_rec_infer.tar"
rec_model_file_path = Path("model/ch_PP-OCRv3_rec_infer/inference.pdmodel")

run_model_download(rec_model_url, rec_model_file_path)
```

**Comment by raymondlo84** [comment]
> @OpenVINO-dev-contest and @zhuo-yoyowz, do we have alternative download links for them? They are pretty slow and may worth rehosting them maybe on huggingface or similar?

My download speed is about 30kb/s... FYI.

**Comment by raymondlo84** [comment]
Make sense. How do we contribute to that storage.openvinotoolkit.org usually?

**Comment by OpenVINO-dev-contest** [comment]
Another issue is that I dont ensure that Paddle can permit us to distribute their pre-trained models, and I prefer to upload our pytorch models to https://storage.openvinotoolkit.org/.

**Comment by eaidova** [comment]
models uploaded on openvino s3
