### ISSUE TITLE
error for custom yolov8 model conversion ,Trying to create tensor with negative dimension -51: [0, -51] 

### ISSUE THREAD

**Issue by akashAD98** [openvinotoolkit/openvino_notebooks#1004]
i converted model to .onnx using your script ,at the time of teting it on single image im getting this error

<img width="847" alt="image" src="https://user-images.githubusercontent.com/62583018/231381104-5e62b515-aed9-485a-bdaf-29c2a8cb8764.png">

d:\openvino\openvino_env\lib\site-packages\ultralytics\yolo\utils\ops.py in non_max_suppression(prediction, conf_thres, iou_thres, classes, agnostic, multi_label, labels, max_det, nc, max_time_img, max_nms, max_wh)     198      199     t = time.time() --> 200     output = [torch.zeros((0, 6 + nm), device=prediction.device)] * bs     201     for xi, x in enumerate(prediction):  # image index, image inference     202         # Apply constraints  RuntimeError: Trying to create tensor with negative dimension -51: [0, -51]

**Comment by adrianboguszewski** [comment]
This is very strange. Could you ensure you're using the specified version of ultralytics package and openvino-dev?

**Comment by ophirhan** [comment]
https://github.com/ultralytics/ultralytics/issues/191#issuecomment-1449735813

In the postprocess function, change the nc (number of classes) parameter sent to ops.non_max_suppression
to the number of classes you model predicts.
