### ISSUE TITLE
Fail to create the validator when using 230-yolov8-optimization.ipynb

### ISSUE THREAD

**Issue by JialiGithub** [openvinotoolkit/openvino_notebooks#1010]
**Describe the bug**
I have used this notebook to convert a yolov8 model to OpenVINO IR and have successfully test the model on single image. The problem I meet is when I go through the part "Configure Validator helper and create DataLoader ". When I run the code:
`det_validator = det_model.ValidatorClass(args)`

I get error info as below:
AttributeError: 'YOLO' object has no attribute 'ValidatorClass'. See valid attributes below.

    YOLO (You Only Look Once) object detection model.

    Args:
        model (str, Path): Path to the model file to load or create.

    Attributes:
        predictor (Any): The predictor object.
        model (Any): The model object.
        trainer (Any): The trainer object.
        task (str): The type of model task.
        ckpt (Any): The checkpoint object if the model loaded from *.pt file.
        cfg (str): The model configuration if loaded from *.yaml file.
        ckpt_path (str): The checkpoint file path.
        overrides (dict): Overrides for the trainer object.
        metrics (Any): The data for metrics.

    Methods:
        __call__(source=None, stream=False, **kwargs):
            Alias for the predict method.
        _new(cfg:str, verbose:bool=True) -> None:
            Initializes a new model and infers the task type from the model definitions.
        _load(weights:str, task:str='') -> None:
            Initializes a new model and infers the task type from the model head.
        _check_is_pytorch_model() -> None:
            Raises TypeError if the model is not a PyTorch model.
        reset() -> None:
            Resets the model modules.
        info(verbose:bool=False) -> None:
            Logs the model info.
        fuse() -> None:
            Fuses the model for faster inference.
        predict(source=None, stream=False, **kwargs) -> List[ultralytics.yolo.engine.results.Results]:
            Performs prediction using the YOLO model.

    Returns:
        list(ultralytics.yolo.engine.results.Results): The prediction results.
    

**Screenshots**
<img width="766" alt="截屏2023-04-13 下午5 20 37" src="https://user-images.githubusercontent.com/52571399/231714765-a785c763-0084-46b3-9026-aaf1ce51879e.png">

 **Installation instructions (Please mark the checkbox)**
[  ] [I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. ](https://github.com/openvinotoolkit/openvino_notebooks/wiki/Conda)

** Environment information **
Please run `python check_install.py` in the _openvino_notebooks_ directory. If the output is _NOT OK_ for any of the checks, please follow the instructions to fix that. If that does not work, or if you still encounter the issue, please paste the output of check_install.py here.
![image](https://user-images.githubusercontent.com/52571399/231716100-3162d00f-0cbc-4c93-a767-bce9648a51fe.png)

 
**Additional context**

**Comment by yoloyash** [comment]
You're using ultralytics > 8.0.43. That's why this is happening. Ultralytics update their library very often and they have removed the ValidatorClass in the following releases. Try it with ultralytics==8.0.43.

**Comment by yoloyash** [comment]
This is working for the latest ultralytics :D

`det_model = YOLO(path/to/model.pt)
args = trainer.args # input_arguments from cfg or your trainer instance
det_validator = trainer.validator
det_validator.data = check_det_dataset(args.data)
det_data_loader = det_validator.get_dataloader(trainer.data['val'], 1)
det_validator.names = det_model.model.names
det_validator.metrics.names = det_validator.names
det_validator.nc = det_model.model.model[-1].nc
quantization_dataset = nncf.Dataset(det_data_loader, transform_fn)`

**Comment by blaz-r** [comment]
@yoloyash thanks for this. @adrianboguszewski @eaidova do you think in this case that ultralytics version should be explicitly set to the one working or should the notebook be adjusted?

**Comment by JialiGithub** [comment]
@yoloyash Thank you for your reply~

**Comment by JialiGithub** [comment]
@yoloyash Thank you for your reply~ I've used the code below to train the model. It would be fairly helpful if you could let me know which class you've used to create the trainer instance that works for the validator case.  
![image](https://user-images.githubusercontent.com/52571399/232369824-f388c9a2-4261-4f5f-8859-8989a17ec59d.png)

**Comment by JialiGithub** [comment]
> 

The branch ultralytics==8.0.43 seems have been removed...
![image](https://user-images.githubusercontent.com/52571399/232370313-e401b66a-f7ea-4215-bd99-df38b4bd0959.png)

**Comment by JialiGithub** [comment]
@yoloyash The branch ultralytics==8.0.43 seems have been removed...
![image](https://user-images.githubusercontent.com/52571399/232370498-7fb2c2db-af66-477b-970f-8c7b28ac3da8.png)

**Comment by adrianboguszewski** [comment]
@blaz-r, The ultralytics version is explicitly listed in the notebook:
![image](https://user-images.githubusercontent.com/4547501/232804334-eda3590b-d841-4072-84d8-10a350e4c3d1.png)

@JialiGithub, in the default repository, 8.0.43 is available as well as other versions. I can see you're using some other pypi repo and this is probably why it doesn't work for you.
![image](https://user-images.githubusercontent.com/4547501/232804635-c4b9c17d-f03e-4bb8-900f-043e89103356.png)

**Comment by JialiGithub** [comment]
@adrianboguszewski I tried to install 8.0.43 using the terminal then it works. After this, the validator can be created normally.  Thanks for your reply.
