### ISSUE TITLE
【PaddlePaddle Hackathon 4】RFC of Task 205 Fighting Recognition Based on PaddleDetection

### ISSUE THREAD

**Issue by sususama** [openvinotoolkit/openvino_notebooks#1016]
# RFC of PaddlePaddle Hackathon 4 Task 205
## Solution name:
Fighting Recognition Based on PaddleDetection
## Description:
Train a fight recognition model based on the PaddleVideo video development kit, and then integrate the trained model into the PP Human of PaddleDetection. Use the pre trained PP-Human model for inference on the OpenVINO platform to detect fights in the video.
## Workflow:
![1681958661343](https://user-images.githubusercontent.com/52159774/233244915-ad9590a5-7605-4b11-b5bd-a4b43ec65978.png)
## Models:
PP-Human, PaddleVideo
## Results visualizing:
![72](https://user-images.githubusercontent.com/52159774/233242322-5af81030-945c-46d3-be16-34ba22299c28.gif)
## Project TimeLine:
4/18 Submitting RFC
4/22 Creating PR
5/7 Merging PR
## My experience in ML and DL
#950 is my PR

**Comment by OpenVINO-dev-contest** [comment]
@sususama thanks for your proposals, but seems the video is lost, could you add more description on this use case ?

**Comment by sususama** [comment]
> @sususama thanks for your proposals, but seems the video is lost, could you add more description on this use case ?

I converted it to gif format
![72](https://user-images.githubusercontent.com/52159774/233242322-5af81030-945c-46d3-be16-34ba22299c28.gif)

**Comment by OpenVINO-dev-contest** [comment]
Meanwhile the workflow is still not clear for me. Since paddledetection is like a toolbox including many kinds of models, could you identify more on which models you will implement and how to connect them together ?

**Comment by sususama** [comment]
> Meanwhile the workflow is still not clear for me. Since paddledetection is like a toolbox including many kinds of models, could you identify more on which models you will implement and how to connect them together ?

I updated the Description and Workflow.

>## Description:
>Train a fight recognition model based on the PaddleVideo video development kit, and then integrate the trained model into the PP Human of PaddleDetection. Use the pre trained PP-Human model for inference on the OpenVINO platform to detect fights in the video.
>## Workflow:
>![1681958661343](https://user-images.githubusercontent.com/52159774/233244915-ad9590a5-7605-4b11-b5bd-a4b43ec65978.png)

**Comment by sususama** [comment]
Hi @OpenVINO-dev-contest, there is a paragraph in the description of the activity:

> In the second stage, we will select 2 excellent solutions from the results submitted in the first stage, and invite corresponding developers to submit PR based on their own solutions.


When will the results of the two proposals selected in the second stage be announced?

**Comment by OpenVINO-dev-contest** [comment]
Hi Actually the deadline of RFC submission is  4/15, but we still can accept some impressive notebook demo.
From my perspective, I prefer to an industrial solution for all anomalous behavior detection including fighting, smoking, telephone call, and fall in a alert zone.

**Comment by sususama** [comment]
I'm quoting an explanation from PaddleVideo's GitHub homepage here:
> PaddleVideo is a toolset for video recognition, action localization, and spatio temporal action detection tasks prepared for the industry and academia. This repository provides examples and best practice guildelines for exploring deep learning algorithm in the scene of video area. 

> From my perspective, I prefer to an industrial solution for all anomalous behavior detection including fighting, smoking, telephone call, and fall in a alert zone, or a template where user can switch their model to detect a different anomalous behavior.

That is to say, I can train several models for different application scenarios, choose according to the needs of users, and even implement it in code: I only need to enter the type of my own requirements, and then select the corresponding model.

**Comment by OpenVINO-dev-contest** [comment]
hi @sususama The pipeline is still unclear for me. I think you should add more detailed description on this flow chart. for example, PP-Human, PaddleVideo are the name of toolkit. and it includes more function and models. I don't know which modules from these toolkits will be implemented in this notebook, and how do you integrate them with your pipeline.
