### ISSUE TITLE
[Hackaton] AI painting project - Paint by Example: Exemplar-based Image Editing with Diffusion Models

### ISSUE THREAD

**Issue by AnishaUdayakumar** [openvinotoolkit/openvino_notebooks#1020]
## Task description
The AI painting project aims to provide an interactive tool for users to create photo-realistic images based on an exemplar image sketch semantic using OpenVINO. The project will involve leveraging the "Paint by example" exemplar-based model, which is a deep learning model that has shown promising results for creating high-quality images. In this task, contributors will explore how deep learning can be used to create an interactive python notebook for image semantic translation. The notebook should utilize [Paint by Example](https://github.com/Fantasy-Studio/Paint-by-Example), exemplar-based image editing approach using diffusion models that can be considered for this task.

As a result, we expect to see the demo where users can draw  sketch using interactive canvas and get a realistic photo based on provided semantic drawings. Similar to images below:

For exemplar painting
![Screenshot from 2023-04-17 09-12-03](https://user-images.githubusercontent.com/29454499/232384367-334d4018-3bec-4214-a7c0-dda9c74b2dbb.png)

### OpenVINO notebooks
A collection of ready-to-run Jupyter notebooks for learning and experimenting with the [OpenVINO™ Toolkit](https://docs.openvino.ai/latest/home.html). The notebooks provide an introduction to OpenVINO basics and teach developers how to leverage our API for optimized deep learning inference.

### Paint by Example
Paint by Example is diffusion-based pipeline for an image-to-image generation. It takes a masked object from one image and embeds it into a reference image. More details about the approach can be found in the [paper](https://arxiv.org/abs/2211.13227) and original [repo]()

## Desired solution
The result of the contribution will be an interactive python notebook that utilizes Deep Learning models, OpenVINO and an interactive user interface for painting. The contribution should follow openvino_notebooks [contribution guide](https://github.com/openvinotoolkit/openvino_notebooks/blob/main/CONTRIBUTING.md).
In this demonstration, the user should provide a reference image and semantic (or source image with mask) for exemplar painting.
As a possible solution for obtaining drawing capabilities for the notebook following solutions can be suggested:

* I[pycanvas](https://ipycanvas.readthedocs.io/en/latest/) is the library with widgets for drawing in Jupyter notebooks
* [gradio](https://gradio.app/docs/) - easy-to-use building blocks for the creation of a web-based GUI / demo around a machine learning model (or any Python function) in a few lines of code, for example, see sketch recognition [tutorial](https://gradio.app/building-a-pictionary-app/)

**Comment by AnishaUdayakumar** [comment]
> 

Thanks for pointing that out. Please note that this issue has been created to assist participants who are part of an internal hackathon.

**Comment by eleemhui** [comment]
Intel(R) Open Source Software Hackathon 2023
AI-Photo_Team1 is working on this issue.
