### ISSUE TITLE
Can not reproduce the result of controlnet 

### ISSUE THREAD

**Issue by Ht-zhang-xianyu** [openvinotoolkit/openvino_notebooks#1035]
**Describe the bug**
The running result of controlnet notebook is mismatch with the given guide even with same random seed 

 **Expected behavior**
Following the guide to implement the controlnet  inference pipeline , bug got the different picture, and the pose can not fit the given  pose picture

** Environment information **
The result of running "python  check_install.py"
➜  openvino_notebooks python check_install.py
System information:
Python executable: /opt/conda/bin/python
Pip version: 21.2.2
OpenVINO source: /opt/conda/lib/python3.7/site-packages/openvino
OpenVINO IE version: 2022.3.0-9052-9752fafe8eb-releases/2022/3
OpenVINO environment activated: NOT OK
Jupyter kernel installed for openvino_env: NOT OK
Python version: 3.7 OK
OpenVINO pip package installed: OK
OpenVINO import succeeds: OK
OpenVINO development tools installed: OK
OpenVINO not installed globally: OK
No broken requirements: OK
 
**Additional context**

**Comment by raymondlo84** [comment]
Can you please post a few example photo, and how you execute the work?

**Comment by hbalasu1** [comment]
Hi @Ht-zhang-xianyu 
Thank you for contacting us. Could you provide us with some instructions on how you obtained these results? 
When you perform python check_install.py, do you do it in the JupyterNotebook? 

Hope to hear from you soon.

**Comment by Ht-zhang-xianyu** [comment]
Sorry, the mismatch was caused by the different env setting.
So, the picture generated by controlnet can now fit the pose extracted by openpose model.
This issue has been resolved and can currently be closed
