### ISSUE TITLE
cannot import name 'load_image' from 'notebook_utils'

### ISSUE THREAD

**Issue by KTOTO9567578347** [openvinotoolkit/openvino_notebooks#1084]

**Comment by brmarkus** [comment]
Can you provide more details, please? Which notebook/example/demo are you referring to?
Which environment are you running the notebooks (MS-Win, Linux, virt-env, which versions, how installed)?

**Comment by avitial** [comment]
@KTOTO9567578347 do you have any updates for us? Please help provide the requested info.

**Comment by eaidova** [comment]
@KTOTO9567578347  notebooks_utils in our case is not pypi package, it is [module](https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/utils) inside repository. Probably, it should be added in your pythonpath using sys.path.append before import.

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and provide additional information or ask any questions related to this topic.
