### ISSUE TITLE
237-segment-anything: sam_mask_predictor fails to compile on iGPU

### ISSUE THREAD

**Issue by arisha07** [openvinotoolkit/openvino_notebooks#1097]
**Describe the bug**
sam_mask_predictor fails to compile on GPU device:
ov_predictor = core.compile_model(ov_model,"GPU")

Error output:
RuntimeError: get_shape was called on a descriptor::Tensor with dynamic shape

 **Expected behavior**
sam_mask_predictor.xml should compile and load successfully on GPU

**Screenshots**

 **Installation instructions (Please mark the checkbox)**
 -  [x]  I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
Please run `python check_install.py` in the _openvino_notebooks_ directory. If the output is _NOT OK_ for any of the checks, please follow the instructions to fix that. If that does not work, or if you still encounter the issue, please paste the output of check_install.py here.
 
**Additional context**

**Comment by eaidova** [comment]
@arisha07 which openvino version do you use?

SAM predictor model requires dynamic input shape (to be able run model with different input formats), so as dynamic shapes support on GPU is experimental feature, firstly introduced in 2023.0 release on limited scope of models, it is possible that it can not work on GPU with dynamic shapes

**Comment by arisha07** [comment]
We are using 2022.3.0 (same as the notebooks)

Thanks for the information.
