### ISSUE TITLE
where is 220-yolov5-accuracy-check-and-quantization?

### ISSUE THREAD

**Issue by Dimitri666** [openvinotoolkit/openvino_notebooks#1098]
why i can not find [220-yolov5-accuracy-check-and-quantization] in openvino_notebooks now? i want to quantize yolov5 model and improve the inference performence on cpu and gpu

**Comment by eaidova** [comment]
@Dimitri666 please check https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/111-yolov5-quantization-migration

**Comment by Dimitri666** [comment]
thanks! i have tried this in GPU by changing device to gpu in config dict, but it does not work. bug is as follow:

``
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

SystemError: <built-in function __import__> returned a result with an error set
Run the POT. This will take few minutes...
Scanning '/home/sstc-big/bsk/pidnetyolodata/labels/test.cache' images and labels... 6 found, 0 missing, 0 empty, 0 corrupt: 100%|████████████████████████████████████████████████████████████████████████| 6/6 [00:00<?, ?it/s]
INFO:openvino.tools.pot.pipeline.pipeline:Evaluation of generated model
Traceback (most recent call last):
  File "quant_openvino.py", line 285, in <module>
    metric_results_fp32 = pipeline.evaluate(model)
  File "/home/sstc-big/.conda/envs/yolov5/lib/python3.8/site-packages/openvino/tools/pot/pipeline/pipeline.py", line 77, in evaluate
    metrics, _ = self._engine.predict(print_progress=logger.progress_bar_disabled)
  File "/home/sstc-big/.conda/envs/yolov5/lib/python3.8/site-packages/openvino/tools/pot/engines/ie_engine.py", line 119, in predict
    self._predict(stats_layout=stats_layout,
  File "/home/sstc-big/.conda/envs/yolov5/lib/python3.8/site-packages/openvino/tools/pot/engines/ie_engine.py", line 174, in _predict
    self._process_dataset_async(stats_layout=stats_layout,
  File "/home/sstc-big/.conda/envs/yolov5/lib/python3.8/site-packages/openvino/tools/pot/engines/ie_engine.py", line 338, in _process_dataset_async
    compiled_model = self._ie.compile_model(model=self._model, device_name=self._device)
  File "/home/sstc-big/.conda/envs/yolov5/lib/python3.8/site-packages/openvino/runtime/ie_api.py", line 266, in compile_model
    super().compile_model(model, device_name, {} if config is None else config)
RuntimeError: Failed to create plugin /home/sstc-big/.conda/envs/yolov5/lib/python3.8/site-packages/openvino/libs/libopenvino_intel_gpu_plugin.so for device GPU
Please, check your environment
[CLDNN ERROR]. No GPU device was found. 
``

Is openvino only support intel gpu but don't support nvidia gpu?

**Comment by eaidova** [comment]
@Dimitri666 probably it is environment issue, please make sure that drivers for GPU properly installed

**Comment by avitial** [comment]
@Dimitri666 seems like you want to run on an NVIDIA GPU. You may need to build from source in order to enable deep neural networks inference on NVIDIA GPUs using OpenVINO API. Please refer to [nvidia_plugin](https://github.com/openvinotoolkit/openvino_contrib/tree/master/modules/nvidia_plugin ) for more info.

If you want to use Intel iGPU/dGPU, ensure the drivers are properly installed. Refer to [configurations for GPU](https://docs.openvino.ai/2022.3/openvino_docs_install_guides_configurations_for_intel_gpu.html).

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen to ask additional questions related to this topic.
