### ISSUE TITLE
can convert model in format openvino to other format like onnx, tflite?

### ISSUE THREAD

**Issue by Dimitri666** [openvinotoolkit/openvino_notebooks#1105]
I have tried [220-yolov5-accuracy-check-and-quantization] in this project. For quantizing yolov5, it convert the model to IR and test the quantized model in openvino format, but i want test the quantized model in other format, it is possible?

**Comment by avitial** [comment]
@Dimitri666 I don't think it is possible to export a quantized model (or non-quantized) in OpenVINO format to another format like ONNX.

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen to ask additional questions related to this topic.
