### ISSUE TITLE
[shared memory]how to implement shared memory in openvino infer code

### ISSUE THREAD

**Issue by lucy3589** [openvinotoolkit/openvino_notebooks#1137]
Shared memory is used in this example, showing that shared memory reduces inference time.

But I don't know how to implement the code for shared memory. How to apply in practical reasoning scenarios

CPU:AMD Ryzen 7 3700X 8-Core Processor

i use shared_memory, but infer time as same as not use shared_memory

![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/33214551/b33e7fff-4932-4697-8c95-279b0f1b0a68)

**Comment by lucy3589** [comment]
109-latent-tricks-with-output display will speed up

But my test results don't feel accelerated

my model is yolov8n-seg. Your acceleration document gives yolov5n, which has fewer parameters than yolov8n-seg

![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/33214551/764c15b2-5016-4412-9d05-7c10a317910e)

**Comment by eaidova** [comment]
@lucy3589 which openvino version do you use?

shapred_memory=True optimization enabled by default in openvino 2023.0, it the reason why result is the same

**Comment by lucy3589** [comment]
> @lucy3589 which openvino version do you use?
> 
> shapred_memory=True optimization enabled by default in openvino 2023.0, it the reason why result is the same

I use openvino==2023.0.  
```
c_input_image = np.ascontiguousarray(input_image, dtype=np.float32)
input_tensor = ov.Tensor(c_input_image, shared_memory=True)
```
or

**Comment by lucy3589** [comment]
or run this code, infer time is same.  shared_memory=False or shared_memory=True
```
input_image = np.expand_dims(np.transpose(normalized_image, (2, 0, 1)), 0)
# Get input and output layers.
output_layer_ir = compiled_model_ir.output(0)
t1 = time.perf_counter()
res_ir = compiled_model_ir(input_image,shared_memory=False)[output_layer_ir][0]
```

**Comment by lucy3589** [comment]
i use CPU:Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
shared_memory is true or false.  infer time is Almost the same

**Comment by adrianboguszewski** [comment]
@jiwaszki, could you look at the above?

**Comment by avitial** [comment]
Ref. 114091

**Comment by avitial** [comment]
@lucy3589 as mentioned previously, _shared_memory_ is enabled by default in OpenVINO v2023.0. This _shared_memory_ option mode is not a magic thing, as you can see in example below, it works great for large copies (i.e. 8k x 2k x 16) 2.39 us vs 75.8 ms, however as inputs are smaller (i.e. 1280 x 1280 x 3) the difference is not so visible (2.4 us vs 262 us). It will pile up eventually in thousands of inference calls for sure, however on single inference call (average) you might not notice it. Hope this helps address your question. 


![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/20826577/6b9e669f-eb6e-46d8-b451-d432e9ccba5f)

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.
