### ISSUE TITLE
OpenVINO notebook 240-dolly-2-instruction-following (Arc 380 doesn't work)

### ISSUE THREAD

**Issue by JKLEE1015** [openvinotoolkit/openvino_notebooks#1156]
**Describe the bug**
OpenVINO notebook 240-dolly-2-instruction-following (Arc 380 doesn't work)

 **Expected behavior**
Shoud be run normal like CPU & iGPU(GPU.0) as shown in picture
![批注 2023-06-27 071712](https://github.com/openvinotoolkit/openvino_notebooks/assets/84305163/9ddc2677-084b-4def-aaac-b070ba0b72b3)

**Screenshots**
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/84305163/abb522a7-b10b-4b96-b6f1-51d42dd5939d)

 **Installation instructions (Please mark the checkbox)**
[  ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
Directly run on Jupyter notebook
CPU: i5-11400 
dGPU: A380 
 
**Additional context**

**Comment by JKLEE1015** [comment]
I saw three devices are recognized. But the issue remains.
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/84305163/e3f52408-c63e-4eb3-a56c-a963f90aad05)

**Comment by avitial** [comment]
@JKLEE1015  it seems the device is being recognized, are you able to run inference outside of this notebook on your discrete GPU with _benchmark_app_ and any model? For example:
```
$ omz_downloader --name face-detection-0200 --precision FP32
$ benchmark_app -m intel/face-detection-0200/FP32/face-detection-0200.xml -d GPU.1 -t 5
```

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. If the issue persists, feel free to reopen and provide additional information or ask any questions related to this topic.
