### ISSUE TITLE
CausalLM inference (240) on GPU extremely slow

### ISSUE THREAD

**Issue by Vipitis** [openvinotoolkit/openvino_notebooks#1157]
**Describe the bug**
Hey, I rose this issue in the Optimum-intel repo a while ago but it lead nowhere. Now I finally have numbers to backup my claim. 
Running the notebook 240 (Dolly-2-insctruction-following) on GPU is a lot slower than CPU. After running all cells and choosing the first example, I do get around 4 tokens/sec with my i5 6600K CPU which is fairly old. 
If I switch to GPU the generation speed slows down to 0.6 tokens/s. My GPU is an Intel A750 LE.
Is this expect behavior? I do got great performance for GPU inference on other notebooks like 236

 **Expected behavior**
CPU inference performance
![CPU inference](https://github.com/openvinotoolkit/openvino_notebooks/assets/23384483/6496f253-1871-4c78-8f80-a1b282edb2f4)
I expect GPU inference performance to be substantially faster

**Screenshots**
Showing GPU inference performance
![GPU inference](https://github.com/openvinotoolkit/openvino_notebooks/assets/23384483/5f7bdbcc-13aa-4641-87cb-4fc07d43aa0a)

 **Installation instructions (Please mark the checkbox)**
[x] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
Please run `python check_install.py` in the _openvino_notebooks_ directory. If the output is _NOT OK_ for any of the checks, please follow the instructions to fix that. If that does not work, or if you still encounter the issue, please paste the output of check_install.py here.

I am not using a venv, simply cloning the repo and running the notebook inside VSCode. Python 3.9.4 with openvino prerelase 2023.1.0.dev20230623(the notebooks downgrades me back to 2023.0.0) and optimum-intel 1.9.2 (the notebook gives me the 1.9.1.0.dev source version which should include all of 1.9.2).
My GPU driver is 4502 (I can try the 4514 beta if that makes any difference) and my iGPU is either broken, or disabled in BIOS. It does not show up `core.available_devices`
 
**Additional context**
I believe this might be related to caching every single input shape - which seems to require a lot of CPU. My CPU is always at 100% in task manager during GPU inference.

**Comment by Vipitis** [comment]
I would like to substantiate my caching hypothesis by sharing a screenshot where I run GPU inference multiple times and it got to 2.6 token/s on the 2nd time and didn't significantly improve afterwards.

![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/23384483/7bedae12-229e-4dec-b804-e7f8a7db00fd)

however the decoded text now seems gibberish, not sure if that is an issue with the gradio space, the helper functions or the decoder classes. It does look somewhat similar to tokens being incorrectly decoded due to missing ov_config kwargs as shared here https://github.com/huggingface/optimum-intel/pull/168#issuecomment-1508404608

**Comment by Wan-Intel** [comment]
Thanks for highlighting this matter. I'll try to run this notebook from my end and update you at the earliest.

**Comment by Vipitis** [comment]
I tried to run this again with the new releases of `optimum 1.9.0` and `optimum-intel 1.9.3` the latter didn't matter as the notebook uses the source from main which already included the PR that improves decoder performance. 
But it did change something for me, since the Jupyter Kernel crashed when I just ran all cells. It did download, export and compile the model. One fact that you might want to include in the notebook could be the storage requirement. 
This 2.3B model is 5.7GB on huggingface, but the exported onnx model is 10.2GB and the cached model is 10.2GB as well. Meaning you end up with 27GB of storage required just to run this notebook alone. (also why are the export files twice the size?)

I really hope you can either recreate this issues or produce some expected numbers for GPU inference.

**Comment by Wan-Intel** [comment]
I also encountered Jupyter Kernel crashing when just running all the cells in the notebook. 

![Windows_terminal_Failed](https://github.com/openvinotoolkit/openvino_notebooks/assets/123156917/941ee6a9-b101-4b52-91d0-22dcea804a2e)

![linux_jupyter_Failed_2](https://github.com/openvinotoolkit/openvino_notebooks/assets/123156917/49c09628-93c2-4d2c-be18-a5e6fa0c35f0)

![linux_terminal_Failed](https://github.com/openvinotoolkit/openvino_notebooks/assets/123156917/4ee274a3-3e23-4176-a6f7-4ceb3c90197e)


I will highlight the issues including the storage requirement with the relevant team and update here soon.

**Comment by hbalasu1** [comment]
Ref 114792

**Comment by Vipitis** [comment]
little update from my end, I tried to run thise notebook on my laptop today and installed the requirements with --upgrade as of today. It did work but was really slow. the first cell took 36 minutes to download, convert and compile the model.

inference on CPU was about 1.48 tokens/s (i7 1165G7) and then switching to GPU 0 (iGPU) took another 5 minutes of compiling and then the generation run at 0.2 token/s. I tried GPU 1 as well (nvidia T500 mobile, 4GB) but that errored out - I assume due to OOM. 

I did not run into any kernel crash or garbage output today. Getting garbage output happend to me earlier this week when running a defualt transformers pipeline (non OV) and forgot to add `trust_remote_code=True`. It doesn't seem to give an error message with the current transformers version (4.30.2). I checked the model card and they only mentioned that this was needed for loading the model checkpoint as pipeline - which the notebook script doesn't do. While looking at the model card I spotted https://huggingface.co/katuni4ka/dolly-v2-3b-ov already hosting a converted model. I will try that tomorrow when I am back home with my A750.

**Comment by hbalasu1** [comment]
Hi @Vipitis 
Since the issue is resolved, can we close this case?

**Comment by Vipitis** [comment]
> Hi @Vipitis Since the issue is resolved, can we close this case?

Yes, you can close this issue. However, I don't believe this is solved. I was told that various 2023.1 prereleses will improve language model inference on GPU but so far that hasn't been the case. There will be another prerelease in September which might do it. 
If you could produce your own inference performance numbers such as tokens/second on various GPU devices - we could rule out issues on my end. 

Given that the LLM chat notebook isn't merged still should also be an indication of such issues. 

But to be fair, I have also given up on using openVINO on large models, the system memory requirements are unsustainable to convert models of 7B or even 15B without renting a large server. Ipex now released for native windows and works nearly out of the box, it provides a much better inference experience and I will go that route for my research project.

**Comment by andrei-kochin** [comment]
@Vipitis First of all thank you for sharing your thoughts.

It's sad to hear you giving up with OpenVINO before actually 23.1 is released with all improvements made for LLM including recent ones.

I really encourage you to try this now by building from source or wait till September 23.1 release and get back with the feedback. Hope to hear from you again!

**Comment by yeonbok** [comment]
@Vipitis  We expect improvement on GPU performance with upcoming 23.1 OV release  + optimum (>= 1.10.2). (Will need update for both of them.) Or as @andrei-kochin  mentioned, you can try with them with building from sources, before they are available from the package.
