### ISSUE TITLE
OpenVINO release notebook docker image rpm link fails

### ISSUE THREAD

**Issue by vbedida79** [openvinotoolkit/openvino_notebooks#1161]
**Describe the bug**
We use [OpenVINO certified operator](https://github.com/openvinotoolkit/operator) on OpenShift 4.12. After creating the Notebook Custom Resource the subsequent build fails. The build uses [notebook docker ](https://github.com/openvinotoolkit/openvino_notebooks/blob/main/Dockerfile)image. It fails at clinfo rpm install- as this link is forbidden `https://download-ib01.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/c/clinfo-3.0.21.02.21-4.el8.x86_64.rpm`. Logs below:

`curl: (22) The requested URL returned error: 403 Forbidden
error: skipping https://download-ib01.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/c/clinfo-3.0.21.02.21-4.el8.x86_64.rpm - transfer failed
Retrieving https://download-ib01.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/c/clinfo-3.0.21.02.21-4.el8.x86_64.rpm
error: build error: error building at STEP "RUN rpm -ivh https://vault.centos.org/centos/8/AppStream/x86_64/os/Packages/mesa-filesystem-21.1.5-1.el8.x86_64.rpm && dnf install --refresh -y intel-opencl-22.28.23726.1-i419.el8.x86_64 intel-media intel-mediasdk libmfxgen1 libvpl2 level-zero intel-level-zero-gpu intel-metrics-library intel-igc-core intel-igc-cm libva libva-utils intel-gmmlib && rpm -ivh http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/Packages/ocl-icd-2.2.12-1.el8.x86_64.rpm && rpm -ivh https://download-ib01.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/c/clinfo-3.0.21.02.21-4.el8.x86_64.rpm": error while running runtime: exit status 1`

 **Expected behavior**
The clinfo link is updated. The build is successful and OpenVINO notebooks can be used on OCP. 
**Screenshots**

 **Installation instructions (Please mark the checkbox)**
[  ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

**Environment information**
OpenShift 4.12.6. We create the OpenVINO notebook Custom resource from the operator according to the [readme](https://github.com/openvinotoolkit/operator/blob/main/docs/notebook_in_rhods.md)  .

Please run `python check_install.py` in the _openvino_notebooks_ directory. If the output is _NOT OK_ for any of the checks, please follow the instructions to fix that. If that does not work, or if you still encounter the issue, please paste the output of check_install.py here.
 
**Additional context**
Submitted a PR https://github.com/openvinotoolkit/openvino_notebooks/pull/1160. 
Please take a look, if this could help fix the issue
Thanks!

**Comment by eaidova** [comment]
@vbedida79 thank you, I think this issue resolved now?

**Comment by vbedida79** [comment]
Yes thanks. closing this issue
