### ISSUE TITLE
notebook_utils.py is not downloading in 230-yolov8-optimization

### ISSUE THREAD

**Issue by RohanSardar** [openvinotoolkit/openvino_notebooks#1169]
I have been trying since last few days but this problem is not solving. I have tried through Windows 11, Anaconda, Miniconda, Ubuntu and even WSL but none worked. I have a good 5G internet with speed ranging from 200Mbps to 650Mbps.
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/77870108/d600decc-8eb2-498d-99de-26f470771c89)
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/77870108/fe5b07ac-019d-45b1-826f-7e2786c7be92)
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/77870108/13abeeef-90cc-4314-90af-0e8320954047)
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/77870108/444dbff6-7351-4126-a95b-2e44ee9c4d4d)

**Comment by igor-davidyuk** [comment]
Thanks for reporting this! Just to make sure, do you have any kind of proxy set up?

**Comment by igor-davidyuk** [comment]
You can try running it in Colab https://colab.research.google.com/github/openvinotoolkit/openvino_notebooks/blob/main/notebooks/230-yolov8-optimization/230-yolov8-optimization.ipynb
The utils downloading works as expected there.

If you cloned the whole repo try replacing the downloading with
```
import sys
sys.path.append("../utils")
```
Then the utils import will work. Just as a temporary solution to unblock you.

**Comment by RohanSardar** [comment]
> Thanks for reporting this! Just to make sure, do you have any kind of proxy set up?

no

**Comment by RohanSardar** [comment]
There was a problem with my ISP's DNS. In India, Jio is the leading 5G internet provider and their DNS is restricting access to raw.githubusercontent.com

The issue is solved by using Cloudflare's 1.1.1.1 and 1.0.0.1 IPv4 DNS
