### ISSUE TITLE
Installation Fails on Ubuntu 23.04

### ISSUE THREAD

**Issue by Kk-VP** [openvinotoolkit/openvino_notebooks#1177]
**Describe the bug**
Following installation steps as per
https://github.com/openvinotoolkit/openvino_notebooks/wiki/Ubuntu
On "pip install -r requirements.txt", error is observed

 **Expected behavior**
Complete successful installation and launch of Jupyter notes.

**Screenshots**
Log
---------------------
pip install -r requirements.txt
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Ignoring tensorflow-macos: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Ignoring tensorflow: markers 'sys_platform == "darwin" and platform_machine != "arm64"' don't match your environment
Ignoring torch: markers 'sys_platform == "darwin"' don't match your environment
Ignoring torchvision: markers 'sys_platform == "darwin"' don't match your environment
Collecting openvino-dev==2023.0.0 (from -r requirements.txt (line 2))
  Downloading openvino_dev-2023.0.0-10927-py3-none-any.whl (5.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.9/5.9 MB 17.0 MB/s eta 0:00:00
Collecting openvino-telemetry==2022.3.0 (from -r requirements.txt (line 3))
  Downloading openvino_telemetry-2022.3.0-py3-none-any.whl (20 kB)
Collecting nncf==2.5.0 (from -r requirements.txt (line 4))
  Downloading nncf-2.5.0-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 20.1 MB/s eta 0:00:00
Collecting tensorflow<=2.12,>=2.5 (from -r requirements.txt (line 10))
  Downloading tensorflow-2.12.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (586.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 586.0/586.0 MB 5.8 MB/s eta 0:00:00
Collecting onnx>=1.11.0 (from -r requirements.txt (line 12))
  Downloading onnx-1.14.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (14.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.6/14.6 MB 13.2 MB/s eta 0:00:00
Collecting torch==1.13.1+cpu (from -r requirements.txt (line 16))
  Downloading https://download.pytorch.org/whl/cpu/torch-1.13.1%2Bcpu-cp311-cp311-linux_x86_64.whl (199.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.1/199.1 MB 13.2 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement torchvision==0.14.1+cpu (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.15.0, 0.15.0+cpu, 0.15.0+cu117, 0.15.0+cu118, 0.15.1, 0.15.1+cpu, 0.15.1+cu117, 0.15.1+cu118, 0.15.2, 0.15.2+cpu, 0.15.2+cu117, 0.15.2+cu118, 0.15.2+rocm5.3, 0.15.2+rocm5.4.2)
ERROR: No matching distribution found for torchvision==0.14.1+cpu

----------------------

 **Installation instructions (Please mark the checkbox)**
[ X ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
Please run `python check_install.py` in the _openvino_notebooks_ directory. If the output is _NOT OK_ for any of the checks, please follow the instructions to fix that. If that does not work, or if you still encounter the issue, please paste the output of check_install.py here.
 
Importing Jupyter failed. Please follow the installation instructions in the README in the same directory as this script or at https://github.com/openvinotoolkit/openvino_notebooks.

**Additional context**

**Comment by Wan-Intel** [comment]
Ubuntu 23.04 and its default Python version (Python 3.11) are not supported in OpenVINO™ Notebooks.

Please refer to [System Requirements](https://github.com/openvinotoolkit/openvino_notebooks#%EF%B8%8F-system-requirements) for more information.

**Comment by Wan-Intel** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
