### ISSUE TITLE
Model compile failing on GPU.1 (ARC A770) in 236-stable-diffusion-v2-optimum-demo notebook

### ISSUE THREAD

**Issue by arisha07** [openvinotoolkit/openvino_notebooks#1182]
**Describe the bug**
After changing pipe.to("GPU") to pipe.to("GPU.1") the models fails to compile. 

 **Expected behavior**
text encoder, unet, vae_decoder should successfully compile on dGPU. 

**Screenshots**
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/23331791/39f1f344-2153-4d01-a9fa-f3e2ff737e51)

 **Installation instructions (Please mark the checkbox)**
Yes I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
Please run `python check_install.py` in the _openvino_notebooks_ directory. If the output is _NOT OK_ for any of the checks, please follow the instructions to fix that. If that does not work, or if you still encounter the issue, please paste the output of check_install.py here.
 
**Additional context**

**Comment by paularamo** [comment]
Could you please run this? 

`from openvino.runtime import Core

ie = Core()
devices = ie.available_devices

for device in devices:
    device_name = ie.get_property(device, "FULL_DEVICE_NAME")
    print(f"{device}: {device_name}")`

**Comment by arisha07** [comment]
Yup I did, 
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/23331791/da9b50b0-94cb-4d37-a5fe-07e03e302e33)

**Comment by paularamo** [comment]
Could you please provide details about your machine? OS, Python version, OpenVINO Version, Intel dGPU driver? Thanks

**Comment by arisha07** [comment]
OS: Windows 11
Python version:
OpenVINO version: 2023.0.0
Intel dGPU driver: 31.0.101.4146

I am able to compile SD2.1-base models on this dGPU using the core.compile instead of the optimum method. This notebook 236-stable-diffusion-v2-text-to-image runs just fine on my GPU.1

**Comment by paularamo** [comment]
Please try to use the latest beta driver version. https://www.intel.ca/content/www/ca/en/download/729157/intel-arc-iris-xe-graphics-beta-windows.html. I have documented it on this blog. https://blog.openvino.ai/blog-posts/install-gpu-drivers-windows-ubuntu.

Please let me know if that works. BR

**Comment by ryanloney** [comment]
@vladimir-paramuzov any suggestions? (aside from using beta driver)

**Comment by arisha07** [comment]
It worked after updating to beta driver. Thank you !
