### ISSUE TITLE
230-yolov8-optimization - AttributeError: module 'ultralytics.yolo.utils.ops' has no attribute 'scale_segments'

### ISSUE THREAD

**Issue by mwright-pivotal** [openvinotoolkit/openvino_notebooks#1185]
Notebook 230-yolov8-optimization has a nethod definition called "postprocess".  In this method there is a reference to module "ops" from "from ultralytics.yolo.utils import ops", where it makes a call to "ops.scale_sements".  It appears that this method does not exist.

segments = [ops.scale_segments(input_hw, x, shape, normalize=False) for x in ops.masks2segments(masks)]

Error from execution:

---> 62         segments = [ops.scale_segments(input_hw, x, shape, normalize=False) for x in ops.masks2segments(masks)]
     63     results.append({"det": pred[:, :6].numpy(), "segment": segments})
     64 return results

AttributeError: module 'ultralytics.yolo.utils.ops' has no attribute 'scale_segments'

For reference, ops docs are here: https://docs.ultralytics.com/reference/yolo/utils/ops/

**Comment by Iffa-Meah** [comment]
@mwright-pivotal From my side, I don't see any issue with that function call with OpenVINO Notebook.

<img width="573" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/a8a4b87c-627c-4568-af1d-1c697e2aefd4">

Test on a single image result.
<img width="784" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/e29f611f-ff83-4df5-b383-21f413696568">

Make sure you had set up and installed the requirements properly according to your OS.
You may refer [here](https://github.com/openvinotoolkit/openvino_notebooks/blob/main/README.md#-installation-guide).

**Comment by mwright-pivotal** [comment]
Ok, I should have clarified.   I am using the docker instructions.  So I assume all the OS needs are already captured in the Dockerfile? 
I'll take a look at how the Dockerfile is being built but I assume it covers the requirements.   

Were you verifying on your local machine or were you testing from the resulting docker image?

Can you point me to the source code for method scale_segments?  I don't see it here: https://docs.ultralytics.com/reference/yolo/utils/ops/

**Comment by Iffa-Meah** [comment]
@mwright-pivotal I'm running the code with Notebook Jupyter on my local machine.

The function call is actually in the 1st screenshot.
Here, I highlighted it (it's in the if & else statement):

<img width="500" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/1a57c3a1-9a5a-4eba-8bfa-1c9530b1fd74">

Just in case, I share this source code link too: [230-yolov8-optimization](https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/230-yolov8-optimization)

Btw, this is the official guide for Docker: [Docker](https://github.com/openvinotoolkit/openvino_notebooks/wiki/Docker)

**Comment by mwright-pivotal** [comment]
SOrry, I think my question was misunderstood.  I have the source code of the notebook and have been using it.

I am asking where to find the source code for the method "scale_segments".  This is referenced off of "ops" from Ultralytics ...

ie.  "from ultralytics.yolo.utils import ops"

So I would expect the method "scale_segments" to be found here: https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/utils/ops.py.   But I do not see it... So my question is really, from where are you getting the definition of that method? 

Does that make sense?  Thank you for your help!

**Comment by Iffa-Meah** [comment]
@mwright-pivotal notice that, in the beginning, the Ultralytics library is installed using pip.
Therefore, to find that specific library, you need to find it in location of your pip install location.


This is [Ultralytics official GitHub page](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/ops.py).

Mine is located in my virtual env Pyton library (since I created, then installed everything in venv):
<img width="254" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/69852a37-54bc-4b4b-97f0-35d6d0054210">

**Comment by mwright-pivotal** [comment]
@Iffa-Meah I really appreciate you trying to help... You replied providing the same github link to Ultralytics' source page for ops.py that I mentioned in my last post.

If you go to that source code for ops.py and search the code you will find that there is no function definition called "scale_segments".   There is "scale_boxes" however...

My question again, is where is the source code for "scale_segments" because it's clearly not defined in ops.py?  Don't you agree?

**Comment by Iffa-Meah** [comment]
@mwri
there is a function definition for scale_segments in that ops.py.
Let me highlight that for you:

<img width="538" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/363d882c-146d-4d25-8593-8477c59e89e2">

**Comment by mwright-pivotal** [comment]
(ultralytics) mwright@cumulus:~/projects/test$ source ultralytics/bin/activate
(ultralytics) mwright@cumulus:~/projects/test$ TMPDIR=/home/mwright/tmp pip install ultralytics==8.0.131
Collecting ultralytics==8.0.131
  Downloading ultralytics-8.0.131-py3-none-any.whl (626 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 626.9/626.9 kB 9.4 MB/s eta 0:00:00
Requirement already satisfied: opencv-python>=4.6.0 in ./ultralytics/lib/python3.10/site-packages (from ultralytics==8.0.131) (4.8.0.74)
Requirement already satisfied: pandas>=1.1.4 in ./ultralytics/lib/python3.10/site-packages (from ultralytics==8.0.131) (2.0.3)
Requirement already satisfied: scipy>=1.4.1 in ./ultralytics/lib/python3.10/site-packages (from ultralytics==8.0.131) (1.11.1)
Requirement already satisfied: torchvision>=0.8.1 in ./ultralytics/lib/python3.10/site-packages (from ultralytics==8.0.131) (0.15.2)
Requirement already satisfied: psutil in ./ultralytics/lib/python3.10/site-packages (from ultralytics==8.0.131) (5.9.5)
Requirement already satisfied: matplotlib>=3.2.2 in ./ultralytics/lib/python3.10/site-packages (from ultralytics==8.0.131) (3.7.2)
Requirement already satisfied: PyYAML>=5.3.1 in ./ultralytics/lib/python3.10/site-packages (from ultralytics==8.0.131) (6.0)
Requirement already satisfied: tqdm>=4.64.0 in ./ultralytics/lib/python3.10/site-packages (from ultralytics==8.0.131) (4.65.0)
Requirement already satisfied: torch>=1.7.0 in ./ultralytics/lib/python3.10/site-packages (from ultralytics==8.0.131) (2.0.1)
Requirement already satisfied: requests>=2.23.0 in ./ultralytics/lib/python3.10/site-packages (from ultralytics==8.0.131) (2.31.0)
Requirement already satisfied: Pillow>=7.1.2 in ./ultralytics/lib/python3.10/site-packages (from ultralytics==8.0.131) (10.0.0)
Requirement already satisfied: seaborn>=0.11.0 in ./ultralytics/lib/python3.10/site-packages (from ultralytics==8.0.131) (0.12.2)
Requirement already satisfied: contourpy>=1.0.1 in ./ultralytics/lib/python3.10/site-packages (from matplotlib>=3.2.2->ultralytics==8.0.131) (1.1.0)
Requirement already satisfied: fonttools>=4.22.0 in ./ultralytics/lib/python3.10/site-packages (from matplotlib>=3.2.2->ultralytics==8.0.131) (4.41.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in ./ultralytics/lib/python3.10/site-packages (from matplotlib>=3.2.2->ultralytics==8.0.131) (3.0.9)
Requirement already satisfied: packaging>=20.0 in ./ultralytics/lib/python3.10/site-packages (from matplotlib>=3.2.2->ultralytics==8.0.131) (23.1)
Requirement already satisfied: cycler>=0.10 in ./ultralytics/lib/python3.10/site-packages (from matplotlib>=3.2.2->ultralytics==8.0.131) (0.11.0)
Requirement already satisfied: python-dateutil>=2.7 in ./ultralytics/lib/python3.10/site-packages (from matplotlib>=3.2.2->ultralytics==8.0.131) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in ./ultralytics/lib/python3.10/site-packages (from matplotlib>=3.2.2->ultralytics==8.0.131) (1.4.4)
Requirement already satisfied: numpy>=1.20 in ./ultralytics/lib/python3.10/site-packages (from matplotlib>=3.2.2->ultralytics==8.0.131) (1.25.1)
Requirement already satisfied: tzdata>=2022.1 in ./ultralytics/lib/python3.10/site-packages (from pandas>=1.1.4->ultralytics==8.0.131) (2023.3)
Requirement already satisfied: pytz>=2020.1 in ./ultralytics/lib/python3.10/site-packages (from pandas>=1.1.4->ultralytics==8.0.131) (2023.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./ultralytics/lib/python3.10/site-packages (from requests>=2.23.0->ultralytics==8.0.131) (2.0.3)
Requirement already satisfied: certifi>=2017.4.17 in ./ultralytics/lib/python3.10/site-packages (from requests>=2.23.0->ultralytics==8.0.131) (2023.5.7)
Requirement already satisfied: idna<4,>=2.5 in ./ultralytics/lib/python3.10/site-packages (from requests>=2.23.0->ultralytics==8.0.131) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in ./ultralytics/lib/python3.10/site-packages (from requests>=2.23.0->ultralytics==8.0.131) (3.2.0)
Requirement already satisfied: triton==2.0.0 in ./ultralytics/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics==8.0.131) (2.0.0)
Requirement already satisfied: typing-extensions in ./ultralytics/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics==8.0.131) (4.7.1)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.4.91 in ./ultralytics/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics==8.0.131) (11.7.4.91)
Requirement already satisfied: filelock in ./ultralytics/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics==8.0.131) (3.12.2)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in ./ultralytics/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics==8.0.131) (11.7.99)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.7.101 in ./ultralytics/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics==8.0.131) (11.7.101)
Requirement already satisfied: networkx in ./ultralytics/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics==8.0.131) (3.1)
Requirement already satisfied: nvidia-nccl-cu11==2.14.3 in ./ultralytics/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics==8.0.131) (2.14.3)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in ./ultralytics/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics==8.0.131) (8.5.0.96)
Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in ./ultralytics/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics==8.0.131) (11.10.3.66)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.0.1 in ./ultralytics/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics==8.0.131) (11.4.0.1)
Requirement already satisfied: jinja2 in ./ultralytics/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics==8.0.131) (3.1.2)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in ./ultralytics/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics==8.0.131) (10.9.0.58)
Requirement already satisfied: nvidia-curand-cu11==10.2.10.91 in ./ultralytics/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics==8.0.131) (10.2.10.91)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in ./ultralytics/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics==8.0.131) (11.7.99)
Requirement already satisfied: sympy in ./ultralytics/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics==8.0.131) (1.12)
Requirement already satisfied: nvidia-nvtx-cu11==11.7.91 in ./ultralytics/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics==8.0.131) (11.7.91)
Requirement already satisfied: setuptools in ./ultralytics/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch>=1.7.0->ultralytics==8.0.131) (65.5.0)
Requirement already satisfied: wheel in ./ultralytics/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch>=1.7.0->ultralytics==8.0.131) (0.40.0)
Requirement already satisfied: lit in ./ultralytics/lib/python3.10/site-packages (from triton==2.0.0->torch>=1.7.0->ultralytics==8.0.131) (16.0.6)
Requirement already satisfied: cmake in ./ultralytics/lib/python3.10/site-packages (from triton==2.0.0->torch>=1.7.0->ultralytics==8.0.131) (3.26.4)
Requirement already satisfied: six>=1.5 in ./ultralytics/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib>=3.2.2->ultralytics==8.0.131) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./ultralytics/lib/python3.10/site-packages (from jinja2->torch>=1.7.0->ultralytics==8.0.131) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in ./ultralytics/lib/python3.10/site-packages (from sympy->torch>=1.7.0->ultralytics==8.0.131) (1.3.0)
Installing collected packages: ultralytics
Successfully installed ultralytics-8.0.131

[notice] A new release of pip is available: 23.0.1 -> 23.2
[notice] To update, run: pip install --upgrade pip
(ultralytics) mwright@cumulus:~/projects/test$ python3
Python 3.10.11 (main, Apr  5 2023, 14:15:10) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ultralytics.yolo.utils import ops
>>> quit()
(ultralytics) mwright@cumulus:~/projects/test$ grep ultralytics/lib/python3.10/site-packages/ultralytics/
assets/      datasets/    hub/         __init__.py  models/      nn/          __pycache__/ tracker/     vit/         yolo/
**(ultralytics) mwright@cumulus:~/projects/test$ grep scale_segments ultralytics/lib/python3.10/site-packages/ultralytics/yolo/utils/ops.py
(ultralytics) mwright@cumulus:~/projects/test$**

I don't know where you got the local copy of ops.py from or if it's one off build for windows, but the version I have has no such method defined.

**Comment by Iffa-Meah** [comment]
@mwright-pivotal this is fresh installation in Ubuntu (Windows is actually a fresh installation too):

<img width="887" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/d94188dc-3aa6-4684-a679-efde8afa0119">


Location of ops.py with scale_segment definition in it:
<img width="894" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/11101c16-1ea1-46ed-9c32-11cdf5ad6b5f">

**Comment by eaidova** [comment]
@mwright-pivotal please check the latest notebook version from main branch, we added code which handle both old and new name function for scaling segments coordinates. Also please make sure that you install the same ultralitics library version that specified in notebook (unfortunately ultralytics code updating time to time without preserving backward compatibility... it lead to such issues when code location or function names changed)

**Comment by tgcandido** [comment]
I'm not getting the error, but I'm finding that the FPS is far from the FPS shown in the docs.

For the OpenVino IR int8 model, I'm getting the following output:

`[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[Step 2/11] Loading OpenVINO Runtime
[ INFO ] OpenVINO:
[ INFO ] Build ................................. 2023.0.1-11005-fa1c41994f3-releases/2023/0
[ INFO ] 
[ INFO ] Device info:
[ INFO ] CPU
[ INFO ] Build ................................. 2023.0.1-11005-fa1c41994f3-releases/2023/0
[ INFO ] 
[ INFO ] 
[Step 3/11] Setting device configuration
[ WARNING ] Performance hint was not explicitly specified in command line. Device(CPU) performance hint will be set to PerformanceMode.THROUGHPUT.
[Step 4/11] Reading model files
[ INFO ] Loading model files
[ INFO ] Read model took 62.30 ms
[ INFO ] Original model I/O parameters:
[ INFO ] Model inputs:
[ INFO ]     images (node: images) : f32 / [...] / [1,3,?,?]
[ INFO ] Model outputs:
[ INFO ]     output0 (node: output0) : f32 / [...] / [1,84,21..]
[Step 5/11] Resizing model to match image sizes and given batch
[ INFO ] Model batch size: 1
[ INFO ] Reshaping model: 'images': [1,3,640,640]
[ INFO ] Reshape model took 32.27 ms
[Step 6/11] Configuring input of the model
[ INFO ] Model inputs:
[ INFO ]     images (node: images) : u8 / [N,C,H,W] / [1,3,640,640]
[ INFO ] Model outputs:
[ INFO ]     output0 (node: output0) : f32 / [...] / [1,84,8400]
[Step 7/11] Loading the model to the device
[ INFO ] Compile model took 550.59 ms
[Step 8/11] Querying optimal runtime parameters
[ INFO ] Model:
[ INFO ]   NETWORK_NAME: torch_jit
[ INFO ]   OPTIMAL_NUMBER_OF_INFER_REQUESTS: 8
[ INFO ]   NUM_STREAMS: 8
[ INFO ]   AFFINITY: Affinity.CORE
[ INFO ]   INFERENCE_NUM_THREADS: 32
[ INFO ]   PERF_COUNT: False
[ INFO ]   INFERENCE_PRECISION_HINT: <Type: 'float32'>
[ INFO ]   PERFORMANCE_HINT: PerformanceMode.THROUGHPUT
[ INFO ]   EXECUTION_MODE_HINT: ExecutionMode.PERFORMANCE
[ INFO ]   PERFORMANCE_HINT_NUM_REQUESTS: 0
[ INFO ]   ENABLE_CPU_PINNING: True
[ INFO ]   SCHEDULING_CORE_TYPE: SchedulingCoreType.ANY_CORE
[ INFO ]   ENABLE_HYPER_THREADING: False
[ INFO ]   EXECUTION_DEVICES: ['CPU']
[Step 9/11] Creating infer requests and preparing input tensors
[ WARNING ] No input files were given for input 'images'!. This input will be filled with random values!
[ INFO ] Fill input 'images' with random values 
[Step 10/11] Measuring performance (Start inference asynchronously, 8 inference requests, limits: 15000 ms duration)
[ INFO ] Benchmarking in inference only mode (inputs filling are not included in measurement loop).
[ INFO ] First inference took 54.97 ms
[Step 11/11] Dumping statistics report
[ INFO ] Execution Devices:['CPU']
[ INFO ] Count:            472 iterations
[ INFO ] Duration:         15323.16 ms
[ INFO ] Latency:
[ INFO ]    Median:        279.37 ms
[ INFO ]    Average:       258.78 ms
[ INFO ]    Min:           125.97 ms
[ INFO ]    Max:           398.44 ms
[ INFO ] Throughput:   30.80 FPS`

I'm using eight cores of mine, Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz, and I'm running in a container with the openvino/ubuntu22_dev image.

Is this supposed to be just 30FPS?

**Comment by Iffa-Meah** [comment]
@tgcandido It's recommended to open a new discussion thread for your issue since this is a slightly different topic from this thread and also to get better tracking/focus on your issue.

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
