### ISSUE TITLE
Hello World Not Found in OpenVINO API Guide

### ISSUE THREAD

**Issue by raymondlo84** [openvinotoolkit/openvino_notebooks#119]
![scrnli_6_12_2021_5-44-34 PM](https://user-images.githubusercontent.com/1720147/121792100-e2cc1500-cba5-11eb-95f1-558c11558390.png)

We should change it to the file name instead of a path.
``
check out the [hello world notebook](../001-hello-world/001-hello-world.ipynb).
``

**Comment by helena-intel** [comment]
Thanks! Fixed in https://github.com/openvinotoolkit/openvino_notebooks/pull/118
