### ISSUE TITLE
Does 236-stable-diffusion-v2 support LoRA

### ISSUE THREAD

**Issue by k80117k80117** [openvinotoolkit/openvino_notebooks#1202]
Hello,

I have some questions regarding LoRA's compatibility with OpenVINO.

Can I directly use a LoRA model on OpenVINO without conversion, or do I need to convert the LoRA model into an IR model first? Alternatively, do I need to pre-train a new IR model with my base model and LoRA model to use it with OpenVINO?

Thank you very much.

**Comment by Wan-Intel** [comment]
LoRA model can be used with OpenVINO Runtime without any prior conversion if the model formats are as follows:
- OpenVINO IR
- ONNX
- PaddlePaddle
- TensorFlow
- TensorFlow Lite

Otherwise, please convert the model into OpenVINO IR before running inference.

**Comment by Wan-Intel** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.

**Comment by k80117k80117** [comment]
Hello, I'm currently working with a LoRA model that is saved with the .safetensor extension, and I was wondering if there is a supported way in converting it to the IR format. If so, are there any references to this in the notebook that can guide me through the conversion process?
