### ISSUE TITLE
ERR when run  402-pose-estimation.ipynb  on  PC :NUC with Mesa Intel® Xe Graphics (TGL GT2)

### ISSUE THREAD

**Issue by yangcopnuli** [openvinotoolkit/openvino_notebooks#1206]
**Describe the bug**
ERR when run  402-pose-estimation.ipynb  on  PC :NUC with Mesa Intel® Xe Graphics (TGL GT2)

err info :
```
error: undefined reference to `__builtin_spirv_intel_sub_group_block_read_uc2_p3i8()'

error: backend compiler failed build.
LLVM ERROR: Error: Attempt to redefine function: ; Function Attrs: convergent
declare spir_func <16 x i8> @_Z33__spirv_SubgroupBlockReadINTEL_uiPU3AS3c(i8 addrspace(3)*) #5
 => i8 (i8 addrspace(3)*)


```
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/138567485/e9dff30e-d94b-40b3-93af-f6d7787cda4a)

![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/138567485/99925b4d-205f-46e3-aaa5-0456e077145c)

OS:ubuntu20.04 
PC: NUC
graph card: Mesa Intel® Xe Graphics (TGL GT2)

**Comment by Iffa-Meah** [comment]
Hi @yangcopnuli I'm using Tiger Lake and didn't face that issue

Init OV
<img width="676" alt="TGL_initOV" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/8f1d13e1-5712-4ec1-80c2-cbfa049dbc10">


Infer Pose Estimation:
<img width="646" alt="TGL_poseEstimation" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/1b9a9a03-1cb1-471d-a5ae-9d1ca1447e7d">

Perhaps you need to check whether your GPU is available before running (yours have red symbol near GPU that mine does not have)

**Comment by Iffa-Meah** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
