### ISSUE TITLE
Nodesource NodeJS RPM fails to verify when FIPS mode is enabled

### ISSUE THREAD

**Issue by Xaenalt** [openvinotoolkit/openvino_notebooks#1219]
**Describe the bug**
QE has identified a scenario in which the OpenVINO notebook will fail to build successfully.

On clusters with FIPS mode enabled, RPMs without a SHA25 hash on the compressed payload will fail to verify with the following error
```
Error: Transaction test error:
  package nodejs-2:14.18.1-1nodesource.x86_64 does not verify: no digest
```

This package seems to be installed from https://github.com/openvinotoolkit/openvino_notebooks/blob/main/Dockerfile#L28

This can be worked around by the nodesource vendor by rebuilding the RPM, or can be worked around by adding
```
--setopt=tsflags=nocrypto --nogpgcheck
```
to the yum install on L28

Alternatively, there is now a pre-built notebooks option for RHODS, but that requires a logic change in the operator

**Comment by avitial** [comment]
@Xaenalt thanks for reporting this issue, we have forwarded this issue to the development team for fixing.

Ref. 116687

**Comment by eaidova** [comment]
@Xaenalt sorry for late responce, I've applied your suggested workaround
