### ISSUE TITLE
failed to convert stable diffusion2.1 onnx file int8 (static quantization)conversion. also not able to read unet file with external data file in neutron app. 

### ISSUE THREAD

**Issue by siddharth062022** [openvinotoolkit/openvino_notebooks#1221]
**Describe the bug**
A clear and concise description of what the bug is, including steps to reproduce the bug if possible.

 **Expected behavior**

**Screenshots**

 **Installation instructions (Please mark the checkbox)**
[  ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
Please run `python check_install.py` in the _openvino_notebooks_ directory. If the output is _NOT OK_ for any of the checks, please follow the instructions to fix that. If that does not work, or if you still encounter the issue, please paste the output of check_install.py here.
 
**Additional context**

**Comment by Iffa-Meah** [comment]
@siddharth062022 could you share:
1. Relevant model files
2. Details of changes that you made to the ONNX model (eg: retrain)
3. Which OS used
4. Does virtual environment involved (Docker,etc)

**Comment by siddharth062022** [comment]
https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/236-stable-diffusion-v2/236-stable-diffusion-v2-text-to-image.ipynb 
i am using colab .
i have also ubuntu support.
model name = stabilityai/stable-diffusion-2-1-base
i want int8 version of onnx file (using static quantization with fine tuning) all model text encoder vae decoder var encoder unet (also unet in single file not in external file ) if externet file is there there how to read those extrenal file any code. (importantaly i needed int8 version of all file not fp 32)

**Comment by avitial** [comment]
Hi @siddharth062022! apologies for the delay in my response. Do you want to perform post-training quantization on stable diffusion pipeline? If so, I'd recommend you to this blog post [Optimizing Stable Diffusion for Intel CPUs with NNCF and 🤗 Optimum](https://huggingface.co/blog/train-optimize-sd-intel) where it provides very good and clear insights on stable diffusion pipeline and optimizations as well as references to the training and quantization code. Hope this helps.

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.
