### ISSUE TITLE
pytorch version error for requirements installation

### ISSUE THREAD

**Issue by alberxualberxu** [openvinotoolkit/openvino_notebooks#1239]
met below issue when running "pip install -r requirements.txt"

Looking in links: https://download.pytorch.org/whl/torch_stable.html
Ignoring tensorflow-macos: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Ignoring tensorflow: markers 'sys_platform == "darwin" and platform_machine != "arm64"' don't match your environment
Ignoring torch: markers 'sys_platform == "darwin"' don't match your environment
Ignoring torchvision: markers 'sys_platform == "darwin"' don't match your environment
Requirement already satisfied: openvino-dev==2023.0.0 in c:\users\15173\openvino_env\lib\site-packages (from -r requirements.txt (line 2)) (2023.0.0)
Collecting openvino-telemetry==2022.3.0 (from -r requirements.txt (line 3))
  Using cached openvino_telemetry-2022.3.0-py3-none-any.whl (20 kB)
Collecting nncf==2.5.0 (from -r requirements.txt (line 4))
  Obtaining dependency information for nncf==2.5.0 from https://files.pythonhosted.org/packages/00/67/da4c44d198bf719a1360e55b29666f95d74f43b945ebf5bf977181db982f/nncf-2.5.0-py3-none-any.whl.metadata
  Using cached nncf-2.5.0-py3-none-any.whl.metadata (29 kB)
Collecting tensorflow<=2.12,>=2.5 (from -r requirements.txt (line 10))
  Using cached tensorflow-2.12.0-cp311-cp311-win_amd64.whl (1.9 kB)
Collecting onnx>=1.11.0 (from -r requirements.txt (line 12))
  Using cached onnx-1.14.0-cp311-cp311-win_amd64.whl (13.3 MB)
**ERROR: Could not find a version that satisfies the requirement torch==1.13.1+cpu (from versions: 2.0.0, 2.0.0+cpu, 2.0.0+cu117, 2.0.0+cu118, 2.0.1, 2.0.1+cpu, 2.0.1+cu117, 2.0.1+cu118)
ERROR: No matching distribution found for torch==1.13.1+cpu**

**Comment by eaidova** [comment]
@alberxualberxu looks like you trying to run notebooks using python3.11, that currently is not supported yet. We are working on that, thank you that you let us know about issue. You can check currently supported system configuration in our [documentation](https://github.com/openvinotoolkit/openvino_notebooks#%EF%B8%8F-system-requirements)
