### ISSUE TITLE
error in 227_whisper_subtitles_generation.ipynb while running for medium model.

### ISSUE THREAD

**Issue by tarunmcom** [openvinotoolkit/openvino_notebooks#1245]
I am getting error when running the notebook for whisper **medium** mode:-

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[10], line 5
      3     if k.endswith('a'):
      4         input_shapes += f",in_{k}[1..5 -1 512]"
----> 5 decoder_model = mo.convert_model(
      6     input_model="whisper_decoder.onnx",
      7     compress_to_fp16=True,
      8     input=input_shapes)
      9 serialize(decoder_model, "whisper_decoder.xml")

File ~/tarun/whisper/ehs/lib/python3.10/site-packages/openvino/tools/mo/convert.py:348, in convert_model(input_model, help, framework, input, output, input_shape, batch, mean_values, scale_values, scale, reverse_input_channels, source_layout, target_layout, layout, compress_to_fp16, extensions, transform, transformations_config, silent, log_level, version, progress, stream_output, example_input, input_model_is_text, input_checkpoint, input_meta_graph, saved_model_dir, saved_model_tags, tensorflow_custom_operations_config_update, tensorflow_object_detection_api_pipeline_config, tensorboard_logdir, tensorflow_custom_layer_libraries, input_symbol, nd_prefix_name, pretrained_model_name, save_params_from_nd, legacy_mxnet_model, enable_ssd_gluoncv, input_proto, caffe_parser_path, k, disable_omitting_optional, enable_flattening_nested_params, counts, remove_output_softmax, remove_memory, **args)
    346 params.update(args)
    347 cli_parser = get_all_cli_parser()
--> 348 ov_model, _ = _convert(cli_parser, framework, params, True)
    349 restore_logger_state(logger_state)
    350 return ov_model

File ~/tarun/whisper/ehs/lib/python3.10/site-packages/openvino/tools/mo/convert_impl.py:972, in _convert(cli_parser, framework, args, python_api_used)
    970 send_conversion_result('fail')
    971 if python_api_used:
--> 972     raise e.with_traceback(None)
    973 else:
    974     return None, argv

RuntimeError: Check 'false' failed at src/frontends/onnx/frontend/src/core/graph.cpp:391:
While validating ONNX node '<Node(Concat): /blocks.0/attn/Concat>':
Check 'T::merge_into(output_shape, input)' failed at src/core/shape_inference/include/concat_shape_inference.hpp:37:
While validating node 'opset1::Concat Concat_10262 (in_k_0a[0]:f32[?,?,512], /blocks.0/attn/key/MatMul[0]:f32[?,?,1024]) -> (dynamic[...])' with friendly_name 'Concat_10262':
Argument shapes are inconsistent; they must have the same rank, and must have equal dimension everywhere except on the concatenation axis (axis 1).

**Comment by eaidova** [comment]
@tarunmcom medium model has 1024 size of encoder embeddings, you need to update shapes in mo command replacing 512 with 1024

**Comment by tarunmcom** [comment]
Thanks this worked
