### ISSUE TITLE
in 236 stable-diffussion-v2: notebook always breakdown ???

### ISSUE THREAD

**Issue by CCMKCCMK** [openvinotoolkit/openvino_notebooks#1250]
**Describe the bug**
in 236 stable-diffussion-v2: notebook always breakdown when running the Unet part, I have tried to run the following 2 parts and both succeed.

 **Expected behavior**
The error seems related to `torch.onnx._export(
                unet, 
                (latents, t, encoder_hidden_state), str(onnx_path),
                input_names=['latent_model_input', 't', 'encoder_hidden_states'],
                output_names=['out_sample'],
                onnx_shape_inference=False
            )`
since it executed `print(4)` but not `print('U-Net successfully converted to ONNX')`.

**Screenshots**
<img width="829" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/120266471/d1e4a147-9c33-4c53-94c9-c6890b9b718d">
<img width="745" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/120266471/82fd7319-25ea-4406-bc30-7da3084b9192">

 **Installation instructions (Please mark the checkbox)**
[ * ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
Please run `python check_install.py` in the _openvino_notebooks_ directory. If the output is _NOT OK_ for any of the checks, please follow the instructions to fix that. If that does not work, or if you still encounter the issue, please paste the output of check_install.py here.
 
<img width="656" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/120266471/77a510c1-9adc-4ec5-8f9d-40b215968412">

<img width="432" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/120266471/106baeae-5df4-4073-a54f-f1be399cba4a">
Although i get an `NOT OK` here, my python version is still 3.10, which satisfy the requirement

**Additional context**
HELP me solve this, please!

**Comment by Iffa-Meah** [comment]
@CCMKCCMK I freshly installed OV notebook as instructed [here](https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide) (the same guide as the one you mentioned).

<img width="733" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/a992c583-6a2e-49a1-90d1-4e375e1f21ec">

From my side, I didn't encounter that issue.

Model is successfully converted into IR:
<img width="752" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/10c88b20-926e-4a96-86cc-a413c118bc5c">

Inferencing demo:
<img width="710" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/a66ce8d9-4ebb-485d-947a-a3f3cbc17cde">

I'm using Windows 11 and my Python version is 3.7.9. I ran the notebook in a virtual environment as instructed in the official guide.


Make sure you installed this required package
<img width="727" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/2fa14129-bdf9-4fbb-b622-bb26fbe4d037">

**Comment by CCMKCCMK** [comment]
Sorry for making some confusions! I am using WSL2 Ubuntu on win11.

**Comment by Iffa-Meah** [comment]
@CCMKCCMK could you share:
1. Which version of WSL2 Ubuntu are you using
2. What Intel GPU is used
3. Does this mean that you intend to run 236-stable-diffusion-v2-text-to-image with GPU instead CPU?
4. Did you do any modifications to the sample code to make it work with GPU? (please help to share)

**Comment by CCMKCCMK** [comment]
1.Ubuntu 22.04
2.Intel iris xe
3.yes
4.no, just copy and paste

**Comment by Iffa-Meah** [comment]
@CCMKCCMK The best stable diffusion sample to be run with GPU is this [225-stable-diffusion-text-to-image](https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/225-stable-diffusion-text-to-image)
which mentioned in ReadMe ([Blog - How to run Stable Diffusion on Intel GPUs with OpenVINO](https://medium.com/openvino-toolkit/how-to-run-stable-diffusion-on-intel-gpus-with-openvino-840714f122b4)
<img width="703" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/74cf1468-1017-4c2f-bd42-10072604af5e">

I'm running this sample on a host that has Intel® Iris Xe Graphics and runs Ubuntu 22.04 LTS:

Configure the hardware selection to GPU
<img width="854" alt="225_1" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/8ae8c5bb-1e1d-4290-ac43-efb4487c5209">

Inferencing result (test-to-image)
<img width="857" alt="225_2" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/3e361b53-609d-4b7f-b67c-293b937af521">

Inferencing result (image-to-image)
<img width="812" alt="225_3" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/7d484630-c39f-4c02-89eb-057c5bbfcbd6">

**Comment by CCMKCCMK** [comment]
Thanks and I will have a try soon! And I may show my final result in early September.

**Comment by CCMKCCMK** [comment]
I changed my mind and decide to use it on Windows. Now it work fine without any problems! Thanks for help me!
