### ISSUE TITLE
Typo in documents

### ISSUE THREAD

**Issue by stvgz** [openvinotoolkit/openvino_notebooks#1272]
**Describe the bug**
Typo in documents
https://www.intel.com/content/www/us/en/developer/articles/training/create-smart-meter-scanning.html

git clone –b recipes https://github.com/openvinotoolkit/openvino_notebooks.git

 **Expected behavior**

The git clone command you're trying to use is correct in structure, but it seems like there's a typographical error. The dash before the b should be a single hyphen (-), not a long dash (–).

**Comment by avitial** [comment]
@stvgz thank you for your feedback, we have captured this as a bug for fixing the typo in the documentation. 


Ref. 119147

**Comment by avitial** [comment]
Typo has been fixed in the article, closing this issue.
