### ISSUE TITLE
236-stable-diffussion-v2-text-to-image-demo can't run

### ISSUE THREAD

**Issue by dnoliver** [openvinotoolkit/openvino_notebooks#1301]
**Describe the bug**
A clear and concise description of what the bug is, including steps to reproduce the bug if possible.

236-stable-diffussion-v2-text-to-image-demo can't run

In this cell https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/236-stable-diffusion-v2/236-stable-diffusion-v2-text-to-image-demo.ipynb?short_path=427ad71#L196-L209, the values for the paths return empty, and then the models can't be loaded in further cells.

In this script https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/236-stable-diffusion-v2/implementation/ov_stable_diffusion_pipeline.py#L12, there is a bad import of openvino, Results in a crash

 **Expected behavior**

Should work end to end

**Screenshots**

First problem:

![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/7730267/7b7a8fe0-7398-4872-8ad7-9ce973e1b37c)

works after defining the paths

```python
txt_encoder_ov_path="./sd2.1/text_encoder.xml"
unet_ov_path="./sd2.1/unet.xml"
vae_encoder_ov_path="./sd2.1/vae_encoder.xml"
vae_decoder_ov_path="./sd2.1/vae_decoder.xml"
```

Second problem:

![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/7730267/fbd5bb0f-cecc-451e-9661-891c20d8a940)

Works after changing the import to `import openvino as ov`

 **Installation instructions (Please mark the checkbox)**
[x] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
Please run `python check_install.py` in the _openvino_notebooks_ directory. If the output is _NOT OK_ for any of the checks, please follow the instructions to fix that. If that does not work, or if you still encounter the issue, please paste the output of check_install.py here.

```bash
root@ubuntu:/opt/intel/openvino_notebooks# python3 check_install.py  
Traceback (most recent call last):                                                                                                                                        
  File "/opt/intel/openvino_notebooks/check_install.py", line 7, in <module> 
    import pip                                                                       
ModuleNotFoundError: No module named 'pip'                                           
root@ubuntu:/opt/intel/openvino_notebooks# source /opt/intel/openvino_venv/bin/activate      
(openvino_venv) root@ubuntu:/opt/intel/openvino_notebooks# python check_install.py  
System information:                     
Python executable: /opt/intel/openvino_venv/bin/python 
Pip version: 23.2.1                     
OpenVINO source: /opt/intel/openvino_venv/lib/python3.10/site-packages/openvino 
OpenVINO IE version: 2023.1.0-12050-e33de350633 
OpenVINO environment activated: NOT OK
Jupyter kernel installed for openvino_env: NOT OK 
Python version: 3.10 NOT OK
OpenVINO pip package installed: OK
OpenVINO import succeeds: OK
OpenVINO development tools installed: OK
OpenVINO not installed globally: OK
No broken requirements: NOT OK

It appears that you are not running Python in an `openvino_env`  
environment. It is possible use the notebooks in a different  
environment, but if you run into trouble, please follow the instructions  
in the README to install and activate the `openvino_env` environment. 

The Python version in openvino_env does not match the openvino_env Jupyter kernel. 
This may not be an issue. If you experience issues, please follow the instructions 
in the README to reinstall the kernel.

`pip check` shows broken requirements:
CompletedProcess(args=['pip', 'check'], returncode=1, stdout='paddleclas 2.5.1 requires easydict, which is not installed.\ngoogle-auth 2.22.0 has requirement urllib3<2.0,
 but you have urllib3 2.0.4.\nnncf 2.5.0 has requirement numpy<1.24,>=1.19.1, but you have numpy 1.25.2.\nnncf 2.5.0 has requirement pandas<2.1,>=1.1.5, but you have pand
as 2.1.0.\nnncf 2.5.0 has requirement pyparsing<3.0, but you have pyparsing 3.0.9.\nopenvino-dev 2023.0.0 has requirement openvino==2023.0.0, but you have openvino 2023.1
.0.dev20230811.\npaddleclas 2.5.1 has requirement faiss-cpu==1.7.1.post2, but you have faiss-cpu 1.7.4.\npaddleclas 2.5.1 has requirement gast==0.3.3, but you have gast 0
.4.0.\ntensorflow 2.12.0 has requirement numpy<1.24,>=1.22, but you have numpy 1.25.2.\n')

The README.md file is located in the openvino_notebooks directory  
and at https://github.com/openvinotoolkit/openvino_notebooks 
Broken requirements are often harmless, but could cause issues.
```

**Additional context**

Looks like the issues were injected in https://github.com/openvinotoolkit/openvino_notebooks/commit/f8e9074bdb686bbb1a129f1c4c9b6c93638997b3#diff-131a295deaceb8fa9e7a92b2f2f1d182261f77396872b1325ac5a9c26468b0f0

**Comment by eaidova** [comment]
@dnoliver please carefully check that you install openvino version defined in notebook.

**Comment by dnoliver** [comment]
Got it, thank you. I did this from a clean virtual environment, and got the right version installed (not sure why I didn't got it in the first place)

```
(openvino_venv) root@ubuntu:/opt/intel# pip list | grep 'diffusers\|openvino\|trasnformers\|accelerate'     
openvino                     2023.0.0                                                         
openvino-dev                 2023.0.0                                                         
openvino-telemetry           2022.3.0                                                         

(openvino_venv) root@ubuntu:/opt/intel# pip list | grep 'diffusers\|openvino\|trasnformers\|accelerate'     
accelerate                  0.22.0
diffusers                   0.20.2
openvino                    2023.1.0.dev20230811
openvino-dev                2023.0.0
openvino-telemetry          2023.1.1
```

After that, the 2 problems are still there. Also tried installing `"openvino-dev==2023.1.0dev20230811"`, but have the same results.

**Comment by eaidova** [comment]
@dnoliver thank you for letting us know, I reproduced reported issues. You can fix for that in this PR https://github.com/openvinotoolkit/openvino_notebooks/pull/1308
