### ISSUE TITLE
cannot import name 'mo' from 'openvino.tools'

### ISSUE THREAD

**Issue by andysingal** [openvinotoolkit/openvino_notebooks#1303]
**Describe the bug**
A clear and concise description of what the bug is, including steps to reproduce the bug if possible.
openViNO notebook following: https://docs.openvino.ai/2023.0/notebooks/233-blip-visual-language-processing-with-output.html
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-9-2c30ea245db0>](https://localhost:8080/#) in <cell line: 3>()
      1 import torch
      2 from pathlib import Path
----> 3 from openvino.tools import mo
      4 from openvino.runtime import Core, serialize
      5 

ImportError: cannot import name 'mo' from 'openvino.tools' (/usr/local/lib/python3.10/dist-packages/openvino/tools/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```
```
where is the blip_vision_model.xml file?"
```

 **Expected behavior**

**Screenshots**
```
link to the notebook: https://colab.research.google.com/drive/1tn6Ty24oHrwV3IGJWLO2GL2XTWIsdGMr?usp=sharing
```

 **Installation instructions (Please mark the checkbox)**
[  ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
Please run `python check_install.py` in the _openvino_notebooks_ directory. If the output is _NOT OK_ for any of the checks, please follow the instructions to fix that. If that does not work, or if you still encounter the issue, please paste the output of check_install.py here.
 
**Additional context**

**Comment by Wan-Intel** [comment]
I've validated [Visual Question Answering and Image Captioning using BLIP and OpenVINO](https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/233-blip-visual-language-processing) from the latest repo and it works fine.

![233_ok](https://github.com/openvinotoolkit/openvino_notebooks/assets/123156917/27be24f9-f750-4822-9211-c636feae214f)

May I know which version of Python and Operating System are you using on your machine? Could you please reinstall OpenVINO Notebooks and see if your issue can be resolved?

**Comment by andysingal** [comment]
3.10 - python

**Comment by Wan-Intel** [comment]
Referring to [System Requirements](https://github.com/openvinotoolkit/openvino_notebooks#%EF%B8%8F-system-requirements), Python 3.10 is supported.

Have you reinstalled the [latest OpenVINO Notebooks](https://github.com/openvinotoolkit/openvino_notebooks) on your machine?

**Comment by andysingal** [comment]
Yes, I installed the version shared in your notebook

**Comment by Wan-Intel** [comment]
Does [Visual Question Answering and Image Captioning using BLIP and OpenVINO](https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/233-blip-visual-language-processing) work on your machine?

**Comment by andysingal** [comment]
It is actually giving error as shared

**Comment by Wan-Intel** [comment]
I've validated the sample in Jupyter lab and it's working fine.

Could you please launch the notebook with the commands as follow and see if your issue can be resolved?

```
source openvino_env/bin/activate

cd openvino_notebooks

jupyter lab notebooks/233-blip-visual-language-processing.ipynb
```

**Comment by andysingal** [comment]
Let me try it again and will let you know

**Comment by eaidova** [comment]
@andysingal does error happends in local environment or your provided colab?

In your install inside colab, you install only `openvino` package, however `openvino.tools.mo` is provided in `openvino-dev`. Probably, it happens because your coping requirement from the latest notebook, but use old code. For openvino release 2023.1.0 we reworked notebook for avoid using mo tool and simplify the conversion step, so I can recommend add openvino-dev into your install
```
%pip install -q openvino-dev>=2023.1.0

 or take a look at updated notebook and use updated code

**Comment by andysingal** [comment]
It happens in provided colab

**Comment by Wan-Intel** [comment]
Just wanted to follow up and see if your issue has been resolved after installing openvino-dev with the command:
`%pip install -q openvino-dev>=2023.1.0`

**Comment by Wan-Intel** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
