### ISSUE TITLE
[How to] Connect with fellow developers?

### ISSUE THREAD

**Issue by mahimairaja** [openvinotoolkit/openvino_notebooks#1335]
I find this [OpenVINO Notebooks](https://github.com/openvinotoolkit/openvino_notebooks/) repo much useful to demonstrate the practical usage of OpenVINO Toolkit in python. I would like to know is there any platform like `slack` or `discord` for the particular repo. Would love to join and contribute...

**Comment by andrei-kochin** [comment]
Hello @mahimairaja,
Unfortunately we don't have established public channels except posts here. We'll discuss internally regarding this. So far feel free to post questions/suggestions here

**Comment by mahimairaja** [comment]
Gotcha...
