### ISSUE TITLE
236 STABLE

### ISSUE THREAD

**Issue by alberxualberxu** [openvinotoolkit/openvino_notebooks#1346]
**Describe the bug**
A clear and concise description of what the bug is, including steps to reproduce the bug if possible.

 **Expected behavior**

**Screenshots**

 **Installation instructions (Please mark the checkbox)**
[  ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
Please run `python check_install.py` in the _openvino_notebooks_ directory. If the output is _NOT OK_ for any of the checks, please follow the instructions to fix that. If that does not work, or if you still encounter the issue, please paste the output of check_install.py here.
 
**Additional context**

**Comment by alberxualberxu** [comment]
Out black image when running 236 with default setting

![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/102842442/48e11366-20aa-45ba-9e09-59a6f56eb91b)

**Comment by eaidova** [comment]
@alberxualberxu could you please check updated notebook version?
this PR https://github.com/openvinotoolkit/openvino_notebooks/pull/1347 should fix black screen issue
