### ISSUE TITLE
Torch version 1.13.1+cpu cannot be found

### ISSUE THREAD

**Issue by Samarthrawat1** [openvinotoolkit/openvino_notebooks#1358]
**Describe the bug**
Requirements.txt not met. Torch cannot be fetched.

error:
ERROR: Could not find a version that satisfies the requirement torch==1.13.1+cpu (from versions: 2.0.0, 2.0.0+cpu, 2.0.0+cu117, 2.0.0+cu118, 2.0.1, 2.0.1+cpu, 2.0.1+cu117, 2.0.1+cu118)
ERROR: No matching distribution found for torch==1.13.1+cpu

 **Expected behavior**
Successful Installation

**Screenshots**
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/63748920/e0fab16b-1a52-4ef6-839d-355b03be57e4)

 **Installation instructions (Please mark the checkbox)**
[ * ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
Still Installing
 
**Additional context**
None

**Comment by Samarthrawat1** [comment]
Update: I have installed the latest versions of the torch(2.0.1+cpu) and torchvision(0.15.2+cpu). However, testing is still required to see if it breaks anything.

**Comment by Samarthrawat1** [comment]
> Can you describe your environment, please? Which OperationSystem in which version do you use (or which virt-env have you created)?
> 
> Looks like your OS version is newer than what is suported (like Ubuntu v23).
> 
> Can you check with "https://github.com/openvinotoolkit/openvino_notebooks#%EF%B8%8F-system-requirements" on the supported OS, please?

I am on windows 11 right now and python version is python3.11

**Comment by brmarkus** [comment]
From "https://github.com/openvinotoolkit/openvino_notebooks#%EF%B8%8F-system-requirements" MS-Windows up to Windows v10 and Python v3.10 is supported...

**Comment by Samarthrawat1** [comment]
okay thank you all
