### ISSUE TITLE
Add OpenVINO version of Mistral 7B - notebook

### ISSUE THREAD

**Issue by mahimairaja** [openvinotoolkit/openvino_notebooks#1365]
Mistral 7B is been the most powerful model in the open source LLM as of now in less parameter size. It would great to have the wonderful version of OpenVINO flavor with it.

**Comment by eaidova** [comment]
we have mistral and zephyr support in our llm chatbot notebook
https://github.com/openvinotoolkit/openvino_notebooks/pull/1505
