### ISSUE TITLE
Intelligent Queue Manager Recipe - utils.py gets the incorrect file size if the file is compressed

### ISSUE THREAD

**Issue by dnoliver** [openvinotoolkit/openvino_notebooks#1373]
**Describe the bug**
A clear and concise description of what the bug is, including steps to reproduce the bug if possible.

In this line https://github.com/openvinotoolkit/openvino_notebooks/blob/recipes/recipes/intelligent_queue_management/utils.py#L156-L158 (in the `recipes` branch), when the code do the request, it gets the file size in the 'Content-length' header.

The value is then used in this line https://github.com/openvinotoolkit/openvino_notebooks/blob/recipes/recipes/intelligent_queue_management/utils.py#L171.

When the file is compressed in the remote server, the size reported by the first call is the size of the compressed file, not the actual file size. This triggers the re-download of the file all the time.

In this line, the sample gets a file from raw.githubusercontent.com https://github.com/openvinotoolkit/openvino_notebooks/blob/recipes/recipes/intelligent_queue_management/convert_and_optimize.py#L18, which happens to be compressed, so the `coco.yaml` file always get downloaded

This behavior is described in https://github.com/psf/requests/issues/5319#issuecomment-575946480

It can be avoided by setting the Accept-Encoding: Identity flag in the first call:

```
response = requests.get(
            url=url, headers={"User-agent": "Mozilla/5.0", "Accept-Encoding": "identity"}, stream=True
        )
```

 **Expected behavior**

Files should not be downloaded if they are already in the target location

**Screenshots**

In the following text (kind of ugly), you can see how coco.yaml gets the wrong size and triggers the download

```
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, tensorflow, onnx, openvino Ultralytics YOLOv8.0.43 🚀 Python-3.8.0 torch-2.0.1+cu117 CPU YOLOv8m summary (fused): 218 layers, 25886080 parameters, 0 gradients, 78.9 GFLOPs PyTorch: starting from model/yolov8m.pt with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (49.7 MB) ONNX: starting export with onnx 1.12.0... ============= Diagnostic Run torch.onnx.export version 2.0.1+cu117 ============= verbose: False, log level: Level.ERROR ======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ======================== ONNX: export success ✅ 2.1s, saved as model/yolov8m.onnx (99.0 MB) OpenVINO: starting export with openvino 2023.0.0-10926-b4452d56304-releases/2023/0... OpenVINO: export success ✅ 2.5s, saved as model/yolov8m_openvino_model/ (49.8 MB) Export complete (5.4s) Results saved to /home/u1012399/Reference-samples/iot-devcloud/openvino-dev-latest/developer-samples/python/intelligent-queue-management/model Predict: yolo predict task=detect model=model/yolov8m_openvino_model imgsz=640 Validate: yolo val task=detect model=model/yolov8m_openvino_model imgsz=640 data=coco.yaml Visualize: [https://netron.app|https://netron.app/]

DEBUG
 815585330
 os.stat_result(st_mode=33277, st_ino=133993840, st_dev=49, st_nlink=1, st_uid=0, st_gid=1360, st_size=815585330, st_atime=1696964269, st_mtime=1696964272, st_ctime=1696968781) 'data/val2017.zip' already exists.

 DEBUG 176694178 os.stat_result(st_mode=33277, st_ino=133994222, st_dev=49, st_nlink=1, st_uid=0, st_gid=1360, st_size=176694178, st_atime=1696964273, st_mtime=1696964273, st_ctime=1696968474) 'data/coco2017labels-segments.zip' already exists. 

DEBUG 1280 os.stat_result(st_mode=33277, st_ino=133994223, st_dev=49, st_nlink=1, st_uid=0, st_gid=1360, st_size=2521, st_atime=1696969338, st_mtime=1696964274, st_ctime=1696968474) data/coco.yaml: 0%| | 0.00/1.25k [00:00<?, ?B/s]
```

 **Installation instructions (Please mark the checkbox)**
[  ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

This is from DevCloud for the Edge

** Environment information **
Please run `python check_install.py` in the _openvino_notebooks_ directory. If the output is _NOT OK_ for any of the checks, please follow the instructions to fix that. If that does not work, or if you still encounter the issue, please paste the output of check_install.py here.

This is from DevCloud for the Edge
 
**Additional context**

**Comment by adrianboguszewski** [comment]
The fix was merged, so I expect it should work now. If not, please reopen.

**Comment by dnoliver** [comment]
Works great, thank you!
