### ISSUE TITLE
OpenVINO RHEL9 support

### ISSUE THREAD

**Issue by vbedida79** [openvinotoolkit/openvino_notebooks#1400]
**Describe the bug**
We are using the [openvino operator](https://github.com/openvinotoolkit/operator) on OCP 4.13 Red Hat Core OS system- based on RHEL 9.2 with Intel Data Center Flex GPU. The notebook custom resource  based on the [notebook image](https://github.com/openvinotoolkit/openvino_notebooks/blob/main/Dockerfile) uses RHEL 8.5 GPU repo, its dependent libraries and UBI8 image.

 **Expected behavior**
Is it possible or planned to add support for RHEL 9 in [system requirements](https://github.com/openvinotoolkit/openvino_notebooks/tree/main#%EF%B8%8F-system-requirements) For docker image, there is s2i-thoth-ubi9-py39 based image, can that help? Would pipenv need to be updated to 3.9 as well and any other significant changes to be noted?

**Screenshots**

 **Installation instructions (Please mark the checkbox)**
[  ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
OpenShift 4.13.10.  OpenVINO notebook Custom resource created according to  [readme](https://github.com/openvinotoolkit/operator/blob/main/docs/notebook_in_rhods.md) .
 
**Additional context**

**Comment by avitial** [comment]
Ref. 126679

**Comment by ilya-lavrenov** [comment]
Hi @vbedida79 
Existing OpenVINO archives, Pip and RPM packages can be installed and used on all RHEL released versions (up to 9.4 for now).
Please, have a try.
