### ISSUE TITLE
Security Issue with Windows 11 - PowerShell

### ISSUE THREAD

**Issue by raymondlo84** [openvinotoolkit/openvino_notebooks#141]
It looks like Windows 11 added another layer of security and enabling the virtual environment is non-trivial with the PowerShell (which is the new default 'Terminal')...

```

PS C:\Users\raymo\Documents> python -m venv openvino_env
PS C:\Users\raymo\Documents> openvino_env\Scripts\activate
openvino_env\Scripts\activate : File C:\Users\raymo\Documents\openvino_env\Scripts\Activate.ps1 cannot be loaded
because running scripts is disabled on this system. For more information, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ openvino_env\Scripts\activate
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

**Comment by raymondlo84** [comment]
We should maybe add this to the known issue. Have to use this workaround. 
https://stackoverflow.com/questions/18713086/virtualenv-wont-activate-on-windows

**Comment by helena-intel** [comment]
In the Windows instructions we say to use cmd.exe, not Powershell. Does that still work on Windows 11? https://github.com/openvinotoolkit/openvino_notebooks/wiki/Windows

**Comment by raymondlo84** [comment]
Ooo! Yes, it works with cmd... and tested the workaround and it works with Powershell too. Phew. 

Windows 11 now makes PowerShell the default. :\ 

![image](https://user-images.githubusercontent.com/1720147/124335201-6bf3bd80-db4e-11eb-9657-705cffc095ae.png)

**Comment by helena-intel** [comment]
We mention this in the troubleshooting section in the main README and in the Windows guide. Do you think more is needed @raymondlo84 ?
For me in Windows 10 Powershell has also been the default when shift right clicking on a folder for some time now (and with just right click there is also no "open with cmd.exe" either).

**Comment by raymondlo84** [comment]
Got it!
