### ISSUE TITLE
240-dolly-2-instruction-following uses a deprecated Gradio API (enable_queue=True)

### ISSUE THREAD

**Issue by dnoliver** [openvinotoolkit/openvino_notebooks#1415]
**Describe the bug**
A clear and concise description of what the bug is, including steps to reproduce the bug if possible.

With the latest version of Gradio (4.0.2 in our tests), the `enable_queue=True` parameter has been changed to `queue()`.
Using `enable_queue` makes the demo crash (see screenshots)

Dolly is using enable_queue, so the demo can't run with latest Gradio: https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/240-dolly-2-instruction-following/240-dolly-2-instruction-following.ipynb?short_path=5d88ad5#L702-L706

 **Expected behavior**

Demo should run with latest gradio versions

**Screenshots**

With `enable_queue=True`

![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/7730267/93c85d24-e1a9-4572-ab57-20365573d3b1)

With `queue()`

![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/7730267/eda315de-649d-4870-964f-1a5a0ea6b8fa)

 **Installation instructions (Please mark the checkbox)**
[  ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
Please run `python check_install.py` in the _openvino_notebooks_ directory. If the output is _NOT OK_ for any of the checks, please follow the instructions to fix that. If that does not work, or if you still encounter the issue, please paste the output of check_install.py here.
 
**Additional context**

This is on Developer Cloud for the Edge (but I am guessing it is also reproducible in other environment)

**Comment by eaidova** [comment]
@itrushkin  could you please take a look?

**Comment by avitial** [comment]
[PR 1422](https://github.com/openvinotoolkit/openvino_notebooks/pull/1422) with fix has been merged to main branch. Closing this as issue has been addressed. Feel free to reopen and ask any questions related to this topic.
