### ISSUE TITLE
2022.3版本的openvino有提供AsyncInferQueue类c++接口吗

### ISSUE THREAD

**Issue by xiaoxia8** [openvinotoolkit/openvino_notebooks#1416]
如题，2022.3版本的openvino有提供AsyncInferQueue类c++接口吗？目前只看到了Python接口的AsyncInferQueue类。

**Comment by OpenVINO-dev-contest** [comment]
目前没有相对应的C++接口，可以参考这里类似功能的实现：
https://github.com/openvinotoolkit/openvino/tree/master/samples/cpp/classification_sample_async
