### ISSUE TITLE
Error @ PaddleGAN pip install after Tensorflow 2.5.0 added

### ISSUE THREAD

**Issue by raymondlo84** [openvinotoolkit/openvino_notebooks#142]
The "pip install" now returned this error/warning. Is that normal? 

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.5.0 requires gast==0.4.0, but you have gast 0.3.3 which is incompatible.
```

**Comment by helena-intel** [comment]
I do not see this error on a clean install of the notebook requirements and then installing paddlepaddle (tried on Ubuntu 20, Python 3.8). Can you share more info about your configuration (OS/Python version)?

**Comment by raymondlo84** [comment]
Just validated that paddlegan install will override Tensorflow 2.5.0's numpy and gast because it uses --upgrade command.

**Comment by raymondlo84** [comment]
Windows 11, Python 3.7

**Comment by helena-intel** [comment]
> Just validated that paddlegan install will override Tensorflow 2.5.0's numpy and gast because it uses --upgrade command.

The `--upgrade` command does not upgrade dependencies by default. 

I just checked this on Windows 10 with Python 3.7 and it doesn't happen for me. PaddlePaddle does not override numpy or gast. This is what it installs for me:

```
Installing collected packages: llvmlite, numba, soundfile, resampy, audioread, munch, librosa, imageio-ffmpeg, easydict, astor, ppgan, paddlepaddle, paddle2onnx
Successfully installed astor-0.8.1 audioread-2.1.9 easydict-1.9 imageio-ffmpeg-0.4.4 librosa-0.7.0 llvmlite-0.31.0 munch-2.5.0 numba-0.48.0 paddle2onnx-0.6 paddlepaddle-2.1.1 ppgan-2.0.0 resampy-0.2.2 soundfile-0.10.3.post1
```

Can you check which version of PaddlePaddle is installed in your environment? The error gives me the impression that it is not 2.1, but the `--upgrade` should install 2.1. If it is not 2.1, I wonder if there is a mismatch between your virtual environment and jupyter kernel. That can happen if at some point you made a new openvino_env environment but did not install the jupyter kernel there. Easiest way to check for now is to remove your openvino_env directory and also do `jupyter kernelspec remove openvino_env` and then install again, and create the kernel again.
