### ISSUE TITLE
POT Slow Performance @ Training Step

### ISSUE THREAD

**Issue by raymondlo84** [openvinotoolkit/openvino_notebooks#143]
I think somehow the training performance is almost 1/2 when we run the training step through the POT notebooks. Not sure but here are my outputs.

![scrnli_7_2_2021_3-03-43 PM](https://user-images.githubusercontent.com/1720147/124332635-c25cfe00-db46-11eb-8003-9fa6322b26c9.png)
![scrnli_7_2_2021_3-03-41 PM](https://user-images.githubusercontent.com/1720147/124332638-c2f59480-db46-11eb-9d14-a13e5ae574b5.png)

**Comment by raymondlo84** [comment]
My guess is the OneDNN should be enabled before we import TF? Maybe that's somehow related . . .

**Comment by helena-intel** [comment]
Yes, that is very likely the cause. I can add that line to the POT notebook too. TF 2.6 is almost out too, and then this will be automatic.

**Comment by helena-intel** [comment]
Since we use TF 2.4 again (aligining with openvino-dev requirements (#146) training speed is now the same in both notebooks, since the OneDNN speedup only works in 2.5+.  It is sad to lose this speedup but there is no discrepancy anymore.
