### ISSUE TITLE
How to run Openvino with FPGA

### ISSUE THREAD

**Issue by lhf552004** [openvinotoolkit/openvino_notebooks#1441]
Hi, I'm looking for the support of FPGA with DE10 Agilex.

How can I use Openvino to program in the FPGA board?

Thanks
Best Regards

**Comment by avitial** [comment]
@lhf552004 take a look at the following user guide: [Intel® FPGA AI Suite PCIe-based Design Example User Guide](https://www.intel.com/content/www/us/en/docs/programmable/768977/2023-2-1/pcie-based-design-example-user-guide-00730.html). Based on the information provided there it seems possible to use "Intel® PAC with Intel® Arria® 10 GX FPGA or a Terasic* DE10-Agilex Development Board" for the guide, hope this helps.

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and provide additional information or ask any questions related to this topic.
