### ISSUE TITLE
254-llm-chatbot.ipynb llama2 model defaults to Mandarin prompts which I do not think is intentional.

### ISSUE THREAD

**Issue by stokesj0001** [openvinotoolkit/openvino_notebooks#1470]
**Describe the bug**
254-llm-chatbot.ipynb llama2 model defaults to mandarin prompts.

 **Expected behavior**
Only models Qwen and Chatgml should have mandarin prompts.

**Screenshots**
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/97129360/416d6012-4cc6-49a2-9cb5-6a4e81f087ea)

** Environment information **
Notebooks are running in a cloud enviroment.
 
**Additional context**
Potential fix, change if statement to the commented out line.
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/97129360/a0caec6c-8149-4261-89b4-94866152a011)

A related issue is that there appears to be a 1 off error in defining the variable 'model_type'. The commented out code is a potential fix.
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/97129360/e3123d9b-9630-4409-aa72-50f734d3622e)

**Comment by eaidova** [comment]
@stokesj0001 thank you for note! we fixed this in this PR https://github.com/openvinotoolkit/openvino_notebooks/pull/1473

**Comment by stokesj0001** [comment]
As of commit https://github.com/openvinotoolkit/openvino_notebooks/pull/1475 this issue appears resolved.
