### ISSUE TITLE
need to update the document for 405-paddle-ocr-webcam

### ISSUE THREAD

**Issue by junxnone** [openvinotoolkit/openvino_notebooks#1484]
The document for [405-paddle-ocr-webcam](https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/405-paddle-ocr-webcam) says:
> PaddleOCR performs the Optical Character Recognition (OCR) function from a video, an image, or a scanned document. It is mainly composed of three parts: DB text detection, detection frame correction and CRNN text recognition.

it is for PPOCR v2, CRNN not used in [PPOCR v3](https://github.com/PaddlePaddle/PaddleOCR/blob/4b17511491adcfd0f3e2970895d06814d1ce56cc/doc/doc_en/PP-OCRv3_introduction_en.md)

> base model of recognition network is replaced from CRNN to SVTR

need to update the [README here](https://github.com/openvinotoolkit/openvino_notebooks/commit/1666d55ecd984f9b8906a50c97f8fc19dd5e4239#diff-128ee685ad8d1d1f529d1bc007b33616efc60a3303c1919ab3b71d4e36f28a7aL6)

**Comment by OpenVINO-dev-contest** [comment]
Hi @zhuo-yoyowz could you help to check ?

**Comment by zhuo-yoyowz** [comment]
Have submitted a PR to update the Readme. Thanks for pointing out.

**Comment by eaidova** [comment]
PR with fix merged
