### ISSUE TITLE
Llama 2 7B

### ISSUE THREAD

**Issue by choochtech** [openvinotoolkit/openvino_notebooks#1488]
When converting the Llama 2 7B to int4 the Kernel dies.

https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/254-llm-chatbot

What type of AWS or Azure device do I need to quantize ?  I am using a m6a.2xlarge AWS device. ( 3rd Generation Intel Xeon Scalable processor)

Thanks

**Comment by mahimairaja** [comment]
Hi @choochtech 

You would probably need 28gigs of VRam for the first time loading alone

I would suggest you to go with - <b> *m6a.8xlarge*

**Comment by choochtech** [comment]
Thanks

**Comment by avitial** [comment]
Closing this issue, I hope previous responses were sufficient to help you proceed. Feel free to reopen to ask any questions related to this topic.
