### ISSUE TITLE
Cannot compress LLama weights

### ISSUE THREAD

**Issue by plischwe** [openvinotoolkit/openvino_notebooks#1494]
In notebook 254-llm-chatb-7b, I run the cell to "save floating point and compress model variants" after choosing the LLama-2-chat-7b and INT8 model, but I get an URL open error that eventually causes the kernel to die- as seen in screenshot attached.
![Screenshot from 2023-11-27 17-41-32](https://github.com/openvinotoolkit/openvino_notebooks/assets/103980143/b86b19e5-59c2-4931-8904-d28bbfe6637e)

I am not sure if this is a memory problem, as I would expect to see an "out of memory error" - but am running out of other reasons for what could be causing this. My machine is an Intel® NUC 13 Extreme Kit - NUC13RNGi9 which has ~32Gb CPU memory which I believe is being used although I also have iGPU (Intel® UHD Graphics 770) and dGPU, which has 32Gb VRAM which I suspect is not being used. I have encountered this same issue on another machine with CPU only and 32Gb mem as well.

I followed the ubuntu installation guide, and successfully ran the hello-world notebook. Thanks in advance.

These are the packages installed in my virtual env:
---------------------------- --------------------
about-time                   4.2.1
absl-py                      2.0.0
accelerate                   0.24.1
addict                       2.4.0
aiofiles                     23.2.1
aiohttp                      3.8.6
aiosignal                    1.3.1
alive-progress               3.1.5
altair                       5.1.2
annotated-types              0.6.0
anyio                        3.7.1
argon2-cffi                  23.1.0
argon2-cffi-bindings         21.2.0
arrow                        1.3.0
asttokens                    2.4.1
astunparse                   1.6.3
async-lru                    2.0.4
async-timeout                4.0.3
attrs                        23.1.0
autograd                     1.6.2
Babel                        2.13.1
beautifulsoup4               4.12.2
bleach                       6.1.0
cachetools                   5.3.2
certifi                      2023.7.22
cffi                         1.16.0
charset-normalizer           3.3.2
click                        8.1.7
cma                          3.2.2
colorama                     0.4.6
coloredlogs                  15.0.1
comm                         0.2.0
cryptography                 41.0.5
cycler                       0.12.1
datasets                     2.14.7
debugpy                      1.8.0
decorator                    5.1.1
defusedxml                   0.7.1
Deprecated                   1.2.14
dill                         0.3.7
einops                       0.7.0
exceptiongroup               1.1.3
executing                    2.0.1
fastapi                      0.104.1
fastjsonschema               2.19.0
ffmpy                        0.3.1
filelock                     3.13.1
flatbuffers                  23.5.26
fonttools                    4.44.3
fqdn                         1.5.1
frozenlist                   1.4.0
fsspec                       2023.10.0
future                       0.18.3
gast                         0.5.4
google-auth                  2.23.4
google-auth-oauthlib         1.0.0
google-pasta                 0.2.0
gradio                       4.3.0
gradio_client                0.7.0
grapheme                     0.6.0
grpcio                       1.59.2
h11                          0.14.0
h5py                         3.10.0
httpcore                     1.0.2
httpx                        0.25.1
huggingface-hub              0.19.3
humanfriendly                10.0
idna                         3.4
imageio                      2.32.0
importlib-resources          6.1.1
ipykernel                    6.26.0
ipython                      8.17.2
ipywidgets                   8.1.1
isoduration                  20.11.0
jedi                         0.19.1
Jinja2                       3.1.2
joblib                       1.3.2
json5                        0.9.14
jsonpointer                  2.4
jsonschema                   4.19.2
jsonschema-specifications    2023.11.1
jstyleson                    0.0.2
jupyter_client               8.6.0
jupyter_core                 5.5.0
jupyter-events               0.9.0
jupyter-lsp                  2.2.0
jupyter_server               2.10.1
jupyter_server_terminals     0.4.4
jupyterlab                   4.0.8
jupyterlab-pygments          0.2.2
jupyterlab_server            2.25.1
jupyterlab-widgets           3.0.9
keras                        2.14.0
kiwisolver                   1.4.5
lazy_loader                  0.3
libclang                     16.0.6
Markdown                     3.5.1
markdown-it-py               3.0.0
MarkupSafe                   2.1.3
matplotlib                   3.5.2
matplotlib-inline            0.1.6
mdurl                        0.1.2
mistune                      3.0.2
ml-dtypes                    0.2.0
mpmath                       1.3.0
multidict                    6.0.4
multiprocess                 0.70.15
natsort                      8.4.0
nbclient                     0.9.0
nbconvert                    7.11.0
nbformat                     5.9.2
ndg-httpsclient              0.5.1
nest-asyncio                 1.5.8
networkx                     2.8.2
ninja                        1.10.2.4
nncf                         2.7.0.dev0+c2529611
notebook_shim                0.2.3
numpy                        1.24.4
oauthlib                     3.2.2
onnx                         1.15.0
opencv-python                4.8.1.78
openvino-nightly             2023.3.0.dev20231127
openvino-telemetry           2023.2.1
opt-einsum                   3.3.0
optimum                      1.14.1
optimum-intel                1.13.0.dev0
orjson                       3.9.10
overrides                    7.4.0
packaging                    23.2
pandas                       2.0.3
pandocfilters                1.5.0
parso                        0.8.3
pexpect                      4.8.0
Pillow                       10.0.1
pip                          23.3.1
platformdirs                 4.0.0
prometheus-client            0.18.0
prompt-toolkit               3.0.41
protobuf                     4.25.0
psutil                       5.9.6
ptyprocess                   0.7.0
pure-eval                    0.2.2
pyarrow                      14.0.1
pyarrow-hotfix               0.5
pyasn1                       0.5.0
pyasn1-modules               0.3.0
pycparser                    2.21
pydantic                     2.5.1
pydantic_core                2.14.3
pydot                        1.4.2
pydub                        0.25.1
Pygments                     2.16.1
pymoo                        0.6.0.1
pyOpenSSL                    23.3.0
pyparsing                    2.4.7
python-dateutil              2.8.2
python-json-logger           2.0.7
python-multipart             0.0.6
pytz                         2023.3.post1
PyYAML                       6.0.1
pyzmq                        25.1.1
referencing                  0.31.0
regex                        2023.10.3
requests                     2.31.0
requests-oauthlib            1.3.1
rfc3339-validator            0.1.4
rfc3986-validator            0.1.1
rich                         13.7.0
rpds-py                      0.12.0
rsa                          4.9
safetensors                  0.4.0
scikit-image                 0.22.0
scikit-learn                 1.3.2
scipy                        1.10.1
seaborn                      0.13.0
semantic-version             2.10.0
Send2Trash                   1.8.2
sentencepiece                0.1.99
sentry-sdk                   1.35.0
setuptools                   59.6.0
shellingham                  1.5.4
six                          1.16.0
sniffio                      1.3.0
soupsieve                    2.5
stack-data                   0.6.3
starlette                    0.27.0
sympy                        1.12
tensorboard                  2.14.1
tensorboard-data-server      0.7.2
tensorflow                   2.14.0
tensorflow-estimator         2.14.0
tensorflow-io-gcs-filesystem 0.34.0
termcolor                    2.3.0
terminado                    0.18.0
texttable                    1.7.0
thop                         0.1.1.post2209072238
threadpoolctl                3.2.0
tifffile                     2023.9.26
tinycss2                     1.2.1
tokenizers                   0.15.0
tomli                        2.0.1
tomlkit                      0.12.0
toolz                        0.12.0
torch                        2.1.0+cpu
torchaudio                   2.1.0+cpu
torchvision                  0.16.0+cpu
tornado                      6.3.3
tqdm                         4.66.1
traitlets                    5.13.0
transformers                 4.35.2
typer                        0.9.0
types-python-dateutil        2.8.19.14
typing_extensions            4.8.0
tzdata                       2023.3
ultralytics                  8.0.43
uri-template                 1.3.0
urllib3                      2.1.0
uvicorn                      0.24.0.post1
wcwidth                      0.2.10
webcolors                    1.13
webencodings                 0.5.1
websocket-client             1.6.4
websockets                   11.0.3
Werkzeug                     3.0.1
wheel                        0.41.3
widgetsnbextension           4.0.9
wrapt                        1.14.1
xxhash                       3.4.1
yarl                         1.9.2

**Comment by plischwe** [comment]
My hf account is logged in and has access to the gated model when I run the jupyter notebook. I also use one of my authentication tokens to login into my account through the jupyter notebook using lines:

from huggingface_hub import login 
login() 

which I am then prompted to insert my authentication token, which gets properly validated. I know this method of logging in has worked for others - I'm not sure why I wouldn't have access to the model. Thanks.

**Comment by YuChern-Intel** [comment]
My request to access the Llama-2-7b-chat-hf model on Hugging Face still in pending.

In a meanwhile, please ensure that you have followed the instruction below:
Please visit [HuggingFace model card](https://huggingface.co/meta-llama/Llama-2-7b-chat-hf), carefully read terms of usage and click accept button in [Meta website](https://ai.meta.com/resources/models-and-libraries/llama-downloads). You will need to use an access token for downloading model. For more information on access tokens, refer to [this section of the documentation](https://huggingface.co/docs/hub/security-tokens).

**Comment by YuChern-Intel** [comment]
After my access is approved , I programmatically login using [login()](https://huggingface.co/docs/huggingface_hub/v0.19.3/en/package_reference/login#huggingface_hub.login) in Jupyter Notebook with my authentication token to download Llama-2-7b-chat-hf model. 
![login](https://github.com/openvinotoolkit/openvino_notebooks/assets/107900329/ab80949a-3797-4a3a-a51c-12b070dfd677)


In the step of saving floating point and compress model variants, I also encountered similar error as you but successfully execute the cell without kernel dead. 
![error](https://github.com/openvinotoolkit/openvino_notebooks/assets/107900329/93f12e9c-5218-4b39-9da7-d9935dc438f6)

At last, I am able to run the demo.
![demo](https://github.com/openvinotoolkit/openvino_notebooks/assets/107900329/e705707e-ac5b-47b8-b9ae-7133c85c0db0)

**Comment by YuChern-Intel** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic, if issue persists kindly share the requested information.
