### ISSUE TITLE
Docker build failed on main branch 

### ISSUE THREAD

**Issue by tom2002965** [openvinotoolkit/openvino_notebooks#1551]
**Describe the bug**
Hi, I followed [this tutorial](https://github.com/openvinotoolkit/openvino_notebooks/wiki/Docker) to build image, but it raised  jupyter-client version confict.
`pkg_resources.ContextualVersionConflict: (jupyter-client 8.6.0 (/opt/app-root/lib/python3.8/site-packages), Requirement.parse('jupyter-client<8,>=5.3.4'), {'notebook'})`
I have tried two different PC but got same issue. 

Solved this issue by changing to release branch.
It seemed some package needed to fix.

 **Expected behavior**

**Screenshots**
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/13653759/3b8493d3-85f5-4347-8b56-b4ff7cd863a6)

 **Installation instructions (Please mark the checkbox)**
[ o ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
Please run `python check_install.py` in the _openvino_notebooks_ directory. If the output is _NOT OK_ for any of the checks, please follow the instructions to fix that. If that does not work, or if you still encounter the issue, please paste the output of check_install.py here.
 
**Additional context**

**Comment by eaidova** [comment]
@tom2002965 Hello, here PR that should fix docker build issue https://github.com/openvinotoolkit/openvino_notebooks/pull/1563

**Comment by tom2002965** [comment]
It's worked, thank you!
