### ISSUE TITLE
Does nncf support qwen-1.8B or  phi-2 ? 

### ISSUE THREAD

**Issue by sanbuphy** [openvinotoolkit/openvino_notebooks#1561]
**Describe the bug**

Hello, I came across some usage instructions for the qwen model in Jupyter Notebook(254-llm-chatbot), but it seems that there is no specific guide for using qwen 1.8B. I attempted to modify the corresponding code to work with the 1.8B version, but it doesn't seem to run successfully. Could you please advise me on what steps I should take? Thank you.

 **Installation instructions (Please mark the checkbox)**
[ yes ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

**Additional context**
`qwen/Qwen-1_8B-Chat`
It seems that there are some issues with quantization accuracy loss occurring.
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/96160062/2a9ef30f-2c7c-4795-91f9-f795f28724d6)

![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/96160062/45aa598a-ab39-455c-8def-5bfdf27b6992)

**Comment by OpenVINO-dev-contest** [comment]
Hi @sanbuphy  Thanks for your feedback

How about the accuracy of FP16 version ?

**Comment by sanbuphy** [comment]
> Hi @sanbuphy Thanks for your feedback
> 
> How about the accuracy of FP16 version ?

Ok, Let me check

**Comment by sanbuphy** [comment]
> Hi @sanbuphy Thanks for your feedback
> 
> How about the accuracy of FP16 version ?

same error:
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/96160062/69680d54-d0fc-4c71-bd0c-5feb3cc3616e)

**Comment by sanbuphy** [comment]
@OpenVINO-dev-contest  Hi, Can i try this again now ?

**Comment by eaidova** [comment]
@sanbuphy regarding ph-2 support, unfortunatly, this model is not good in chatbot scenario as it is not fine-tuned for this case. We prepared separated demo, that allow you run it as text generator for answering questions or following instructions:
https://github.com/openvinotoolkit/openvino_notebooks/pull/1577
The only limitation that our model support is based on model implementation from transformers lib and original phi-2 model is not migrated on it yet (hope migration happens soon based on discussions on hf hub)

**Comment by sanbuphy** [comment]
> @sanbuphy regarding ph-2 support, unfortunatly, this model is not good in chatbot scenario as it is not fine-tuned for this case. We prepared separated demo, that allow you run it as text generator for answering questions or following instructions: #1577 The only limitation that our model support is based on model implementation from transformers lib and original phi-2 model is not migrated on it yet (hope migration happens soon based on discussions on hf hub)

Thank you !  get it ,so, I just need to wait for qwen to fix the issues, as it seems there are still some bugs present.

**Comment by OpenVINO-dev-contest** [comment]
> qwen/Qwen-1_8B-Chat

Hi I think Qwen-7b-chat can work now, and we are trying to enable Qwen-1_8B-Chat.  We will keep you in tune. thanks

**Comment by fengenbao** [comment]
> > qwen/Qwen-1_8B-Chat
> 
> Hi I think Qwen-7b-chat can work now, and we are trying to enable Qwen-1_8B-Chat. We will keep you in tune. thanks

Does Openbino currently support the Qwen-14B-Chat model?Or baichuan-13B-Chat model, because 7B or 6B models are still too weak

**Comment by OpenVINO-dev-contest** [comment]
LLM notebook is updated with QWEN1.5-1.8b, pls check:
https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/254-llm-chatbot

**Comment by sanbuphy** [comment]
> LLM notebook is updated with QWEN1.5-1.8b, pls check: https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/254-llm-chatbot

Thanks !

**Comment by sanbuphy** [comment]
> LLM notebook is updated with QWEN1.5-1.8b, pls check: https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/254-llm-chatbot

i want to ask if openvino support  RAG rerank model now?  like : https://huggingface.co/maidalun1020/bce-reranker-base_v1

**Comment by OpenVINO-dev-contest** [comment]
> > LLM notebook is updated with QWEN1.5-1.8b, pls check: https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/254-llm-chatbot
> 
> i want to ask if openvino support RAG rerank model now? like : https://huggingface.co/maidalun1020/bce-reranker-base_v1

we have new RAG notebook, which can support rerank model:
https://github.com/openvinotoolkit/openvino_notebooks/tree/latest/notebooks/llm-rag-langchain

**Comment by sanbuphy** [comment]
> > > LLM notebook is updated with QWEN1.5-1.8b, pls check: https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/254-llm-chatbot
> > 
> > 
> > i want to ask if openvino support RAG rerank model now? like : https://huggingface.co/maidalun1020/bce-reranker-base_v1
> 
> we have new RAG notebook, which can support rerank model: https://github.com/openvinotoolkit/openvino_notebooks/tree/latest/notebooks/llm-rag-langchain

cool！ let me try it
