### ISSUE TITLE
Missing implementation of preprocess function in 272-paint-by-example.ipynb notebook

### ISSUE THREAD

**Issue by anujonthemove** [openvinotoolkit/openvino_notebooks#1579]
I was going through the code in the notebook: **272-paint-by-example.ipynb**, I could not find the implementation of `preprocess` function used in the `prepare_latents` method of the class `OVStableDiffusionInpaintingPipeline`

![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/3261438/f4503eaf-03f8-4168-877a-59411535980e)

This is definitely missing. Please look into it.

**Comment by Iffa-Intel** [comment]
Hi @anujonthemove 

I managed to run the notebook:

<img width="821" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/f8140344-1e40-4495-87a1-8e28c38e175f">


The only thing that I need to modify is the grdio version: %pip install gradio==3.50.2
Once installed, restart kernel & run the cells.

**Comment by anujonthemove** [comment]
Thanks for getting back to me. Yes, I know that the notebook works fine with gradio version 3.50.2 because the latest versions don't have the sketch tool for the Image component yet.

Just wanted to point out that the notebook doesn't have the `preprocess` function, but it still runs smoothly. The reason is that the `process_latent` function wraps up just before `preprocess` kicks in, so it doesn't impact anything.

I noticed the same thing in the `236-stable-diffusion-v2-infinite-zoom.ipynb` notebook. On the flip side, the `225-stable-diffusion-text-to-image.ipynb` notebook has it sorted.

If needed, I can fix it, double-check, and send in a pull request.

**Comment by avitial** [comment]
@anujonthemove please submit your changes in a pull request and we can discuss your proposed changes there. Refer to https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md for guidelines.
