### ISSUE TITLE
Error: Unexpected type of example_input 

### ISSUE THREAD

**Issue by kolabearafk** [openvinotoolkit/openvino_notebooks#1581]
**Describe the bug**

Can't use dictionary type for example_input when trying to convert pytorch model

 **Expected behavior**

Not giving this - "Error: Unexpected type of example_input" and successfully convert the pytorch model to openvino 

**Screenshots**

See attached for screenshot.

![Error_OpenVino](https://github.com/openvinotoolkit/openvino_notebooks/assets/125360715/caf0be3e-3f14-46bf-9dae-df55c4f2310c)

 **Installation instructions (Please mark the checkbox)**

[ x ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 
 
**Additional context**

I'm trying to convert the UNet model from diffusers library's StableDiffusionPipeline but with an additional parameter called "added_cond_kwargs" that is supposed to be Dict[str, torch.Tensor]. But openvino's ov.convert_model(unet, example_input) function is giving the error "Error: Unexpected type of example_input". 

It seems openvino's pytorch_frontend_utils.py script raises an error if the type of example_input doesn't match the expected type (see https://github.com/openvinotoolkit/openvino/blob/9dad09aea42977a9b237b717da82bdbe5cefb0ff/tools/mo/openvino/tools/mo/moc_frontend/pytorch_frontend_utils.py#L158) but the diffusers library's UNet model requires the added_cond_kwargs  parameter to be a Dict (see https://github.com/huggingface/diffusers/blob/645a62bf3bcba47f97bf2a36a8689f40bd6b04fd/src/diffusers/models/unet_2d_condition.py#L843).

Please help! Thank you.

**Comment by eaidova** [comment]
@kolabearafk, Hello, support directly passing dict as parameter  of example input is planed feature for openvino release 2023.3. You can test it using [openvino-nightly ](https://pypi.org/project/openvino-nightly/) package(please note, it can be incompatible with openvino and openvino-dev installed in your env, it is recommended to delete these packages before installing openvino-nightly or use this package in separated virtual env).

With existing release, this issue can be workarounded creating wrapper on model with passing keys of dict as arguments and building dict from them inside wrapper forward as demonstrated in this notebook (in LCM related part) https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/248-stable-diffusion-xl/248-ssd-b1.ipynb

**Comment by kolabearafk** [comment]
Hi @eaidova, 

Thank you for your reply! I tried a similar way mentioned in the above notebook in the LCM part with openvino 2023.2. Below is the code used. There's still a problem with TorchScript not being able to do tracing with the exception: mat1 and mat2 shapes cannont be multiplied (2x1280 and 1024x3072). Please see the attached screenshot below for the error message. 

`
from diffusers import StableDiffusionPipeline
import torch
import gc
import numpy as np
import openvino as ov

pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5")
pipe.load_ip_adapter("h94/IP-Adapter", subfolder="models", weight_name="ip-adapter_sd15.bin")

def convert(model: torch.nn.Module, xml_path: str, example_input):
    xml_path = Path(xml_path)
    if not xml_path.exists():
        xml_path.parent.mkdir(parents=True, exist_ok=True)
        with torch.no_grad():
            converted_model = ov.convert_model(model, example_input=example_input)
        ov.save_model(converted_model, xml_path)
        
        # cleanup memory
        torch._C._jit_clear_class_registry()
        torch.jit._recursive.concrete_type_store = torch.jit._recursive.ConcreteTypeStore()
        torch.jit._state._clear_class_state()


UNET_OV_PATH = Path('model/unet_ir.xml')

class UNETWrapper(torch.nn.Module):
    def __init__(self, unet):
        super().__init__()
        self.unet = unet

    def forward(self, sample=None, timestep=None, encoder_hidden_states=None, image_embeds=None):
        
        return self.unet.forward(
            sample,
            timestep, 
            encoder_hidden_states, 
            added_cond_kwargs={'image_embeds': image_embeds}
        )

example_input = {
    'sample': torch.rand([1, 4, 128, 128], dtype=torch.float32),
    'timestep': torch.from_numpy(np.array(1, dtype=float)),
    'encoder_hidden_states': torch.rand([1, 77, 2048], dtype=torch.float32),
    'image_embeds': torch.rand([2, 1280], dtype=torch.float32),
}

pipe.unet.eval()
w_unet = UNETWrapper(pipe.unet)
convert(w_unet, UNET_OV_PATH, example_input)
`

![OpenVino_Error](https://github.com/openvinotoolkit/openvino_notebooks/assets/125360715/7d6ed52f-e38c-4b6b-be79-b000345da8a2)

I also tried the openvino-nightly version after uninstalling the openvino 2023.2 version. But that one gives a different error when passing a dictionary for added_cond_kwargs parameter in the unet. Please see the below screen for the error message.

<img width="815" alt="Openvino-Nightly-Error" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/125360715/57b5a079-8c90-4bd8-9c6b-5470866fc4e2">

Ultimately, I'm trying to see if OVStableDIffusionPipeline can be extended with IP-Adapter feature because I don't see any notebook example for it in this repo. 

Thanks so much!
