### ISSUE TITLE
GIF for notebooks/210-slowfast-video-recognition is misleading

### ISSUE THREAD

**Issue by devvaibhav455** [openvinotoolkit/openvino_notebooks#1654]
Hi,

Thanks for your work on the notebook. I see that the notebook classifies an entire video as shown in this tutorial: [https://docs.openvino.ai/nightly/notebooks/210-slowfast-video-recognition-with-output.html](url) and the respective notebook. It works on the Kinetic dataset. However, the GIF accompanying the notebook: [https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/210-slowfast-video-recognition/210-slowfast-video-recognition.gif](url) suggests that it can do bounding box and action performed by the subject inside that box that I guess can be done through the AVA Action dataset.

Please correct me if I am wrong. Also, could you please help with how to do so for the AVA action dataset?

**Comment by avitial** [comment]
@devvaibhav455 please check out the [SlowFast repository](https://github.com/facebookresearch/SlowFast/tree/main) for the model information. For the AVA dataset, check the [Dataset Preparation](https://github.com/facebookresearch/SlowFast/blob/main/slowfast/datasets/DATASET.md) of the model for what you are looking for. Hope this helps address your queries.

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen to ask any questions related to this topic.
