### ISSUE TITLE
[GPU] execution order corrupted: _Map_base::at

### ISSUE THREAD

**Issue by jinz2014** [openvinotoolkit/openvino_notebooks#1706]
Running the example from 254-llm-chatbot shows the following error. Can you reproduce the error ?  Thanks for your instruction.

```
Selected model mpt-7b-chat
/path/.cache/huggingface/modules/transformers_modules/mosaicml/mpt-7b-chat/1a1d410c70591fcc1a46486a254cd0e600e7b1b4/configuration_mpt.py:114: UserWarning: alibi or rope is turned on, setting `learned_pos_emb` to `False.`
  warnings.warn(f'alibi or rope is turned on, setting `learned_pos_emb` to `False.`')
/path/.cache/huggingface/modules/transformers_modules/mosaicml/mpt-7b-chat/1a1d410c70591fcc1a46486a254cd0e600e7b1b4/configuration_mpt.py:141: UserWarning: If not using a Prefix Language Model, we recommend setting "attn_impl" to "flash" instead of "triton".
  warnings.warn(UserWarning('If not using a Prefix Language Model, we recommend setting "attn_impl" to "flash" instead of "triton".'))
Size of FP16 model is 12682.63 MB
Size of model with INT8 compressed weights is 6345.15 MB
Compression rate for INT8 model: 1.999
Size of model with INT4 compressed weights is 4005.57 MB
Compression rate for INT4 model: 3.166
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading model from mpt-7b-chat/INT4_compressed_weights
The argument `trust_remote_code` is to be used along with export=True. It will be ignored.
Compiling the model to GPU ...
Traceback (most recent call last):
  File "/path/LLM/openvino_notebooks/notebooks/254-llm-chatbot-2/main.py", line 293, in <module>
    answer = ov_model.generate(**input_tokens, max_new_tokens=512)
  File "/path/triton-xpu-build/intel-xpu-backend-for-triton/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/path/triton-xpu-build/intel-xpu-backend-for-triton/.venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 1479, in generate
    return self.greedy_search(
  File "/path/triton-xpu-build/intel-xpu-backend-for-triton/.venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 2340, in greedy_search
    outputs = self(
  File "/path/triton-xpu-build/intel-xpu-backend-for-triton/.venv/lib/python3.10/site-packages/optimum/modeling_base.py", line 90, in __call__
    return self.forward(*args, **kwargs)
  File "/path/LLM/openvino_notebooks/notebooks/254-llm-chatbot-2/ov_llm_model.py", line 151, in forward
    self.request.wait()
RuntimeError: Exception from src/inference/src/infer_request.cpp:256:
Exception from src/bindings/python/src/pyopenvino/core/infer_request.hpp:54:
Caught exception: Check 'false' failed at src/plugins/intel_gpu/src/graph/primitive_inst.cpp:1146:
[GPU] execution order corrupted: _Map_base::at


```

**Comment by Wan-Intel** [comment]
I've validated the following command when running [Create an LLM-powered Chatbot using OpenVINO](https://github.com/openvinotoolkit/openvino_notebooks/blob/2023.3/notebooks/254-llm-chatbot/254-llm-chatbot.ipynb) with [OpenVINO™ Notebooks 2023.3](https://github.com/openvinotoolkit/openvino_notebooks/tree/2023.3?tab=readme-ov-file#-openvino-notebooks).

```
model_configuration = SUPPORTED_LLM_MODELS[model_id.value]
print(f"Selected model {model_id.value}")
```

Result:
![selected_model](https://github.com/openvinotoolkit/openvino_notebooks/assets/123156917/00378061-fa5e-436c-9c96-b4bc613d54d9)


Please re-install [OpenVINO™ Notebooks 2023.3](https://github.com/openvinotoolkit/openvino_notebooks/tree/2023.3?tab=readme-ov-file#-openvino-notebooks) with the steps from the [Installation Guide](https://github.com/openvinotoolkit/openvino_notebooks/tree/2023.3?tab=readme-ov-file#-installation-guide) and re-launch [Create an LLM-powered Chatbot using OpenVINO](https://github.com/openvinotoolkit/openvino_notebooks/blob/2023.3/notebooks/254-llm-chatbot/254-llm-chatbot.ipynb).

**Comment by jinz2014** [comment]
@Wan-Intel  It is not about which model is selected. Can you reproduce the error during the inference phase ?

**Comment by Wan-Intel** [comment]
I'm able to run inference of [Create an LLM-powered Chatbot using OpenVINO](https://github.com/openvinotoolkit/openvino_notebooks/blob/2023.3/notebooks/254-llm-chatbot/254-llm-chatbot.ipynb) with [OpenVINO™ Notebooks 2023.3](https://github.com/openvinotoolkit/openvino_notebooks/tree/2023.3?tab=readme-ov-file#-openvino-notebooks).

![ok_254](https://github.com/openvinotoolkit/openvino_notebooks/assets/123156917/3a135475-ffd8-4ddd-a0ee-6821f14c1173)

Please re-install [OpenVINO™ Notebooks 2023.3](https://github.com/openvinotoolkit/openvino_notebooks/tree/2023.3?tab=readme-ov-file#-openvino-notebooks) with the steps from the [Installation Guide](https://github.com/openvinotoolkit/openvino_notebooks/tree/2023.3?tab=readme-ov-file#-installation-guide) and re-launch [Create an LLM-powered Chatbot using OpenVINO](https://github.com/openvinotoolkit/openvino_notebooks/blob/2023.3/notebooks/254-llm-chatbot/254-llm-chatbot.ipynb).
