### ISSUE TITLE
(llm-chatbot notebook) Weight compression using Optimum Intel/NNCF

### ISSUE THREAD

**Issue by HLneoh** [openvinotoolkit/openvino_notebooks#1723]
In the llm-chatbot notebook - https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/254-llm-chatbot/254-llm-chatbot.ipynb, within the section "Weight Compression using Optimum Intel/NNCF", I noticed that the procedure involves converting the model to FP16 before proceeding with INT4/INT8 weight compression. 

Any reason behind not converting the model to FP32 for use in the weight compression process?

![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/25906607/9dd632b7-8b4d-4c41-93c5-0b899934cab1)

**Comment by Wan-Intel** [comment]
FP16 half-precision, which halves the model size of FP32 precision, can get an almost identical inference outcome while using half the GPU resources. You may refer to [Common data types used in Machine Learning](https://huggingface.co/blog/hf-bitsandbytes-integration#common-data-types-used-in-machine-learning) for more information.

**Comment by Wan-Intel** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
