### ISSUE TITLE
Binder environment not loading

### ISSUE THREAD

**Issue by antoniomtz** [openvinotoolkit/openvino_notebooks#1724]
**Describe the bug**
Once I try to open a Binder environment, the page throws an error while loading

**Screenshots**
![binder](https://github.com/openvinotoolkit/openvino_notebooks/assets/2906855/f16e2ef4-ec70-4e60-bd67-2c402a30abca)

 **Installation instructions (Please mark the checkbox)**
[  ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
Please run `python check_install.py` in the _openvino_notebooks_ directory. If the output is _NOT OK_ for any of the checks, please follow the instructions to fix that. If that does not work, or if you still encounter the issue, please paste the output of check_install.py here.
 
**Additional context**

**Comment by Wan-Intel** [comment]
I've run `[Hello Image Classification Notebook with launch binder](https://mybinder.org/v2/gh/openvinotoolkit/openvino_notebooks/HEAD?filepath=notebooks%2F001-hello-world%2F001-hello-world.ipynb)` and encountered the same error: `Error loading openvinotoolkit/openvino_notebooks/HEAD!`

Let me check with relevant team and we'll update you as soon as possible.

**Comment by antoniomtz** [comment]
@Wan-Intel I'm planning to use this material for an upcoming AI workshop. If you can provide an alternative to run those binder notebooks somewhere else I'd appreciate it.

**Comment by ryanloney** [comment]
@antoniomtz have you tried the Intel Developer Cloud’s Jupyter notebook environment?

https://genai.edge.devcloud.intel.com/hub/login

**Comment by avitial** [comment]
> @Wan-Intel I'm planning to use this material for an upcoming AI workshop. If you can provide an alternative to run those binder notebooks somewhere else I'd appreciate it.

@antoniomtz I was able to get the _215-image-inpainting/215-image-inpainting.ipynb_ notebook working using the _2023.3_ branch, as a workaround please try using this branch or also refer to Ryan's comment. Let us know if this helps.

![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/20826577/37763f48-eb12-4cce-bc21-71d47ed02f04)

**Comment by avitial** [comment]
> @Wan-Intel I'm planning to use this material for an upcoming AI workshop. If you can provide an alternative to run those binder notebooks somewhere else I'd appreciate it.

@antoniomtz I was able to get the _218-vehicle-detection-and-recognition_ notebook working using the _2023.3_ branch, as a workaround please try using this branch or also refer to Ryan's comment. Let us know if this helps.

![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/20826577/2c34a542-20cc-4aea-8085-108665aedb1d)

![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/20826577/9f9d1d88-2428-4503-8c52-d8f29a369240)

**Comment by andrei-kochin** [comment]
@antoniomtz 
Do you still see the issue as I wasn't able to replicate the issue:
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/72827868/a91a4b7d-ae1c-478d-9333-cd12cef5bb78)

**Comment by antoniomtz** [comment]
it is working now. Thank you!
I was also able to use Intel devCloud

**Comment by avitial** [comment]
Ref. 134555

**Comment by eaidova** [comment]
@antoniomtz could you please try my provided [link](https://mybinder.org/v2/gh/eaidova/openvino_notebooks_binder.git/main?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fopenvinotoolkit%252Fopenvino_notebooks%26urlpath%3Dtree%252Fopenvino_notebooks%252Fnotebooks%252F001-hello-world%252F001-hello-world.ipynb%26branch%3Dmain) for opening hello calssification notebook in binder?

Looks like the size of repository and cloning time inside binder environment increased and reached RAM provided by binder server (I'm tried to do this locally and process was killed), we are investigating how to reduce it, but for now for stabilization of loading binder, I changed configuration approach and links for openvining in binder. it should speed up notebooks loading, hopes it works for you.

**Comment by aabimbola29** [comment]
@antoniomtz Did this work for you?

**Comment by antoniomtz** [comment]
@aabimbola29 Yes, they are working now. Also, changing to 2023.3 tag worked. Thanks
