### ISSUE TITLE
Issue with the package Lap

### ISSUE THREAD

**Issue by Abhijeet241093** [openvinotoolkit/openvino_notebooks#1746]
**Describe the bug**
1. Error in installing pip install -U lap

 **Expected behavior**
2. Whenever run det_tracking_result, it return error:
hint: See above for details.
requirements: ❌ Command 'pip install --no-cache "lap>=0.4"  ' returned non-zero exit status 1.

**Screenshots**
![Screenshot from 2024-02-23 15-54-21](https://github.com/openvinotoolkit/openvino_notebooks/assets/38974232/bd1f4b61-7cff-4b3e-b3b4-3a56e97fded0)

 **Installation instructions (Please mark the checkbox)**
 I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **

**Additional context**

**Comment by andrei-kochin** [comment]
@Abhijeet241093 thank you for reaching the OpenVINO!

Could you please let me know about your environment as you've left this filed empty? What is the OS? What is the python version?

Also I haven't found the lap package requirement. Could you please point where have you found it?

**Comment by Wan-Intel** [comment]
Referring to [requirements.txt](https://github.com/openvinotoolkit/openvino_notebooks/blob/2023.3/requirements.txt) from [OpenVINO™ Notebooks 2023.3](https://github.com/openvinotoolkit/openvino_notebooks/tree/2023.3), lap package is not a required package for using OpenVINO™ Notebooks 2023.3.

I've installed lap package with the command as follows:
```
python -m venv virtual_env
virtual_env\Scripts\activate
python -m pip install --upgrade pip
pip install numpy
pip install wheel
pip install --no-cache "lap>=0.4
```

**Comment by Abhijeet241093** [comment]
Issue solved. This error can be resolved by creating a new virtual environment and installing lap before any other dependencies.
