### ISSUE TITLE
Error in Receipt generated in automated self checkout

### ISSUE THREAD

**Issue by Abhijeet241093** [openvinotoolkit/openvino_notebooks#1765]
**Describe the bug**
If we create multiple zone boundaries, in that case, even after removing or adding same item in refrigerator it show  recipt one bottle actually it must show receipt nothing.

![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/38974232/d25de6ce-acf0-4dd8-a5b9-403244a05552)

 **Expected behavior**
Actually, if bottle removed and added into refrigerator it must show receipt zero. 

**Screenshots**
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/38974232/8058bb15-b25e-4b81-b709-19aca8a43ebc)

 **Installation instructions (Please mark the checkbox)**
[ Yes ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
Please run `python check_install.py` in the _openvino_notebooks_ directory. If the output is _NOT OK_ for any of the checks, please follow the instructions to fix that. If that does not work, or if you still encounter the issue, please paste the output of check_install.py here.
 
**Additional context**

**Comment by Wan-Intel** [comment]
Could you please share the following information with us so that we can further investigate the issue?

- Operating System
- Python Version
- Which Notebook sample are you using?

**Comment by Abhijeet241093** [comment]
1. Ubuntu 20.04.6 LTS

2. Python 3.9.18

3. jupyter lab

Code_ Reference :  https://github.com/riacheruvu/openvino_notebooks/tree/recipes/recipes/automated_self_checkout

**Comment by adrianboguszewski** [comment]
@riacheruvu please look at it

**Comment by riacheruvu** [comment]
@Abhijeet241093, thank you for this issue report! Please see my comment at #1754; briefly: I am looking into reproducing the issue and will be providing the solution patch shortly within the next week.

**Comment by Abhijeet241093** [comment]
Sure, thank you very much :)~ @riacheruvu

**Comment by adrianboguszewski** [comment]
Covered by #1754
