### ISSUE TITLE
Error in object detection:  instead of object removed it show object added

### ISSUE THREAD

**Issue by Abhijeet241093** [openvinotoolkit/openvino_notebooks#1766]
**Describe the bug**
When an object is removed from the boundary, it indicates that an object has been added to the zone.

 **Expected behavior**
When an object is removed from the boundary, it signifies that an object has been removed from the zone.

**Screenshots**

![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/38974232/1452c70c-1d0f-42ad-bfad-4f5ec774bcf6)

 **Installation instructions (Please mark the checkbox)**
[ Yes] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
Please run `python check_install.py` in the _openvino_notebooks_ directory. If the output is _NOT OK_ for any of the checks, please follow the instructions to fix that. If that does not work, or if you still encounter the issue, please paste the output of check_install.py here.
 
**Additional context**

**Comment by adrianboguszewski** [comment]
@riacheruvu please look at it

**Comment by riacheruvu** [comment]
@Abhijeet241093, thank you for this issue report! Please see my comment at #1754; briefly: I am looking into reproducing the issue and will be providing the solution patch shortly within the next week. Thank you.

**Comment by Abhijeet241093** [comment]
Sure, @riacheruvu , thank you very much.

**Comment by adrianboguszewski** [comment]
Covered by #1754
