### ISSUE TITLE
267-distil-whisper-asr.ipynb - generation config for "distil-whisper/distil-medium.en" and "distil-whisper/distil-small.en" are missing 'lang_to_id' attributes

### ISSUE THREAD

**Issue by josuebatista** [openvinotoolkit/openvino_notebooks#1783]
When running the model interface in [notebooks/267-distil-whisper-asr/267-distil-whisper-asr.ipynb](https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/267-distil-whisper-asr/267-distil-whisper-asr.ipynb) the generation config for "distil-whisper/distil-medium.en" and "distil-whisper/distil-small.en" are missing 'lang_to_id' attributes.

A related issue at HF seems related to the problem I am experiencing. 

[https://github.com/huggingface/transformers/issues/25084](https://github.com/huggingface/transformers/issues/25084)

Thanks in advance for your guidance.

```
import IPython.display as ipd

predicted_ids = pt_model.generate(input_features)
transcription = processor.batch_decode(predicted_ids, skip_special_tokens=True)

display(ipd.Audio(sample["audio"]["array"], rate=sample["audio"]["sampling_rate"]))
print(f"Reference: {sample['text']}")
print(f"Result: {transcription[0]}")

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-6-3bfa91aa6ccf>](https://localhost:8080/#) in <cell line: 3>()
      1 import IPython.display as ipd
      2 
----> 3 predicted_ids = pt_model.generate(input_features)
      4 transcription = processor.batch_decode(predicted_ids, skip_special_tokens=True)
      5 

1 frames
[/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py](https://localhost:8080/#) in _retrieve_init_tokens(self, input_features, generation_config, config, num_segment_frames, kwargs)
   1132         is_lang_id_undefined = len(init_tokens) <= 1 or (len(init_tokens) > 1 and init_tokens[1] is None)
   1133         if language is not None:
-> 1134             if language in generation_config.lang_to_id.keys():
   1135                 language_token = language
   1136             elif language in TO_LANGUAGE_CODE.keys():

AttributeError: 'GenerationConfig' object has no attribute 'lang_to_id'
```

**Comment by Iffa-Intel** [comment]
@josuebatista from my side I can run that part with no issue

<img width="952" alt="ipython" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/cd952f84-0dc8-4e52-9f5f-d580a952f6f4">

Ensure you restart your kernel before running any cell after installation of the prerequisite
<img width="787" alt="prerequisite" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/e299371d-9c05-4dda-a8b2-9c1e155acf7b">

**Comment by josuebatista** [comment]
@Iffa-Intel, what model did you select? did you try distil-medium.en or distil-small.en?
As I indicated when I reported the error, AttributeError only shows for me when selecting "distil-whisper/distil-medium.en" or "distil-whisper/distil-small.en".  I am running the notebook in Google Colab.
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/25143822/b4cbf4bf-4add-4ccd-b031-e571d4597852)
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/25143822/d61df5e9-3a58-4753-a496-40bae750505f)

**Comment by mrigank590** [comment]
> @Iffa-Intel, what model did you select? did you try distil-medium.en or distil-small.en? As I indicated when I reported the error, AttributeError only shows for me when selecting "distil-whisper/distil-medium.en" or "distil-whisper/distil-small.en". I am running the notebook in Google Colab. ![image](https://private-user-images.githubusercontent.com/25143822/311728709-b4cbf4bf-4add-4ccd-b031-e571d4597852.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNjc5MjUsIm5iZiI6MTcxMDE2NzYyNSwicGF0aCI6Ii8yNTE0MzgyMi8zMTE3Mjg3MDktYjRjYmY0YmYtNGFkZC00Y2NkLWIwMzEtZTU3MWQ0NTk3ODUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDE0MzM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMzQzNjkwY2Q2ZGM2NDU4ODMyMGZjNGI1OTk3NDdjY2Q5MDQxODQ4MjBjNjRiMjY4NmM1MDNiZDkzZDRiN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DM-7pv6kcI3_Q-QbXcoa9r8NPxyrkH_uqRF4gxqABCo) ![image](https://private-user-images.githubusercontent.com/25143822/311728972-d61df5e9-3a58-4753-a496-40bae750505f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNjc5MjUsIm5iZiI6MTcxMDE2NzYyNSwicGF0aCI6Ii8yNTE0MzgyMi8zMTE3Mjg5NzItZDYxZGY1ZTktM2E1OC00NzUzLWE0OTYtNDBiYWU3NTA1MDVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDE0MzM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZWEyNWExMDYzYTkyM2Y3YjMzMDM3ZDI4NDQ4YWVlZWNlODgwNmQ5MTljN2E1Y2ZmZGM0NjcwNzY4NjM4OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F8APptwPTtLPluIXw1mhwfffbDXBwlkftdJ161Pr-Aw)

same here i am also experiencing the same issue

**Comment by Iffa-Intel** [comment]
@josuebatista I managed to run them

<img width="938" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/5bcb6a60-0bac-4432-998a-0651762591e7">

<img width="929" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/ce7591e2-62be-472e-a25f-47ef1086b771">


<img width="930" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/478dba17-7b8a-4130-a06f-e69e2f57febf">
<img width="905" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/5386068e-7192-413e-a785-ec6b3372f461">


I need to tweak  into these versions instead to make it work:
!pip install sentence-transformers==2.3.1
!pip install transformers==4.37.2

We'll work on updating the OV notebook prerequisite.

**Comment by hbalasu1** [comment]
Hi @eaidova, please take note of the workaround.

**Comment by Iffa-Intel** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.

**Comment by josuebatista** [comment]
> Closing issue, feel free to re-open or start a new issue if additional assistance is needed.

@Iffa-Intel Thanks! Looking forward to the updated OV notebook prerequisite.
