### ISSUE TITLE
Issue in running 273-stable-zephyr-3b-chatbot notebook

### ISSUE THREAD

**Issue by xiangyang-95** [openvinotoolkit/openvino_notebooks#1784]
**Describe the bug**
Unable to convert the stable-zephyr-3b model.

 **Expected behavior**
The notebook should be able to run and convert the model

**Screenshots**
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/18331729/8b1d661d-f4ea-4b8b-90b1-f0a0ad90ce23)

 **Installation instructions (Please mark the checkbox)**
- [x]  I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/18331729/e4703732-e4ed-4be3-b01e-8fb17f413bf5) 

**Additional context**

**Comment by eaidova** [comment]
@xiangyang-95 thank you for reporting this. Recently stablelm was integrated into transformers library and its change model configuration for running. I prepared 2 connected PRs with update:
https://github.com/openvinotoolkit/openvino.genai/pull/286 and https://github.com/openvinotoolkit/openvino_notebooks/pull/1787

it is recommended to remove cloned openvino.genai inside notebook and repeat cloning or pull it on the latest state
