### ISSUE TITLE
requirements: Ultralytics requirement "lap>=0.4" not found : Automated Self Checkout

### ISSUE THREAD

**Issue by Abhijeet241093** [openvinotoolkit/openvino_notebooks#1797]
**Describe the bug**
requirements: Ultralytics requirement "lap>=0.4" not found, attempting AutoUpdate...

[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: pip install --upgrade pip
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com/
Requirement already satisfied: lap>=0.4 in /home/phuongnd/projects/anaconda3/envs/env_name/lib/python3.8/site-packages (0.4.0)

requirements: 1 package updated per ['lap>=0.4']
requirements: ⚠️ Restart runtime or rerun command for updates to take effect

 **Expected behavior**
After restart, program must run. Requirement already installed but it never executed. 

**Screenshots**
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/38974232/2110690e-055e-4327-920b-489a9647a0b4)

![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/38974232/8f49fae3-1a45-4c13-8c3e-2b85fdc6d42d)

 **Installation instructions (Please mark the checkbox)**
[  ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
Please run `python check_install.py` in the _openvino_notebooks_ directory. If the output is _NOT OK_ for any of the checks, please follow the instructions to fix that. If that does not work, or if you still encounter the issue, please paste the output of check_install.py here.
 
**Additional context**

**Comment by Abhijeet241093** [comment]
@riacheruvu

**Comment by riacheruvu** [comment]
Hi @Abhijeet241093, thanks for the note! This is an issue corresponding to Ultralytics pip install - you can avoid the issue by manually pip installing [the lap library](https://github.com/ultralytics/ultralytics/issues/1775), as documented here. I'll also add this to this kit's manifest file as well. Since this isn't an issue concerning OpenVINO, requesting @adrianboguszewski to close this thread for now.
