### ISSUE TITLE
HTTP download causes ocl-icd-2.2.12-1.el8.x86_64.rpm download to fail with Proxy while building on OpenShift

### ISSUE THREAD

**Issue by Feelas** [openvinotoolkit/openvino_notebooks#1803]
Because `ocl-icd-2.2.12-1.el8.x86_64.rpm` is downloaded through an HTTP channel ([here](https://github.com/openvinotoolkit/openvino_notebooks/blame/f935d5cca61924c4b8cfd6da3fcb7de98a2f995c/Dockerfile#L42)), the building process might fail on OpenShift if the cluster has http and https proxies configured.

BuildConfigs in OpenShift set HTTP_PROXY and HTTPS_PROXY environment values automatically, but not http_proxy.

Build process output suggests that `rpm -ivh` is using `curl` under the hood for the download. `curl` is notorious for using lowercase `http_proxy` when establishing an HTTP connection (in contrast to HTTPS where both uppercase and lowercase work).

The best way would be to download `ocl-icd-2.2.12-1.el8.x86_64.rpm` through an HTTPS channel (though it seems like mirror.centos.org doesn't allow HTTPS access).
As a workaround, it seems like adding `http_proxy=${HTTP_PROXY}` in front of the the command that does the installation of ocl-icd from `http://mirror.centos.org`  would be enough to fix the problem, but there might be a better and cleaner solution.

**Comment by eaidova** [comment]
docker was updated to use different way and the latest GPU driver, so I believe this issue should be solved by this PR https://github.com/openvinotoolkit/openvino_notebooks/pull/1875
