### ISSUE TITLE
Issues in running GPU device on MTL iGPU in notebook 261-fast-segment-anything

### ISSUE THREAD

**Issue by xiangyang-95** [openvinotoolkit/openvino_notebooks#1817]
**Describe the bug**
No results are seen when running the notebooks with iGPU on MTL platform. The Inference is done but no bounding box is seen, However, when change the device to CPU, the bounding box results are seen.

 **Expected behavior**
Can see the result when using iGPU to perform inference.

**Screenshots**

 **Installation instructions (Please mark the checkbox)**
- [x] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
 
**Additional context**

**Comment by YuChern-Intel** [comment]
I obtained the same result as you when inferencing with iGPU. 

Inferencing on CPU:
![CPU](https://github.com/openvinotoolkit/openvino_notebooks/assets/107900329/5d68153c-bd78-4b5a-9ed1-631ee276a297)

Inferencing on iGPU:
![GPU](https://github.com/openvinotoolkit/openvino_notebooks/assets/107900329/11bf028f-8148-4440-8280-72e1e9b5ba0b)

We'll investigate the issue and update you as soon as possible.

**Comment by eaidova** [comment]
@xiangyang-95 could you please try to apply configuration changes proposed in this PR https://github.com/openvinotoolkit/openvino_notebooks/pull/1829? Fast-Segment-Anything is based on yolov8, it is known limitation that it may requires to disable some optimization for GPU to get accurate result on some platforms

**Comment by xiangyang-95** [comment]
@eaidova I am still having the same issue after applying the configurations in the PR.
Based on some tests, I found that when we export the model to a static shape, then it works.
Using a dynamic shape has no detections on the result when the accuracy is high, if the accuracy threshold is tuned down to very low (0.01), the results can be seen. 
I also find that the tensor data between the static and dynamic shapes are different as well.

**Comment by eaidova** [comment]
@xiangyang-95 thank you for your findings, I updated notebook to use static input shapes
