### ISSUE TITLE
[Notebook Hello Segmentation] segmented image result is not displaying expected image

### ISSUE THREAD

**Issue by sarang-26** [openvinotoolkit/openvino_notebooks#1895]
**Describe the bug**
The expected image is not being displayed.

 **Expected behavior**
![Screenshot 2024-04-07 at 10 29 59 PM](https://github.com/openvinotoolkit/openvino_notebooks/assets/65524630/66e15741-8ee5-4067-a87f-cf5d5b5eee68)

**Output*

![Screenshot 2024-04-07 at 10 30 25 PM](https://github.com/openvinotoolkit/openvino_notebooks/assets/65524630/84afba7e-ac4f-4983-93a1-f3320c572f75)

**Comment by sarang-26** [comment]
.take

**Comment by Iffa-Intel** [comment]
@sarang-26 could you share:
1. which OS are you using?
2. your hardware (CPU and GPU)
3. did the issue happen on both CPU & GPU?
4. OpenVINO version

**Comment by Iffa-Intel** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
