### ISSUE TITLE
load model with GPU error

### ISSUE THREAD

**Issue by mingLZheng** [openvinotoolkit/openvino_notebooks#1896]
RuntimeError: Exception from src\inference\src\cpp\core.cpp:109:
Exception from src\inference\src\dev\plugin.cpp:54:
Check 'input_order_shape[0].compatible(input_rank.get_max_length()) || input_order_shape[0] == 0' failed at src\core\shape_inference\include\transpose_shape_inference.hpp:74:
While validating node 'opset1::Transpose __module.transformer/aten::transpose/Transpose (gpu_opset::GatherCompressed __module.transformer/aten::index/Gather[0]:f16[?,?,64], opset1::Constant __module.transformer/aten::transpose/ScatterElementsUpdate[0]:i32[4]) -> (f16[?,?,32,2])' with friendly_name '__module.transformer/aten::transpose/Transpose':
Shape inference input shapes {[?,?,64],[4]}
Input order must have shape [n], where n is the rank of arg.

**Comment by Iffa-Intel** [comment]
@mingLZheng could you share:
1. which notebook sample you used?
2. which OS are you using?
3. what model that causing this error (is it  a custom or modified model?)
4. did the issue happen on both CPU & GPU?
5. your OpenVINO version

**Comment by mingLZheng** [comment]
1.notebook is 254-rag-chatbot
2.window 11 
3.chatglm3-6b
4.yes issue happen on CPU & GPU
5.openvino 2024.0.0

**Comment by mingLZheng** [comment]
chatglm3-6b model is custom

**Comment by Iffa-Intel** [comment]
@mingLZheng if possible could you 
1. share that custom model for us to test?
2. elaborate further regarding the custom model, eg: static shaped/dynamic shaped, framework: Tensorflow, etc

**Comment by mingLZheng** [comment]
however I use the official ChatGLM3-6B model. the same problem occurs.

**Comment by Iffa-Intel** [comment]
@mingLZheng I managed to convert and load that model:

ChatGLM3-6B model
<img width="631" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/061bf31b-bea1-4f5d-9f29-599fb58c2ebe">

Tested with INT4 precision
<img width="539" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/32ec50d3-12e1-4541-b348-8786baf92ee6">

Selected INT4 for model to run section
<img width="242" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/468df171-b108-4e6d-b656-75d18b17ca77">

Model loaded without any issue
<img width="649" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/22908306-b3f6-46dd-9f8c-a6cb6aa2f4a7">

**Comment by mingLZheng** [comment]
@Iffa-Intel It can work on CPU, but not on GPU.

**Comment by Iffa-Intel** [comment]
I managed to run it on CPU and GPU

For GPU:

<img width="437" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/55703f8b-154f-4830-a5da-b53a2749724c">


<img width="437" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/51eccdf1-b6fd-4d83-89cc-9bc5424f4e4a">

**Comment by Iffa-Intel** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
