### ISSUE TITLE
llm-chatbot can't run on Ultra7 155H NPU

### ISSUE THREAD

**Issue by mattchai** [openvinotoolkit/openvino_notebooks#1900]
The argument `trust_remote_code` is to be used along with export=True. It will be ignored.
Compiling the model to NPU ...
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[34], line 27
     20 tok = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
     22 model_class = (
     23     OVModelForCausalLM
     24     if not model_configuration["remote"]
     25     else model_classes[class_key]
     26 )
---> 27 ov_model = model_class.from_pretrained(
     28     model_dir,
     29     device=device.value,
     30     ov_config=ov_config,
     31     config=AutoConfig.from_pretrained(model_dir, trust_remote_code=True),
     32     trust_remote_code=True,
     33 )

File [C:\env\openvino_env\lib\site-packages\optimum\modeling_base.py:401](file:///C:/env/openvino_env/lib/site-packages/optimum/modeling_base.py#line=400), in OptimizedModel.from_pretrained(cls, model_id, export, force_download, use_auth_token, cache_dir, subfolder, config, local_files_only, trust_remote_code, revision, **kwargs)
    397     trust_remote_code = False
    399 from_pretrained_method = cls._from_transformers if export else cls._from_pretrained
--> 401 return from_pretrained_method(
    402     model_id=model_id,
    403     config=config,
    404     revision=revision,
    405     cache_dir=cache_dir,
    406     force_download=force_download,
    407     use_auth_token=use_auth_token,
    408     subfolder=subfolder,
    409     local_files_only=local_files_only,
    410     trust_remote_code=trust_remote_code,
    411     **kwargs,
    412 )

File [C:\env\openvino_env\lib\site-packages\optimum\intel\openvino\modeling_decoder.py:610](file:///C:/env/openvino_env/lib/site-packages/optimum/intel/openvino/modeling_decoder.py#line=609), in OVModelForCausalLM._from_pretrained(cls, model_id, config, use_auth_token, revision, force_download, cache_dir, file_name, subfolder, from_onnx, local_files_only, load_in_8bit, quantization_config, **kwargs)
    607     init_cls = cls
    609 enable_compilation = kwargs.pop("compile", True) and not load_in_4bit
--> 610 causal_model = init_cls(
    611     model=model,
    612     config=config,
    613     model_save_dir=model_cache_path.parent,
    614     compile=enable_compilation,
    615     quantization_config=quantization_config,
    616     **kwargs,
    617 )
    619 if load_in_4bit:
    620     if not is_nncf_available():

File [C:\env\openvino_env\lib\site-packages\optimum\intel\openvino\modeling_decoder.py:163](file:///C:/env/openvino_env/lib/site-packages/optimum/intel/openvino/modeling_decoder.py#line=162), in OVBaseDecoderModel.__init__(self, model, config, device, dynamic_shapes, ov_config, model_save_dir, quantization_config, **kwargs)
    160     raise_error(self.use_cache, use_cache, "use_cache")
    162 if enable_compilation:
--> 163     self.compile()

File [C:\env\openvino_env\lib\site-packages\optimum\intel\openvino\modeling_decoder.py:325](file:///C:/env/openvino_env/lib/site-packages/optimum/intel/openvino/modeling_decoder.py#line=324), in OVBaseDecoderModel.compile(self)
    323 def compile(self):
    324     if self.request is None:
--> 325         super().compile()
    326         self.request = self.request.create_infer_request()

File [C:\env\openvino_env\lib\site-packages\optimum\intel\openvino\modeling_base.py:400](file:///C:/env/openvino_env/lib/site-packages/optimum/intel/openvino/modeling_base.py#line=399), in OVBaseModel.compile(self)
    398     ov_config["CACHE_DIR"] = str(cache_dir)
    399     logger.info(f"Setting OpenVINO CACHE_DIR to {str(cache_dir)}")
--> 400 self.request = core.compile_model(self.model, self._device, ov_config)
    401 # OPENVINO_LOG_LEVEL can be found in https://docs.openvino.ai/2023.2/openvino_docs_OV_UG_supported_plugins_AUTO_debugging.html
    402 if "OPENVINO_LOG_LEVEL" in os.environ and int(os.environ["OPENVINO_LOG_LEVEL"]) > 2:

File C:\env\openvino_env\lib\site-packages\openvino\runtime\ie_api.py:521, in Core.compile_model(self, model, device_name, config, weights)
    516     if device_name is None:
    517         return CompiledModel(
    518             super().compile_model(model, {} if config is None else config),
    519         )
    520     return CompiledModel(
--> 521         super().compile_model(model, device_name, {} if config is None else config),
    522     )
    523 else:
    524     if device_name is None:

RuntimeError: Exception from src/inference/src/cpp/core.cpp:109:
Exception from src/inference/src/dev/plugin.cpp:54:
Exception from src/plugins/intel_npu/src/plugin/src/plugin.cpp:513:
get_shape was called on a descriptor::Tensor with dynamic shape

python: 3.10.10
about-time                   4.2.1
absl-py                      2.1.0
alive-progress               3.1.5
anyio                        4.3.0
argon2-cffi                  23.1.0
argon2-cffi-bindings         21.2.0
arrow                        1.3.0
asttokens                    2.4.1
astunparse                   1.6.3
async-lru                    2.0.4
attrs                        23.2.0
autograd                     1.6.2
Babel                        2.14.0
beautifulsoup4               4.12.3
bleach                       6.1.0
cachetools                   5.3.3
certifi                      2024.2.2
cffi                         1.16.0
charset-normalizer           3.3.2
cma                          3.2.2
colorama                     0.4.6
comm                         0.2.2
contourpy                    1.2.1
cycler                       0.12.1
debugpy                      1.8.1
decorator                    5.1.1
defusedxml                   0.7.1
Deprecated                   1.2.14
dill                         0.3.8
exceptiongroup               1.2.0
executing                    2.0.1
fastjsonschema               2.19.1
filelock                     3.13.3
flatbuffers                  24.3.25
fonttools                    4.51.0
fqdn                         1.5.1
fsspec                       2024.3.1
future                       1.0.0
gast                         0.5.4
google-auth                  2.29.0
google-auth-oauthlib         1.0.0
google-pasta                 0.2.0
grapheme                     0.6.0
grpcio                       1.62.1
h11                          0.14.0
h5py                         3.10.0
httpcore                     1.0.5
httpx                        0.27.0
huggingface-hub              0.22.2
idna                         3.6
imageio                      2.34.0
ipykernel                    6.29.4
ipython                      8.23.0
ipywidgets                   8.1.2
isoduration                  20.11.0
jedi                         0.19.1
Jinja2                       3.1.3
joblib                       1.4.0
json5                        0.9.24
jsonpointer                  2.4
jsonschema                   4.21.1
jsonschema-specifications    2023.12.1
jstyleson                    0.0.2
jupyter_client               8.6.1
jupyter_core                 5.7.2
jupyter-events               0.10.0
jupyter-lsp                  2.2.4
jupyter_server               2.13.0
jupyter_server_terminals     0.5.3
jupyterlab                   4.1.6
jupyterlab_pygments          0.3.0
jupyterlab_server            2.26.0
jupyterlab_widgets           3.0.10
keras                        2.14.0
kiwisolver                   1.4.5
lazy_loader                  0.4
libclang                     18.1.1
Markdown                     3.6
markdown-it-py               3.0.0
MarkupSafe                   2.1.5
matplotlib                   3.6.3
matplotlib-inline            0.1.6
mdurl                        0.1.2
mistune                      3.0.2
ml-dtypes                    0.2.0
mpmath                       1.3.0
natsort                      8.4.0
nbclient                     0.10.0
nbconvert                    7.16.3
nbformat                     5.10.4
nest-asyncio                 1.6.0
networkx                     3.1
ninja                        1.10.2.4
nncf                         2.9.0
notebook_shim                0.2.4
numpy                        1.26.4
oauthlib                     3.2.2
onnx                         1.16.0
opencv-python                4.9.0.80
openvino                     2024.0.0
openvino-dev                 2024.0.0
openvino-telemetry           2024.1.0
opt-einsum                   3.3.0
overrides                    7.7.0
packaging                    24.0
pandas                       2.1.4
pandocfilters                1.5.1
parso                        0.8.4
pillow                       10.3.0
pip                          24.0
platformdirs                 4.2.0
prometheus_client            0.20.0
prompt-toolkit               3.0.43
protobuf                     4.25.3
psutil                       5.9.8
pure-eval                    0.2.2
pyasn1                       0.6.0
pyasn1_modules               0.4.0
pycparser                    2.22
pydot                        2.0.0
Pygments                     2.17.2
pymoo                        0.6.1.1
pyparsing                    3.1.2
python-dateutil              2.9.0.post0
python-json-logger           2.0.7
pytz                         2024.1
pywin32                      306
pywinpty                     2.0.13
PyYAML                       6.0.1
pyzmq                        25.1.2
referencing                  0.34.0
regex                        2023.12.25
requests                     2.31.0
requests-oauthlib            2.0.0
rfc3339-validator            0.1.4
rfc3986-validator            0.1.1
rich                         13.7.1
rpds-py                      0.18.0
rsa                          4.9
safetensors                  0.4.2
scikit-image                 0.22.0
scikit-learn                 1.4.1.post1
scipy                        1.13.0
Send2Trash                   1.8.3
setuptools                   69.2.0
six                          1.16.0
sniffio                      1.3.1
soupsieve                    2.5
stack-data                   0.6.3
sympy                        1.12
tensorboard                  2.14.1
tensorboard-data-server      0.7.2
tensorflow                   2.14.0
tensorflow-estimator         2.14.0
tensorflow-intel             2.14.0
tensorflow-io-gcs-filesystem 0.31.0
termcolor                    2.4.0
terminado                    0.18.1
texttable                    1.7.0
threadpoolctl                3.4.0
tifffile                     2024.2.12
tinycss2                     1.2.1
tokenizers                   0.15.2
tomli                        2.0.1
torch                        2.1.0+cpu
torchaudio                   2.1.0+cpu
torchvision                  0.16.0+cpu
tornado                      6.4
tqdm                         4.66.2
traitlets                    5.14.2
transformers                 4.39.3
types-python-dateutil        2.9.0.20240316
typing_extensions            4.11.0
tzdata                       2024.1
uri-template                 1.3.0
urllib3                      2.2.1
wcwidth                      0.2.13
webcolors                    1.13
webencodings                 0.5.1
websocket-client             1.7.0
Werkzeug                     3.0.2
wheel                        0.43.0
widgetsnbextension           4.0.10
wrapt                        1.14.1

**Comment by avitial** [comment]
@mattchai currently as of Intel OpenVINO™ version 2024.0, Large Language Models (LLMs) are not supported by the Intel® NPU plugin. So the behavior you observe with NPU is expected.

**Comment by MansonHua** [comment]
I meet the same problem, when i try to run huggingface models on openvino and set the device as 'npu', it reported the same error:
RuntimeError: Exception from src\inference\src\cpp\core.cpp:109:
Exception from src\inference\src\dev\plugin.cpp:54:
Exception from src\plugins\intel_npu\src\plugin\src\plugin.cpp:513:
get_shape was called on a descriptor::Tensor with dynamic shape

**Comment by sahilmerai** [comment]
I'm Facing the same issue.
RuntimeError: Exception from src\inference\src\cpp\core.cpp:109:
Exception from src\inference\src\dev\plugin.cpp:54:
Exception from src\plugins\intel_npu\src\plugin\src\plugin.cpp:513:
get_shape was called on a descriptor::Tensor with dynamic shape
