### ISSUE TITLE
from openvino.inference_engine import IECore error.

### ISSUE THREAD

**Issue by TVI-BIZ** [openvinotoolkit/openvino_notebooks#20]
thanks for that notebooks.
I am in Ubuntu 20.04 and have the error with IECore import.
Do all steps in the github page. Check installation - ok.
(openvino_env) vlad@vlad-system-product-name:~/Vlad_Ai/Intel/openvino_notebooks$ python3 check_install.py 

System information:
Python executable: /home/vlad/Vlad_Ai/Intel/openvino_notebooks/openvino_env/bin/python3
OpenVINO environment activated: OK
Python version: 3.7 OK
OpenVINO development tools installed: OK
Numpy version: 1.18.5 OK

when I start jupyter lab notebooks and execute import 

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-82b2d7f92c72> in <module>
----> 1 from openvino.inference_engine import IECore

~/Vlad_Ai/Intel/openvino_notebooks/openvino_env/lib/python3.7/site-packages/openvino/inference_engine/__init__.py in <module>
     32         os.environ["PATH"] = os.path.abspath(openvino_dlls) + ";" + os.environ["PATH"]
     33 
---> 34 from .ie_api import *
     35 __all__ = ['IENetwork', "TensorDesc", "IECore", "Blob", "PreProcessInfo", "get_version"]
     36 __version__ = get_version()

ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory

Do I miss something? 
Also in jupyterlab:
import cv2
print(cv2.__version__)
4.5.1 
when is it correct? when normally we use OpenCv from OpenVino - it have to be 4.5.1 - openvino something

**Comment by TVI-BIZ** [comment]
I do all the things in my MacOS 10.15.4 - and all works fine. 
IECore exported - no errors.
and
_import cv2
print(cv2.__version__)
4.5.2-openvino_

**Comment by ryanloney** [comment]
On your Ubuntu machine, can you try `apt install libpython3.7-dev` and see if this resolves the ImportError?

**Comment by TVI-BIZ** [comment]
thanks for you reply.
E: Unable to locate package libpython3.7-dev
E: Couldn't find any package by glob 'libpython3.7-dev'
but when I try 
sudo apt install libpython3.8-dev
libpython3.8-dev is already the newest version (3.8.6-1ubuntu0.2)
 python -V
Python 3.7.10
So can't install - libpython3.7-dev. try to find any solution in google but without sucess.

**Comment by ryanloney** [comment]
We added support for Python 3.8 earlier this week. Can you try using Python 3.8? It should still work with 20.10, we just do not validate and run CI tests.

**Comment by ryanloney** [comment]
Hi @TVI-BIZ - did switching to Python 3.8 on your Ubuntu 20.10 system work?

Please reopen if you have any more issues.
