### ISSUE TITLE
Error building openvino notebooks on Ubuntu 

### ISSUE THREAD

**Issue by brijean** [openvinotoolkit/openvino_notebooks#2012]
**Describe the bug**
Following Docker install instructions (https://github.com/openvinotoolkit/openvino_notebooks/wiki/Docker) on  Ubuntu 22.04.4 with Docker version 26.1.1, build 4cf5afa.

"docker build" command fails with the following error:
bjean09@n4-emr-1:~/openvino_notebooks$ sudo docker build -t openvino_notebooks .
[+] Building 243.0s (8/25)                                                                                                        docker:default
 => [internal] load build definition from Dockerfile                                                                                        0.0s
 => => transferring dockerfile: 3.03kB                                                                                                      0.0s
 => [internal] load metadata for quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.29.0                                                          0.2s
 => [internal] load .dockerignore                                                                                                           0.0s
 => => transferring context: 2B                                                                                                             0.0s
 => [ 1/21] FROM quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.29.0@sha256:457c5346b912e2fe383d61bc8409ec3fca130034c7875646671192587e9839c0  0.0s
 => [internal] load build context                                                                                                           0.1s
 => => transferring context: 36.65kB                                                                                                        0.0s
 => CACHED [ 2/21] RUN dnf --disableplugin=subscription-manager remove -y nodejs &&   dnf --disableplugin=subscription-manager module -y r  0.0s
 => CACHED [ 3/21] RUN dnf --disableplugin=subscription-manager install -y 'dnf-command(config-manager)' &&     dnf --disableplugin=subscr  0.0s
 => ERROR [ 4/21] RUN rpm -ivh https://vault.centos.org/centos/8/AppStream/x86_64/os/Packages/mesa-filesystem-21.1.5-1.el8.x86_64.rpm &&  242.8s
------                                                                                                                                           
 > [ 4/21] RUN rpm -ivh https://vault.centos.org/centos/8/AppStream/x86_64/os/Packages/mesa-filesystem-21.1.5-1.el8.x86_64.rpm &&     dnf --disableplugin=subscription-manager install --refresh -y     intel-opencl intel-media intel-mediasdk libmfxgen1 libvpl2     level-zero intel-level-zero-gpu     intel-metrics-library intel-igc-core intel-igc-cm     libva libva-utils  intel-gmmlib &&     rpm -ivh http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/Packages/ocl-icd-2.2.12-1.el8.x86_64.rpm &&     rpm -ivh https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/c/clinfo-3.0.21.02.21-4.el8.x86_64.rpm:                                                                                                    
5.700 warning: /var/tmp/rpm-tmp.giQ7BE: Header V3 RSA/SHA256 Signature, key ID 8483c65d: NOKEY
5.772 Retrieving https://vault.centos.org/centos/8/AppStream/x86_64/os/Packages/mesa-filesystem-21.1.5-1.el8.x86_64.rpm
5.772 Verifying...                          ########################################
5.818 Preparing...                          ########################################
5.821 Updating / installing...
5.821 mesa-filesystem-21.1.5-1.el8          ########################################
13.93 Intel graphics rhel-8.6                          13 kB/s |  98 kB     00:07    
17.34 Red Hat Universal Base Image 8 (RPMs) - BaseOS  1.1 kB/s | 3.8 kB     00:03    
20.79 Red Hat Universal Base Image 8 (RPMs) - AppStre 1.3 kB/s | 4.2 kB     00:03    
27.68 Red Hat Universal Base Image 8 (RPMs) - AppStre 446 kB/s | 3.0 MB     00:06    
31.54 Red Hat Universal Base Image 8 (RPMs) - CodeRea 1.1 kB/s | 3.8 kB     00:03    
38.44 Red Hat Universal Base Image 8 (RPMs) - CodeRea  15 kB/s | 102 kB     00:06    
38.72 Dependencies resolved.
38.72 =======================================================================================
38.72  Package                 Arch    Version                 Repository                Size
38.72 =======================================================================================
38.72 Installing:
38.72  intel-gmmlib            x86_64  22.3.1-i529.el8         intel-graphics-rhel-8.6  153 k
38.72  intel-igc-cm            x86_64  1.0.176-i537.el8        intel-graphics-rhel-8.6   17 M
38.72  intel-igc-core          x86_64  1.0.12504.6-i537.el8    intel-graphics-rhel-8.6   22 M
38.72  intel-level-zero-gpu    x86_64  1.3.24595.35-i538.el8   intel-graphics-rhel-8.6  1.9 M
38.72  intel-media             x86_64  22.6.4-i539.el8         intel-graphics-rhel-8.6  7.2 M
38.72  intel-mediasdk          x86_64  22.6.4-i539.el8         intel-graphics-rhel-8.6  3.2 M
38.72  intel-metrics-library   x86_64  1.0.114-i524.el8        intel-graphics-rhel-8.6  616 k
38.72  intel-opencl            x86_64  22.43.24595.35-i538.el8 intel-graphics-rhel-8.6  2.0 M
38.72  level-zero              x86_64  1.8.8-i524.el8          intel-graphics-rhel-8.6  150 k
38.72  libmfxgen1              x86_64  22.6.4-i539.el8         intel-graphics-rhel-8.6  3.6 M
38.72  libva                   x86_64  2.16.0.2-41.el8         intel-graphics-rhel-8.6  102 k
38.72  libva-utils             x86_64  2.16.0.2-1.0.40.el8     intel-graphics-rhel-8.6  518 k
38.72  libvpl2                 x86_64  2023.1.0.0-i529.el8     intel-graphics-rhel-8.6  100 k
38.72 Installing dependencies:
38.72  intel-igc-opencl        x86_64  1.0.12504.6-i537.el8    intel-graphics-rhel-8.6   21 M
38.72  libwayland-client       x86_64  1.21.0-1.el8            ubi-8-appstream           41 k
38.72 
38.72 Transaction Summary
38.72 =======================================================================================
38.72 Install  15 Packages
38.72 
38.73 Total download size: 79 M
38.73 Installed size: 79 M
38.73 Downloading Packages:
42.74 (1/15): intel-gmmlib-22.3.1-i529.el8.x86_64.rpm  38 kB/s | 153 kB     00:04    
42.91 (2/15): intel-igc-cm-1.0.176-i537.el8.x86_64.rp 3.9 MB/s |  17 MB     00:04    
43.01 (3/15): intel-igc-core-1.0.12504.6-i537.el8.x86 5.1 MB/s |  22 MB     00:04    
43.16 (4/15): intel-igc-opencl-1.0.12504.6-i537.el8.x  49 MB/s |  21 MB     00:00    
43.20 (5/15): intel-level-zero-gpu-1.3.24595.35-i538. 6.7 MB/s | 1.9 MB     00:00    
43.29 (6/15): intel-media-22.6.4-i539.el8.x86_64.rpm   26 MB/s | 7.2 MB     00:00    
43.46 (7/15): intel-mediasdk-22.6.4-i539.el8.x86_64.r  11 MB/s | 3.2 MB     00:00    
43.46 (8/15): intel-metrics-library-1.0.114-i524.el8. 2.2 MB/s | 616 kB     00:00    
43.56 (9/15): intel-opencl-22.43.24595.35-i538.el8.x8 7.5 MB/s | 2.0 MB     00:00    
43.72 (10/15): level-zero-1.8.8-i524.el8.x86_64.rpm   581 kB/s | 150 kB     00:00    
43.79 (11/15): libmfxgen1-22.6.4-i539.el8.x86_64.rpm   11 MB/s | 3.6 MB     00:00    
43.82 (12/15): libva-2.16.0.2-41.el8.x86_64.rpm       393 kB/s | 102 kB     00:00    
43.98 (13/15): libva-utils-2.16.0.2-1.0.40.el8.x86_64 2.0 MB/s | 518 kB     00:00    
44.05 (14/15): libvpl2-2023.1.0.0-i529.el8.x86_64.rpm 390 kB/s | 100 kB     00:00    
47.60 (15/15): libwayland-client-1.21.0-1.el8.x86_64.  11 kB/s |  41 kB     00:03    
47.61 --------------------------------------------------------------------------------
47.61 Total                                           8.9 MB/s |  79 MB     00:08     
51.41 Intel graphics rhel-8.6                         480  B/s | 1.8 kB     00:03    
51.46 Importing GPG key 0xDBB72B06:
51.46  Userid     : "Intel Corporation (repositories.intel.com key) <graphics-support@intel.com>"
51.46  Fingerprint: 1C1B 89D0 2C92 9514 698A A805 9B10 C065 DBB7 2B06
51.46  From       : https://repositories.intel.com/graphics/intel-graphics.key
51.46 Key imported successfully
51.81 Running transaction check
51.82 Transaction check succeeded.
51.82 Running transaction test
52.10 Transaction test succeeded.
52.10 Running transaction
52.38   Preparing        :                                                        1/1 
52.42   Installing       : intel-gmmlib-22.3.1-i529.el8.x86_64                   1/15 
52.43   Installing       : libwayland-client-1.21.0-1.el8.x86_64                 2/15 
52.45   Installing       : libva-2.16.0.2-41.el8.x86_64                          3/15 
54.07   Installing       : intel-igc-core-1.0.12504.6-i537.el8.x86_64            4/15 
55.53   Installing       : intel-igc-opencl-1.0.12504.6-i537.el8.x86_64          5/15 
55.69   Installing       : intel-level-zero-gpu-1.3.24595.35-i538.el8.x86_64     6/15 
55.87   Installing       : intel-opencl-22.43.24595.35-i538.el8.x86_64           7/15 
57.04   Installing       : intel-igc-cm-1.0.176-i537.el8.x86_64                  8/15 
57.66   Installing       : intel-media-22.6.4-i539.el8.x86_64                    9/15 
57.99   Installing       : intel-mediasdk-22.6.4-i539.el8.x86_64                10/15 
58.26   Installing       : libmfxgen1-22.6.4-i539.el8.x86_64                    11/15 
58.32   Installing       : libva-utils-2.16.0.2-1.0.40.el8.x86_64               12/15 
58.34   Installing       : libvpl2-2023.1.0.0-i529.el8.x86_64                   13/15 
58.36   Installing       : level-zero-1.8.8-i524.el8.x86_64                     14/15 
58.43   Installing       : intel-metrics-library-1.0.114-i524.el8.x86_64        15/15 
58.45   Running scriptlet: intel-metrics-library-1.0.114-i524.el8.x86_64        15/15 
58.51   Verifying        : intel-gmmlib-22.3.1-i529.el8.x86_64                   1/15 
58.51   Verifying        : intel-igc-cm-1.0.176-i537.el8.x86_64                  2/15 
58.51   Verifying        : intel-igc-core-1.0.12504.6-i537.el8.x86_64            3/15 
58.51   Verifying        : intel-igc-opencl-1.0.12504.6-i537.el8.x86_64          4/15 
58.51   Verifying        : intel-level-zero-gpu-1.3.24595.35-i538.el8.x86_64     5/15 
58.51   Verifying        : intel-media-22.6.4-i539.el8.x86_64                    6/15 
58.51   Verifying        : intel-mediasdk-22.6.4-i539.el8.x86_64                 7/15 
58.51   Verifying        : intel-metrics-library-1.0.114-i524.el8.x86_64         8/15 
58.51   Verifying        : intel-opencl-22.43.24595.35-i538.el8.x86_64           9/15 
58.51   Verifying        : level-zero-1.8.8-i524.el8.x86_64                     10/15 
58.51   Verifying        : libmfxgen1-22.6.4-i539.el8.x86_64                    11/15 
58.51   Verifying        : libva-2.16.0.2-41.el8.x86_64                         12/15 
58.51   Verifying        : libva-utils-2.16.0.2-1.0.40.el8.x86_64               13/15 
58.51   Verifying        : libvpl2-2023.1.0.0-i529.el8.x86_64                   14/15 
58.51   Verifying        : libwayland-client-1.21.0-1.el8.x86_64                15/15 
58.58 Installed products updated.
58.63 
58.64 Installed:
58.64   intel-gmmlib-22.3.1-i529.el8.x86_64                                           
58.64   intel-igc-cm-1.0.176-i537.el8.x86_64                                          
58.64   intel-igc-core-1.0.12504.6-i537.el8.x86_64                                    
58.64   intel-igc-opencl-1.0.12504.6-i537.el8.x86_64                                  
58.64   intel-level-zero-gpu-1.3.24595.35-i538.el8.x86_64                             
58.64   intel-media-22.6.4-i539.el8.x86_64                                            
58.64   intel-mediasdk-22.6.4-i539.el8.x86_64                                         
58.64   intel-metrics-library-1.0.114-i524.el8.x86_64                                 
58.64   intel-opencl-22.43.24595.35-i538.el8.x86_64                                   
58.64   level-zero-1.8.8-i524.el8.x86_64                                              
58.64   libmfxgen1-22.6.4-i539.el8.x86_64                                             
58.64   libva-2.16.0.2-41.el8.x86_64                                                  
58.64   libva-utils-2.16.0.2-1.0.40.el8.x86_64                                        
58.64   libvpl2-2023.1.0.0-i529.el8.x86_64                                            
58.64   libwayland-client-1.21.0-1.el8.x86_64                                         
58.64 
58.64 Complete!
242.7 curl: (56) Recv failure: Connection reset by peer
242.7 error: skipping http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/Packages/ocl-icd-2.2.12-1.el8.x86_64.rpm - transfer failed
242.7 Retrieving http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/Packages/ocl-icd-2.2.12-1.el8.x86_64.rpm
------
Dockerfile:36
--------------------
  35 |     
  36 | >>> RUN rpm -ivh https://vault.centos.org/centos/8/AppStream/x86_64/os/Packages/mesa-filesystem-21.1.5-1.el8.x86_64.rpm && \
  37 | >>>     dnf --disableplugin=subscription-manager install --refresh -y \
  38 | >>>     intel-opencl intel-media intel-mediasdk libmfxgen1 libvpl2 \
  39 | >>>     level-zero intel-level-zero-gpu \
  40 | >>>     intel-metrics-library intel-igc-core intel-igc-cm \
  41 | >>>     libva libva-utils  intel-gmmlib && \
  42 | >>>     rpm -ivh http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/Packages/ocl-icd-2.2.12-1.el8.x86_64.rpm && \
  43 | >>>     rpm -ivh https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/c/clinfo-3.0.21.02.21-4.el8.x86_64.rpm
  44 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c rpm -ivh https://vault.centos.org/centos/8/AppStream/x86_64/os/Packages/mesa-filesystem-21.1.5-1.el8.x86_64.rpm &&     dnf --disableplugin=subscription-manager install --refresh -y     intel-opencl intel-media intel-mediasdk libmfxgen1 libvpl2     level-zero intel-level-zero-gpu     intel-metrics-library intel-igc-core intel-igc-cm     libva libva-utils  intel-gmmlib &&     rpm -ivh http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/Packages/ocl-icd-2.2.12-1.el8.x86_64.rpm &&     rpm -ivh https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/c/clinfo-3.0.21.02.21-4.el8.x86_64.rpm" did not complete successfully: exit code: 1

**Expected behavior**
container built successfully

**Screenshots**

 **Installation instructions (Please mark the checkbox)**
[  ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
Please run `python check_install.py` in the _openvino_notebooks_ directory. If the output is _NOT OK_ for any of the checks, please follow the instructions to fix that. If that does not work, or if you still encounter the issue, please paste the output of check_install.py here.

bjean09@n4-emr-1:~/openvino_notebooks$ python3 check_install.py 
System information:
Python executable: /usr/bin/python3
Pip version: 22.0.2
OpenVINO environment activated: NOT OK
Jupyter kernel installed for openvino_env: NOT OK
Python version: 3.10 OK
OpenVINO pip package installed: NOT OK
OpenVINO import succeeds: NOT OK
OpenVINO development tools installed: NOT OK
OpenVINO not installed globally: OK
No broken requirements: NOT OK

 
**Additional context**

**Comment by brijean** [comment]
adding complete output from docker build command:

bjean09@n4-emr-1:~/openvino_notebooks$ sudo docker build -t openvino_notebooks .
[+] Building 180.5s (8/25)                                                                                                        docker:default
 => [internal] load build definition from Dockerfile                                                                                        0.0s
 => => transferring dockerfile: 3.03kB                                                                                                      0.0s
 => [internal] load metadata for quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.29.0                                                          0.2s
 => [internal] load .dockerignore                                                                                                           0.0s
 => => transferring context: 2B                                                                                                             0.0s
 => [ 1/21] FROM quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.29.0@sha256:457c5346b912e2fe383d61bc8409ec3fca130034c7875646671192587e9839c0  0.0s
 => [internal] load build context                                                                                                           0.0s
 => => transferring context: 36.65kB                                                                                                        0.0s
 => CACHED [ 2/21] RUN dnf --disableplugin=subscription-manager remove -y nodejs &&   dnf --disableplugin=subscription-manager module -y r  0.0s
 => CACHED [ 3/21] RUN dnf --disableplugin=subscription-manager install -y 'dnf-command(config-manager)' &&     dnf --disableplugin=subscr  0.0s
 => ERROR [ 4/21] RUN rpm -ivh https://vault.centos.org/centos/8/AppStream/x86_64/os/Packages/mesa-filesystem-21.1.5-1.el8.x86_64.rpm &&  180.3s
------                                                                                                                                           
 > [ 4/21] RUN rpm -ivh https://vault.centos.org/centos/8/AppStream/x86_64/os/Packages/mesa-filesystem-21.1.5-1.el8.x86_64.rpm &&     dnf --disableplugin=subscription-manager install --refresh -y     intel-opencl intel-media intel-mediasdk libmfxgen1 libvpl2     level-zero intel-level-zero-gpu     intel-metrics-library intel-igc-core intel-igc-cm     libva libva-utils  intel-gmmlib &&     rpm -ivh http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/Packages/ocl-icd-2.2.12-1.el8.x86_64.rpm &&     rpm -ivh https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/c/clinfo-3.0.21.02.21-4.el8.x86_64.rpm:                                                                                                    
4.508 warning: /var/tmp/rpm-tmp.5tCDiK: Header V3 RSA/SHA256 Signature, key ID 8483c65d: NOKEY
4.581 Retrieving https://vault.centos.org/centos/8/AppStream/x86_64/os/Packages/mesa-filesystem-21.1.5-1.el8.x86_64.rpm
4.581 Verifying...                          ########################################
4.632 Preparing...                          ########################################
4.636 Updating / installing...
4.636 mesa-filesystem-21.1.5-1.el8          ########################################
12.85 Intel graphics rhel-8.6                          12 kB/s |  98 kB     00:07    
16.27 Red Hat Universal Base Image 8 (RPMs) - BaseOS  1.1 kB/s | 3.8 kB     00:03    
19.73 Red Hat Universal Base Image 8 (RPMs) - AppStre 1.3 kB/s | 4.2 kB     00:03    
26.59 Red Hat Universal Base Image 8 (RPMs) - AppStre 449 kB/s | 3.0 MB     00:06    
30.35 Red Hat Universal Base Image 8 (RPMs) - CodeRea 1.1 kB/s | 3.8 kB     00:03    
37.26 Red Hat Universal Base Image 8 (RPMs) - CodeRea  15 kB/s | 102 kB     00:06    
37.55 Dependencies resolved.
37.55 =======================================================================================
37.55  Package                 Arch    Version                 Repository                Size
37.55 =======================================================================================
37.55 Installing:
37.55  intel-gmmlib            x86_64  22.3.1-i529.el8         intel-graphics-rhel-8.6  153 k
37.55  intel-igc-cm            x86_64  1.0.176-i537.el8        intel-graphics-rhel-8.6   17 M
37.55  intel-igc-core          x86_64  1.0.12504.6-i537.el8    intel-graphics-rhel-8.6   22 M
37.55  intel-level-zero-gpu    x86_64  1.3.24595.35-i538.el8   intel-graphics-rhel-8.6  1.9 M
37.55  intel-media             x86_64  22.6.4-i539.el8         intel-graphics-rhel-8.6  7.2 M
37.55  intel-mediasdk          x86_64  22.6.4-i539.el8         intel-graphics-rhel-8.6  3.2 M
37.55  intel-metrics-library   x86_64  1.0.114-i524.el8        intel-graphics-rhel-8.6  616 k
37.55  intel-opencl            x86_64  22.43.24595.35-i538.el8 intel-graphics-rhel-8.6  2.0 M
37.55  level-zero              x86_64  1.8.8-i524.el8          intel-graphics-rhel-8.6  150 k
37.55  libmfxgen1              x86_64  22.6.4-i539.el8         intel-graphics-rhel-8.6  3.6 M
37.55  libva                   x86_64  2.16.0.2-41.el8         intel-graphics-rhel-8.6  102 k
37.55  libva-utils             x86_64  2.16.0.2-1.0.40.el8     intel-graphics-rhel-8.6  518 k
37.55  libvpl2                 x86_64  2023.1.0.0-i529.el8     intel-graphics-rhel-8.6  100 k
37.55 Installing dependencies:
37.55  intel-igc-opencl        x86_64  1.0.12504.6-i537.el8    intel-graphics-rhel-8.6   21 M
37.55  libwayland-client       x86_64  1.21.0-1.el8            ubi-8-appstream           41 k
37.55 
37.55 Transaction Summary
37.55 =======================================================================================
37.55 Install  15 Packages
37.55 
37.55 Total download size: 79 M
37.55 Installed size: 79 M
37.55 Downloading Packages:
41.46 (1/15): intel-igc-core-1.0.12504.6-i537.el8.x86 5.6 MB/s |  22 MB     00:03    
41.49 (2/15): intel-gmmlib-22.3.1-i529.el8.x86_64.rpm  39 kB/s | 153 kB     00:03    
41.62 (3/15): intel-igc-cm-1.0.176-i537.el8.x86_64.rp 4.1 MB/s |  17 MB     00:04    
41.82 (4/15): intel-igc-opencl-1.0.12504.6-i537.el8.x  57 MB/s |  21 MB     00:00    
41.83 (5/15): intel-level-zero-gpu-1.3.24595.35-i538. 5.7 MB/s | 1.9 MB     00:00    
41.92 (6/15): intel-media-22.6.4-i539.el8.x86_64.rpm   24 MB/s | 7.2 MB     00:00    
42.09 (7/15): intel-mediasdk-22.6.4-i539.el8.x86_64.r  12 MB/s | 3.2 MB     00:00    
42.10 (8/15): intel-metrics-library-1.0.114-i524.el8. 2.2 MB/s | 616 kB     00:00    
42.20 (9/15): intel-opencl-22.43.24595.35-i538.el8.x8 7.2 MB/s | 2.0 MB     00:00    
42.36 (10/15): level-zero-1.8.8-i524.el8.x86_64.rpm   561 kB/s | 150 kB     00:00    
42.38 (11/15): libmfxgen1-22.6.4-i539.el8.x86_64.rpm   13 MB/s | 3.6 MB     00:00    
42.46 (12/15): libva-2.16.0.2-41.el8.x86_64.rpm       380 kB/s | 102 kB     00:00    
42.63 (13/15): libva-utils-2.16.0.2-1.0.40.el8.x86_64 1.9 MB/s | 518 kB     00:00    
42.64 (14/15): libvpl2-2023.1.0.0-i529.el8.x86_64.rpm 389 kB/s | 100 kB     00:00    
45.87 (15/15): libwayland-client-1.21.0-1.el8.x86_64.  12 kB/s |  41 kB     00:03    
45.88 --------------------------------------------------------------------------------
45.88 Total                                           9.4 MB/s |  79 MB     00:08     
49.72 Intel graphics rhel-8.6                         475  B/s | 1.8 kB     00:03    
49.77 Importing GPG key 0xDBB72B06:
49.77  Userid     : "Intel Corporation (repositories.intel.com key) <graphics-support@intel.com>"
49.77  Fingerprint: 1C1B 89D0 2C92 9514 698A A805 9B10 C065 DBB7 2B06
49.77  From       : https://repositories.intel.com/graphics/intel-graphics.key
49.78 Key imported successfully
50.13 Running transaction check
50.14 Transaction check succeeded.
50.14 Running transaction test
50.42 Transaction test succeeded.
50.42 Running transaction
50.69   Preparing        :                                                        1/1 
50.74   Installing       : intel-gmmlib-22.3.1-i529.el8.x86_64                   1/15 
50.75   Installing       : libwayland-client-1.21.0-1.el8.x86_64                 2/15 
50.77   Installing       : libva-2.16.0.2-41.el8.x86_64                          3/15 
52.40   Installing       : intel-igc-core-1.0.12504.6-i537.el8.x86_64            4/15 
53.86   Installing       : intel-igc-opencl-1.0.12504.6-i537.el8.x86_64          5/15 
54.02   Installing       : intel-level-zero-gpu-1.3.24595.35-i538.el8.x86_64     6/15 
54.20   Installing       : intel-opencl-22.43.24595.35-i538.el8.x86_64           7/15 
55.37   Installing       : intel-igc-cm-1.0.176-i537.el8.x86_64                  8/15 
55.99   Installing       : intel-media-22.6.4-i539.el8.x86_64                    9/15 
56.31   Installing       : intel-mediasdk-22.6.4-i539.el8.x86_64                10/15 
56.58   Installing       : libmfxgen1-22.6.4-i539.el8.x86_64                    11/15 
56.64   Installing       : libva-utils-2.16.0.2-1.0.40.el8.x86_64               12/15 
56.66   Installing       : libvpl2-2023.1.0.0-i529.el8.x86_64                   13/15 
56.68   Installing       : level-zero-1.8.8-i524.el8.x86_64                     14/15 
56.76   Installing       : intel-metrics-library-1.0.114-i524.el8.x86_64        15/15 
56.77   Running scriptlet: intel-metrics-library-1.0.114-i524.el8.x86_64        15/15 
56.83   Verifying        : intel-gmmlib-22.3.1-i529.el8.x86_64                   1/15 
56.83   Verifying        : intel-igc-cm-1.0.176-i537.el8.x86_64                  2/15 
56.83   Verifying        : intel-igc-core-1.0.12504.6-i537.el8.x86_64            3/15 
56.83   Verifying        : intel-igc-opencl-1.0.12504.6-i537.el8.x86_64          4/15 
56.83   Verifying        : intel-level-zero-gpu-1.3.24595.35-i538.el8.x86_64     5/15 
56.83   Verifying        : intel-media-22.6.4-i539.el8.x86_64                    6/15 
56.83   Verifying        : intel-mediasdk-22.6.4-i539.el8.x86_64                 7/15 
56.83   Verifying        : intel-metrics-library-1.0.114-i524.el8.x86_64         8/15 
56.83   Verifying        : intel-opencl-22.43.24595.35-i538.el8.x86_64           9/15 
56.83   Verifying        : level-zero-1.8.8-i524.el8.x86_64                     10/15 
56.83   Verifying        : libmfxgen1-22.6.4-i539.el8.x86_64                    11/15 
56.83   Verifying        : libva-2.16.0.2-41.el8.x86_64                         12/15 
56.83   Verifying        : libva-utils-2.16.0.2-1.0.40.el8.x86_64               13/15 
56.83   Verifying        : libvpl2-2023.1.0.0-i529.el8.x86_64                   14/15 
56.83   Verifying        : libwayland-client-1.21.0-1.el8.x86_64                15/15 
56.90 Installed products updated.
56.95 
56.96 Installed:
56.96   intel-gmmlib-22.3.1-i529.el8.x86_64                                           
56.96   intel-igc-cm-1.0.176-i537.el8.x86_64                                          
56.96   intel-igc-core-1.0.12504.6-i537.el8.x86_64                                    
56.96   intel-igc-opencl-1.0.12504.6-i537.el8.x86_64                                  
56.96   intel-level-zero-gpu-1.3.24595.35-i538.el8.x86_64                             
56.96   intel-media-22.6.4-i539.el8.x86_64                                            
56.96   intel-mediasdk-22.6.4-i539.el8.x86_64                                         
56.96   intel-metrics-library-1.0.114-i524.el8.x86_64                                 
56.96   intel-opencl-22.43.24595.35-i538.el8.x86_64                                   
56.96   level-zero-1.8.8-i524.el8.x86_64                                              
56.96   libmfxgen1-22.6.4-i539.el8.x86_64                                             
56.96   libva-2.16.0.2-41.el8.x86_64                                                  
56.96   libva-utils-2.16.0.2-1.0.40.el8.x86_64                                        
56.96   libvpl2-2023.1.0.0-i529.el8.x86_64                                            
56.96   libwayland-client-1.21.0-1.el8.x86_64                                         
56.96 
56.96 Complete!
180.2 curl: (56) Recv failure: Connection reset by peer
180.2 error: skipping http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/Packages/ocl-icd-2.2.12-1.el8.x86_64.rpm - transfer failed
180.2 Retrieving http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/Packages/ocl-icd-2.2.12-1.el8.x86_64.rpm
------
Dockerfile:36
--------------------
  35 |     
  36 | >>> RUN rpm -ivh https://vault.centos.org/centos/8/AppStream/x86_64/os/Packages/mesa-filesystem-21.1.5-1.el8.x86_64.rpm && \
  37 | >>>     dnf --disableplugin=subscription-manager install --refresh -y \
  38 | >>>     intel-opencl intel-media intel-mediasdk libmfxgen1 libvpl2 \
  39 | >>>     level-zero intel-level-zero-gpu \
  40 | >>>     intel-metrics-library intel-igc-core intel-igc-cm \
  41 | >>>     libva libva-utils  intel-gmmlib && \
  42 | >>>     rpm -ivh http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/Packages/ocl-icd-2.2.12-1.el8.x86_64.rpm && \
  43 | >>>     rpm -ivh https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/c/clinfo-3.0.21.02.21-4.el8.x86_64.rpm
  44 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c rpm -ivh https://vault.centos.org/centos/8/AppStream/x86_64/os/Packages/mesa-filesystem-21.1.5-1.el8.x86_64.rpm &&     dnf --disableplugin=subscription-manager install --refresh -y     intel-opencl intel-media intel-mediasdk libmfxgen1 libvpl2     level-zero intel-level-zero-gpu     intel-metrics-library intel-igc-core intel-igc-cm     libva libva-utils  intel-gmmlib &&     rpm -ivh http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/Packages/ocl-icd-2.2.12-1.el8.x86_64.rpm &&     rpm -ivh https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/c/clinfo-3.0.21.02.21-4.el8.x86_64.rpm" did not complete successfully: exit code: 1

**Comment by Iffa-Intel** [comment]
Hi @brijean I managed to build the OpenVINO Notebook in Ubuntu 22.04 using Docker.

<img width="557" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/9015dfb1-7d95-41aa-bfe2-c971318930a3">

I'm using Docker version 26.1.2
<img width="437" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/79643476/782e1297-b6ef-4cef-80aa-1b615f853ab4">

Try upgrading your Docker version to the latest as I did using the command:
sudo apt-get update
sudo apt-get upgrade docker-ce

**Comment by Iffa-Intel** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
