### ISSUE TITLE
Is  LLama3 model (int4) compiled for NPU compatible to connect Langchain based RAG system

### ISSUE THREAD

**Issue by sujikarNStarx** [openvinotoolkit/openvino_notebooks#2067]
Issue brief:

We have been trying to use llama3 model (int4) compiled for NPU (using Intel cpu acceleration library) to connect with langchain RAG (using  HuggingFacePipeline method). 

It would helpful if there are any compatibility issues between NPU compiled LLM and Langchain based RAG framework.

If there is no compatibility issues, may I know the suitable method.

**Comment by Aznie-Intel** [comment]
Hi @sujikarNStarx, to load LLM model, OpenVINO models can be run locally using the HuggingFacePipeline class by specifying the backend;="openvino" parameter to trigger the backend inference framework. However, as of Intel OpenVINO version 2024.0, Large Language models (LLMs) are not supported by the Intel NPU plugin.

You may refer to [Create a RAG system using OpenVINO and Langchain](https://docs.openvino.ai/2024/notebooks/llm-rag-langchain-with-output.html#create-a-rag-system-using-openvino-and-langchain).

**Comment by Aznie-Intel** [comment]
Closing issue, feel free to re-open or start a new issue if additional information assistance is needed.
