### ISSUE TITLE
Unable to compile Llama3 8B model for NPU using Openvino  (we have latest NPU drivers - April 2024 version)

### ISSUE THREAD

**Issue by sujikarNStarx** [openvinotoolkit/openvino_notebooks#2068]
While we try to compile Llama3 model (int8 and IR version) using Openvino Compile method, we end up with following error:

**RuntimeError: Exception from src\inference\src\cpp\core.cpp:109:
Exception from src\inference\src\dev\plugin.cpp:54:
Exception from src\plugins\intel_npu\src\plugin\src\plugin.cpp:513:
get_shape was called on a descriptor::Tensor with dynamic shape**

**Code Used:**

import os
from functions import convert_to_int8
from pathlib import Path
import requests
import io
import openvino as ov
import torch
from transformers import (
    TextIteratorStreamer,
    StoppingCriteria,
    StoppingCriteriaList,
)
from llm_config import (
    SUPPORTED_EMBEDDING_MODELS,
    SUPPORTED_RERANK_MODELS,
    SUPPORTED_LLM_MODELS,
)
from langchain_community.embeddings import OpenVINOBgeEmbeddings
from langchain_community.document_compressors.openvino_rerank import OpenVINOReranker
from langchain_community.llms.huggingface_pipeline import HuggingFacePipeline
from langchain.docstore.document import Document
from langchain.retrievers import ContextualCompressionRetriever
from langchain.prompts import PromptTemplate
from langchain.vectorstores import Chroma
from langchain.chains.combine_documents import create_stuff_documents_chain
from langchain.chains.retrieval import create_retrieval_chain
from langchain.text_splitter import CharacterTextSplitter, RecursiveCharacterTextSplitter, MarkdownTextSplitter

model_language = "English"
llm_model_id = "llama-3-8b-instruct"
embedding_model_id = "bge-large-en-v1.5"
rerank_model_id = "bge-reranker-large"
embedding_device = "CPU"
rerank_device = "CPU"
llm_device = "NPU"
docs = [{'name': '/home/skasi/kovid/openvino_notebooks/notebooks/llm-rag-langchain/text_example_cn.pdf'}]
model_to_run = "INT8"
llm_model_configuration = SUPPORTED_LLM_MODELS[model_language][llm_model_id]
print(f"Selected LLM model {llm_model_id}")

# Weights Compression using Optimum-CLI
int8_model_dir = Path(llm_model_id) / "INT8_compressed_weights"
convert_to_int8()
int8_weights = int8_model_dir / "openvino_model.bin"

# Load LLM model
core = ov.Core()
support_devices = core.available_devices
model_dir = int8_model_dir
ov_config = {"PERFORMANCE_HINT": "LATENCY", "INFERENCE_NUM_THREADS": "3", "NUM_STREAMS": "1", "CACHE_DIR": ""}

# model = intel_npu_acceleration_library.compile(str(model_dir), dtype=torch.int8)
device = "NPU"
model_compile_xml= r"C:\Users\SHI-Labs-01\Documents\euc_docker\openvino_notebooks\notebooks\llm-rag-langchain\llama-3-8b-instruct\INT8_compressed_weights\openvino_model.xml"
# # model = intel_npu_acceleration_library.compile(str(model_dir),dtype= torch.int8)
model = core.read_model(str(model_compile_xml))
compiled_model = core.compile_model(model, device)

llm = HuggingFacePipeline.from_model_id(
    model_id= compiled_model,
    task="text-generation",
    backend="openvino",
    model_kwargs={
        "device": device,
        "ov_config": ov_config,
        "trust_remote_code": True,
    },
    pipeline_kwargs={"max_new_tokens": 360},
)
print('1')
print(llm_model_id)
print(llm.invoke("who is ram chandra prabhu?”))

**Below two lines are important in the above code:**

model = core.read_model(str(model_compile_xml))
compiled_model = core.compile_model(model, device)

**Comment by Aznie-Intel** [comment]
Hi @sujikarNStarx , the error is expected due to the limitation of NPU plugin. Only models with static shapes are supported on NPU. You may refer to [Limitations](https://docs.openvino.ai/2024/openvino-workflow/running-inference/inference-devices-and-modes/npu-device.html#limitations) in NPU Device.

**Comment by Aznie-Intel** [comment]
Closing issue, feel free to re-open or restart a new issue if additional assistance is needed.
