### ISSUE TITLE
[Issue]: KeyError: "phi3 is not supported yet for transformers.

### ISSUE THREAD

**Issue by saivivekseeram1** [openvinotoolkit/openvino_notebooks#2082]
### Context

Worked in phi-3, model id  from hugging face: **microsoft/Phi-3-mini-128k-instruct**.
opevino-version: 2024.3.0-15583-df6a25800d3
i'm using transformers: **transformers 4.39.3** 

below is the error:

KeyError: "**phi3 is not supported yet for transformers.** Only ['audio-spectrogram-transformer', 'albert', 'bart', 'beit', 'bert', 'blenderbot', 'blenderbot-small', 'bloom', 'camembert', 'clip', 'codegen', 'convbert', 'convnext', 'convnextv2', 'cvt', 'data2vec-text', 'data2vec-vision', 'data2vec-audio', 'deberta', 'deberta-v2', 'deit', 'detr', 'distilbert', 'donut', 'donut-swin', 'dpt', 'electra', 'encoder-decoder', 'esm', 'falcon', 'flaubert', 'gemma', 'glpn', 'gpt2', 'gpt-bigcode', 'gptj', 'gpt-neo', 'gpt-neox', 'groupvit', 'hubert', 'ibert', 'imagegpt', 'layoutlm', 'layoutlmv3', 'lilt', 'levit', 'longt5', 'marian', 'markuplm', 'mbart', 'mistral', 'mobilebert', 'mobilevit', 'mobilenet-v1', 'mobilenet-v2', 'mpnet', 'mpt', 'mt5', 'musicgen', 'm2m-100', 'nystromformer', 'owlv2', 'owlvit', 'opt', 'qwen2', 'llama', 'pegasus', 'perceiver', 'phi', 'pix2struct', 'poolformer', 'regnet', 'resnet', 'roberta', 'roformer', 'sam', 'segformer', 'sew', 'sew-d', 'speech-to-text', 'speecht5', 'splinter', 'squeezebert', 'swin', 'swin2sr', 't5', 'table-transformer', 'trocr', 'unispeech', 'unispeech-sat', 'vision-encoder-decoder', 'vit', 'wavlm', 'wav2vec2', 'wav2vec2-conformer', 'whisper', 'xlm', 'xlm-roberta', 'yolos', 'baichuan', 'minicpm', 'stablelm', 'chatglm', 'mixtral', 'qwen', 'starcoder2', 'yi', 'jais', 'stablelm_epoch', 'stablelm-epoch', 'stablelm2', 'aquila', 'codegen2'] are supported for the library transformers. If you want to support phi3 please propose a PR or open up an issue."

but i've seen the **transformers>=4.38.1** which is used  in openvino_notebooks.
for the referfence i've attched the screeshots.

![ov-notebbok-phi3](https://github.com/openvinotoolkit/openvino.genai/assets/92068535/1b3cf771-9f26-45a1-945e-ec5d160ed017)

![Screenshot 2024-06-06 105857](https://github.com/openvinotoolkit/openvino.genai/assets/92068535/857f6ff7-46f6-4617-978a-8dc70d54cabb)

### What needs to be done?

provide transformers for phi-3 model

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers
- [How to link your Pull Request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar)

### Contact points

@ngaloppo @ilya-lavrenov @alexsu52 @ljaljushkin @pavel-esir

**Comment by eaidova** [comment]
@saivivekseeram1 thank that you let us know! I prepared upgrade version in notebooks https://github.com/openvinotoolkit/openvino_notebooks/pull/2085
