### ISSUE TITLE
Rename to tutorials

### ISSUE THREAD

**Issue by AlexKoff88** [openvinotoolkit/openvino_notebooks#210]
While it is not so popular outside can we rename this repo to "tutorials". I think openvio_ prefix is not needed because it is already in the group that is named openvinotoolkit.
The official name can be changed to OpenVINO™ Tutorials.

**Comment by raymondlo84** [comment]
It is not as simple, unfortunately. Also, once you have this checkout or cloned, you will see a generic name (tutorial folder) and it also create other issues as it is losing its product branding. 

Also, we don't consider this as just a pure tutorial - but a bridge to Jupyter Notebooks. We have other efforts that also create tutorials, including c++ so we cannot simply support all different variances.

:) Let's chat with me more and @ryanloney can also put a few cents here and there too.
