### ISSUE TITLE
Pip install intel-extension-for-pytorch does not work. 

### ISSUE THREAD

**Issue by T-Bradley** [openvinotoolkit/openvino_notebooks#2104]
I tried to follow the OneAPI toolkit and Intel extension for pytorch installation process as described [here.](https://community.intel.com/t5/GPU-Compute-Software/How-to-train-yolov8-using-intel-arc-770-gpu/m-p/1597471#M1418

pip install intel-extension-for-pytorch returned this error:

ERROR: Could not find a version that satisfies the requirement intel-extension-for-pytorch (from versions: none)
ERROR: No matching distribution found for intel-extension-for-pytorch

----------

I also tried to install intel-extensions-for-pytorch by following the github documentation [here.](https://intel.github.io/intel-extension-for-pytorch/index.html#installation?platform=gpu&version=v2.1.30%2bxpu&os=windows&package=pip)

When I tried to import intel-extension-for-pytorch in python, I received this error. 

OSError: [WinError 126] The specified module could not be found. Error loading "C:\ProgramData\anaconda3\envs\arc\Lib\site-packages\intel_extension_for_pytorch\bin\intel-ext-pt-gpu.dll" or one of its dependencies.
 
I am using HP laptop with Ultra 5 125 H and Intel Arc Graphics.

**Comment by andrei-kochin** [comment]
Hello @T-Bradley,

We are not responsible for the IPEX so I'd suggest you to follow out Yolov8 notebooks and enjoy the optimized performance on the Intel HW https://github.com/openvinotoolkit/openvino_notebooks/tree/latest/notebooks/yolov8-optimization

Happy coding!

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen to ask any questions concerning OpenVINO.
