### ISSUE TITLE
Binder URL is not working for 208 notebook

### ISSUE THREAD

**Issue by ryanloney** [openvinotoolkit/openvino_notebooks#213]
This is what I see after clicking on the Binder link in 208 OCR README (https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/208-optical-character-recognition/README.md) and main README:
![image](https://user-images.githubusercontent.com/15709723/130703439-8eef6633-7324-46af-8b6e-c7ebed13d0ca.png)

**Comment by Debskij** [comment]
Removed binder buttons due to exceeding memory
