### ISSUE TITLE
105 Notebook Error

### ISSUE THREAD

**Issue by raymondlo84** [openvinotoolkit/openvino_notebooks#216]
When I run this on Windows, I got this error. 

```
'unzip' is not recognized as an internal or external command,
operable program or batch file.
```

I would recommend use the Python library and so we don't depend on the user's environments.
(e.g., import zipfile)

@ryanloney - what's your setup on Windows?

**Comment by raymondlo84** [comment]
Also, we shall standardize all 'curl' downloads with the progress bar UI. That was one of the key UX requirements we discussed much much earlier.

**Comment by helena-intel** [comment]
Thanks for catching this @raymondlo84, and for the fix @Debskij .
