### ISSUE TITLE
llm-rag-langchain answer wrongly when using llama-3-8b-instruct

### ISSUE THREAD

**Issue by openvino-book** [openvinotoolkit/openvino_notebooks#2164]
**Describe the bug**
llm-rag-langchain answer wrongly when using llama-3-8b-instruct + bge-small-en-v1.5 model + bge-reranker-large
The llama-3-8b-instruct is quantized to INT4

All models are loaded into CPU
bge-small-en-v1.5 model  looks being loaded successfully.
![1719997033377](https://github.com/openvinotoolkit/openvino_notebooks/assets/128127436/2d7d47a8-eff9-4b3d-9609-1c677ff48da3)

bge-reranker-large model  looks being loaded successfully.
![1719997103108](https://github.com/openvinotoolkit/openvino_notebooks/assets/128127436/61f2fcfb-6e71-4a08-832c-8337c032ee57)

 llama-3-8b-instruct INT4 model looks being loaded successfully.
![1719997177987](https://github.com/openvinotoolkit/openvino_notebooks/assets/128127436/35700033-87bc-4965-80ca-ebb439751347)

**Bug**: The generated answer should be correct, however, it's totally **wrong**!
![1719997413806](https://github.com/openvinotoolkit/openvino_notebooks/assets/128127436/007dc4b7-a260-4123-b544-1ea32b3be639)

 **Installation instructions (Please mark the checkbox)**
[ √ ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
Please run `python check_install.py` in the _openvino_notebooks_ directory. If the output is _NOT OK_ for any of the checks, please follow the instructions to fix that. If that does not work, or if you still encounter the issue, please paste the output of check_install.py here.
 
![1719997534263](https://github.com/openvinotoolkit/openvino_notebooks/assets/128127436/7798a98a-f77c-4fbc-a63e-c6aea3cd864b)

**Additional context**

**Comment by openvino-dev-samples** [comment]
hi @openvino-book could you click on the `Hide searching result in prompt` and then try it again ?

It works good on my side.

![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/91237924/fcdda309-fa03-4586-b799-79b4de0ce987)

**Comment by openvino-dev-samples** [comment]
Here my langchain and Transformers lib version, for your reference

```
langchain==0.2.6
langchain-community==0.2.6
langchain-core==0.2.11
langchain-text-splitters==0.2.2
langchainhub==0.1.20
llama-index-llms-langchain==0.1.4

sentence-transformers==3.0.1
transformers==4.40.2
transformers-stream-generator==0.0.5
```

**Comment by openvino-book** [comment]
> Here my langchain and Transformers lib version, for your reference
> 
> ```
> langchain==0.2.6
> langchain-community==0.2.6
> langchain-core==0.2.11
> langchain-text-splitters==0.2.2
> langchainhub==0.1.20
> llama-index-llms-langchain==0.1.4
> 
> sentence-transformers==3.0.1
> transformers==4.40.2
> transformers-stream-generator==0.0.5
> ```

That's helpful! I guess I use the Ali source, which keeps the version of transformer as **4.32.1**
![9d0eda81d02983b43400a752be24c9a](https://github.com/openvinotoolkit/openvino_notebooks/assets/128127436/52567856-42ce-47b4-a04f-a967245d4d34)

I'll try it again, let you know the result

**Comment by openvino-book** [comment]
Finally, the problem has been solved, thank you @OpenVINO-dev-contest very much!
![QAwithLlama3](https://github.com/openvinotoolkit/openvino_notebooks/assets/128127436/a4951a3e-9226-42c3-97ec-62d28b1a232a)

**Comment by openvino-book** [comment]
The key Python packages should be
> transformers==4.41.2
optimum-intel==1.18.0
openvino-tokenizers==2024.2.0.0
openvino==2024.2.0
nncf==2.11.0
langchain==0.2.6
langchain-community==0.2.6
langchain-core==0.2.11
langchain-text-splitters==0.2.2
langchainhub==0.1.20

The Llama3 weights should choose the certifed one from LLM Research
![1720256896748](https://github.com/openvinotoolkit/openvino_notebooks/assets/128127436/b5997042-afa5-4599-9be7-c1c67f6808cc)
