### ISSUE TITLE
Cannot create StringTensorUnpack layer StringTensorUnpack_220719 id:5 from unsupported opset: extension

### ISSUE THREAD

**Issue by GaryLin-04** [openvinotoolkit/openvino_notebooks#2263]
**Describe the bug**

import argparse
from pathlib import Path

core = ov.Core()

parser = argparse.ArgumentParser()
parser.add_argument('-m', '--model', type=str, help="The local llm's folder", default='OV_Llama-3-8B-Instruct_Int4')
args = parser.parse_args()

tokenizer_path = Path(args.model, "openvino_tokenizer.xml")
model_path = Path(args.model, "openvino_model.xml")
detokinizer_path = Path(args.model, "openvino_detokenizer.xml")  
  
compiled_tokenizer = core.compile_model(tokenizer_path.as_posix())
compiled_model = core.compile_model(model_path.as_posix())
compiled_detokenizer = core.compile_model(detokinizer_path.as_posix())

the **compiled_tokenizer**  and **compiled_detokenizer**  will error and show 
Traceback (most recent call last):
  File "D:\Code\React\[TD-KQX60]OmniNote\CODE\llama2_test\tt.py", line 15, in <module>
    compiled_tokenizer = core.compile_model(tokenizer_path.as_posix())
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\compa\anaconda3\envs\KQX50_60\Lib\site-packages\openvino\runtime\ie_api.py", line 540, in compile_model
    super().compile_model(model, {} if config is None else config),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Exception from src\inference\src\cpp\core.cpp:124:
Exception from src\inference\src\dev\plugin.cpp:58:
Exception from src\plugins\auto\src\auto_schedule.cpp:441:
[AUTO] compile model failed, GPU:Exception from src\inference\src\dev\plugin.cpp:58:
Exception from src\frontends\ir\src\ir_deserializer.cpp:911:
Cannot create StringTensorUnpack layer StringTensorUnpack_220719 id:5 from unsupported opset: extension

; CPU:Exception from src\inference\src\dev\plugin.cpp:58:
Exception from src\frontends\ir\src\ir_deserializer.cpp:911:
Cannot create StringTensorUnpack layer StringTensorUnpack_220719 id:5 from unsupported opset: extension

;

but compiled_model  pass

 **Expected behavior**
Convert llama3 Pytorch model to OpenVINO NNCF INT4 Mode
use convert.py  :  python convert.py -m  Meta-Llama-3-8B-Instruct/ -p FP16 --compress_weights_backends openvino -c INT4_SYM --ratio 1 --group_size 128 --stateful --force_convert -o Meta-Llama-3-8B-Instruct-OV

use optimum-cli  : optimum-cli export openvino --model "./Meta-Llama-3-8B-Instruct_huggingface"  --trust-remote-code --task text-generation-with-past --weight-format int4 "OV_Llama-3-8B-Instruct_Int4"

both model fail

**Screenshots**
![image](https://github.com/user-attachments/assets/1301fb4f-e6fd-4583-a3aa-fb3fec6d7daf)

 **Installation instructions (Please mark the checkbox)**
[  ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
![image](https://github.com/user-attachments/assets/f5a08246-555e-46ad-b94b-980dfe2d5e95) 

**Additional context**
![image](https://github.com/user-attachments/assets/bf7f6ca6-5127-413b-8628-3a08d500d094)

**Comment by eaidova** [comment]
@GaryLin-04 to register tokenizer extension, you need to add  import openvino_tokenzizers before import openvino. See for details https://github.com/openvinotoolkit/openvino_tokenizers?tab=readme-ov-file#use-extension-with-converted-detokenizer-or-model-with-detokenizer

**Comment by GaryLin-04** [comment]
> @GaryLin-04 to register tokenizer extension, you need to add import openvino_tokenzizers before import openvino. See for details https://github.com/openvinotoolkit/openvino_tokenizers?tab=readme-ov-file#use-extension-with-converted-detokenizer-or-model-with-detokenizer

Tks,  it  ok now
