### ISSUE TITLE
llm-chatbot-generate-api notebook fails during pip / git install routine

### ISSUE THREAD

**Issue by RyanMetcalfeInt8** [openvinotoolkit/openvino_notebooks#2273]
![image](https://github.com/user-attachments/assets/d660414a-da50-4963-b0b7-29fde7617ccd)

Digging into it a bit, it looks like support-transformers-4.43 branch of optimum repo was merged / deleted 2 days ago:https://github.com/huggingface/optimum/pull/1971

**Comment by Wan-Intel** [comment]
I also encountered the following error when running [Create an LLM-powered Chatbot using OpenVINO™ Generate API](https://github.com/openvinotoolkit/openvino_notebooks/blob/latest/notebooks/llm-chatbot/llm-chatbot-generate-api.ipynb) with the [OpenVINO™ Notebooks Master branch](https://github.com/openvinotoolkit/openvino_notebooks):
`git checkout -q support-transformers-4.43 did not run successfully`

![support-transformers error](https://github.com/user-attachments/assets/5f898728-8cea-47c6-bda2-7f0e1d220e62)

Let me check with relevant team and we'll update you as soon as possible.

**Comment by eaidova** [comment]
should be fixed here https://github.com/openvinotoolkit/openvino_notebooks/pull/2274

**Comment by avitial** [comment]
Closing this as PR addressing this issue has been merged to master. Feel free to reopen and ask additional questions related to this topic.
