### ISSUE TITLE
Problem with openvino's yolov8-keypoint-detection tutorial

### ISSUE THREAD

**Issue by yunseok624** [openvinotoolkit/openvino_notebooks#2296]
**Describe the bug**
I'm getting a problem within the openvino tutorial. When I run code in the jupyter notebook then everything is okay. However, if I run the same code as a script to run outside the jupyter notebook then I get a problem.
```
Traceback (most recent call last):
  File "create_video_demo_openvino_1.py", line 25, in <module>
    pose_model.predictor.inference = infer
AttributeError: 'NoneType' object has no attribute 'inference'
```

 **Code to replicate**
```
import openvino as ov
from ultralytics import YOLO
import cv2
import numpy as np
from pathlib import Path
import torch

device = "GPU"

pose_model = YOLO("/home/aias-nuc/Documents/benchmark/azure_pose.pt")

pose_model_path = "/home/aias-nuc/Documents/benchmark/azure_pose_openvino_model/azure_pose.xml"

core = ov.runtime.Core()
pose_ov_model = core.read_model(pose_model_path)

pose_ov_model.reshape({0: [1, 3, 640, 640]})
ov_config = {"GPU_DISABLE_WINOGRAD_CONVOLUTION": "YES"}
pose_compiled_model = core.compile_model(pose_ov_model, device, ov_config)

def infer(*args):
    result = pose_compiled_model(args)
    return torch.from_numpy(result[0])

pose_model.predictor.inference = infer
pose_model.predictor.model.pt = False
```

 **Installation instructions (Please mark the checkbox)**
[ x ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks.

**Comment by brmarkus** [comment]
Looks like you haven't exported the model.

You initialize `pose_model` with `pose_model = YOLO("/home/aias-nuc/Documents/benchmark/azure_pose.pt")`.

Then you need to export with `pose_model.export(format="openvino", dynamic=True, half=True)`.

Otherwise `pose_model.predictor.inference` won't be created.

It looks like you don't need to export it - as just a few lines later you load it with `pose_ov_model = core.read_model(pose_model_path)`, assuming you already had exported it, right?

You could directly continue to a later section from the Jupyter notebook where you do the inference with OpenVINO, instead of via YOLO.

**Comment by yunseok624** [comment]
> Looks like you haven't exported the model.
> 
> You initialize `pose_model` with `pose_model = YOLO("/home/aias-nuc/Documents/benchmark/azure_pose.pt")`.
> 
> Then you need to export with `pose_model.export(format="openvino", dynamic=True, half=True)`.
> 
> Otherwise `pose_model.predictor.inference` won't be created.
> 
> It looks like you don't need to export it - as just a few lines later you load it with `pose_ov_model = core.read_model(pose_model_path)`, assuming you already had exported it, right?
> 
> You could directly continue to a later section from the Jupyter notebook where you do the inference with OpenVINO, instead of via YOLO.

I don't see a later section [here](https://github.com/openvinotoolkit/openvino_notebooks/blob/latest/notebooks/yolov8-optimization/yolov8-keypoint-detection.ipynb) where I can do the inference with OpenVINO instead of via YOLO.

What I also do not understand is that it works perfectly fine in jupyter notebook, however if I just copy paste the code in the Python script then it shows me an error.

**Comment by brmarkus** [comment]
In the Jupyter notebook "https://github.com/openvinotoolkit/openvino_notebooks/blob/latest/notebooks/yolov8-optimization/yolov8-keypoint-detection.ipynb", it starts in cell [3] with the initialization of variable `pose_model`.
An inference is done with YOLO with `pose_model(IMAGE_PATH)`.

In cell [6] the object `pose_model` gets extended with additional attributes when exporting to and storing as OpenVINO IR.

In cell [8] the OpenVINO IR model gets compiled and stored in `pose_compiled_model`. That is done using the OpenVINO core class with `core = ov.Core()` and with `pose_compiled_model = core.compile_model(pose_ov_model, device.value, ov_config)`.

YOLO calls the "callback" function `def infer(*args)` and calls the OpenVINO inferene with `result = pose_compiled_model(args)`.

You could have a look into the pose-estimation notebook under "https://github.com/openvinotoolkit/openvino_notebooks/blob/latest/notebooks/pose-estimation-webcam/pose-estimation.ipynb" - where you could use the YOLO-exported OpenVINO IR model files (using a single picture, or video-file or webcam; you would need to double-check the "keypoints" from the Yolov8-keyport model and compare with the notebook "pose-estimation-webcam" where the "skeleton" gets drawn using the knowledge about the keypoints).
