### ISSUE TITLE
Cannot export pytorch to onnx

### ISSUE THREAD

**Issue by adrianboguszewski** [openvinotoolkit/openvino_notebooks#232]
In `102-pytorch-onnx-to-openvino` and fourth code cell:
`RuntimeError: Exporting the operator relu6 to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.`

Tried with python 3.9.6 and pytorch 1.9.0

**Comment by helena-intel** [comment]
Sadly, at this moment Python 3.9 is not yet supported by OpenVINO. The notebooks are tested with Python 3.6-3.8 and the requirements.txt in this repository. See the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide
