### ISSUE TITLE
Cannot benchmark app

### ISSUE THREAD

**Issue by adrianboguszewski** [openvinotoolkit/openvino_notebooks#233]
In `104-model-tools` and `105-language-quantize-bert `both `benchmark_model` and `benchmark_app` shows following issue:
`ModuleNotFoundError: No module named 'openvino.tools'`

I've installed `openvino-dev==2021.4.0 `

**Comment by helena-intel** [comment]
I assume this was with Python 3.9? If so, see #232

**Comment by adrianboguszewski** [comment]
Yes, but it doesn't look like related to a specific python version

**Comment by helena-intel** [comment]
Do you still see this issue with Python 3.6-3.8? Can give more information about your environment? Could you run `python check_install.py` in the root of the openvino_notebooks directory and post the output?

**Comment by adrianboguszewski** [comment]
Yes, this is the same for the environment created as specified in the readme.
`System information:
Python executable: /home/adrian/repos/intel/openvino_notebooks/venv38/bin/python
Pip version: 21.0.1
OpenVINO environment activated: NOT OK
Jupyter kernel installed for openvino_env: OK
Jupyter kernel Python executable: /home/adrian/repos/intel/openvino_notebooks/venv38/bin/python
Jupyter kernel Python and OpenVINO environment Python match: OK
Python version: 3.8 OK
OpenVINO pip package installed: OK
OpenVINO import succeeds: OK
OpenVINO development tools installed: OK
OpenVINO not installed globally: OK
No broken requirements: OK

It appears that you are not running Python in an `openvino_env` 
environment. It is possible use the notebooks in a different 
environment, but if you run into trouble, please follow the instructions 
in the README to install and activate the `openvino_env` environment.


The README.md file is located in the openvino_notebooks directory 
and at https://github.com/openvinotoolkit/openvino_notebooks
`
