### ISSUE TITLE
Memory Leak in "Human 3D Pose Estimation" https://github.com/openvinotoolkit/openvino_notebooks/blob/latest/notebooks/3D-pose-estimation-webcam/3D-pose-estimation.ipynb

### ISSUE THREAD

**Issue by TheArbitraryConstant** [openvinotoolkit/openvino_notebooks#2420]
**Describe the bug**
Program ran easily as expected with very pretty graphics.  After 30 minutes, memory usage exploded from 352 MB to 897 MB and continues to grow.  Will eventually cause the computer to crash (happened earlier).  

 **Expected behavior**
I expected the program to run within a reasonable amount of memory without growing out of control and crashing the system.  

**Screenshots**
![image](https://github.com/user-attachments/assets/ddf3030b-b234-4b30-aa1e-d8af7c6cf261)

 **Installation instructions (Please mark the checkbox)**
[ X ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 
https://github.com/openvinotoolkit/openvino_notebooks/blob/latest/notebooks/3D-pose-estimation-webcam/3D-pose-estimation.ipynb.  Running on Webcam mode so changed "use_popup=True" and "use_webcam=True".  

** Environment information **
Windows 11, not an IT build. Fully updated.  Python 3.11.9.  openvino version 2023.3.0-13775
 
**Additional context**

(openvino_env) C:\Users\Intel\openvino_notebooks>python check_install.py
System information:
Python executable: C:\Users\Intel\openvino_env\Scripts\python.exe
Pip version: 24.2
OpenVINO source: C:\Users\Intel\openvino_env\Lib\site-packages\openvino
OpenVINO IE version: 2024.4.0-16579-c3152d32c9c-releases/2024/4
OpenVINO environment activated: OK
Jupyter kernel installed for openvino_env: NOT OK
Python version: 3.11 OK
OpenVINO pip package installed: OK
OpenVINO import succeeds: OK
OpenVINO development tools installed: OK
OpenVINO not installed globally: OK
No broken requirements: OK

The Python version in openvino_env does not match the openvino_env Jupyter kernel.
This may not be an issue. If you experience issues, please follow the instructions
in the README to reinstall the kernel.

The README.md file is located in the openvino_notebooks directory
and at https://github.com/openvinotoolkit/openvino_notebooks

**Comment by brmarkus** [comment]
Do you use "Jupyter Notebook", or, as recommended within the notebook, use "JupyterLab"?
(I haven't used "JupyterLab", yet, I think, but just to make sure we all use the same fo reproduction)

**Comment by TheArbitraryConstant** [comment]
I initially just took the code and copy/pasted it into my customer demo without Jupyter anything.  I ran it overnight for a stability test and the memory overflowed and crashed the system.  To fill out the bug report, I went ahead and installed Jupyter something-or-other just so I could say I followed the instructions on the bug report.  Task Manager indicated that the memory was noticeably growing in the Jupyter environment too.  It would take many hours to crash, but it’s still a memory leak.

I lost my reservation on that computer and won’t be able to get onto it until tomorrow.  I’ll see what flavor of “Jupyter” is running.

Cheers,
Scott

**Comment by brmarkus** [comment]
Do you see the same when using e.g. "https://github.com/openvinotoolkit/openvino_notebooks/blob/latest/notebooks/pose-estimation-webcam/pose-estimation.ipynb"?

"Human 3D Pose Estimation" uses a thirdparty dependency "threejs", otherwise they are very similar.

**Comment by Aznie-Intel** [comment]
Hi @TheArbitraryConstant I didn't see any memory leaking when running in JupyterLab. Below are my observations:

use_popup=True" and "use_webcam=True".

![true](https://github.com/user-attachments/assets/fa93c6f4-ef92-4b1c-8fde-7642633fc7d7)

use_popup=False" and "use_webcam=True".
![Capture](https://github.com/user-attachments/assets/38530bdd-3a00-4bab-af9f-3cb0e11405f5)

use_popup=False" and "use_webcam=False".
![using-video](https://github.com/user-attachments/assets/c7851fd9-c819-412f-8443-f123023eb5f9)


It is recommended to use JupyterLab.

**Comment by TheArbitraryConstant** [comment]
Sorry, I got busy.  If the leak is fixed on this model, I’ll just switch to this.  I’ll be sure and whine to you if it persists, but I don’t expect it to if it works for you.

Cheers,
Scott

**Comment by Aznie-Intel** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
