### ISSUE TITLE
Bug in notebook inadvertently uninstalls tools needed by notebook

### ISSUE THREAD

**Issue by nicholasvmoore** [openvinotoolkit/openvino_notebooks#2443]
When running through this notebook I was consistently running into an issue `optimum-cli` command not found. I believe there is a mistake in this notebook [here](https://github.com/openvinotoolkit/openvino_notebooks/blob/11d7b9aeab199ac10e59f6dd709e22137ed31dbb/notebooks/llm-chatbot/llm-chatbot-generate-api.ipynb#L79) where the steps uninstall the tool needed below. Is this intended?

![image](https://github.com/user-attachments/assets/98cfdb0e-ccdd-42e3-9d3b-33b313ed7f96)

This causes the conversion step below to fail with `command not found`.

**Comment by brmarkus** [comment]
It first uninstall `optimum` and `optimum-intel` if it was installed before (in whatever version) and then install (clone) from the repo `git+https://github.com/huggingface/optimum-intel.git`, see a few lines below.

If you remove all those `-q` (quiet) parameters, what would the logs look like? Did cloning of the repo(s) work?

**Comment by nicholasvmoore** [comment]
Removing the `-q` parameters shows that the tool is reinstalled. That's strange... Maybe I had another issue with my venv? I'll close this issue for now and can reopen later if needed.

Thanks @brmarkus !
