### ISSUE TITLE
Difficulties using Object segmentations with FastSAM and OpenVINO

### ISSUE THREAD

**Issue by D10123** [openvinotoolkit/openvino_notebooks#2482]
I am trying to use the OpenVINO model without first loading the FastSAM model (thus, I only need to use the OpenVINO one).
To do that, I directly loaded the model and used ov.compile_model() to initialize it. Also, I am not using the OVwrapper class.
I am now trying to apply the function segment() on this model but I do not understand how I need to manipulate the input data and how to modify the segment function for it to work. Does anyone know where I can find this information in the documentation?

**Comment by Wan-Intel** [comment]
You may modify the function below that is called to segment an image based on user input.

```
def segment(
    image,
    model_type,
    input_size=1024,
    iou_threshold=0.75,
    conf_threshold=0.4,
    better_quality=True,
    with_contours=True,
    use_retina=True,
    mask_random_color=True,
)
```

For more information, please refer to [Object segmentations with FastSAM and OpenVINO
](https://github.com/openvinotoolkit/openvino_notebooks/blob/latest/notebooks/fast-segment-anything/fast-segment-anything.ipynb)

**Comment by Wan-Intel** [comment]
Closing issue, feel free to re-open or start a new issue if additional assistance is needed.
