### ISSUE TITLE
302 README formatting issue

### ISSUE THREAD

**Issue by ryanloney** [openvinotoolkit/openvino_notebooks#257]
Looks like the markdown needs to be updated. Creating an issue so we remember to update it. We should also follow the README guidelines in contribution guide. 

![image](https://user-images.githubusercontent.com/15709723/133848493-4299df98-da19-4a7f-a347-c6531d833de5.png)

**Comment by helena-intel** [comment]
Fixed formatting issue and added line about installing dependencies in #258

**Comment by ryanloney** [comment]
Thanks @helena-intel !
