### ISSUE TITLE
How Can I Run the LLM-Chatbot on NPU?

### ISSUE THREAD

**Issue by tim102187S** [openvinotoolkit/openvino_notebooks#2573]
### **Environment :** 
Intel Core Ultra 7 165H (Meteor Lake),
Ubuntu 24.04 (LTS),
Kernel : 6.8.0-49-generic,
Python 3.12,
OpenVINO 2024.5.0,
GPU Driver : 24.31.30508.7,
NPU Driver : 1.5.1 [After updating to **1.10.0**, the issue remains the same.]

### **Use :** 
openvino_notebooks/notebooks/llm-chatbot/llm-chatbot.ipynb

### **Model :** 
meta-llama/llama-3-8b-instruct / INT4

### **Description :** 
After launching the Jupyter notebook and following the steps, I installed the specified OpenVINO version (openvino==2024.5.0). 
At the step "Select device," there was no option to choose NPU. 
So I removing  _exclude=["NPU"]_  from the device selection and selecting NPU, a "Kernel Restarting" error window appeared. (I've confirmed that the NPU Driver is correctly installed, as I can use the NPU to run VisionAI examples, such as object detection on YOLOv3.)
![image](https://github.com/user-attachments/assets/cb3009a7-6b76-48cc-84a9-c911585d9500)

Could you please advise me on how to run the chatbot using the NPU in this project?

**Comment by brmarkus** [comment]
WHen it is about dynamic shapes then have a look at the comment of this issue "https://github.com/openvinotoolkit/openvino_notebooks/issues/2068#issuecomment-2153681563".

> Limitations
> Currently, only models with static shapes are supported on NPU.

**Comment by tim102187S** [comment]
Thank you for the information regarding the limitations of NPU usage. I understand that NPU currently only supports models with static shapes.
However, I raised this question because the latest release notes for OpenVINO 2024.5.0 mention support for LLMs on NPU, specifically models like Llama 3 8B, Llama 2 7B, Mistral-v0.2-7B, Qwen2-7B-Instruct, and Phi-3 Mini-Instruct.

I was interested in testing this feature. Could you please clarify if this is indeed possible?

For your reference, here is the link to the release notes: 
[https://docs.openvino.ai/2024/about-openvino/release-notes-openvino.html?fbclid=IwZXh0bgNhZW0CMTAAAR0P9LLEm_XUOa-4QcGoSNA-CebaIwpuxvUvI3aAjZ_oy1YKy2Aou-qMXaY_aem_sslq7DOKw55B4JXdKEpvoA](url)

![image](https://github.com/user-attachments/assets/261e6c87-af3f-4c4e-af07-1eee70413bb5)



Thank you.

**Comment by brmarkus** [comment]
Hmm, now I wanted to test "https://github.com/openvinotoolkit/openvino_notebooks/tree/latest/notebooks/mllama-3.2" on my NPU enabled laptop (updated NPU-driver, restarted, re-created the VirtualEnvironment, re-cloned latest OpenVINO-Notebooks) and started the JupyterNotebooks...

But it turned out I cannot test it:

> Meta-llama has disallowed access to this model in the EU
> Downloads of this model are not accessible from the European Union (EU). Please see the Llama Acceptable Use Policy and License FAQ page for more information.

Yes, I'm located in the EU (in Germany).

Can you try it and get it working? (but this notebook also excludes NPU from the device-selection list...)

**Comment by tim102187S** [comment]
I have already tested the **Llama-3-8b** model, which is listed as supported in the OpenVINO Release Notes (2024.5 - 20 November 2024), using the latest versions of **OpenVINO (2024.5.0)**, **NPU Driver (1.10.0)**, and the latest cloned version of OpenVINO-Notebooks.

I encountered the same issue as mentioned earlier.

Do you have any suggestions on how I can try using the NPU to run the chatbot, or should I wait for future updates of OpenVINO, the NPU Driver, or OpenVINO-Notebooks?

**Comment by brmarkus** [comment]
Sorry, no suggestions regarding e.g. LLM models - the samples and models I saw are using dynamic shapes, which are not supported by the NPU plugin (yet?).

Let's wait for the OpenVINO dev-team feedback. Hopefully they can provide more details about the mentioned sections in the ReleaseNotes.

**Comment by eaidova** [comment]
please check llm chatbot that based on openvino-genai notebook https://github.com/openvinotoolkit/openvino_notebooks/pull/2607

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.
