### ISSUE TITLE
Support for Colab

### ISSUE THREAD

**Issue by awsaf49** [openvinotoolkit/openvino_notebooks#259]
I'm struggling to run the notebooks in both **binder** and **local**. It would be really nice if there were **Colab** examples of those notebooks as well...

**Comment by helena-intel** [comment]
What is the issue you have running the notebooks in MyBinder or locally? I hope we can help you get them working! Colab support for all notebooks is not immediately planned. We do hope to have another cloud option soon where you can run all the notebooks. 

If you're experiencing issues with a local install, it would be helpful if you can paste the output of `python check_install.py`, run from the root of the repository directory, with `openvino_env` activated.

**Comment by awsaf49** [comment]
I tried to use `202-vision-superresolution-image` but as it didn't have access to **GPU** it got stuck. In local, I also don't have access to GPU. As **Colab** has access to free **GPU** it would've been lot easier to run those notebooks.

**Comment by helena-intel** [comment]
OpenVINO is not optimized for NVIDIA GPUs, so having the GPU in Colab does not make inference faster. The superresolution notebook is a bit slow - but it should still work, even on Binder. Inference on the 202 notebook took less than a minute for me there (see screenshot). Binder is a free resource though - so at times resources may be more limited than usual.

Please try it locally if you want! You do not need a GPU to use OpenVINO. 

![image](https://user-images.githubusercontent.com/77325899/134043948-9bd848a8-a4c4-4891-a92c-f258d897bbd6.png)

**Comment by awsaf49** [comment]
Looking forward to **GPU** support someday. Running a Deep Learning model on **CPU** might be consuming after all .....

**Comment by helena-intel** [comment]
OpenVINO is optimized to run on CPU, and if you have a recent Intel Core CPU with Intel Integrated Graphics Card, it can use that as well. It can also use both at the same time, for even better performance. See the [104-model-tools](https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/104-model-tools) notebook for some quick performance checks with Open Model Zoo models. You'll see that you get quite good performance with many models on CPU (using `benchmark_app` to check the performance). In the 102 notebook you can also see how running the converted model on CPU or iGPU is much faster than the original PyTorch model. In the PaddleGAN notebook the difference is very large - the PaddlePaddle model is too heavy for MyBinder, but the converted OpenVINO IR model runs well there.
