### ISSUE TITLE
Jupyter Git for Open Data Hub / OpenShift Data Science

### ISSUE THREAD

**Issue by ryanloney** [openvinotoolkit/openvino_notebooks#266]
We have been asked to include jupyterlab-git in the Dockerfile for the notebooks. This is commonly used in ODH/ODS. I don't know if we need it for all users, but can we add it to the Dockerfile? Is it as simple as adding jupyterlab-git to requirements? 

https://github.com/jupyterlab/jupyterlab-git

Since we are using JupyterLab 3.X, it looks like we do not need to run "jupyter lab build"

Let me know what you think. This can wait a few weeks, but want to make sure it is technically feasible.

**Comment by helena-intel** [comment]
It is no problem to add it, we already have it in dev-requirements.txt. But it adds an element to the UI, and the extension had issues for me recently (the diff would not show correctly). I don't recommend adding it for everyone.

**Comment by helena-intel** [comment]
Fixed in #268
