### ISSUE TITLE
Git pull causes pod to crash loop on new push to main

### ISSUE THREAD

**Issue by Xaenalt** [openvinotoolkit/openvino_notebooks#273]
**Describe the bug**
In cases where the user has modified or done anything to the default notebooks, a new commit to main on github can cause pods to crash loop

 **Expected behavior**
User modifications should not impact functionality of the notebook image

**Screenshots**
![image](https://user-images.githubusercontent.com/8479010/135145973-adf213e0-a5ca-4988-9b09-2df60429cb42.png)

 **Installation instructions (Please mark the checkbox)**
[X] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

 
**Additional context**
It stems from this addition

https://github.com/openvinotoolkit/openvino_notebooks/blob/16de32f51f701fa5d49301333582054972cb2c4c/.docker/builder/run#L49

The point of the preload environment variable is to pre-load content for demos/labs/etc, however adding the git pull causes a problem when the user attempts to do any modifications.

To reproduce:
1. Checkout an older version of the repo, eg: `git checkout HEAD^`
2. Replace `main` branch with it, so that main now points to an older commit. Eg: `git branch -D main; git switch -c main` (this simulates the effect of a new commit being pushed to main upstream)
3. Make any change to the code, editing any line in any notebook
4. Restart the container
The pod will now crash loop, and will continue to do so until the user either manually intervenes outside of the OpenVINO image or deletes their PVC

I'd propose a solution would be either to version the selected notebooks into the image, or use the preload variable as intended. Additionally, if it's absolutely necessary to have this functionality, the notebooks could get cloned/updated in a pristine condition somewhere else in the image, and then copied into the user's volume to avoid this type of conflict

I can draft a PR to address

**Comment by helena-intel** [comment]
Thanks @Xaenalt ! If you want to make a PR that fixes this am happy with any solution that works for you.

**Comment by Xaenalt** [comment]
So question, how critical of a feature is this git pull thing? I'm thinking just preloading the notebooks into the image, and copying them into place would be better

Also, is there a plan for version tagging? If so that would be good to pin library versions for RHODS as well

**Comment by helena-intel** [comment]
We currently have no plan for version tagging - we recommend everyone to always run the main version since that is up-to-date with bug fixes and improvements, and tested daily in the CI. Since we support 3 different Python versions and 5 operating systems and we want to have a simple requirements.txt for users, it is not possible to have releases that are known-to-work on all supported configurations. 

The git pull line is not required from our side. I am happy with any solution that works best for you.

**Comment by Xaenalt** [comment]
Ok, cool
