### ISSUE TITLE
Changing JUPYTER_SERVER_ROOT makes data inaccessible to users of other notebooks

### ISSUE THREAD

**Issue by Xaenalt** [openvinotoolkit/openvino_notebooks#274]
**Describe the bug**
The OpenVINO image changes JUPYTER_SERVER_ROOT to point to the set of example notebooks as its root. However, if users are attempting to migrate work over onto OpenVINO, this effectively locks them out of the data on their volume in an unintuitive way.

 **Expected behavior**
JUPYTER_SERVER_ROOT should point to the regular location

**Screenshots**
Screenshot of a standard setup:
![image](https://user-images.githubusercontent.com/8479010/135147006-1a6f3118-3aed-4535-97de-bdce4636e376.png)

Screenshot of the change in the OpenVINO image, note that the work the user may have had at /opt/app-root/src is now no longer accessible:
![image](https://user-images.githubusercontent.com/8479010/135147085-f725f02a-88f2-487d-a9ac-41a7069c2284.png)

 **Installation instructions (Please mark the checkbox)**
[X] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 
 
**Additional context**

**Comment by helena-intel** [comment]
Thanks for the very clear report. We use this as a Docker image also for people who just want to try out OpenVINO Notebooks locally - and then having it start in the notebooks directory, so that it looks the same as with a local install, makes sense. I see the usecase though - we can change this.

**Comment by Xaenalt** [comment]
Gotcha, maybe we can throw it behind some kind of flag

**Comment by helena-intel** [comment]
I think we were not overriding JUPYTER_SERVER_ROOT, but I edited start-notebooks.sh at some point to start Jupyter Lab in the notebooks directory. I just reverted that in the PR linked above.

**Comment by Xaenalt** [comment]
Cool, looks like a good fix
