### ISSUE TITLE
504 Gateway Timeout when multiple tabs are reopened

### ISSUE THREAD

**Issue by Xaenalt** [openvinotoolkit/openvino_notebooks#313]
**Describe the bug**
We identified a minor bug when the notebook image is stopped and restarted while 2+ ipynb notebooks are open. There appears to be an unusual problem restarting the kernels when the notebook resumes

 **Expected behavior**
Kernels are resumed without showing an error to the user

**Screenshots**
![image](https://user-images.githubusercontent.com/8479010/138924909-9fb05c7e-3627-417d-9283-955388543ab6.png)
![image](https://user-images.githubusercontent.com/8479010/138924932-05de861e-56f4-4f67-a62b-9f064bfe461c.png)

 **Installation instructions (Please mark the checkbox)**
[X] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks.

**Comment by helena-intel** [comment]
@Xaenalt I updated jupyterhub. It is still difficult to replicate this for me. Could you try on your end if that fixed the issue?

**Comment by Xaenalt** [comment]
Rebuilding it now, will get back to you with results shortly

**Comment by Xaenalt** [comment]
Confirming this is resolved with this update

**Comment by helena-intel** [comment]
Thanks for testing @Xaenalt ! Glad that it is resolved.
