### ISSUE TITLE
<IPython.core.display.Image object> 

### ISSUE THREAD

**Issue by yizhuyiru** [openvinotoolkit/openvino_notebooks#342]
When I want to run the code in my own computer. It cannot shoe me any images or videos.

**Comment by helena-intel** [comment]
The notebooks are indeed meant to be run in Jupyter. The code itself is not Jupyter specific, but in a script you would add `plt.show()` for some matplotlib plots, and some specific widgets will not work outside of a notebook. The `! mo` cells and similar cells that run shell commands are also jupyter/ipython specific. 

Can you tell a bit more about your use case? For most notebook code, using ipython should work. You may need to install tk (depending how you installed Python), then you can do `ipython --matplotlib tk -i 001-hello-world.py` and the image from the code that was exported from the 001 notebook shows up as expected.

**Comment by helena-intel** [comment]
Closing this issue, please feel free to open a new issue if you have more information or a new question.
