### ISSUE TITLE
git clone error "fatal: did not receive expected object"

### ISSUE THREAD

**Issue by kmurugay** [openvinotoolkit/openvino_notebooks#351]
**Describe the bug**
Unsuccessful repository Clone with Command "git clone https://github.com/openvinotoolkit/openvino_notebooks.git""

 **Expected behavior**
Cloning should exit without errors. 

**Screenshots**
![image](https://user-images.githubusercontent.com/54974990/145589956-172db006-640e-403f-8ed8-fb45d41df905.png)

 **Installation instructions (Please mark the checkbox)**
[  ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks.

**Comment by helena-intel** [comment]
Thanks for reporting this. It is a known issue, we are working on it and hope to resolve it soon. In the meantime, cloning with a depth of 1 works: `git clone --depth=1 https://github.com/openvinotoolkit/openvino_notebooks.git` I also added that to the README and installation guides for now.

**Comment by kmurugay** [comment]
Thank you @helena-intel. It works well now.
