### ISSUE TITLE
Video player is crashing 

### ISSUE THREAD

**Issue by raymondlo84** [openvinotoolkit/openvino_notebooks#381]
The video player is releasing resource before the loop ends and it crashed the kernel...

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/1720147/150429727-a48f9c28-ab34-4f8b-ae22-e35028cfe2b3.png)

http://localhost:8888/lab/tree/utils/notebook_utils.py

"""
Stop playing and release resources.
"""

A workaround I put in now is to put a wait, but we shall wait for the main loop to finish before releasing the cap.

def stop(self):
self.__stop = True
time.sleep(1);
self.__cap.release()

**Comment by adrianboguszewski** [comment]
Fixed in #365
