### ISSUE TITLE
DLL load to fail error

### ISSUE THREAD

**Issue by alletsr** [openvinotoolkit/openvino_notebooks#384]
![Screenshot (293)](https://user-images.githubusercontent.com/94032610/150722587-bed6b2c3-8e5d-437b-b679-b4abc4fda865.png)
Am using Anaconda. Facing this issue while using all the models. Please help me out.

**Comment by helena-intel** [comment]
Can you try if it works if you follow this guide https://github.com/openvinotoolkit/openvino_notebooks/wiki/Conda ?

**Comment by alletsr** [comment]
Yes Working, Thank you so Much

**Comment by helena-intel** [comment]
I am happy this worked! Thanks for reporting back.

**Comment by alletsr** [comment]
Hi,

Thank You for Replying so quickly.  It helped me a lot

I am a Data ScienceStudent.
Currently Am Studying about Sensor Fusion.
So if You have Seminar related to the topic Sensor Fusion, Please Kindly
forward that to me. It will be very helpful

Apologizes for seeking your help for matters other than Open Vino.

Thank You
