### ISSUE TITLE
Intermittent CI failures with VideoPlayer

### ISSUE THREAD

**Issue by helena-intel** [openvinotoolkit/openvino_notebooks#387]
The CI intermittently fails with this error "Cell 10: Timeout of 2000 seconds exceeded while executing cell. Failed to interrupt kernel in 5 seconds, so failing without traceback."

![fdc03df1b814270a956cbed6c22dac85](https://user-images.githubusercontent.com/77325899/151332003-817286f4-0848-4cfa-a9bc-e4178936f327.png)
See https://github.com/openvinotoolkit/openvino_notebooks/runs/4954487391?check_suite_focus=true

**Comment by adrianboguszewski** [comment]
Probably fixed in #393

**Comment by raymondlo84** [comment]
Is that addressed? Let's make sure we don't fail the CI and also know why it fails?
