### ISSUE TITLE
Could not find a version that satisfies the requirement tensorflow~=2.4.1; extra == "tensorflow2"

### ISSUE THREAD

**Issue by aakashsengar** [openvinotoolkit/openvino_notebooks#390]
**Describe the bug**
I am always getting this error `ERROR: Could not find a version that satisfies the requirement tensorflow~=2.4.1; extra == "tensorflow2" (from openvino-dev[onnx,tensorflow2]) (from versions: 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.5.2, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.8.0rc0, 2.8.0rc1)
ERROR: No matching distribution found for tensorflow~=2.4.1; extra == "tensorflow2"`
whenever I am trying to install packages from requirements.txt
OS - Ubuntu 20.04

**Comment by helena-intel** [comment]
Do you use Python 3.9 or 3.10? These versions are not supported by OpenVINO at the moment. 3.9 will work in the next OpenVINO version, which will be released in March. For now, please use Python 3.6 through 3.8.

**Comment by helena-intel** [comment]
Do you use Python 3.9 or 3.10? These versions are not supported by OpenVINO at the moment. 3.9 will work in the next OpenVINO version, which will be released in March. For now, please use Python 3.6 through 3.8.
