### ISSUE TITLE
Virtual webcam and deadlock

### ISSUE THREAD

**Issue by raymondlo84** [openvinotoolkit/openvino_notebooks#399]
The input_fps can be zero with virtual webcams like OBS and Logi Capture... We shall not assume CAP_PROP_FPS is always valid, and the easiest workaround is to preset it to 60fps by default if we do not know the source FPS. 

Also, we can also face a 1/fps = dividing by zero error if fps is 0. 

        # fps of input file
        self.__input_fps = self.__cap.get(cv2.CAP_PROP_FPS)
        if self.__input_fps <= 0:
            self.__input_fps = 60
        # target fps given by user
        self.__output_fps = fps if fps is not None else self.__input_fps

**Comment by raymondlo84** [comment]
![image](https://user-images.githubusercontent.com/1720147/152285806-84d332ae-2198-4812-99ea-32905a61f6f5.png)
and here we can run zoom and other streaming feed together with the notebook.

**Comment by adrianboguszewski** [comment]
@raymondlo84 I think the better assumption is 30 fps instead of 60 fps. It's the most popular value.

**Comment by raymondlo84** [comment]
if you assume 30fps then if the feed is 60fps then we will run into extra lag and so.

**Comment by raymondlo84** [comment]
For example, the logic here will make a 60fps source crash as we will be waiting beyond the buffer extensively?
            wait_time = 1 / self.__input_fps - (t2 - t1)

**Comment by raymondlo84** [comment]
However, if you assume it's 60fps then we will wait a bit less, but also the read will block the next call. In short, we shall always try to wait slightly less?

**Comment by adrianboguszewski** [comment]
If you assume 60 FPS and there is 30 FPS you will see fast motion. There is no good solution, but in my opinion, 30 FPS is the most popular value.

**Comment by adrianboguszewski** [comment]
ok, I understand your point

**Comment by adrianboguszewski** [comment]
Fixed in #404

**Comment by raymondlo84** [comment]
Please only close this after it's validated with CI etc...
