### ISSUE TITLE
Problem installing OpenVINO with pip install on Windows

### ISSUE THREAD

**Issue by mulderp** [openvinotoolkit/openvino_notebooks#410]
Hello,

when following the installation steps on Windows 10, with Minforge/Anaconda environment I see this:

```
c:/temp> pip install -r requirements.txt

...

 happened here: https://pip.pypa.io/surveys/backtracking
Collecting paddlepaddle==2.1.*
  Using cached paddlepaddle-2.1.0-cp39-cp39-win_amd64.whl (61.4 MB)
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of torchmetrics to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement tensorflow~=2.4.1; extra == "tensorflow2" (from openvino-dev[onnx,tensorflow2]) (from versions: 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 2.8.0rc0, 2.8.0rc1, 2.8.0)
ERROR: No matching distribution found for tensorflow~=2.4.1; extra == "tensorflow2"
```

I would expect to have the installation resolve all dependencies. I would like to re-use my existing Python environment. But if you think it will be better, I can install the OpenVINO Windows distribution for Windows.

Thanks for your help!

**Comment by ryanloney** [comment]
Hi @mulderp 

Can you please try these instructions? Also note that Python 3.9 is not supported yet. Starting in March, we will have support for 3.9.

https://github.com/openvinotoolkit/openvino_notebooks/wiki/Conda

Thanks,

Ryan

**Comment by mulderp** [comment]
Thanks the link is helpful. Good to see the Python 3.9 version is planned soon, and we can switch different Python with Conda.

Now pip install works fine, but I get:


```
C:\Miniconda3\envs\openvino_env\lib\site-packages\openvino\inference_engine\__init__.py in <module>
     28                 os.environ['PATH'] = os.path.abspath(lib_path) + ';' + os.environ['PATH']
     29 
---> 30 from .ie_api import *
     31 
     32 __all__ = ['IENetwork', 'TensorDesc', 'IECore', 'Blob', 'PreProcessInfo', 'get_version']

ImportError: DLL load failed while importing ie_api: The specified module could not be found.
```

Maybe I am missing the path mentioned in:

[](https://github.com/openvinotoolkit/openvino_notebooks/wiki/Conda#step-7-conda-launch-the-notebooks)set PATH=C:\Users\<username>\Miniconda3\envs\openvino_env\Lib\site-packages\openvino\libs;%PATH%

I will try that

**Comment by mulderp** [comment]
Yes it works, maybe a debug notebook to make sure the paths are in could be helpful e.g. 

```
import os
print(os.environ['PATH'])
```

**Comment by helena-intel** [comment]
Great, nice that it works, thanks for reporting back! We have a check_install.py script that helps debugging these issues, I'm adding a step to try to detect Conda there with a reference to the PATH instructions. You only need to set this PATH manually on Conda; if you use a pip virtual environment it is detected automatically. In the next release this should also be the case for Conda environments.
