### ISSUE TITLE
Use the simplified compiled_model([input_data])

### ISSUE THREAD

**Issue by ryanloney** [openvinotoolkit/openvino_notebooks#430]
Please use `compiled_model([input_data])` method instead of current 3 line approach. This change should be applied for 2022.1 release.

**Comment by Debskij** [comment]
Changed it where applicable

**Comment by Debskij** [comment]
Updated in PR https://github.com/openvinotoolkit/openvino_notebooks/pull/483

**Comment by ryanloney** [comment]
@Debskij can you also update 201 monodepth to use `compiled_model([input_data])` instead of  `result = compiled_model(inputs={input_key.any_name: input_image})[output_key]` ?

**Comment by Debskij** [comment]
@ryanloney it seems like all notebooks are patched, can you close it?

**Comment by adrianboguszewski** [comment]
Fixed in #516
