### ISSUE TITLE
Improve documentation: Update Readme and create a wiki section (2022.1)

### ISSUE THREAD

**Issue by paularamo** [openvinotoolkit/openvino_notebooks#464]
**Describe the issue**
Missing installation process details for 2022.1

 **Expected behavior**
We are expecting to see a clear explanation about the installation process of 2022.1 and avoid confusions with 2021.4, for example, the kernel environment and so on. Could you (@adrianboguszewski and @Debskij) help us with that?

Please Update the readme file and correlated installation files if it is necessary. Could you create a wiki page with a description of this process?

**Comment by adrianboguszewski** [comment]
Is this related to #468?

**Comment by ryanloney** [comment]
These are tasks that should have been complete before merging the 2022.1 to main. We can discuss on Wednesday.
