### ISSUE TITLE
Notebook links in Readme files are not working.

### ISSUE THREAD

**Issue by paularamo** [openvinotoolkit/openvino_notebooks#488]
**Describe the bug**
Notebook links in Readme files are not working. Could it be because of the actual update? I could support those, but I still wonder why that happened.

**Comment by Debskij** [comment]
Can you specify which notebooks links are not working?

**Comment by paularamo** [comment]
Unfortunately, none.

**Comment by ryanloney** [comment]
@Debskij I believe Paula is referring to the URLs on the page: https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/README.md

@paularamo can you confirm it is just the links on notebooks/readme.md page? The main readme seems to work OK.

**Comment by paularamo** [comment]
Thanks, @ryanloney. Yes, I am referring to the URLs (links) on the page.

**Comment by adrianboguszewski** [comment]
The reason is double "notebooks" in the path for every notebook.
