### ISSUE TITLE
TensorFlowVersion

### ISSUE THREAD

**Issue by kglasnapp** [openvinotoolkit/openvino_notebooks#49]
When I run the command pip install -r requirements.txt
I get -->
 ERROR: Could not find a version that satisfies the requirement tensorflow<2.4,>=2.2 (from -r requirements.txt (line 20)) (from versions: 2.5.0rc0, 2.5.0rc1, 2.5.0rc2)
ERROR: No matching distribution found for tensorflow<2.4,>=2.2 (from -r requirements.txt (line 20))

**Comment by helena-intel** [comment]
What platform are you running on (Operating system and Python version)? Could you run `python check_install.py` (in the root of the openvino_notebooks repository) and copy/paste the output here?

**Comment by kglasnapp** [comment]
(openvino_env) c:\FunStuff\openvino\openvino_notebooks>python check_install.py

System information:

Python executable: c:\FunStuff\openvino\openvino_notebooks\openvino_env\Scripts\python.exe

OpenVINO environment activated: OK

Python version: 3.9 NOT OK

OpenVINO pip package installed: NOT OK

OpenVINO import succeeds: NOT OK

OpenVINO development tools installed: NOT OK

OpenVINO not installed globally: OK

**Comment by helena-intel** [comment]
Thanks! Sadly Python 3.9 is not supported yet by OpenVINO. Can you try with Python 3.6 to 3.8, for example with 3.7 from this installer: https://www.python.org/ftp/python/3.7.9/python-3.7.9-amd64.exe If you then make the virtual environment with `py -3.7 -m venv openvino_env` everything should work. (You can delete the existing openvino_env folder first).

**Comment by helena-intel** [comment]
Closing this issue, please feel free to open a new issue if installing Python 3.7 did not solve the problem.
