### ISSUE TITLE
CI issues for Paddle model direct loading

### ISSUE THREAD

**Issue by OpenVINO-dev-contest** [openvinotoolkit/openvino_notebooks#510]
Pls check the PR 504:
https://github.com/openvinotoolkit/openvino_notebooks/pull/504

**Runtime**: OpenVINO 2022.1
**Problem**: I have test that notebook on my PC and everything is fine. But the PR CI failed on:

_**"RuntimeError: Check 'read_succeed' failed at frontends/paddle/src/input_model.cpp:295:
FrontEnd API failed with GeneralFailure: :
File containing constant with name embedding_0.w_0 wasn't successfully read."**_

Is it because the OpenVINO runtime in CI do not support Paddle BERT model ?

**Comment by Debskij** [comment]
One of model files is stored in Git LFS (notebooks/005-hello-paddle-nlp/model/model.pdiparams) which might be not downloaded by CI.

**Comment by OpenVINO-dev-contest** [comment]
> One of model files is stored in Git LFS (notebooks/005-hello-paddle-nlp/model/model.pdiparams) which might be not downloaded by CI.

Yes but in this situation, the log should to be "xxx.pdmodel cannot be open", but not some OPs wasn't successfully read.
