### ISSUE TITLE
401 object detection notebook NMS

### ISSUE THREAD

**Issue by thavens** [openvinotoolkit/openvino_notebooks#532]
**Describe the bug**
Inside the 401 notebook call to cv2 NMS suppression uses the wrong bounding box coordinates. The notebook uses left, top, right, bot type coordinates while cv2 should take left, top, width, height coordinates.

 **Expected behavior**
With nms_threshold=0, the bounding boxes should disappear ONLY when the blue bounding boxes touch.

**Video**
[youtube video](https://www.youtube.com/watch?v=PKfTuewXiwk)
 
**Additional context**
The white boxes represent what NMS suppression sees. Basically left, top, right, bot coordinates are displayed as
left, top, right + left, top + bot. As you can see, the bounding boxes disappear when the white boxes touch rather than when the blue boxes touch.

If you want to make the fix here is the code showing the issue and the fix is commented. I could make a pr if people want me to later though.
[401-object-detection.zip](https://github.com/openvinotoolkit/openvino_notebooks/files/8449262/401-object-detection.zip)

**Comment by raymondlo84** [comment]
It would be great if you can create a PR, and so I can test it out too? :)

**Comment by raymondlo84** [comment]
https://github.com/openvinotoolkit/openvino_notebooks/pull/538 

Somehow the CI failed. I'm rerunning it again.

I see there are very few lines of code changes. I wonder why it failed.

**Comment by raymondlo84** [comment]
Saw the commit, that's cool. But do you also notice the drop in detection?

**Comment by thavens** [comment]
Hmm. I'll try it out. How should I reproduce it?
In theory, the detection should be even better since IOU is the same or reduced which means less NMS.

**Comment by raymondlo84** [comment]
Maybe run a test video and log the output? https://archive.org/serve/ISSVideoResourceLifeOnStation720p/ISS%20Video%20Resource_LifeOnStation_720p.mp4.

**Comment by adrianboguszewski** [comment]
Fixed in #538
