### ISSUE TITLE
Add boto3 to container for Red Hat integration

### ISSUE THREAD

**Issue by ryanloney** [openvinotoolkit/openvino_notebooks#535]
Request to add https://pypi.org/project/boto3/ to the docker image for Open Data Hub / OpenShift Data Science integration that uses OpenVINO Notebooks. This is because optimized models need to be uploaded to a model repository in cloud storage. This can be done easily with boto3. 

Please start the process of adding to the container. It does not need to be in main requirements.txt though.

**Comment by Debskij** [comment]
Hi @ryanloney, 
There is a check in our CI that tests are there any differences between Pipfile and requirements ([def test_requirements_docker(](https://github.com/openvinotoolkit/openvino_notebooks/blob/main/.ci/test_notebooks.py#L46)). That means that we have to add it to both container and requirements. Is that also fine?

**Comment by ryanloney** [comment]
@Debskij we don't need it in the main requirements, so if there is a way to add an exception to the test requirements docker check, that would be best.
