### ISSUE TITLE
Mac OS Webcam Low performance with 4 series notebooks

### ISSUE THREAD

**Issue by raymondlo84** [openvinotoolkit/openvino_notebooks#536]
It seems the webcam interface with Macbook's built-in webcam is not working properly with the notebooks. It's going at 1-2fps at most. The performance is ok with an external webcam or virtual camera. I believe it can be related to the opencv interface + mac os x. 

![image](https://user-images.githubusercontent.com/1720147/163088043-cb3f635f-fc44-4c3e-9ec2-5386f64e10b3.png)

The current workaround is to use OBS or virtual webcam like logicapture .

**Comment by paularamo** [comment]
We could add a little tutorial about how to create a virtual camera or URLs for setting up.

**Comment by raymondlo84** [comment]
https://www.youtube.com/watch?v=Xx7TVO7x6zY :) let's all watch a video? This is pretty much it. Install OBS, configure the built-in webcam as source, and click start virtual webcam.

Then, you will be able to see the virtual webcam as one of the webcam devices.

**Comment by raymondlo84** [comment]
The only difference it seems is the skip_first_frame was not 0. And adding 15 skip frames seems to be able to unlock that.

**Comment by raymondlo84** [comment]
It seems to be fixed in 12.6. I will close this for now.
