### ISSUE TITLE
Old OpenVINO API in some notebooks

### ISSUE THREAD

**Issue by adrianboguszewski** [openvinotoolkit/openvino_notebooks#544]
There is still old OpenVINO API in 110, 210 and notebooks_utils. It causes import errors for Python 3.8 and 3.9 and Ubuntu 22.04 (104):
![image](https://user-images.githubusercontent.com/4547501/165349953-565d7159-2228-412e-99d7-d2a2d0de6ef4.png)

**Comment by helena-intel** [comment]
For 110/210 this was a known limitation for 2022.1 release. It will be fixed, but these notebooks should work with Python 3.8 and 3.9  (this is tested in CI). Did you install openvino-3.9-dev?

**Comment by Debskij** [comment]
From my point of view, it's caused by using an unsupported OS. For the current release of OpenVINO, we are not supporting Ubuntu 22.04

**Comment by helena-intel** [comment]
I still expect OpenVINO to work on most Linuxes though. I did not do a thorough test, but I use Ubuntu 22.04 myself with no issues (after installing a supported Python version and development libraries).

**Comment by adrianboguszewski** [comment]
Yes. It works after installing python3.9-dev. Thanks.
It's interesting that the new API works without the development version of Python but the old one doesn't.
