### ISSUE TITLE
Can't Convert PyTorch model to ONNX

### ISSUE THREAD

**Issue by shliar** [openvinotoolkit/openvino_notebooks#549]
Hi  I'm using 102-pytorch-onnx-to-openvino in the official example, but I made an error while doing  Convert PyTorch model to ONNX ，the error is: RuntimeError: ONNX export failed: Couldn't export Python operator HardSwishJitAutoFn，in pytorch,this problem can be solved by set_swish()，but in the official example,MobileV3Large object has no attribute 'set_swish'.
How can I solve this problem？
my PyTorch == 1.8.1 +cpu

**Comment by raymondlo84** [comment]
https://github.com/lukemelas/EfficientNet-PyTorch/issues/199 related?

**Comment by helena-intel** [comment]
The model in 102 is not compatible with PyTorch 1.8+ indeed. `pip install -r requirements.txt` will install 1.7. The notebook does work with that version.

**Comment by shliar** [comment]
thanks

**Comment by BelalElhossany** [comment]
@shliar  have you solved this? I have installed torch1.7.1 but problem haven't been solved.

**Comment by shliar** [comment]
> @shliar have you solved this? I have installed torch1.7.1 but problem haven't been solved.

Yes, I have successfully run in notebook, but openvino does not seem to be able to completely convert all the pytorch models. For example, when I use openvino to convert the craft model, even if the conversion is successful, it cannot be predicted normally

**Comment by weinixuehao** [comment]
my mobile is mobilenetv3 that has no set_swish
