### ISSUE TITLE
ssdlite_mobilenet_v2.xml cannot be opened!

### ISSUE THREAD

**Issue by fenaux** [openvinotoolkit/openvino_notebooks#554]
**Describe the bug**
I followed notebook 401-object-detection and it works.  Then I wanted to reuse the converted model within a python script with the same command line :
ie_core = Core()
model = ie_core.read_model(model=root + converted_model_path)
where "root" is path to openvino_notebooks
 
But I get
openvino_notebooks/notebooks/401-object-detection-webcam/model/public/ssdlite_mobilenet_v2/FP16/ssdlite_mobilenet_v2.xml cannot be opened!

 **Expected behavior**
I hope I can reuse the converted model from my script

**Screenshots**

 **Installation instructions (Please mark the checkbox)**
[ x ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 
I did it twice !

** Environment information **
Pip version: 22.1
OpenVINO source: /home/fenaux/openvino_env/lib/python3.9/site-packages/openvino
OpenVINO IE version: 2022.1.0-7019-cdb9bec7210-releases/2022/1
OpenVINO environment activated: OK
Jupyter kernel installed for openvino_env: **NOT OK**
Python version: 3.9 OK
OpenVINO pip package installed: OK
OpenVINO import succeeds: OK
OpenVINO development tools installed: OK
OpenVINO not installed globally: OK
No broken requirements: OK

 Thanks for your  help

**Comment by Debskij** [comment]
Hey, can't see any information about OS that you are using. If you are using Linux based OS, would you mind to share `tree` command output for notebook 401 directory and all subdirectories?

**Comment by fenaux** [comment]
Sorry it's Ubuntu 20.04.4 LTS
and here is the result of tree
├── 401-object-detection.ipynb
├── model
│   ├── 1
│   │   ├── 8e
│   │   │   └── 205630237f1913ac0ed623d48798f1fa03a9e95c467bd149eb5f6107e704a8131cdb0a72fcf6517dafa0ff47d32a4e
│   │   └── staging
│   └── public
│       └── ssdlite_mobilenet_v2
│           ├── FP16
│           │   ├── ssdlite_mobilenet_v2.bin
│           │   ├── ssdlite_mobilenet_v2.mapping
│           │   └── ssdlite_mobilenet_v2.xml
│           └── ssdlite_mobilenet_v2_coco_2018_05_09
│               ├── checkpoint
│               ├── frozen_inference_graph.pb
│               ├── model.ckpt.data-00000-of-00001
│               ├── model.ckpt.index
│               ├── model.ckpt.meta
│               ├── pipeline.config
│               └── saved_model
│                   ├── saved_model.pb
│                   └── variables
└── README.md

10 directories, 13 files

**Comment by Debskij** [comment]
Isn't the path for the model `openvino_notebooks/notebooks/401-object-detection-webcam/model/FP16/ssdlite_mobilenet_v2.xml`?

**Comment by fenaux** [comment]
openvino_notebooks directoy is not directly at the root. 

I replaced the original code in script with
cmd = f"ls {root + converted_model_path}"
os.system(cmd)

and I got
/home/fenaux/stick/openvino_notebooks/notebooks/401-object-detection-webcam/model/public/ssdlite_mobilenet_v2/FP16/ssdlite_mobilenet_v2.xml
as exepected so the file is there

**Comment by brmarkus** [comment]
Using this path - is it working now, can it be opened now?

**Comment by fenaux** [comment]
No it is exactly the same path that i used before
I just changed

model = ie_core.read_model(model=root + converted_model_path)
still leading to
RuntimeError: Model file ~/stick/openvino_notebooks/notebooks/401-object-detection-webcam/model/public/ssdlite_mobilenet_v2/FP16/ssdlite_mobilenet_v2.xml cannot be opened!

with
cmd = f"ls {root + converted_model_path}"
os.system(cmd)
to check there was no mistake in the complete path

**Comment by Debskij** [comment]
Can you show access permissions for files in `~/stick/openvino_notebooks/notebooks/401-object-detection-webcam/model/public/ssdlite_mobilenet_v2/FP16/`?

**Comment by fenaux** [comment]
total 9632
8744 -rw-rw-r-- 1 fenaux fenaux 8950538 mai   18 15:08 ssdlite_mobilenet_v2.bin
 364 -rw-rw-r-- 1 fenaux fenaux  369345 mai   18 15:08 ssdlite_mobilenet_v2.mapping
 524 -rw-rw-r-- 1 fenaux fenaux  535961 mai   18 15:08 ssdlite_mobilenet_v2.xml

**Comment by brmarkus** [comment]
Can you copy the two files ("ssdlite_mobilenet_v2.bin" and "ssdlite_mobilenet_v2.xml") to another, simple folder (e.g. "/tmp/ssdlite_mobilenet_v2.xml" and "/tmp/ssdlite_mobilenet_v2.bin")?

Please copy the files as your current user.

Do you start you application/script as your current user, or as different user?

Do you start your application "directly" via "python3 my_application.py" in the terminal, or are you in a Docker container, in a VirtualMachine, do you start it remotely via an "ssh" command?

There is a chance that the user has changed or that e.g. libraries or ENV variables are missing when you start the application remotely via SSH.

You don't show WHAT you start, you don't show HOW you start it.

Can you use an OpenVINO sample&demo and provide the model-filename to it?

For instance, can you use the OpenVINO sample:

```
$> python3 benchmark_app.py -m "/home/fenaux/stick/openvino_notebooks/notebooks/401-object-detection-webcam/model/public/ssdlite_mobilenet_v2/FP16/ssdlite_mobilenet_v2.xml" -d CPU

$> python3 benchmark_app.py -m /tmp/ssdlite_mobilenet_v2.xml -d CPU
```

**Comment by fenaux** [comment]
I do all usage from virtual environment as show in installation guide and always with the same user ("fenaux")

Can you copy the two files ("ssdlite_mobilenet_v2.bin" and "ssdlite_mobilenet_v2.xml") to another, simple folder (e.g. "/tmp/ssdlite_mobilenet_v2.xml" and "/tmp/ssdlite_mobilenet_v2.bin")?

Please copy the files as your current user.
_It woks this ways when I copy the files to the directory where is my script_ 

Do you start you application/script as your current user, or as different user?
_From current user_

Do you start your application "directly" via "python3 my_application.py" in the terminal, or are you in a Docker container, in a VirtualMachine, do you start it remotely via an "ssh" command?
_"directly" via "python3 my_application.py" in the terminal_

There is a chance that the user has changed or that e.g. libraries or ENV variables are missing when you start the application remotely via SSH.

You don't show WHAT you start, you don't show HOW you start it.
(openvino_env) (base) fenaux@fenaux-HP-EliteBook-840-G3:~/stick/contact$ python test_ext.py

$> python3 benchmark_app.py -m /tmp/ssdlite_mobilenet_v2.xml -d CPU
I do not find benchmark_app.py
the only benchmark_app file is a binary file in openvino_env/bin

**Comment by brmarkus** [comment]
You can also use the "benchmark_app" binary, compiled from C/C++ code. It should support the same command line parameters.

This was just to do a consistency-check of your environment and OpenVINO installation.

Good to hear that after copying the files to another folder then you got it working.
Then there is something strange with your path (too many subfolders? access-/user-rights?)...
