### ISSUE TITLE
RuntimeError: Cannot load library 'libopenvino_intel_myriad_plugin.so

### ISSUE THREAD

**Issue by fenaux** [openvinotoolkit/openvino_notebooks#556]
I have a script test_exp.py contining following commands

ie_core = Core()
model = ie_core.read_model(model=converted_model_path)
# compile the model for the CPU (you can choose manually CPU, GPU, MYRIAD etc.)
# or let the engine choose the best available device (AUTO)
#compiled_model = ie_core.compile_model(model=model, device_name="CPU")
compiled_model = ie_core.compile_model(model=model, device_name="MYRIAD")

I run it with 
python test_exp.py
and the get
RuntimeError: Cannot load library 'libopenvino_intel_myriad_plugin.so

the same script with
compiled_model = ie_core.compile_model(model=model, device_name="CPU")
runs correctly

** Environment information **
Pip version: 22.1
OpenVINO source: /home/fenaux/openvino_env/lib/python3.9/site-packages/openvino
OpenVINO IE version: 2022.1.0-7019-cdb9bec7210-releases/2022/1
OpenVINO environment activated: OK
Jupyter kernel installed for openvino_env: NOT OK
Python version: 3.9 OK
OpenVINO pip package installed: OK
OpenVINO import succeeds: OK
OpenVINO development tools installed: OK
OpenVINO not installed globally: OK
No broken requirements: OK

Ubuntu 20.04.4 LTS

I could not run
source ~/intel/openvino/bin/setupvars.sh
cd ~/intel/openvino/install_dependencies
./install_NCS_udev_rules.sh

as i do not find setupvars.sh
nor install_dependencies

thanks for your help

**Comment by Debskij** [comment]
Hi @fenaux! I don't think that its something that we are able to fix in this repository. Can you report this issue to [OpenVINO repository](https://github.com/openvinotoolkit/openvino)?

**Comment by fenaux** [comment]
I agree. thanks
