### ISSUE TITLE
how to do inference for custom converted model?

### ISSUE THREAD

**Issue by akashAD98** [openvinotoolkit/openvino_notebooks#561]
i have converted yolo.onxx model into IR form using this

`from openvino.runtime import Core

ie = Core()
onnx_model_path = r"D:\sciffer\Neuralmagic-fps\ONNX_WEIGHTS\yolov4-416.onnx"
model_onnx = ie.read_model(model=onnx_model_path)
compiled_model_onnx = ie.compile_model(model=model_onnx, device_name="CPU")`

from openvino.offline_transformations import serialize

serialize(model=model_onnx, model_path=r"D:\sciffer\Neuralmagic-fps\ONNX_WEIGHTS\yolov4onnx_model.xml", weights_path=r"D:\sciffer\Neuralmagic-fps\ONNX_WEIGHTS\yolov4onnx_model.bin")

i got .bin & xml file which has IR openvino format

now i want to use inference script for my converted yolov4.xml  model.

**Comment by Debskij** [comment]
Hi @akashAD98! Thanks for reaching out.
As you already mentioned you are using different model, having different input and output. After searching for model that you've mentioned I've found that there ([link to ONNX YOLOv4 readme file](https://github.com/onnx/models/blob/main/vision/object_detection_segmentation/yolov4/README.md)) are snippets how to preprocess model input and postprocess model output.

**Comment by raymondlo84** [comment]
If you have more questions, please raise and we will open this ticket again :) Thank you.
