### ISSUE TITLE
"Note: Model Caching is not available on CPU devices" is correct?

### ISSUE THREAD

**Issue by dlod-openvino** [openvinotoolkit/openvino_notebooks#566]
In the [OpenVINO API tutorial](https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/002-openvino-api/002-openvino-api.ipynb) notebook, Caching a Model says:
"Note: Model Caching is not available on CPU devices"
![Note: Model Caching is not available on CPU devices](https://user-images.githubusercontent.com/59691336/172152962-97a9dfbb-e196-4700-ad3b-eec492fd4c87.png)

However, in the https://docs.openvino.ai/latest/openvino_docs_OV_UG_Model_caching_overview.html, says:
The** GPU plugin** does not have the EXPORT_IMPORT capability, and **does not support model caching** yet.
![the GPU plugin does not support model caching](https://user-images.githubusercontent.com/59691336/172153190-5e717a24-d22f-4133-99df-8d48f17826ce.png)

Which one is correct? Thanks!

**Comment by raymondlo84** [comment]
@helena-intel  ;)? I remember Helena talked about this in the past.... :)

**Comment by raymondlo84** [comment]
What's our proposed fixes?
