### ISSUE TITLE
YOLOv5 Real Time Detection With OpenVINO

### ISSUE THREAD

**Issue by ConorHackett98** [openvinotoolkit/openvino_notebooks#570]
Hi,

I've recently started using YOLOv5 and I have been trying to perform real time object detection using OpenVINO on a Movidius Neural Compute Stick 2.

For practice I've used the YOLOv5 tutorial.ipynb to train a custom dataset on the coco128 dataset. I've tried running this model on the YOLOv5 detect.py program and it seems to work perfectly (https://github.com/ultralytics/yolov5).

I then export the model to OpenVINO format which succeeds. The main issue appears when I try and run real time object detection with OpenVINO. I am using a sample OpenVINO notebook to initiate the detection (https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/401-object-detection-webcam). This sample program uses the ssdlite_mobilenet_v2 model which has an input of (B, H, W, C) and an output of (1, 1, 100, 7). The custom model I have trained using the YOLOv5 tutorial.ipynb has an input of (B, C, H, W) and an output of (1, 25200, 85).

I was wondering if there is any way for me to edit the object detection webcam program to accept a similar input and output as to what is produced by YOLOv5 trained models.

Thank you.

**Comment by raymondlo84** [comment]
Shall we create a new notebook just for YOLO?

**Comment by ryanloney** [comment]
@ConorHackett98 we have a notebook under development for YOLOv5 quantization. It is passing CI, but some minor changes may be implemented before it gets merged to the main branch. Take a look at this PR: https://github.com/openvinotoolkit/openvino_notebooks/pull/589

Link to the notebook: https://github.com/openvinotoolkit/openvino_notebooks/blob/f8fc9f8d33c24a69347becea70b5e9df9e33cdf3/notebooks/219-pytorch-object-detection-accuracy-check-and-quantization/219-pytorch-object-detection-accuracy-check-and-quantization.ipynb

**Comment by adrianboguszewski** [comment]
YOLOv5 notebook has been already merged and it's available here: https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/220-yolov5-accuracy-check-and-quantization
