### ISSUE TITLE
CVPR - Prework

### ISSUE THREAD

**Issue by zayedmohamed** [openvinotoolkit/openvino_notebooks#575]
### Discussed in https://github.com/openvinotoolkit/openvino_notebooks/discussions/568

<div type='discussions-op-text'>

<sup>Originally posted by **paularamo** June  6, 2022</sup>
We will start this conversation with a big WELCOME to the CVPR community, we are pleased you have chosen this tutorial. Here, you will learn how to set up and run many AI models with OpenVINO and your webcam in just 10 minutes. As part of the tutorial, you should set up your laptop, in order to run the demonstration we have prepared for you. 

- Follow the instructions of this [Wiki page](https://github.com/openvinotoolkit/openvino_notebooks/wiki).
- Run the notebooks 301 and 401.
- Share a screenshot in this thread.

This image most likely belongs to dandelion with a 99.77 percent confidence. 👍 
![image](https://user-images.githubusercontent.com/10484631/174400701-f0cbbaaa-4001-4e11-8beb-82e146001ea2.png)

Accuracy almoste the same with original and quatized model 👍
![image](https://user-images.githubusercontent.com/10484631/174400952-33448b92-a201-48df-8b83-6776765a1b47.png)

30 FPS successfull detection using webcam with cpu 👍
![image](https://user-images.githubusercontent.com/10484631/174401329-7347a870-94cc-459d-afb3-4c2eda01247d.png)

</div>

**Comment by raymondlo84** [comment]
what's the issue? =) I am closing this for now and please re-open if needed.
