### ISSUE TITLE
Webcam Demo failed due to memory leaks and long lags

### ISSUE THREAD

**Issue by raymondlo84** [openvinotoolkit/openvino_notebooks#584]
**Describe the bug**
The webcam demos 4xx series seems to suffer some sort of lag if we run the application for a long time. 

 **Expected behavior**
Run the demo for over 15 minutes, a high lag or excessive amount of ram will be consumed (till it crashed).

**Comment by raymondlo84** [comment]
Also, we used AUTO plugin? That's another hint and things we did't test fully.

**Comment by adrianboguszewski** [comment]
We were using the GPU plugin. After a day of debugging, I can say that long lag is a non-deterministic issue. It happened only once and looked like a Jupyter Notebook issue with displaying (I couldn't stop kernel). No memory leaks were detected.

**Comment by adrianboguszewski** [comment]
The bug is gone if using popup mode. The performance is also better with popup mode. The recommendation: use popup mode.
