### ISSUE TITLE
Openvino compatibility with pyinstaller

### ISSUE THREAD

**Issue by Meruman** [openvinotoolkit/openvino_notebooks#600]
I have a problem with open vino and python, I need to do a stand-alone app for some customers. This app is a websocket server that needs to run an inference on command with a tensorflow object detection model, that is why I am loading the model to memory from the beggining, this was very slow (about 900ms per inference) because it was running in the CPU so I managed to convert the model to IR model and it works way faster with openvino (about 200ms per inference). Everything works when I run the python script on my computer with Visual studio code but once I create a "onefile" pyinstaller exe file, I think the program have a problem loading the Core from open vino because it crashes even before starting the webserver. Sometimes it works the first time I run it after creating the exe file, but when I close it and try to run it again it starts having problems. Other behaviour that I have seen is that normally, the model takes about 500mb of memory when its loaded and working correctly, but when the problem happens, sometimes the memory goes to 300mb and then it drops to 6mb or so, so I am thinking that the model can not properly load to memory.

Does openvino changes something on windows environment? or does it creates something like a cache that is later corrupted when I bundle it with pyinstaller?.

I installed openvino (version: 2022.1.0) on my virtual environment with this command:
`pip install openvino-dev[tensorflow2]`
I have python 3.7.6 running and I created the exe file using pyinstaller 4.10 with this spec file:

```
# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(['websocketServer.py'],
             pathex=['C:\\Users\\user\\Documents\\Project\\websocketServerEnv'],
             binaries=[],
             datas=[,
                 ("model_ir", "model_ir"),
                 ("numpy_image.p", "."),
                ("websocketServerEnv\\Lib\\site-packages\\openvino","openvino")
             ],
             hiddenimports=[],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
# Rename _pywrap_tensorflow_internal to tensorflow.python._pywrap_tensorflow_internal
for i in range(len(a.binaries)):
  dest, origin, kind = a.binaries[i]

  if '_pywrap_tensorflow_internal' in dest:
      print('Remapping TF-INTERNAL')
      print(dest,origin,kind)
      a.binaries[i] = ('tensorflow/python/' + dest, origin, kind)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,  
          [],
          name='websocketServer',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None )
```
I added the complete openvino folder into the bundle to see if that fixes the problem but it didn't, before I had some issues running the exe file because the dlls required to run openvino were missing. I fixed it by adding binaries to those dll on the spec file with:
`binaries=[('C:/Users/user/Documents/Project/websocketServerEnv/Lib/site-packages/openvino/libs','openvino/libs')],`
without the need to add all the folder into the bundle but this also had the problem I described.

To load the model and run inference, I used the method described in the [tutorial](https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/101-tensorflow-to-openvino/101-tensorflow-to-openvino.ipynb).

A part of my script that runs open vino is:
```
import pickle
import argparse
from openvino.runtime import Core
#os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
from tensorflow import convert_to_tensor, image, gather

#OPENVino
compiled_model_ir = None
output_layer_ir = None
model_ir = None
ie = None

def load_model():
    global model
    global category_index
    global compiled_model_ir
    global model_ir
    global ie
    global output_layer_ir

    # Load the network
    ie =  Core()
    model_ir = ie.read_model(model=resource_path("model_ir\saved_model.xml"), weights=resource_path("model_ir\saved_model.bin"))
    compiled_model_ir = ie.compile_model(model=model_ir, device_name="CPU")

    # Get output layer
    output_layer_ir = compiled_model_ir.output(0)

    input_data= pickle.load(open(resource_path("numpy_image.p"), "rb"))
    input_data= np.expand_dims(input_data, axis=0)

    # Run inference on the input image
    t0 = time.time()
    result = compiled_model_ir([input_data])
    t1 = time.time()
    print(t1-t0)


if __name__ == "__main__":
    
    default_config_path = os.getenv('APPDATA') + "config.json"
    parser = argparse.ArgumentParser(description="configuration",
                                 formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("-c", "--config_path", type=str, default=default_config_path , help="path to the config.json")
    args = vars(parser.parse_args())
    configuration_path = args["config_path"]
    if not os.path.exists(configuration_path):
        configuration_path = "config.json"
        print(f"Configuration running in local: {configuration_path}")
    else:
        print(f"Configuration running: {configuration_path}")
    print("Loading AI model...")
    load_model()
    print("AI Model loaded...")
    start_webserver()
```
I run the openvino model right at the beginning to load the model to memory and to check that it is working.
Is there anything I could do to debug the crashes of openvino in the exe file console?

**Comment by adrianboguszewski** [comment]
Hi @Meruman, please open an issue in the OpenVINO repository (https://github.com/openvinotoolkit/openvino). This repository is only for tutorials, not OpenVINO itself.
