### ISSUE TITLE
Changing mac os installation guide wiki

### ISSUE THREAD

**Issue by Fiston-pro** [openvinotoolkit/openvino_notebooks#628]
In 'https://github.com/openvinotoolkit/openvino_notebooks/wiki/macOS' on step 5 after activating a virtual environment you have to `cd openvino_env` because on step 6 you clone the repo when you are still outside the virtual environment

**Comment by adrianboguszewski** [comment]
The instruction assumes you're creating a virtual environment outside of the repo. Like the following structure:
```
--+
  |
  +- openvino_env
  +- openvino_notebooks
```
You don't have to clone the repo inside `openvino_env`. It's enough to activate the environment.

**Comment by Fiston-pro** [comment]
Don't you think the structure might be a bit wrong cz after that you follow up by installing packages in requirements.txt and in that structure the packages will be global not in virtual environment.
