### ISSUE TITLE
Wrong model  caching info and code in OpenVINO API sample

### ISSUE THREAD

**Issue by AlexKoff88** [openvinotoolkit/openvino_notebooks#629]
**Describe the bug**
OpenVINO API [notebook](https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/002-openvino-api/002-openvino-api.ipynb) contains incorrect information and code about the model caching, for example, "Model caching is not available on CPU devices."

 **Expected behavior**
Regardless of the device, caching works smoothly and there should be no special checks or comments about the supported devices.

**Comment by AlexKoff88** [comment]
cc'ed @ilya-lavrenov

**Comment by brmarkus** [comment]
Is there a concept of OpenCL-kernel-cache at all for CPU?
When exporting `cl_cache_dir` (pointing to an existing and writable folder) and running inference on the CPU, then no OpenCL-kernels get compiled and stored in the "cache".
However, when using e.g. GPU for inference, then OpenCL-kernels get stored in the "cache".

I think it's just another concept - and not just "not available on CPU devices"?

**Comment by AlexKoff88** [comment]
I've heard about some caching on CPU, like caching the graph that came through the transformations. Maybe @ilya-lavrenov can comment here. 
Anyway, I don't think the current code snippet exposes the right user behavior with "if" statements, etc. The proper way is to use the caching function without keeping in mind what particular device will be used in each particular run.

**Comment by ilya-lavrenov** [comment]
> Is there a concept of OpenCL-kernel-cache at all for CPU?

Who said that it's CL cache dir? It's just a common [ov::cache_dir](https://docs.openvino.ai/latest/groupov_runtime_cpp_prop_api.html#doxid-group-ov-runtime-cpp-prop-api-1ga3276fc4ed7cc7d0bbdcf0ae12063728d), which can be used by any device, which can store intermediate data between `ov::Core::compile_model` calls. Please, read https://docs.openvino.ai/latest/openvino_docs_OV_UG_Model_caching_overview.html
