### ISSUE TITLE
Binder kernel dies while running Object Detection Quantization example

### ISSUE THREAD

**Issue by EdjeElectronics** [openvinotoolkit/openvino_notebooks#648]
**Describe the bug**
While running through the Object Detection Quantization notebook ([111-detection-quantization](https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/111-detection-quantization)) with Binder, I get an error message saying "The kernel appears to have died. It will restart automatically." This error occurs when I try to run the code block in the "Run Quantization Pipeline" section. I am not able to continue running the code when the kernel dies.

I tried three times to close the web browser, re-open the notebook in a new Binder session, and re-run the notebook, and the kernel died each time. I am able to run through each step of the Hello World notebook, so I don't think it's an issue with my browser.

 **Expected behavior**
I expect the full Jupyter Notebook to execute successfully in Binder.

**Screenshots**
Here's a screenshot of the message that appears when the kernel dies.
![image](https://user-images.githubusercontent.com/26154245/196760537-a71276d8-a539-453d-ae54-29158543a01f.png)

 **Installation instructions (Please mark the checkbox)**
[  ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

I am running the notebook in Binder, so it is not installed locally.

**Environment information**
Binder environment
 
**Additional context**
None

**Comment by adrianboguszewski** [comment]
Thanks @EdjeElectronics for reporting this. Indeed, 111-detection-quantization doesn't work in Binder anymore. The memory requirements are too high and Binder offers us limited resources. Unfortunately, the only solution, for now, is to clone it and run it locally.
