### ISSUE TITLE
Now requirements.txt has conflicting dependencies

### ISSUE THREAD

**Issue by buckw6eat** [openvinotoolkit/openvino_notebooks#667]
**Describe the bug**
`pip install -r requirements.txt`, Step 6 of [the installation guide for Ubuntu](https://github.com/openvinotoolkit/openvino_notebooks/wiki/Ubuntu), will fail with following error:

```
ERROR: Cannot install -r requirements.txt (line 18), -r requirements.txt (line 19), -r requirements.txt (line 38), -r requirements.txt (line 48), -r requirements.txt (line 8), nncf[tf,torch]==2.3.0.dev0+ccfb230 and torch==1.8.1+cpu because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested torch==1.8.1+cpu
    torchvision 0.9.1+cpu depends on torch==1.8.1
    torchmetrics 0.6.2 depends on torch>=1.3.1
    monai 0.9.1 depends on torch>=1.7
    geffnet 0.9.8 depends on torch>=1.2
    fastseg 0.1.0 depends on torch>=1.5.0
    nncf[tf,torch] 2.3.0.dev0+ccfb230 depends on torch==1.12.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

 **Expected behavior**
Should not cause errors and conflicting dependencies.

 **Installation instructions (Please mark the checkbox)**
- [x] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

---
It looks like the nncf package will be sourced from [github project page](https://github.com/openvinotoolkit/nncf) after 1e2cdaf0b5235df7e2d0a35761969af87f88143c, and recent update of the nncf introduced dependency on torch 1.12.1 at https://github.com/openvinotoolkit/nncf/blob/develop/setup.py#L116 in openvinotoolkit/nncf@39df8832b4459b4b3f878392a802ac5b74c1f3ac.

**Comment by eaidova** [comment]
@buckw6eat, sorry for inconvinience. We updated our requirements for resolving this issue, now it should works, thank you :)
