### ISSUE TITLE
Why is the quantified convnext model still slower than the original 32-bit unquantified model

### ISSUE THREAD

**Issue by DDI1999** [openvinotoolkit/openvino_notebooks#683]
**Describe the bug**
A clear and concise description of what the bug is, including steps to reproduce the bug if possible.

 **Expected behavior**

**Screenshots**

 **Installation instructions (Please mark the checkbox)**
[  ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
Please run `python check_install.py` in the _openvino_notebooks_ directory. If the output is _NOT OK_ for any of the checks, please follow the instructions to fix that. If that does not work, or if you still encounter the issue, please paste the output of check_install.py here.
 
**Additional context**

![image](https://user-images.githubusercontent.com/78290725/204167860-e85c34af-554a-4daf-92c2-6ac9ce56fe45.png)
这是我量化后的结果，
我测了一下32位IR中间模型的速度如下图
![image](https://user-images.githubusercontent.com/78290725/204167909-a4f09eeb-08db-44ca-888b-abd7896c8f9b.png)
![image](https://user-images.githubusercontent.com/78290725/204167945-cb422b33-6722-4a4a-8ce0-0db33bb5ec1b.png)

这是量化后的速度
![image](https://user-images.githubusercontent.com/78290725/204167963-b0e6de74-a19e-42a3-8655-d0f9a0465c35.png)
![image](https://user-images.githubusercontent.com/78290725/204167984-d392bae7-c7cb-40dd-bae9-326ad817115d.png)
为什么量化后还掉了5帧

**Comment by DDI1999** [comment]
我用的是api接口自定义的方式进行量化的
希望能帮忙解答我的问题谢谢！

**Comment by DDI1999** [comment]
我用相同的方式量化resnet网络速度会有很大提升，但是对于convnext就出现了上面的问题

**Comment by DDI1999** [comment]
I quantified the resnet network speed in the same way, but for convnext the above problem occurred

**Comment by DDI1999** [comment]
api量化方式参考示例113的代码

**Comment by zhuo-yoyowz** [comment]
Thank you for your question. Could you provide the link to your model and we could take a test as well to see where the problem is.

**Comment by zhuo-yoyowz** [comment]
> api量化方式参考示例113的代码

是我们Notebook 113的代码吗？ 麻烦提供你的模型的link，我们这边也下载测试一下，看看原因在哪里。谢谢~

**Comment by DDI1999** [comment]
是的

**Comment by DDI1999** [comment]
convnexty模型用的https://github.com/facebookresearch/ConvNeXt/blob/main/models/convnext.py中tiny版本，我自己用的灰度图训练改了第一层conv（1,1,224,224）和最后一次输出为1x3分类的，初次之外别的都没改

**Comment by DDI1999** [comment]
convnext模型用的https://github.com/facebookresearch/ConvNeXt/blob/main/models/convnext.py中tiny版本，我自己的训练数据是灰度图，模型改了第一层conv的channel（1,1,224,224）和最后一次输出为1x3分类的，除此之外别的都没改

**Comment by DDI1999** [comment]
[https://github.com/DDI1999/convnext.git](url)
这是我用的权重文件

**Comment by DDI1999** [comment]
[https://github.com/DDI1999/convnext](url)
量化后的权重文件

**Comment by DDI1999** [comment]
[https://github.com/DDI1999/convnext](url)
量化后的权重文件请在浏览器中打开

**Comment by DDI1999** [comment]
> > api量化方式参考示例113的代码
> 
> 是我们Notebook 113的代码吗？ 麻烦提供你的模型的link，我们这边也下载测试一下，看看原因在哪里。谢谢~

[https://github.com/DDI1999/convnext](url)
这是我量化后的权重文件
请在浏览器中打开

**Comment by DDI1999** [comment]
> > api量化方式参考示例113的代码
> 
> 是我们Notebook 113的代码吗？ 麻烦提供你的模型的link，我们这边也下载测试一下，看看原因在哪里。谢谢~

是的

**Comment by DDI1999** [comment]
我想知道你们找到原因了吗

**Comment by DDI1999** [comment]
我想知道你们找到原因了吗

**Comment by zhuo-yoyowz** [comment]
> 我想知道你们找到原因了吗

麻烦再提供一下你使用的数据集

**Comment by zhuo-yoyowz** [comment]
> > > api量化方式参考示例113的代码
> > 
> > 
> > 是我们Notebook 113的代码吗？ 麻烦提供你的模型的link，我们这边也下载测试一下，看看原因在哪里。谢谢~
> 
> [https://github.com/DDI1999/convnext](url) 这是我量化后的权重文件 请在浏览器中打开

这个link打不开

**Comment by zhuo-yoyowz** [comment]
> > > api量化方式参考示例113的代码
> > 
> > 
> > 是我们Notebook 113的代码吗？ 麻烦提供你的模型的link，我们这边也下载测试一下，看看原因在哪里。谢谢~
> 
> [https://github.com/DDI1999/convnext](url) 这是我量化后的权重文件 请在浏览器中打开

麻烦再发一下原始fp32模型的下载地址

**Comment by DDI1999** [comment]
> > > > api量化方式参考示例113的代码
> > > 
> > > 
> > > 是我们Notebook 113的代码吗？ 麻烦提供你的模型的link，我们这边也下载测试一下，看看原因在哪里。谢谢~
> > 
> > 
> > [https://github.com/DDI1999/convnext](url) 这是我量化后的权重文件 请在浏览器中打开
> 
> 麻烦再发一下原始fp32模型的下载地址

[https://github.com/DDI1999/weights](url)这是我的原始pth地址，[https://github.com/DDI1999/convnext](url)这里有我的量化脚本和配置

**Comment by zhuo-yoyowz** [comment]
Hi, I cloned your [https://github.com/DDI1999/convnext] and [https://github.com/DDI1999/weights] repo, so far I could only find the folder with Int8 IR files, while the following files are missing.
![image](https://user-images.githubusercontent.com/35246475/205489499-a8610161-5887-43a1-8033-14a445aef363.png)
I took benchmark_app test with you int8 IR files, and here's what I've got
![image](https://user-images.githubusercontent.com/35246475/205489545-43e4fc32-576d-4a9e-a53e-19cadff574fc.png)
![image](https://user-images.githubusercontent.com/35246475/205489568-4505b623-e1a1-40f6-acbb-e6167b88e07d.png)

Please provide the onnx file or the other missing files to obtain FP32 IR files for further testing. Thanks.

**Comment by DDI1999** [comment]
> 
[https://github.com/DDI1999/weights](url)这里面有量化过程中的所有文件，麻烦你测试一下

**Comment by DDI1999** [comment]
> Hi, I cloned your [https://github.com/DDI1999/convnext] and [https://github.com/DDI1999/weights] repo, so far I could only find the folder with Int8 IR files, while the following files are missing. ![image](https://user-images.githubusercontent.com/35246475/205489499-a8610161-5887-43a1-8033-14a445aef363.png) I took benchmark_app test with you int8 IR files, and here's what I've got ![image](https://user-images.githubusercontent.com/35246475/205489545-43e4fc32-576d-4a9e-a53e-19cadff574fc.png) ![image](https://user-images.githubusercontent.com/35246475/205489568-4505b623-e1a1-40f6-acbb-e6167b88e07d.png)
> 
> Please provide the onnx file or the other missing files to obtain FP32 IR files for further testing. Thanks.

[https://github.com/DDI1999/weights](https://github.com/openvinotoolkit/openvino_notebooks/issues/url)这里面有量化过程中的所有文件，麻烦你测试一下

**Comment by DDI1999** [comment]
> Hi, I cloned your [https://github.com/DDI1999/convnext] and [https://github.com/DDI1999/weights] repo, so far I could only find the folder with Int8 IR files, while the following files are missing. ![image](https://user-images.githubusercontent.com/35246475/205489499-a8610161-5887-43a1-8033-14a445aef363.png) I took benchmark_app test with you int8 IR files, and here's what I've got ![image](https://user-images.githubusercontent.com/35246475/205489545-43e4fc32-576d-4a9e-a53e-19cadff574fc.png) ![image](https://user-images.githubusercontent.com/35246475/205489568-4505b623-e1a1-40f6-acbb-e6167b88e07d.png)
> 
> Please provide the onnx file or the other missing files to obtain FP32 IR files for further testing. Thanks.

[[https://github.com/DDI1999/weights](https://github.com/openvinotoolkit/openvino_notebooks/issues/url)](url)这是我新上传的权重文件，里面有fp32位的权重和onnx权重还有.pth的权重文件

**Comment by brmarkus** [comment]
INT8 quantized/re-trained/trained models make most sense if the underlying HW (SoC/CPU) has VNNI/AVXxxx/AMX/TMUL/BF16 instruction set available.

Were performance-per-layer measures done (see e.g. "https://docs.openvino.ai/latest/openvino_inference_engine_tools_benchmark_tool_README.html#per-layer-performance-and-logging") to identify where most of the resources were used?
(maybe the model's convolution-kernel-sizes are not ideal)
