### ISSUE TITLE
Known Issues with OpenVINO 2022.3 + OpenVINO Notebooks

### ISSUE THREAD

**Issue by raymondlo84** [openvinotoolkit/openvino_notebooks#685]
Here is a list of known issues for using OpenVINO 2022.3 and OpenVINO Notebooks. You can compile and obtain the 2022.3 from here.

https://github.com/openvinotoolkit/openvino/wiki

Known issues (Ubuntu 22.04 + Python 3.10):

1. Python 3.10 and torch 1.8.1 dependencies is conflicting. (ERROR: Could not find a version that satisfies the requirement torch==1.8.1+cpu)
2. PaddlePaddle 2.2 is also conflicting/missing. (ERROR: Could not find a version that satisfies the requirement paddlepaddle==2.2.*)
3. Tensorflow 2.5.3 (ERROR: Could not find a version that satisfies the requirement tensorflow==2.5.3)

**Comment by raymondlo84** [comment]
```
The conflict is caused by:
    The user requested tensorflow
    nncf[tf,torch] 2.3.0 depends on tensorflow~=2.5.0; extra == "tf"
```
NNCF had a hard conflict with tensorflow. We shall look into this as it constraints lots of the requirements.

**Comment by raymondlo84** [comment]
ONNX also failed to build with the wheel.
```
/bin/python3', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-310-x86_64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/tmp/pip-install-e06bivys/onnx_9ba0baa30db34cf89a28f2a1eeb1ab7b']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for onnx
  Running setup.py clean for onnx
```

**Comment by raymondlo84** [comment]
![image](https://user-images.githubusercontent.com/1720147/204206272-544de4ca-e0ea-448b-be45-b8cefe199a97.png)

**Comment by eaidova** [comment]
> ```
> The conflict is caused by:
>     The user requested tensorflow
>     nncf[tf,torch] 2.3.0 depends on tensorflow~=2.5.0; extra == "tf"
> ```
> 
> NNCF 2.3.0 had a hard conflict with tensorflow. We shall look into this as it constraints lots of the requirements.

it is the reason why we use nncf from  github for now

**Comment by eaidova** [comment]
> PaddlePaddle 2.2 is also conflicting/missing. (ERROR: Could not find a version that satisfies the requirement paddlepaddle==2.2.*)

Should be already updated to work with 2.4

**Comment by eaidova** [comment]
> Python 3.10 and torch 1.8.1 dependencies is conflicting. (ERROR: Could not find a version that satisfies the requirement torch==1.8.1+cpu)

it is the most hard topic, I'm trying to update to torch 1.12.1 or 1.13, but all attempts for now are not successful
here some of my experiments:  https://github.com/openvinotoolkit/openvino_notebooks/pull/697
and additionally we need replace model in 102 notebook

**Comment by eaidova** [comment]
> ONNX also failed to build with the wheel.
> 
> ```
> /bin/python3', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-310-x86_64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/tmp/pip-install-e06bivys/onnx_9ba0baa30db34cf89a28f2a1eeb1ab7b']' returned non-zero exit status 1.
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for onnx
>   Running setup.py clean for onnx
> ```

in 2022.2 we had onnx < 1.12 supported only in openvino, for 2022.3 added support 1.12 too.
according to comment in requirements, we need upgraded onnx version for windows only, so possibly we can use default onnx version required for openvino-dev for any other platforms

**Comment by eaidova** [comment]
Torch and ONNX requirements finally updated

**Comment by eaidova** [comment]
Ubunutu22.04 and python3.10 added to precommit runs, here successful build https://github.com/openvinotoolkit/openvino_notebooks/actions/runs/3752632439/jobs/6375010431
@raymondlo84 I believe we can close this issue as done?
