### ISSUE TITLE
Timeout when downloading diffusion model

### ISSUE THREAD

**Issue by adrianboguszewski** [openvinotoolkit/openvino_notebooks#691]
**Describe the bug**
I cannot run 224 stable diffusion, because there is a timeout when downloading the model. I'd suggest increasing the waiting time as my internet connection (like many others also) is not very fast and stable. 

**Screenshots**
![image](https://user-images.githubusercontent.com/4547501/205095138-ee46fe6f-05cf-4ba6-a0f6-92ae691e984f.png)

**Comment by raymondlo84** [comment]
@AnishaUdayakumar fyi.

**Comment by eaidova** [comment]
resolved as part of https://github.com/openvinotoolkit/openvino_notebooks/pull/703
