### ISSUE TITLE
Duplicated images in the repository

### ISSUE THREAD

**Issue by adrianboguszewski** [openvinotoolkit/openvino_notebooks#711]
I found there are many duplicates in the repository e.g coco.jpg. It increases cloning time and space usage. It would be good to create a "central directory" with images and videos to use across all notebooks. 

I propose:
1. Create the "data" dir in the root dir
2. Move all images and videos from specific notebooks, remove duplicates
3. Update links to media in all notebooks
4. Update contributing guide

**Comment by raymondlo84** [comment]
Let's make sure we don't make the repos any larger too.
