### ISSUE TITLE
Error about asynchronous inference AsyncInferQueue 

### ISSUE THREAD

**Issue by DDI1999** [openvinotoolkit/openvino_notebooks#717]
![image](https://user-images.githubusercontent.com/78290725/208035059-a6fe4caf-6a89-47e6-a834-8c7d0e017677.png)
为什么异步推理调用完callback后不能有返回值
![image](https://user-images.githubusercontent.com/78290725/208035882-748bf6f5-3f93-4809-ac48-1bc4077966bb.png)
为什么我用相同的方法获取不到模型输出呢
我用的yolov7应该有三个输出的

**Comment by DDI1999** [comment]
![image](https://user-images.githubusercontent.com/78290725/208036120-df337668-d689-42b4-b2dd-b3466257172d.png)
我用115教程里面的方法获取推理结果失败
![image](https://user-images.githubusercontent.com/78290725/208036378-5e6f0f1f-83f0-4c70-b5a5-e7244f5cf768.png)

**Comment by DDI1999** [comment]
如果使用v7网络做异步推理一个输入三个节点输出怎么设置AsyncInferQueue和相关设置呢
我需要推理的输出结果做后处理，这该怎么获取呢？
希望你们能给我一些建议

**Comment by eaidova** [comment]
Sorry, unfortunately, I do not speak on language what you use and can have some issues with attempts to translate it :)
Are you sure that you follow to our tutorial? Looks like you export model to onnx without grid layer in comparision with postprocessing used on our side. Using grid layer makes output compatible with code used by model authors in torch and also embed part of postprocessing to the model.
There any reasons why do you need to use model in this format or it can be reexported?

**Comment by DDI1999** [comment]
> Sorry, unfortunately, I do not speak on language what you use and can have some issues with attempts to translate it :) Are you sure that you follow to our tutorial? Looks like you exported model to onnx without grid layer in comparision with postprocessing used on our side. Using grid layer makes output compatible with code used by model authors in torch and also embed part of postprocessing to the model. There any reasons why do you need to use model in this format or it can be reexported?

What does it mean that you export your model to onnx without a grid layer

**Comment by DDI1999** [comment]
> Sorry, unfortunately, I do not speak on language what you use and can have some issues with attempts to translate it :) Are you sure that you follow to our tutorial? Looks like you exported model to onnx without grid layer in comparision with postprocessing used on our side. Using grid layer makes output compatible with code used by model authors in torch and also embed part of postprocessing to the model. There any reasons why do you need to use model in this format or it can be reexported?

If you use v7 network to do asynchronous inference input (1,3,640,640) output three nodes how do you set AsyncInferQueue and related Settings

I need to post-process the output of the asynchronous inference, but the callback function does not return a value. How do I get the output of the inference?

I hope you can give me some advice

**Comment by eaidova** [comment]
> What does it mean that you export your model to onnx without a grid layer

yolov7 is compex and unfriendly for onnx conversion, that is why model authors provides several options for model export with export.py script
https://github.com/WongKinYiu/yolov7/blob/main/export.py#L26
By default, if you export model without any additional arguments you got part of model which just contains all layers before "trouble makers", and need inplement postprocessing on own side.You got raw 3 outputs which in original torch moidel pass to Detect layer (need to be postproocessed in similar with this way):
https://github.com/WongKinYiu/yolov7/blob/main/models/yolo.py#L42

or you can add --grid parameter for get single output and postprocess it in way provided in detect.py.

You can see how it is done in our tutorial https://github.com/openvinotoolkit/openvino_notebooks/blob/develop/notebooks/226-yolov7-optimization/226-yolov7-optimization.ipynb

> I need to post-process the output of the asynchronous inference, but the callback function does not return a value. How do I get the output of the inference?

in callback you have `infer_request.results`, which contains dictionary with outputs tensors and their results, postprocessing can be applied to them. 
Although it does not allow return values, you can define some storage for results (e.g. list or dict for storing per image results) and use it for pushing results inside call back for future processing (e.g. visualization results)

**Comment by eaidova** [comment]
@DDI1999 do you have any updates?

**Comment by OpenVINO-dev-contest** [comment]
hi @DDI1999  This sample shows how to run yolov7 with AsyncInferQueue
https://github.com/OpenVINO-dev-contest/YOLOv7_OpenVINO_cpp-python
