### ISSUE TITLE
Failed to import the module.

### ISSUE THREAD

**Issue by DDI1999** [openvinotoolkit/openvino_notebooks#721]
![image](https://user-images.githubusercontent.com/78290725/208551985-986e0a4e-adfb-4d86-bf30-9cbf189bca4a.png)
I tried two methods to import failed，Why is that? Is there a problem with my version?

![image](https://user-images.githubusercontent.com/78290725/208551941-e621ab93-9744-41f5-bdac-670a005f7db8.png)
This is the version I use

**Comment by eaidova** [comment]
@DDI1999, yes, these changes available on `develop` branch, we use it for providing changes required for upcoming openvino version (at this time, it is 2022.3, which will be officially released soon).
For now we can install prerelease openvino version from pypi. Please install [requirements.txt ](https://github.com/openvinotoolkit/openvino_notebooks/blob/develop/requirements.txt)from the same branch what you use.

**Comment by eaidova** [comment]
@DDI1999  I happy to say that openvino 2022.3 finally available via pypi. You can install and run notebooks :)

**Comment by DDI1999** [comment]
> @DDI1999 I happy to say that openvino 2022.3 finally available via pypi. You can install and run notebooks :)

ok，Let me try
