### ISSUE TITLE
timeout error when running 102 jupter NB

### ISSUE THREAD

**Issue by alberxualberxu** [openvinotoolkit/openvino_notebooks#738]
![102 timeout error](https://user-images.githubusercontent.com/102842442/209456122-eb5b470a-0ac8-4ab5-879a-bcc3eda75c9a.png)

i follow guide to install required components, run the juypter notebook locally, incurred this issue, is there any thing i need to check to fix this issue

**Comment by eaidova** [comment]
@alberxualberxu could you please try to download and convert model using omz tools?
```
omz_downloader --name fastseg-large
omz_converter --name fastseg-large
```
Unfortunately, fastseg model repo is no longer maintained by its authors... It may be broken at all or some temporal connection issue... In the latest release, on main branch, we replace fastseg model with another model if you looking to this tutorial to see how to convert pytorch models, I recommend to use the latest notebook version

**Comment by alberxualberxu** [comment]
@eaidova thanks for sharing on this, is it to use the same command as showed below to download the latest NB version?
git clone --depth=1 https://github.com/openvinotoolkit/openvino_notebooks.git

**Comment by eaidova** [comment]
@alberxualberxu  this command clone repo, but you already have cloned repo, probably it does not need to clone it one more time,just go to the openvino_notebooks directory and make `git pull` command for obtain the latest changes. After that probably, you need to reinstall requirements.txt (they can be updated with repo content)

**Comment by alberxualberxu** [comment]
@eaidova i ran "git pull" and reinstall requirements.txt, but still see timeout issue although the log details is little different, another clue not sure related to this sympton is, i marked below command with # in requirements.txt since it always hang there:
quote from requirements. txt:

# NNCF notebook requirements
#git+https://github.com/openvinotoolkit/nncf.git@f62b6629c71822b5241e175e0a03c3acb42ae01e#egg=nncf[torch]
tensorflow>=2.5,<=2.9.3
tensorflow_datasets==4.2.0
![102 timeout error2](https://user-images.githubusercontent.com/102842442/209897541-93311876-19bc-421d-b13b-ca39f9893bc7.png)

**Comment by eaidova** [comment]
@alberxualberxu it sitll looks strange, because the latest version of requirements.txt does not contains nncf installation? s I assume you still have not the latest version
Do you do something with repo after `git clone` (possibly you fork it or switch to another branch ?)
please try this `git pull origin main` instead of just `git pull`

**Comment by alberxualberxu** [comment]
@eaidova i disabled nncf installation intensionally because i met an issue when downloading nncf, below is the screen shot, after i disabled nncf's downloading, the rest in requirement txt are able to install successfully.

![nncf downloading issue](https://user-images.githubusercontent.com/102842442/209948960-fc352e1b-596f-4f9e-8235-35245bf8042f.png)

**Comment by eaidova** [comment]
@alberxualberxu  please look on this file: https://github.com/openvinotoolkit/openvino_notebooks/blob/main/requirements.txt
it is look like the latest requirements and there is no nncf at all, so it is the reason why I assume that you have not the latest version.
If notebooks repo will finished successfully you should have the same file like avilable on link above

**Comment by alberxualberxu** [comment]
@eaidova what you advised is quite correct! I use git pull origin main, both NB file and reuirement file updated, and 102 run successfully, thanks a lot!

**Comment by eaidova** [comment]
@alberxualberxu Gteat! Can we close this issue then?

**Comment by alberxualberxu** [comment]
@eaidova yes, pls, thanks!
