### ISSUE TITLE
Demo 224 - Part Segmentation of 3D Point Clouds with OpenVINO - mo argument not recognized

### ISSUE THREAD

**Issue by RobsonEsteves** [openvinotoolkit/openvino_notebooks#740]
Hi,
I'm getting the error below in this demo, when trying to Convert the ONNX model to OpenVINO IR.

usage: main.py [options]
main.py: error: unrecognized arguments: --compress_to_fp16

Why the previous version (with --data_type FP16 argument), was changed? Can I used it instead of -- --compress_to_fp16?

Thanks,
Robson

**Comment by eaidova** [comment]
@RobsonEsteves, recently `main` branch of this repository was upgraded to use openvino 2022.3, where `--data_type` option is deprecated and `--compress_to_fp16` is introduced as its replacement. If you intrested only run this specific notebook you can replace back, but for some other tutorials where new features demonstrated, it is recommended to upgrade openvino version

**Comment by RobsonEsteves** [comment]
@eaidova thanks by the feedback. 
OK, I understood.  After the changes I tried to run the demo and in the step **Visualize the original 3D data**  I'm getting the following errors below.  Do you know what could be the problem? Thanks a lot!
BR,
Robson

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-9ae4df47407d> in <module>
      1 point_data = "data/chair.pts"
----> 2 points = load_data(point_data)
      3 X = points[:, 0]
      4 Y = points[:, 2]
      5 Z = points[:, 1]

<ipython-input-4-4aa46c243b58> in load_data(point_file)
      7     """
      8 
----> 9     point_set = np.loadtxt(point_file).astype(np.float32)
     10 
     11     # normailization

c:\users\f8028140\openvino_env\lib\site-packages\numpy\lib\npyio.py in loadtxt(fname, dtype, comments, delimiter, converters, skiprows, usecols, unpack, ndmin, encoding, max_rows)
   1137         # converting the data
   1138         X = None
-> 1139         for x in read_data(_loadtxt_chunksize):
   1140             if X is None:
   1141                 X = np.array(x, dtype)

c:\users\f8028140\openvino_env\lib\site-packages\numpy\lib\npyio.py in read_data(chunk_size)
   1065 
   1066             # Convert each value according to its column and store
-> 1067             items = [conv(val) for (conv, val) in zip(converters, vals)]
   1068 
   1069             # Then pack it according to the dtype's nesting

c:\users\f8028140\openvino_env\lib\site-packages\numpy\lib\npyio.py in <listcomp>(.0)
   1065 
   1066             # Convert each value according to its column and store
-> 1067             items = [conv(val) for (conv, val) in zip(converters, vals)]
   1068 
   1069             # Then pack it according to the dtype's nesting

c:\users\f8028140\openvino_env\lib\site-packages\numpy\lib\npyio.py in floatconv(x)
    761         if '0x' in x:
    762             return float.fromhex(x)
--> 763         return float(x)
    764 
    765     typ = dtype.type

ValueError: could not convert string to float: '<!DOCTYPE'

**Comment by eaidova** [comment]
@RobsonEsteves could you please check that data/chair.pts is correctly downloaded and try to remove and redownload it?
The text in ValueError looks like some HTML page artifact...

**Comment by RobsonEsteves** [comment]
@eaidova, you are right!
Everything is running now 
Thanks again. 
Robson

**Comment by eaidova** [comment]
@RobsonEsteves if you have not additional questions, can we close this issue?
Thanks

**Comment by RobsonEsteves** [comment]
Yes, I agree.
Thanks!
R


Em qui., 29 de dez. de 2022 02:02, Ekaterina Aidova <
***@***.***> escreveu:
