### ISSUE TITLE
Windows installation of  openvino documents are not proper,not able to load openvino

### ISSUE THREAD

**Issue by akashAD98** [openvinotoolkit/openvino_notebooks#741]
its very difficult for beginners, there are different blogs & posts regarding installation of openvino.

i tried this & its installed successfully, but not able to run notebook. 

i have tried both anaconda & cmd , assigned path to environment variable still no luck

its showing openvino installed 

<img width="592" alt="image" src="https://user-images.githubusercontent.com/62583018/209804991-f02ee340-9531-4a1b-85a5-24e388c42fea.png">

<img width="627" alt="image" src="https://user-images.githubusercontent.com/62583018/209804838-3d756289-c2f0-45a1-8abe-ca45b8965fce.png">

1.https://docs.openvino.ai/latest/openvino_docs_install_guides_install_dev_tools.html#install-dev-tools

2.https://github.com/openvinotoolkit/openvino/wiki/BuildingForWindows

3.https://docs.openvino.ai/2022.3/notebooks-installation.html#-installation-guide

4.https://docs.openvino.ai/2021.1/openvino_docs_install_guides_installing_openvino_windows.html

5.https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/download.html

lots of sources but not single working. please let me know which one should I follow & how can I run the notebook successfully

**Comment by eaidova** [comment]
For launching notebooks, probably you should follow notebooks installation instruction, it involves openvino installation as part of requirements.txt
https://github.com/openvinotoolkit/openvino_notebooks/wiki/Windows

Regarding current problem:
1. please make sure that you use the same virtual environment for launching jupyter and in cmd (it seems that they are different).
2. which openvino version do you use? Jugging by the python version 3.6 in console, it does not look like 2022.3 (in 2022.3 python3.6 support was removed), probably you need to updated python version.

**Comment by eaidova** [comment]
@akashAD98 to know which openvino version installed in your environment please try in cmd:
```python
from openvino.inference_engine import get_version
    print(get_version())
```
if it prints > 2021.4.0, then try (to see that it is correctly loaded):
```
from openvino.runtime import Core
```
if not, then probably you need to upgrade your installation
If you have previously installed version with 2021 release please make sure that you have not environment variables overriding your environment (do not call setup_vars.bat in the same environment)

**Comment by akashAD98** [comment]
@eaidova it solved my issue in wndiws thanks
