### ISSUE TITLE
Unable to convert model while running Working with Open Model Zoo Models notebook

### ISSUE THREAD

**Issue by juliomorero** [openvinotoolkit/openvino_notebooks#755]
**Describe the bug**
While running through the [104-model-tools](https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/104-model-tools/104-model-tools.ipynb) notebook, I get the following error when running the cell to convert the model from PyTorch to OpenVINO IR (see attached screenshot for more details)
```
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
```

I tried both the `resnet-50-pytorch` and `mobilenet-v2-pytorch` but to no avail.

 **Expected behavior**
I expect the whole notebook to run successfully in my environment.

**Screenshots**
Here's a screenshot showing the failed cell
<img width="1680" alt="Screenshot 2023-01-05 at 6 33 45 PM" src="https://user-images.githubusercontent.com/29715691/210885342-2bb4dc87-de3c-4365-a052-5f7797972ed4.png">

 **Installation instructions (Please mark the checkbox)**
- [x] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

Specifically I followed the macOS section.

**Environment information**
```
> python check_install.py
System information:
Python executable: /Users/juliomorero/Documents/bdti/openvino_env/bin/python
Pip version: 22.3.1
OpenVINO source: /Users/juliomorero/Documents/bdti/openvino_env/lib/python3.10/site-packages/openvino
OpenVINO IE version: 2022.3.0-9052-9752fafe8eb-releases/2022/3
OpenVINO environment activated: OK
Jupyter kernel installed for openvino_env: NOT OK
Python version: 3.10 NOT OK
OpenVINO pip package installed: OK
OpenVINO import succeeds: OK
OpenVINO development tools installed: OK
OpenVINO not installed globally: OK
No broken requirements: OK

The Python version in openvino_env does not match the openvino_env Jupyter kernel.
This may not be an issue. If you experience issues, please follow the instructions
in the README to reinstall the kernel.

The README.md file is located in the openvino_notebooks directory
and at https://github.com/openvinotoolkit/openvino_notebooks
```
It shows that both the kernel installed and the python version are not ok but I could ran successfully the previous cells on the notebook.
 
**Additional context**
None

**Comment by eaidova** [comment]
@juliomorero it is known bug on open_model_zoo side, which already should be fixed on master branch https://github.com/openvinotoolkit/open_model_zoo/pull/3639

could you please try to install it from github, according to this instruction https://github.com/openvinotoolkit/open_model_zoo/tree/master/tools/model_tools#installation
