### ISSUE TITLE
Failed to download models - 203-meter-reader

### ISSUE THREAD

**Issue by raymondlo84** [openvinotoolkit/openvino_notebooks#756]
SEG_MODEL_LINK = "https://bj.bcebos.com/paddlex/examples2/meter_reader/meter_seg_model.tar.gz"

It hits timeout a few times and the download speed is about 50kb/s. We shall consider mirroring this to USA servers. 

Since download failure is always an issue. Shall we aim for a new routine to figure out where to find the best downloads.

**Comment by raymondlo84** [comment]
![image](https://user-images.githubusercontent.com/1720147/210897974-d69e5ebb-56b9-4091-a201-b99630201516.png)
it's very very slow.

**Comment by raymondlo84** [comment]
Thanks!

**Comment by OpenVINO-dev-contest** [comment]
The model is hosted by Baidu's server which is located in PRC.
Shall we migrate it to S3 bucket.
