### ISSUE TITLE
Python 3.7 from Windows Store = DLL Import Error

### ISSUE THREAD

**Issue by raymondlo84** [openvinotoolkit/openvino_notebooks#77]
https://www.microsoft.com/en-us/p/python-37/9nj46sx7x90p?activetab=pivot:regionofsystemrequirementstab

I got a DLL import error if I use Python 3.7 version from the Windows Store. I believe this is something others should be aware of?  

-ray

**Comment by helena-intel** [comment]
That is annoying indeed. It is strange that Microsoft Store doesn't just install the regular Python. I added a note to the wiki. https://github.com/openvinotoolkit/openvino_notebooks/wiki/Windows  
We now link to the wiki in the README (currently in develop) so hopefully people who run into this will find that.

**Comment by raymondlo84** [comment]
The instruction is updated (README.md) and we should use the official Python 3.7 for now.
