### ISSUE TITLE
226-yolov7 on Windows (errors or just warning)

### ISSUE THREAD

**Issue by raymondlo84** [openvinotoolkit/openvino_notebooks#772]
![image](https://user-images.githubusercontent.com/1720147/211676518-251e94c1-e625-456a-9ce7-e8871be87486.png)

It seems the code will still run even due to the deps error.

**Comment by eaidova** [comment]
yes, it is just pip warning about potential dependency conflict

**Comment by raymondlo84** [comment]
Ok. Would this installation perform self update? I see it connects to the git. How is it tracking versioning?
