### ISSUE TITLE
ModuleNotFoundError: No module named 'openvino.tools' on Google Colab

### ISSUE THREAD

**Issue by tungnt90** [openvinotoolkit/openvino_notebooks#783]
Hello, im trying to optimization model on Google Colab.

![error](https://user-images.githubusercontent.com/1974628/212568235-8656d00e-bb42-4538-81a6-2b9b0798fdd2.jpg)

Can you advice? Thank in advance!

**Comment by eaidova** [comment]
@tungnt90 unfortunatly, openvino is not a part of preinstalled google colab libs, please install them according this repo installation instruction
https://github.com/openvinotoolkit/openvino_notebooks/blob/main/requirements.txt

**Comment by eaidova** [comment]
@tungnt90 do you resolve your issue?
