### ISSUE TITLE
231-instruct-pix2pix-image-editing 'extensive' RAM usage

### ISSUE THREAD

**Issue by raymondlo84** [openvinotoolkit/openvino_notebooks#809]
I see the RAM usage spike to over 32GB. Shall we break down the flow and see where we can clean the memory?

**Comment by adrianboguszewski** [comment]
@eaidova I have the same issue. I cannot run 231 or modified 225 (PR version)

**Comment by eaidova** [comment]
@adrianboguszewski  for 225, do you tried the latest version?
I refactored code to reduce memory consumption, all models converted successfully (I tested via VS code extensions for jupyter on my laptop) with 16 GB ram), I refactor 231 in the same way later

**Comment by adrianboguszewski** [comment]
I have to see either dying or other errors
![image](https://user-images.githubusercontent.com/4547501/217061412-28911cb5-711c-4ef7-9dd1-af3ffe42a288.png)

**Comment by adrianboguszewski** [comment]
And 231 uses more than 50GB of RAM...
![Screenshot from 2023-02-06 20-11-45](https://user-images.githubusercontent.com/4547501/217063412-04da75ea-c819-4107-ab3a-d92e3c8d0ce5.png)

**Comment by raymondlo84** [comment]
> It's either dying or other errors ![image](https://user-images.githubusercontent.com/4547501/217061412-28911cb5-711c-4ef7-9dd1-af3ffe42a288.png)

Ubuntu version, Python version etc?

**Comment by raymondlo84** [comment]
> @adrianboguszewski for 225, do you tried the latest version? I refactored code to reduce memory consumption, all models converted successfully (I tested via VS code extensions for jupyter on my laptop) with 16 GB ram), I refactor 231 in the same way later

Is that windows? 

https://phoenixnap.com/kb/linux-commands-check-memory-usage

With Ubuntu, if you did not enable swap manually, application can crash if it runs out of RAM.


-ray

**Comment by eaidova** [comment]
> It's either dying or other errors ![image](https://user-images.githubusercontent.com/4547501/217061412-28911cb5-711c-4ef7-9dd1-af3ffe42a288.png)

it is wrong shape for export, I updated it.

Regarding 231, I'm working on the same improvements for memory, but my final estimation ~21 GB, possibly we can consider to upload model in hf hub and make conversion optional for machines with small RAM

**Comment by raymondlo84** [comment]
> > It's either dying or other errors ![image](https://user-images.githubusercontent.com/4547501/217061412-28911cb5-711c-4ef7-9dd1-af3ffe42a288.png)
> 
> it is wrong shape for export, I updated it.
> 
> Regarding 231, I'm working on the same improvements for memory, but my final estimation ~21 GB, possibly we can consider to upload model in hf hub and make conversion optional for machines with small RAM

we can divide up the notebook into two parts. 

Part 1 - model conversion / optimizations
Part 2 - inferences and samples / demos

**Comment by eaidova** [comment]
there is no optimzation part unfortunatly for now

**Comment by adrianboguszewski** [comment]
225 works now with occasional dying

**Comment by raymondlo84** [comment]
> 225 works now with occasional dying

what's your swap size?

**Comment by adrianboguszewski** [comment]
I increased it to 32GB and dying occurs with the increased swap.
