### ISSUE TITLE
Poor iGPU performance on Stable Diffusion

### ISSUE THREAD

**Issue by raymondlo84** [openvinotoolkit/openvino_notebooks#835]
It seems like the iGPU was not fully utilized, and part of the pipeline is kinda blocking or locking.

![image](https://user-images.githubusercontent.com/1720147/219138980-43ec8459-181b-43f4-8c50-50aee0bcf4c4.png)

**Comment by bouachalazhar** [comment]
> It seems like the iGPU was not fully utilized, and part of the pipeline is kinda blocking or locking.
> 
> ![image](https://user-images.githubusercontent.com/1720147/219138980-43ec8459-181b-43f4-8c50-50aee0bcf4c4.png)

Maybe you don't configure [multi-device](https://docs.openvino.ai/latest/openvino_docs_OV_UG_Running_on_multiple_devices.html#doxid-openvino-docs-o-v-u-g-running-on-multiple-devices) but tell me how you configure iGPU with your Intel Iris Xe graphics.
Show me the ouput of this command : 
```
from openvino.runtime import Core

ie = Core()

devices = ie.available_devices

for device in devices:
    device_name = ie.get_property(device, "FULL_DEVICE_NAME")
    print(f"{device}: {device_name}")
```

**Comment by brmarkus** [comment]
@bouachalazhar it was about running inference of StableDiffusion on GPU only - to show how the GPU gets utilized; this lead to other optimizations as bottlenecks were found.
Considering batch, num-of-inference-requests, async-mode and making use of all available "accelerators" - and the overall throughput will look differently.
