### ISSUE TITLE
whisper-subtitle notebbok error

### ISSUE THREAD

**Issue by akashAD98** [openvinotoolkit/openvino_notebooks#841]
**Describe the bug**
not able to run files, even i tried to remove .dtype from x varable,still im getting error

**Screenshots**
<img width="693" alt="image" src="https://user-images.githubusercontent.com/62583018/219868865-d39d34bd-3934-4a6d-bd80-74f6aa61b954.png">

<img width="601" alt="image" src="https://user-images.githubusercontent.com/62583018/219868846-cc8425d8-9781-46be-be1a-7948c6a2eae0.png">

** Environment information **
``` windows 10 ```
```I'm using windows10,
Name: openvino
Version: 2022.3.0
Summary: OpenVINO(TM) Runtime```


**Additional context**
Add any other context about the problem here.

**Comment by eaidova** [comment]
@akashAD98  I can not reproduce reported issue on the latest master, please try to update repo with notebooks

**Comment by eaidova** [comment]
probably the fix was done 2 jan https://github.com/openvinotoolkit/openvino_notebooks/pull/746

**Comment by akashAD98** [comment]
@eaidova let me try

**Comment by eaidova** [comment]
@akashAD98 then please double chek that you use `main` branch, possibly you previously switched on develop, it does not contains these changes yet
