### ISSUE TITLE
Adding Notebook Specific requirements.txt file

### ISSUE THREAD

**Issue by sawradip** [openvinotoolkit/openvino_notebooks#851]
## Current State
There is one central [`requirements.txt`](https://github.com/openvinotoolkit/openvino_notebooks/) file in the root directory of this repository.

That file contains all the general requirements including generally necessary libraries like:
```
numpy>=1.21.0
opencv-python
Pillow>=8.3.2
matplotlib>=3.4,<3.5.3
scipy
pytube>=12.1.0
librosa>=0.8.1
shapely>=1.7.1
pyclipper>=1.2.1
psutil
gdown
yaspin
seaborn>=0.11.0
scikit-image>=0.19.2
jedi>=0.17.2
setuptools>=56.0.0
pygments>=2.7.4 # not directly required, pinned by Snyk to avoid a vulnerability
rsa>=4.7 # 
```

But also includes libraries large libraries like:
```
tensorflow-macos>=2.5,<=2.9.3; sys_platform == 'darwin' and platform_machine == 'arm64' # macOS M1 and M2
tensorflow>=2.5,<=2.9.3; sys_platform == 'darwin' and platform_machine != 'arm64' # macOS x86
tensorflow>=2.5,<=2.9.3; sys_platform == 'linux' or platform_system == 'Windows'
tensorflow-datasets==4.2.0
```
```
torch==1.13.1; sys_platform == 'darwin'
torch==1.13.1+cpu; sys_platform == 'linux' or platform_system == 'Windows'
torchvision==0.14.1; sys_platform == 'darwin'
torchvision==0.14.1+cpu; sys_platform == 'linux' or platform_system == 'Windows'
torchmetrics>=0.11.0
pytorch-lightning
```
```
paddlepaddle>=2.4.0
paddle2onnx>=0.6
paddlenlp>=2.0.8 # workaround for "cannot import name '_C_ops'" error with paddlehub
```

While using this repository as a whole, all those libraries are important, either in one notebook or other.

Then there are individual `requirements.txt` files, in notebook folders such as, [210-ct-scan-live-inference](https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/210-ct-scan-live-inference), [212-pyannote-speaker-diarization](https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/212-pyannote-speaker-diarization) and [225-stable-diffusion-text-to-image](https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/225-stable-diffusion-text-to-image).

## Problems
* Using this repository becomes complicated for in low-resource and time-constraint environment, For example: Very few notebooks use `tensorflow` and `pytorch` together, by the user will have to install all libraries even if he only wants to use only pytorch-based notebooks, **which  is quite an irony, because the main goal of `Openvino` is to make usage and inference of model in the fastest way with low-resource hardware.** 
* As we are planning to add [Google Colab support](https://github.com/openvinotoolkit/openvino_notebooks/discussions/850), so then we would have to install 2 different `requirement.txt` files, one general requirement, another special for the model(if exists)
* Things often becomes confusing for users, when to look for one extra `requirements.txt` file.
* The users that have low-internet speed at their local devices, specially when currently `tensorflow-gpu` package is `=1 GB`, and `pytorch` is `>1.5GB` if I remember correctly.

## Solution
1. We can have compulsory seperate `requirements.txt` file for each of notebooks in their corresponding folder. So, the pytorch model user won't need to install the general `requirements.txt` file.
2. The `requirements.txt` file in the root folder will be there, and we can refer that file to users, who are going to work on general development of this repository, not some specific notebooks.
3. We can add tests for checking if the notebook-creator has added the `requirements.txt` files. We already do such test for `readme.md` file.

**Comment by sawradip** [comment]
@eaidova  @adrianboguszewski

**Comment by adrianboguszewski** [comment]
Thanks for bringing it up. We're aware of challenges related to the requirements file. @eaidova, are we working on this right now? Should it wait until you finish the restructuring?
