### ISSUE TITLE
issues for combining deepsort(.xml ) to converted (yolov7int8.xml) model

### ISSUE THREAD

**Issue by akashAD98** [openvinotoolkit/openvino_notebooks#854]
I'm getting size mismatch error,
i m using this notebook (https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/407-person-tracking-webcam ) & loading the yolov7-tiny.xml  ( )file instead of pedestrian weight,

```
detection_model_path='model\intel\person-detection-0202\FP16\yolov7-tiny_int8.xml'
reidentification_model_path='model\intel\person-reidentification-retail-0287\FP16\person-reidentification-retail-0287.xml'
```
1.)may i know what should i do to fix it?

<img width="486" alt="image" src="https://user-images.githubusercontent.com/62583018/220407552-f0dd5ad8-68cc-4b57-80be-5540a5ea5b54.png">

2) my approch is correct? can we try yolov7-tiny.xml & .Reid.xml weights to get higher fps

3)what changes should i need to do ,to usse any custom yolov7 object det model

**Comment by eaidova** [comment]
@OpenVINO-dev-contest could you please help?
@akashAD98
the [model](https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/intel/person-detection-0202/README.md) used in tutorial SSD based and has a different output format from yolov7. Error message comes from postprocessing code which is model specific. For successful integration yolov7 you need to write own postprocessing code. Also please pay attention that it is single class prediction model (only person), if your model predicts more, probably you need also provide filtering for getting only boxes  with appropriate label

**Comment by OpenVINO-dev-contest** [comment]
> @OpenVINO-dev-contest could you please help? @akashAD98 the [model](https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/intel/person-detection-0202/README.md) used in tutorial SSD based and has a different output format from yolov7. Error message comes from postprocessing code which is model specific. For successful integration yolov7 you need to write own postprocessing code. Also please pay attention that it is single class prediction model (only person), if your model predicts more, probably you need also provide filtering for getting only boxes with appropriate label

Yes, If your model have can detect multi-classes objects, you have to decide to track which of them.
@eaidova Thanks, I have tried to answer his question in my personal repository: https://github.com/OpenVINO-dev-contest/YOLOv7_OpenVINO_cpp-python/issues/15

**Comment by akashAD98** [comment]
@OpenVINO-dev-contest  @eaidova 
```
Orignal_model_shape [1,3,256,128]
~~~~ RESHAPED MODEL ~~~~
after resuze input shape [1,3,256,256]
after resize height 256
after resize width 256
compiled_model input shape: [1,3,256,256]
compiled_model output shape: [9,256]
```

shape of image: (256, 256, 3)

i was able to detect first few frames & got this error again
```
    return super().infer(normalize_inputs(self, {index: input for index, input in enumerate(inputs)}))
RuntimeError: The input blob size is not equal to the network input size: got 393216 expecting 196608```

**Comment by OpenVINO-dev-contest** [comment]
> @OpenVINO-dev-contest @eaidova
> 
> ```
> Orignal_model_shape [1,3,256,128]
> ~~~~ RESHAPED MODEL ~~~~
> after resuze input shape [1,3,256,256]
> after resize height 256
> after resize width 256
> compiled_model input shape: [1,3,256,256]
> compiled_model output shape: [9,256]
> ```
> 
> shape of image: (256, 256, 3)
> 
> i was able to detect first few frames & got this error again
> 
> ```
>     return super().infer(normalize_inputs(self, {index: input for index, input in enumerate(inputs)}))
> RuntimeError: The input blob size is not equal to the network input size: got 393216 expecting 196608```
> ```
> 
> here is my below code, im getting issue for normalising input,
> 
> ```
>     def get_features(self, im_crops): 
>         faces_im = []
>         c=0
>         for face in im_crops:
>             c=c+1
>             print("count face",c)
>             print("face",face)
>           
>             #if face.shape != (self.height, self.width, 3):
>             #    raise ValueError(f"Input image shape {face.shape} does not match expected shape {(self.height, self.width, 3)}")
>             face = cv2.resize(face, (self.height, self.width), interpolation=cv2.INTER_AREA)  # (h, w, 3)
>             assert face.shape == (self.height, self.width, 3), f"Input image shape {face.shape} does not match expected shape {(self.height, self.width, 3)}"
>             print("shape of image:",face.shape)
>             #print("shape of face is ",face.shape())
>             face = face.transpose(2, 0, 1)                  # (3, H, W)
>             face = torch.from_numpy(np.float32(face))
>             #face = (face - 127.5) / 128.0
>             faces_im.append(face)
> 
> 
>         #faces_im = torch.stack(faces_im, dim=0).unsqueeze(0)
>         faces_im = torch.stack(faces_im)
> 
>         return faces_im
> ```
> 
> first few frames im getting detection but later im getting this error
> 
> ```
> Frame 20 Done. Det-time:(0.368s) SORT-time:(0.000s)
> Frame 21 Done. Det-time:(0.350s) SORT-time:(0.000s)
> Frame 22 Done. Det-time:(0.333s) SORT-time:(0.000s)
> original--> [[        460         226         779         630]
>  [        579         320         958         717]]
> reshaped--> [[      619.5         428         319         404]
>  [      768.5       518.5         379         397]]
> count face 1
> face [[[161 173 165]
>   [165 177 169]
>   [164 177 166]
>   ...
>   [162 174 166]
>   [169 181 173]
>   [172 184 176]]
> 
>  [[158 170 162]
>   [163 175 167]
>   [162 175 164]
>   ...
>   [169 179 171]
>   [174 184 176]
>   [179 189 181]]
> 
>  [[159 171 163]
>   [162 174 166]
>   [162 175 164]
>   
>   ...
>   [ 78  74  70]
>   [ 78  75  69]
>   [ 78  75  69]]
> 
>  [[108 125 129]
>   [114 131 135]
>   [116 133 137]
>   ...
>   [ 78  74  70]
>   [ 78  75  69]
>   [ 78  75  69]]]
> shape of image: (256, 256, 3)
> count face 2
> face [[[ 34  39  52]
>   [ 35  40  53]
>   [ 35  40  53]
>   ...
>   [ 54  58  53]
>   [ 55  59  54]
>   [ 69  74  67]]
> 
>  [[ 32  37  50]
>   [ 34  39  52]
>   [ 35  40  53]
>   ...
>   [ 35  39  34]
>   [ 52  56  51]
>   [ 85  90  83]]
> 
>  [[ 31  36  49]
>   [ 34  39  52]
>   [ 35  40  53]
>   ...
>   [ 31  33  26]
>   [ 48  50  43]
>   [ 87  90  80]]
> 
>  ...
> 
>  [[ 80 103 116]
>   [ 80 103 116]
>   [ 80 103 116]
>   ...
>   [ 76  74  88]
>   [ 63  61  75]
>   [ 50  48  62]]
> 
>  [[ 80 103 116]
>   [ 80 103 116]
>   [ 80 103 116]
>   ...
>   [ 70  68  82]
>   [ 58  56  70]
>   [ 45  43  57]]
> 
>  [[ 80 103 116]
>   [ 80 103 116]
>   [ 80 103 116]
>   ...
>   [ 78  76  90]
>   [ 66  64  78]
>   [ 54  51  68]]]
> shape of image: (256, 256, 3)
> <class 'RuntimeError'> The input blob size is not equal to the network input size: got 393216 expecting 196608 <traceback object at 0x0000018B91CBCA80>
> ```

the model's input shape should be [-1, 3, 256, 256], but not [-1,3,256,256]. did you try to reshape it?

**Comment by akashAD98** [comment]
i solve it by passing it to list , instead of 
`` faces_im = torch.stack(faces_im)```
i directly return faces_im


after that i got this error


```
 File "D:\openVINO\openvino_env\lib\site-packages\openvino\runtime\ie_api.py", line 152, in infer
    return super().infer(normalize_inputs(self, {index: input for index, input in enumerate(inputs)}))
  File "D:\openVINO\openvino_env\lib\site-packages\openvino\runtime\ie_api.py", line 109, in normalize_inputs
    raise TypeError(f"Incompatible input data of type {type(value)} under {key} key!")
TypeError: Incompatible input data of type <class 'list'> under 0 key!


```

**Comment by akashAD98** [comment]
if i directly pass shape here im getting
```
new_shape = PartialShape([-1, 3, 256, 256])
```
```
  File "D:\openVINO\working_code_deep_sort\ORI_MA\DeepSORT_Object-master\deep_sort\deep_sort_object.py", line 26, in __init__
    self.extractor = ModelExtractor(reid_model_path,-1)
  File "D:\openVINO\working_code_deep_sort\ORI_MA\DeepSORT_Object-master\deep_sort\deep\extractor.py", line 221, in __init__
    self.input_shape = self.input_layer.shape
ValueError: get_shape was called on a descriptor::Tensor with dynamic shape
```


should i directly pass

**Comment by OpenVINO-dev-contest** [comment]
```self.extractor = ModelExtractor(reid_model_path,-1)``` can solve your issue on arbitrary batch size.

**Comment by akashAD98** [comment]
yes im already doing it, can see my above code?
is it a batch size problem or a stacking problem or anything else problem

**Comment by OpenVINO-dev-contest** [comment]
<class 'RuntimeError'> The input blob size is not equal to the network input size: got 393216 expecting 196608 <traceback object at 0x0000018B91CBCA80>
Is it solved ?

**Comment by akashAD98** [comment]
no I'm getting that issue only, after few frames of detection it is stopping, i guess in one frame if there are two person then its throwing this error, maybe im wrong I dont know what's the solution.

if two detections are there ,is it correct way to use stack?

**Comment by OpenVINO-dev-contest** [comment]
```
def batch_preprocess(img_crops, height, width):
    """
    Preprocess batched images
    
    Parameters
    ----------
    img_crops: batched input images
    height: height of model input data
    width: width of model input data
    """
    img_batch = np.concatenate([
        preprocess(img, height, width)
        for img in img_crops
    ], axis=0)
    return img_batch
```
This is the function I used in this notebook to handle detection's outputs. it will concat multiple objects into one. the batchsize of new object depends on the number of people in single frame.

**Comment by akashAD98** [comment]
yes but this is i did in object detection code part, its possible to edit get_features() code , what exactly i need to do

**Comment by OpenVINO-dev-contest** [comment]
Could you show me the line of code where the error happened ? and also the codes near it?  thanks

**Comment by akashAD98** [comment]
my shared code works fine for other.xml file but not for this person.xml file can I share all code? drop your mail id
```
  [ 78  76  90]
  [ 66  64  78]
  [ 54  51  68]]]
shape of image: (256, 256, 3)
<class 'RuntimeError'> The input blob size is not equal to the network input size: got 393216 expecting 196608 <traceback object at 0x0000025429E60640>
Traceback (most recent call last):
  File "main_face.py", line 249, in <module>
    vdo_trk.run()
  File "main_face.py", line 119, in run
    outputs, yt, st = self.image_track(img0)        # (#ID, 5) x1,y1,x2,y2,id
  File "main_face.py", line 202, in image_track
    outputs = self.deepsort.update(bbox_xywh, confs,labels, im0)
  File "D:\openVINO\working_code_deep_sort\ORI_MA\DeepSORT_Object-master\deep_sort\deep_sort_object.py", line 46, in update
    features = self._get_features(bbox_xywh, ori_img)
  File "D:\openVINO\working_code_deep_sort\ORI_MA\DeepSORT_Object-master\deep_sort\deep_sort_object.py", line 146, in _get_features
    features = self.extractor(im_crops)
  File "D:\openVINO\working_code_deep_sort\ORI_MA\DeepSORT_Object-master\deep_sort\deep\extractor.py", line 432, in __call__
    output = self.compiled_model([img_batch])[self.output_layer_ir]
  File "D:\openVINO\openvino_env\lib\site-packages\openvino\runtime\ie_api.py", line 273, in __call__
    return self.infer_new_request(inputs)
  File "D:\openVINO\openvino_env\lib\site-packages\openvino\runtime\ie_api.py", line 266, in infer_new_request
    return self.create_infer_request().infer(inputs)
  File "D:\openVINO\openvino_env\lib\site-packages\openvino\runtime\ie_api.py", line 152, in infer
    return super().infer(normalize_inputs(self, {index: input for index, input in enumerate(inputs)}))```

**Comment by akashAD98** [comment]
```
def preprocess(self, face):
        """
        Preprocess a single face image   
        Parameters
        ----------
        face: input face image
        """
        resized_image = cv2.resize(face, (self.width, self.height))
        resized_image = resized_image.transpose((2, 0, 1))
        input_image = np.expand_dims(resized_image, axis=0).astype(np.float32)
        return input_image

    def batch_preprocess_akash(self, img_crops):
        """
        Preprocess batched face images
        
        Parameters
        ----------
        img_crops: batched input face images
        """
        img_batch = np.concatenate([
            self.preprocess(face)
            for face in img_crops
        ], axis=0)
        return img_batch
```

my old code:

```

    def get_features_Akash_working(self, im_crops): 
        faces_im = []
        c=0
        for face in im_crops:
            c=c+1
            print("count face",c)
            print("face",face)
          
            #if face.shape != (self.height, self.width, 3):
            #    raise ValueError(f"Input image shape {face.shape} does not match expected shape {(self.height, self.width, 3)}")
            face = cv2.resize(face, (self.height, self.width), interpolation=cv2.INTER_AREA)  # (h, w, 3)
            assert face.shape == (self.height, self.width, 3), f"Input image shape {face.shape} does not match expected shape {(self.height, self.width, 3)}"
            print("shape of image:",face.shape)
            #print("shape of face is ",face.shape())
            face = face.transpose(2, 0, 1)                  # (3, H, W)
            face = torch.from_numpy(np.float32(face))
            face = (face - 127.5) / 128.0
            faces_im.append(face)

        #faces_im = torch.stack(faces_im, dim=0).unsqueeze(0)
        #faces_im =faces_im.append(face)
        # torch.stack(faces_im)

        faces_im = torch.stack(faces_im)

        return faces_im

```


also tried this code as per repo still same error, i think there is problem with normaliser?

**Comment by OpenVINO-dev-contest** [comment]
I think you have hard coded the batch size as 1 at here.
```
        for layer in self.model.inputs:
            input_shape = layer.partial_shape
            input_shape[0] = batchsize
            self.model.reshape({layer: input_shape})
```

**Comment by akashAD98** [comment]
can you tell me what lines should i need to replace with what? thanks a lot for your quick reply

**Comment by OpenVINO-dev-contest** [comment]
Manually set the batchsize as -1 when create a new object:  
```
def __init__(self, model_path,img_size=160, batchsize=1, device="AUTO"):
````

**Comment by akashAD98** [comment]
for batchsize=-1 getting error

```
    def __init__(self, model_path,img_size=160, batchsize=-1, device="AUTO"):
        """
        Initialize the model object
        
        Parameters
        ----------
        model_path: path of inference model
        batchsize: batch size of input data
        device: device used to run inference
        """
        self.img_size = img_size
        
        self.model = ie_core.read_model(model=model_path)
        self.input_layer = self.model.input(0)
        self.input_shape = self.input_layer.shape
        self.height = self.input_shape[2]
        self.width = self.input_shape[3]
        print("Orignal_model_shape",self.input_layer.shape)


        new_shape = PartialShape([1, 3, 256, 256])
        self.model.reshape({self.input_layer.any_name: new_shape})
        #self.height = self.input_shape[2]
        #self.width = self.input_shape[3]
        self.input_layer = self.model.input(0)
        self.input_shape = self.input_layer.shape
        self.height = self.input_shape[2]
        self.width = self.input_shape[3]

        print("~~~~ RESHAPED MODEL ~~~~")
        print("after resuze input shape",self.input_layer.shape)
        print("after resize height",self.input_shape[2])
        print("after resize width",self.input_shape[3])
  
        for layer in self.model.inputs:
            input_shape = layer.partial_shape
            input_shape[0] = batchsize
            self.model.reshape({layer: input_shape})
        self.compiled_model = ie_core.compile_model(model=self.model, device_name=device)
        print(f"compiled_model input shape: "
            f"{self.compiled_model.input(index=0).shape}"
        )
        self.output_layer = self.compiled_model.output(0)
        print(f"compiled_model output shape: {self.output_layer.shape}")

```

```
 File "D:\openVINO\working_code_deep_sort\ORI_MA\DeepSORT_Object-master\deep_sort\deep_sort_object.py", line 26, in __init__
    self.extractor = ModelExtractor(reid_model_path,-1)
  File "D:\openVINO\working_code_deep_sort\ORI_MA\DeepSORT_Object-master\deep_sort\deep\extractor.py", line 235, in __init__
    print(f"compiled_model input shape: "
ValueError: get_shape was called on a descriptor::Tensor with dynamic shape
```

**Comment by akashAD98** [comment]
also commenting this lines will not have any impact on code

```
        # for layer in self.model.inputs:
        #     input_shape = layer.partial_shape
        #     input_shape[0] = batchsize
        #     self.model.reshape({layer: input_shape})
```

**Comment by OpenVINO-dev-contest** [comment]
Do not use get shape method on a dynamic shape model, just delete it will be OK

**Comment by akashAD98** [comment]
> also commenting this lines will not have any impact on code
> 
> ```
>         # for layer in self.model.inputs:
>         #     input_shape = layer.partial_shape
>         #     input_shape[0] = batchsize
>         #     self.model.reshape({layer: input_shape})
> ```

its correct,i deleted it, still got same error
```
    return super().infer(normalize_inputs(self, {index: input for index, input in enumerate(inputs)}))
RuntimeError: The input blob size is not equal to the network input size: got 393216 expecting 196608
```

**Comment by akashAD98** [comment]
> Do not use get shape method on a dynamic shape model, just delete it will be OK

which lines i need to delet?

**Comment by akashAD98** [comment]
https://github.com/openvinotoolkit/openvino_notebooks/issues/863 is there any update on this ?
@eaidova @OpenVINO-dev-contest can you please help me to solve this issue?

**Comment by OpenVINO-dev-contest** [comment]
if you get issue like "RuntimeError: The input blob size is not equal to the network input size: got 393216 expecting 196608“， pls set the batch size to -1 ``` def __init__(self, model_path,img_size=160, batchsize=-1, device="AUTO"):```
if you get issue like "ValueError: get_shape was called on a descriptor::Tensor with dynamic shape", pls delete the line of 
```
print(f"compiled_model input shape: "
            f"{self.compiled_model.input(index=0).shape}"
        )
```

**Comment by akashAD98** [comment]
im already doing it , now i got this error @OpenVINO-dev-contest , its batch size error i know,but don't konw how to resolve

im able to track 1st id 
<img width="292" alt="image" src="https://user-images.githubusercontent.com/62583018/221770249-5960d44d-983f-4a2a-974c-0df32c513ffa.png">

then getting this error
```
    distances = _cosine_distance(x, y)
  File "D:\openVINO\working_code_deep_sort\ORI_MA\DeepSORT_Object-master\deep_sort\sort\nn_matching.py", line 52, in _cosine_distance
    return 1. - np.dot(a, b.T)
  File "<__array_function__ internals>", line 180, in dot
ValueError: shapes (1,3,256,256) and (256,256,3,2) not aligned: 256 (dim 3) != 3 (dim 2)

```

**Comment by akashAD98** [comment]
her is my code
```
    def get_features(self, face):
        faces_im = []
        for f in face:
            f = cv2.resize(np.array(f, dtype=np.uint8), (self.width, self.height), interpolation=cv2.INTER_AREA)  # (h, w, 3)
            assert f.shape == (self.height, self.width, 3), f"Input image shape {f.shape} does not match expected shape {(self.height, self.width, 3)}"
            f = f.transpose(2, 0, 1)                  # (3, H, W)
            f = np.float32(f) / 255                   # convert to float and scale to [0, 1]
            f = (f - 127.5) / 128                      # normalize the image
            f = torch.from_numpy(f)
            faces_im.append(f)
        faces_im = torch.stack(faces_im)
        return faces_im
```
```
    def __call__(self, im_crops):
        img_batch = self.get_features(im_crops)
        output = self.compiled_model([img_batch])[self.output_layer_ir]
        return output
```

**Comment by OpenVINO-dev-contest** [comment]
Hi @akashAD98 the error message is obvious which is caused by incorrect data format, and you should be able to solve it by yourself. Please try on it.

**Comment by akashAD98** [comment]
yes @OpenVINO-dev-contest i know this is a data shape error, i m not able to solve it so just give me suggestions, should i need to check which part of code? i was trying to pass single image at one time & doing for loop on it, still not able to solve it.

**Comment by OpenVINO-dev-contest** [comment]
The inputs of ```cosine_distance(x, y) ``` function should be the output vector of REID model, but I guess you sent a numpy image directly to it ?

**Comment by akashAD98** [comment]
yes i did it

**Comment by akashAD98** [comment]
deep_sort/nn_matching.py also not using torchid,

**Comment by akashAD98** [comment]
i loaded person-reid.xml (tracking extractor) & yolov7 object detector
in few cases model is doing detections but ids are changing very fastly, how can i solve this issue

**Comment by OpenVINO-dev-contest** [comment]
> i loaded person-reid.xml (tracking extractor) & yolov7 object detector in few cases model is doing detections but ids are changing very fastly, how can i solve this issue

Hi what do you mean " changing very fastly". Does it happen when you play with the default notebook ?

**Comment by akashAD98** [comment]
not with default but with person redid.xml & yolov7_custommodel.xml

may I know if this person's reid weight will work for all categories? like my objects are shirts, pants, earrings, and lipsticks, I want to track them
which is a good tracker .xml for this case?
1) this person reid tracker will work in my all cases, i have objects of different categories apart from person & vehicle
2) adding a tracker on top of object detection will improve accuracy? it will make less false detection
3)which is faster object detection vs object tracker

**Comment by OpenVINO-dev-contest** [comment]
the default person's reid weight in this notebook will not work other categories.
1. You can filter out the the object you wish to track from detection output, and add the reid models for different categories. Besides DEEPSORT, i know some trackers can track the object without reid model, and the performance of it could be better, but the accuracy may drop.
2. A tracker can work without object detection, but you have to identify the pose of each object firstly. 
3. You should consider your project requirement, then decide which one to implement. they are for different scenarios

**Comment by akashAD98** [comment]
@OpenVINO-dev-contest thanks a lot, is cross-domain reid.xml weight available ?
https://kaiyangzhou.github.io/deep-person-reid/MODEL_ZOO , may i know which weights openvino support?

**Comment by akashAD98** [comment]
@OpenVINO-dev-contest also im able to get tracking results, but its automatically stopping video prediction & video gets stopped? may i know what are the reasons behind it?

other model is doing predictions fine for long videos, but this is falling

**Comment by akashAD98** [comment]
i stared testing with different videos & i got this, code is not working now :/
@OpenVINO-dev-contest

 ``` File "D:\openVINO\openvino_env\lib\site-packages\openvino\runtime\ie_api.py", line 100, in normalize_inputs
    update_tensor(value, request, key)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\functools.py", line 874, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "D:\openVINO\openvino_env\lib\site-packages\openvino\runtime\ie_api.py", line 65, in _
    tensor.shape = inputs.shape
RuntimeError: Dims and format are inconsistent.

```

**Comment by akashAD98** [comment]
no i havnt changed anything, i was just changed reid weight, then i switched backed to my petson-reid.xml weight & i got this error

**Comment by OpenVINO-dev-contest** [comment]
Did you rerun the whole notebook again after switching to default model ?

**Comment by akashAD98** [comment]
no i just runed my main_file.py

**Comment by OpenVINO-dev-contest** [comment]
> no i havnt changed anything, i was just changed reid weight, then i switched backed to my person-reid.xml weight & i got this error, i dont know seriouly whats wrong here? :/, can I share my code? can you help me to figure it out??

Sure, you can share all your code here, but I suppose to review it when I have spare time.

**Comment by akashAD98** [comment]
can you drop you mail

**Comment by OpenVINO-dev-contest** [comment]
ethan.yang@intel.com, but i suggest you can share it through your github repo, then people in this group can see it and help you as well.

**Comment by akashAD98** [comment]
sure ill do that,

**Comment by akashAD98** [comment]
```
    return super().infer(normalize_inputs(self, {index: input for index, input in enumerate(inputs)}))
RuntimeError: Can't set input blob with name: data, because model input (shape=[1,3,256,128]) and blob (shape=(1.3.128.256)) are incompatible

The orignal shape of reid model is 
(Orignal_model_shape [1,3,256,128]), it has no fix width & height ,so i was doing reshape on top of it & it was working yestarday, again i got this error & issue 

```
again i started debugging to solve tensor mismatch error, & i got this error,

**Comment by akashAD98** [comment]
same error im getting :/ @eaidova @OpenVINO-dev-contest 


after conversion model & input image shape intpo same format

```
    return self.create_infer_request().infer(inputs)
  File "D:\openVINO\openvino_env\lib\site-packages\openvino\runtime\ie_api.py", line 152, in infer
    return super().infer(normalize_inputs(self, {index: input for index, input in enumerate(inputs)}))
RuntimeError: The input blob size is not equal to the network input size: got 393216 expecting 196608
```

**Comment by akashAD98** [comment]
@OpenVINO-dev-contest any suggestions for this?

**Comment by akashAD98** [comment]
moedl loading code

```
from openvino.runtime import Core, PartialShape
ie_core = Core()
class ModelExtractor(object):
    """
    This class represents a OpenVINO model object.

    """
    def __init__(self,img_size=128, batchsize=-1, device="AUTO",use_cuda=False):
        """
        Initialize the model object
        
        Parameters
        ----------
        model_path: path of inference model
        batchsize: batch size of input data
        device: device used to run inference
        """
        model_path=r'D:\openVINO\working_code_deep_sort\ORI_MA\DeepSORT_Object-master\model_weight\fp16\person-reidentification-retail-0287.xml'
        ie_core = Core()
    
        self.img_size = img_size
        
        self.model = ie_core.read_model(model=model_path)
        self.input_layer = self.model.input(0)
        self.input_shape = self.input_layer.shape
        self.height = self.input_shape[2]
        self.width = self.input_shape[3]
        print("Orignal_model_shape",self.input_layer.shape)


        new_shape = PartialShape([1, 3, 256, 256])
        self.model.reshape({self.input_layer.any_name: new_shape})
        #self.height = self.input_shape[2]
        #self.width = self.input_shape[3]
        self.input_layer = self.model.input(0)
        self.input_shape = self.input_layer.shape
        self.height = self.input_shape[2]
        self.width = self.input_shape[3]

        print("~~~~ RESHAPED MODEL ~~~~")
        print("after resize input shape",self.input_layer.shape)
        print("after resize height",self.input_shape[2])
        print("after resize width",self.input_shape[3])
  
        # for layer in self.model.inputs:
        #     input_shape = layer.partial_shape
        #     input_shape[0] = batchsize
        #     self.model.reshape({layer: input_shape})

        self.compiled_model = ie_core.compile_model(model=self.model, device_name=device)
        print(f"compiled_model input shape: "
            f"{self.compiled_model.input(index=0).shape}"
        )
        self.output_layer = self.compiled_model.output(0)
        print(f"compiled_model output shape: {self.output_layer.shape}")



    def get_features_single(self, face):
        faces_im = []
        for f in face:
            f = cv2.resize(f, (self.width, self.height), interpolation=cv2.INTER_AREA)  # (h, w, 3)
            #assert f.shape == (self.height, self.width, 3), f"Input image shape {f.shape} does not match expected shape {(self.height, self.width, 3)}"
            f = f.transpose(2, 0, 1)                  # (3, H, W)
            f = np.float32(f) / 255                   # convert to float and scale to [0, 1]
            f = (f - 127.5) / 128                      # normalize the image
            f = torch.from_numpy(f)
            faces_im.append(f)
        faces_im = torch.stack(faces_im)
        return faces_im

    def get_features(self, im_crops):
        features = []
        for face in im_crops:
            feature = self.get_features_single([face])
            features.append(feature)
        features = torch.cat(features, dim=0)
        return features

    def __call__(self, im_crops):

        img_batch = self.get_features(im_crops)   
	output = self.compiled_model([img_batch])[self.output_layer]
        return output

```

**Comment by akashAD98** [comment]
i solve this issue finalyy

**Comment by akashAD98** [comment]
<img width="627" alt="image" src="https://user-images.githubusercontent.com/62583018/222371853-80ecd229-9023-4079-8f31-ac350377671c.png">

**Comment by OpenVINO-dev-contest** [comment]
> @eaidova @OpenVINO-dev-contest if its a single object its tracking it, for multiple object the ids & labels are not correct, may i know how should i solve it?
> 
> my detector is working correct
> 
> <img alt="image" width="627" src="https://user-images.githubusercontent.com/62583018/222371853-80ecd229-9023-4079-8f31-ac350377671c.png">
> 
> <img alt="image" width="404" src="https://user-images.githubusercontent.com/62583018/222372109-e9fa5805-0c7b-4396-92b0-06b5e22995e3.png">
> 
> <img alt="image" width="625" src="https://user-images.githubusercontent.com/62583018/222372643-2fbce289-c402-47ab-b272-92e52fe2104e.png">

I think you can create more than one ```Tracker``` object, for example one tracker for person, and another for cat.
```
tracker = Tracker(
    metric,
    max_iou_distance=0.7,
    max_age=70,
    n_init=3
)
```

**Comment by akashAD98** [comment]
ohkay,how can i solve this?

**Comment by OpenVINO-dev-contest** [comment]
> ohkay,how can i solve this?

Please try to understand the the notebook codes firstly, then you will the answer.

**Comment by akashAD98** [comment]
okay let me try

**Comment by akashAD98** [comment]
@OpenVINO-dev-contest my tracker.py code is exactly same like deepsort object detection, still i havnt understood ,how should i create multiple tracker, cn you just give me hint or reference? thanks

**Comment by akashAD98** [comment]
i dont have any person class in it, i have 30 different classes like ring,watch,dress,shoes etc,
so should i need to create tracker for each class ? sorry im not understanding exactly so asking this quetion

**Comment by OpenVINO-dev-contest** [comment]
Yes probably you need to in this case, and you also have to prepare 30 reid models for different stuff.

**Comment by akashAD98** [comment]
okay let me try,Ohh okay, you don't think it's expensive? or its just normal,
is there any alternative for this

**Comment by akashAD98** [comment]
@OpenVINO-dev-contest  https://github.com/akashAD98/yolov7_vino_with_object_tracking/blob/50c88ef7ca479b60120beaec8a5ef982f3cebd59/deep_sort/deep_sort_object.py#L96 

is this correct approch?

**Comment by akashAD98** [comment]
Yes its real use case , this is useful for avoiding false detection & also we don’t want to skip any frames while it’s running on testing environment. Sometimes what happens when we are detecting few frames are model not able to detect, we want to detect all. 

Also lets say we detected shoes in one frame & agiin it’s saying different prediction, so using tracking we can avoid it & many more usecase

**Comment by akashAD98** [comment]
> @OpenVINO-dev-contest @eaidova https://github.com/akashAD98/yolov7_vino_with_object_tracking/blob/50c88ef7ca479b60120beaec8a5ef982f3cebd59/deep_sort/deep_sort_object.py#L96
> 
> is this correct approch?, im getting errors,but atleast want to know mt approch is correct or not
> 
> also im directly using strongsort -tracker.py file ,where they are also doing multiclass detection, then why i need to do like this here? can you help me here

@eaidova @OpenVINO-dev-contest any update on this?

**Comment by OpenVINO-dev-contest** [comment]
Sorry @akashAD98 since I never received a project requirement for multiclass tracking before, actually i dont have much experience on it, and the only suggestions I can provide is based on my personal understanding. But if you can find another latest tracker repository which do multiclass tracking, it will be more helpful to your project than my suggestion I believe.

> Yes its real use case , this is useful for avoiding false detection & also we don’t want to skip any frames while it’s running on testing environment. Sometimes what happens when we are detecting few frames are model not able to detect, we want to detect all. Using tracking we can solve this issue
> 
> Also lets say we detected shoes in one frame & agiin it’s saying different prediction, so using tracking we can avoid it & many more usecase

For this purpose, I believe you should use another tracker (not deepsort) without REID model, which may track the object based on its motions and IOU, without the appearance identity. in this case you only need to create one general Tracker, and  it will improve the performance of your project.

**Comment by akashAD98** [comment]
is there any tracker available which is supported by openvino? or any other tracker suggestions?

**Comment by eaidova** [comment]
@akashAD98 @OpenVINO-dev-contest  Sorry for interrupting a fascinating discussion, but I think it is not moving in the right direction... This repository for openvino notebooks examples and our aim is to give people advice regarding the usage our API, not providing full guide how to write own application for desired use cases for arbitrary models. Probably, @akashAD98, you need to investigate and explore your target application architecture yourself with your team (you will not give us part of your salary that we do your job instead of you, right? :))

**Comment by akashAD98** [comment]
Thank you for taking the time to respond. While I acknowledge that it is our team's responsibility to investigate and explore our target application architecture, I was hoping to seek some guidance or insights from the community here. Nevertheless, I appreciate your input and value your time. Have a great day. @eaidova  anyways i thouth you guys also provide support for openvino different models but now i understood.its only for using api & nothing else, so we can do customization more woth openvino

**Comment by eaidova** [comment]
@akashAD98 thank you for sharing your feedback, we are trying to be useful in many areas and provide a good variety of supported use cases, but unfortunately, we can not be experts in all areas at the same time... Maybe you need to search support in different sources, because your questions are very general and not related to openvio itself, I mean even if you use another framework, you still will have the same issues. I'm very glad that you have interest to our project and hope your all the best with trying to find the right solution for your issue

**Comment by akashAD98** [comment]
@eaidova @OpenVINO-dev-contest I would like to express my feedback regarding our previous conversation. I felt that the comment 'you will not give us part of your salary that we do your job instead of you, right?' was inappropriate and unprofessional. As a user of your repository and the Redi.xml weight, I understand that you are responsible for maintaining the repository and providing guidance and suggestions. I appreciate your help in this matter and have followed your advice to the best of my ability. However, I believe that it is important to maintain a professional tone in our interactions, and comments like the one mentioned above are not constructive. Thank you for your understanding."

**Comment by akashAD98** [comment]
I appreciate your assistance in troubleshooting the issue I was experiencing with the OpenVINO framework. While I am aware that there are alternative solutions available, I was specifically interested in exploring the use of the personid.xml file and any potential related issues with OpenVINO. Thank you for taking the time to address my questions and provide guidance. I would also like to extend my thanks to the @OpenVINO-dev-contest  for their valuable support

**Comment by OpenVINO-dev-contest** [comment]
There is a implementation with PaddlePaddle can track object without REID model. You can try it.
https://github.com/openvinotoolkit/openvino_notebooks/pull/801
Please understand we all have some project tasks to finish, and we can't answer your every question on time. For some general problem, you should be able to solve it by sourcing the solution on internet. OpenVINO can be used to deploy any deep learning model, but the logic or process out of the model inference should be designed by yourself.

**Comment by akashAD98** [comment]
yes i know that,im have build logic myself only you know it right,
this issue is regarding only openvino.reid weight , bcz for other weights im not getting that error, thats why im asking this quetion its normal or thats issue of openvino model.Thnaks for support & all the best for openvino projects

**Comment by aiakash** [comment]
@eaidova @OpenVINO-dev-contest i have done sucesfully implementation of yolov7_custom.xml & deepsort reid.xml 
Thank you so much for your guidance & your amazing work  also :)

**Comment by akashAD98** [comment]
@eaidova @OpenVINO-dev-contest i have solved this issue,now successfully implemented yolov7int8.xml tracker with deepsort reid.xml .Thanks for your support & amazing work.
in further if you want to add other tracker support let me know, also if you want me to publish my code here for community let me know thanks
