### ISSUE TITLE
There was a problem quantifying models in the new version of yolov8

### ISSUE THREAD

**Issue by SiChuanJay** [openvinotoolkit/openvino_notebooks#855]
**Describe the bug**
A clear and concise description of what the bug is, including steps to reproduce the bug if possible.

 **Expected behavior**

**Screenshots**

 **Installation instructions (Please mark the checkbox)**
[  ] I followed the installation guide at https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide to install the notebooks. 

** Environment information **
Please run `python check_install.py` in the _openvino_notebooks_ directory. If the output is _NOT OK_ for any of the checks, please follow the instructions to fix that. If that does not work, or if you still encounter the issue, please paste the output of check_install.py here.
 
**Additional context**

Hello, thanks for your contribution! I am implementing an example provided by openvino( https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/230-yolov8-optimization/230-yolov8-optimization.ipynb ), which was successfully implemented when I used version 8.0.5. But when I used the latest version, I got the following error.
![图片](https://user-images.githubusercontent.com/52130681/220487575-d65465c5-b14c-44d6-91fb-d5d2c2c532cd.png)
![图片](https://user-images.githubusercontent.com/52130681/220487590-6a446554-36d4-4bb1-8a83-e13d09fe0053.png)

I checked that the det_validator is of the same type in both versions, but the newer version will report an error when calling get_dataloader(), while the older version will not. Please, thank you!

**Comment by eaidova** [comment]
@SiChuanJay thank you for reporting. yolov8 project is developed rapidly without preserving compatibility between versions.
I prepare update for notebook which work on the latest available version:
https://github.com/openvinotoolkit/openvino_notebooks/pull/859
