### ISSUE TITLE
About the installation of openvino：

### ISSUE THREAD

**Issue by Lexiaotian** [openvinotoolkit/openvino_notebooks#857]
I want to ask how to solve the problem that when the latest version of openvino is installed in pip, from openvino.runtime import model will report errors in the model!

**Comment by eaidova** [comment]
@Lexiaotian could you please provide more details? Which model do you try? Do you have logs for error?

**Comment by Lexiaotian** [comment]
230-yolov8-optimization [10]
from openvino.runtime import Core, Model

core = Core()
det_ov_model = core.read_model(det_model_path)
device = "CPU"  # "GPU"
if device != "CPU":
    det_ov_model.reshape({0: [1, 3, 640, 640]})
det_compiled_model = core.compile_model(det_ov_model, device)


def detect(image:np.ndarray, model:Model):
    """
    OpenVINO YOLOv8 model inference function. Preprocess image, runs model inference and postprocess results using NMS.
    Parameters:
        image (np.ndarray): input image.
        model (Model): OpenVINO compiled model.
    Returns:
        detections (np.ndarray): detected boxes in format [x1, y1, x2, y2, score, label]
    """
    num_outputs = len(model.outputs)
    preprocessed_image = preprocess_image(image)
    input_tensor = image_to_tensor(preprocessed_image)
    result = model(input_tensor)
    boxes = result[model.output(0)]
    masks = None
    if num_outputs > 1:
        masks = result[model.output(1)]
    input_hw = input_tensor.shape[2:]
    detections = postprocess(pred_boxes=boxes, input_hw=input_hw, orig_img=image, pred_masks=masks)
    return detections


input_image = np.array(Image.open(IMAGE_PATH))
detections = detect(input_image, det_compiled_model)[0]
image_with_boxes = draw_results(detections, input_image, label_map)

Image.fromarray(image_with_boxes)

from openvino.runtime import Core, Model！   
Model is always marked red！

**Comment by Lexiaotian** [comment]
Is this an error in the openvino installation？

**Comment by eaidova** [comment]
@Lexiaotian just for clarification, it is marked red in code editor? Do you tried to run code? Does it gives some errors?

Red mark can be connected with impossibility to inspect module in code editor. OpenVINO written on C++ and has bindings for python, so this class defined inside C++ modules and can be not visible for static code analizers, but available during running code.

**Comment by eaidova** [comment]
@Lexiaotian do you solved your issue?
