### ISSUE TITLE
Example how to write out video with inference

### ISSUE THREAD

**Issue by mulderp** [openvinotoolkit/openvino_notebooks#861]
Hello,
I am having difficulties in writing out a video that was generated with the example in:

https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/402-pose-estimation-webcam

```
video_file = "[https://github.com/intel-iot-devkit/sample-videos/blob/master/store-aisle-detection.mp4?raw=true"](https://github.com/intel-iot-devkit/sample-videos/blob/master/store-aisle-detection.mp4?raw=true%22)

run_pose_estimation(video_file, flip=False, use_popup=False, skip_first_frames=500)
```

It might be related to the frame rate and/or frame size.
Do you have an example how to write out a video file that was generated like above?

Thanks for your help!

**Comment by brmarkus** [comment]
Inside of the referenced notebook I did the following, inside "def run_pose_estimation()":

`myout = cv2.VideoWriter( 'output.avi', cv2.VideoWriter_fourcc('M', 'J', 'P', 'G'), 59.940, (720,404) )`

Then feeding the (raw) `frame` (decoded input with overlayed pose-skeleton, plus Inference time) into the writer (before encoding to JPG):

`myout.write( frame )`

And then, finally, to get the written video-file "flushed" to the file-system, release the video-writer:

`myout.release()`

However, this resulted in a zero-byte file `output.avi` for me, when running under MS-Win, within a Python virtual-env and Jupyter in the browser...

I just have not placed `myout.release()` to the correct place, where the method finishes and returns gracefully (and doesn't react properly on keyboard-input like the given ESC-key escape).

I.e. make sure to get the video-writer released (considering exception, considering error-handling, considering end-of-video-file).

**Comment by mulderp** [comment]
Thanks, this works indeed on the demo video.
When I apply the function to my custom video I still get an empty video.
The details from mediainfo for the result looks like this

```

Video
ID                                       : 0
Format                                   : JPEG
Codec ID                                 : MJPG
Width                                    : 720 pixels
Height                                   : 404 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 59.940 (60000/1001) FPS
Color space                              : YUV
Compression mode                         : Lossy
```

But the input video has this format:

```
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 2 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 2 frames
Format settings, GOP                     : M=1, N=25
Muxing mode                              : Container profile=Baseline@3.0
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 1 min 1 s
Bit rate mode                            : Variable
Bit rate                                 : 7 716 kb/s
Maximum bit rate                         : 12.0 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Standard                                 : Component
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.149
Stream size                              : 56.4 MiB (97%)
Language                                 : English
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Codec configuration box                  : avcC
```

The frames with inference are shown as expected. But then something must go wrong either in flushing or somewhere else.
Maybe I need to wait longer as the video has higher resolution.

**Comment by adrianboguszewski** [comment]
@mulderp, the example on how to write a video is in [201-vision-monodepth](https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/201-vision-monodepth/201-vision-monodepth.ipynb)
