### ISSUE TITLE
The input blob size is not equal to the network input size: got 153600 expecting 98304

### ISSUE THREAD

**Issue by aiakash** [openvinotoolkit/openvino_notebooks#863]
im trying to load person_reid.xml weight & getting this error
im passing extractor to my yolov7 detector & getting this error

```
  File "D:\openVINO\openvino_env\lib\site-packages\openvino\runtime\ie_api.py", line 273, in __call__
    return self.infer_new_request(inputs)
  File "D:\openVINO\openvino_env\lib\site-packages\openvino\runtime\ie_api.py", line 266, in infer_new_request
    return self.create_infer_request().infer(inputs)
  File "D:\openVINO\openvino_env\lib\site-packages\openvino\runtime\ie_api.py", line 152, in infer
    return super().infer(normalize_inputs(self, {index: input for index, input in enumerate(inputs)}))
RuntimeError: The input blob size is not equal to the network input size: got 153600 expecting 98304

```

how should i solve this error

**Comment by eaidova** [comment]
@aiakash Usually this error means that your provided data differs from the expected model input shape. Please check preprocessing code (it can be connected with the wrong size for resizing input data) and which input shape is expected by your model

**Comment by eaidova** [comment]
You also can find useful this notebook, it explains basic openvino API and provides information about how to obtain model input size and change it if it is required:
https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/002-openvino-api/002-openvino-api.ipynb

**Comment by akashAD98** [comment]
https://github.com/openvinotoolkit/openvino_notebooks/issues/854#issuecomment-1451327361
