### ISSUE TITLE
[GSoC] Unable to convert tensorflow model to openvino

### ISSUE THREAD

**Issue by adrianboguszewski** [openvinotoolkit/openvino_notebooks#869]
### Discussed in https://github.com/openvinotoolkit/openvino/discussions/16001

<div type='discussions-op-text'>

<sup>Originally posted by **m-gopichand** February 28, 2023</sup>
i have selected  [Coltran](https://github.com/google-research/google-research/tree/master/coltran) Unable to convert tensorflow model to openvino [Click](https://storage.cloud.google.com/gresearch/coltran/coltran.zip) to download dataset @eaidova @adrianboguszewski 

![Screenshot_20230228_073906](https://user-images.githubusercontent.com/80762088/221879182-57b70fd5-1367-4579-b238-fd3e83ea54d8.png)
</div>

**Comment by adrianboguszewski** [comment]
I transferred this discussion to the OV notebooks issue as it's related to the prerequisite task.

**Comment by adrianboguszewski** [comment]
@m-gopichand, please try to provide `--framework` parameter. Look here also: https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html#converting-tensorflow-2-models

**Comment by m-gopichand** [comment]
Tried , still not working   can we export ``` .data``` extension file  i have aslo used new ```--use_new_frontend``` feature but i am unable to find what's wrong ?? 

![Screenshot_20230301_092010](https://user-images.githubusercontent.com/80762088/222040682-01e2abc7-ceaf-42b3-aa58-2f65705b2e43.png)

**Comment by rkazants** [comment]
Hi @m-gopichand,

Please look at this documentation about how to convert `MetaGraph` format: https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html

Best regards,
Roman

**Comment by eaidova** [comment]
@m-gopichand probably it is required to convert model checkpoint to one of supported format. If it is difficult for you, I suggest to change task

**Comment by m-gopichand** [comment]
Hi @eaidova can you change my task to ```style-swapping```
