### ISSUE TITLE
[IWD]How to generate your AI painting with notebook

### ISSUE THREAD

**Issue by OpenVINO-dev-contest** [openvinotoolkit/openvino_notebooks#880]
- ###  [**System Requirements**](https://github.com/openvinotoolkit/openvino_notebooks#%EF%B8%8F-system-requirements)

- ###  [**Installation Guide**](https://github.com/openvinotoolkit/openvino_notebooks#-installation-guide)
- ### **Run ```225-stable-diffusion-text-to-image```**

Launch OpenVINO notebook in your web browser：

```
&cd notebooks
&jupyter lab notebooks
```
[**Step 1**]: double click the fold ```225-stable-diffusion-text-to-image``` in left column.
![image](https://user-images.githubusercontent.com/91237924/222656925-a159c18a-1beb-46ab-b251-739ef25126d4.png)

[**Step 2**], Select file ```225-stable-diffusion-text-to-image.ipynb``` in left column

[**Step 3**], Select the first code block of ```225-stable-diffusion-text-to-image.ipynb```

[**Step 4**], Keep clicking the Run button until we reach the code block in **step5**
![image](https://user-images.githubusercontent.com/91237924/222657079-1ce56f84-aeda-4f9e-a0ac-fc342a7f03a0.png)

[**Step 5**], Input your prompt sentence as the picture below, and it will help to customize your AI generated picture. Optionally, you can also change the random generator seed for latent state initialization and number of steps.
![image](https://user-images.githubusercontent.com/91237924/222683336-0f4b0320-5f48-47dd-bcaa-3499ae8f7db3.png)

[**Step 6**], Continue to run each code block until the customized picture generates. If the result needs to be updated, you can go back to **Step 5** to modify the prompt and repeat the **Step 6**.
![image](https://user-images.githubusercontent.com/91237924/222657304-817cb1e5-9a51-4543-b2a5-9a017e4387a5.png)

**You can also follow the instruction video below to generate your paintings:**

https://user-images.githubusercontent.com/91237924/223928007-ad30465c-d8ea-48d7-9f59-35509bb7902d.mp4

**Comment by raymondlo84** [comment]
Got my result! :) and here is how I get it. 
![image](https://user-images.githubusercontent.com/1720147/223581128-39d5b01c-f5a1-4571-8649-75fc511ae226.png)
![image](https://user-images.githubusercontent.com/1720147/223581136-15a39552-597f-45e8-b742-47d1c7f2964f.png)

**Comment by OpenVINO-dev-contest** [comment]
> Got my result! :) and here is how I get it! -- the result.png is actually in the folder. ![image](https://user-images.githubusercontent.com/1720147/223583021-54a0bfc4-8500-4b77-a807-e22d430b035f.png) ![image](https://user-images.githubusercontent.com/1720147/223581128-39d5b01c-f5a1-4571-8649-75fc511ae226.png) ![image](https://user-images.githubusercontent.com/1720147/223581136-15a39552-597f-45e8-b742-47d1c7f2964f.png)

Looks great, could you also post it on our submission pages, thanks https://github.com/openvinotoolkit/openvino_notebooks/discussions/879

**Comment by Lannndun** [comment]
I followed the steps but no image generated, just edit the text prompt and description.
![image](https://user-images.githubusercontent.com/99628887/223648743-b0210617-8612-4093-a2ce-c6473b432df3.png)

**Comment by OpenVINO-dev-contest** [comment]
> I followed the steps but no image generated, just edit the text prompt and description. ![image](https://user-images.githubusercontent.com/99628887/223648743-b0210617-8612-4093-a2ce-c6473b432df3.png)

Did you run each block? is there any error message coming out ?
If the block is run correctly, you can find a number tagged in the left as the examples picture shows, but I don't see it in your sreen shot.

**Comment by OpenVINO-dev-contest** [comment]
> > I followed the steps but no image generated, just edit the text prompt and description. ![image](https://user-images.githubusercontent.com/99628887/223648743-b0210617-8612-4093-a2ce-c6473b432df3.png)
> 
> Did you run each block? is there any error message coming out ? If the block is run correctly, you can find a number tagged in the left as the examples picture shows, but I don't see it in your screen shot.
