### ISSUE TITLE
[GSoc] Need review for my prerequisite task  Pytorch_Style_Swap

### ISSUE THREAD

**Issue by m-gopichand** [openvinotoolkit/openvino_notebooks#881]
Hi , Please check the notebook , Markdown coloum addition and refactoring the codel are pending i will update them .
[Download ](https://drive.google.com/file/d/19J9iFRa7H72I0yiTOigEtHKDNz1Xe7O9/view?usp=share_link) Notebook

**Comment by adrianboguszewski** [comment]
@m-gopichand, we don't accept notebooks to download. Creating PRs is an essential part of any GSoC project, and it's also required for the prerequisite task. All steps are listed here: https://github.com/openvinotoolkit/openvino/wiki/Google-Summer-Of-Code#prerequisite-task

**Comment by m-gopichand** [comment]
Sorry @adrianboguszewski i am new to Open Source , i will create a PR

**Comment by adrianboguszewski** [comment]
You can find some useful information here: https://medium.com/openvino-toolkit/how-to-contribute-to-an-ai-open-source-project-c741f48e009e

**Comment by m-gopichand** [comment]
Thankyou!
