### ISSUE TITLE
225 running issue

### ISSUE THREAD

**Issue by alberxualberxu** [openvinotoolkit/openvino_notebooks#885]
notebook environment was intalled one month before, met a issue as showed in snapshot below,

![image](https://user-images.githubusercontent.com/102842442/222946450-55b020ba-649f-40a1-bf88-579dfa4cc73f.png)

**Comment by OpenVINO-dev-contest** [comment]
Could you check the version of these library ?
```
diffusers[torch]>=0.9.0
huggingface-hub>=0.9.1
transformers>=4.21.1
```

**Comment by eaidova** [comment]
@alberxualberxu could you please provide info on which transformers library you have in your environment?
(you can find all library versions using `pip list` command)

**Comment by alberxualberxu** [comment]
![image](https://user-images.githubusercontent.com/102842442/224528955-a1f95c39-aee3-402c-92b2-6a6ff710a8ee.png)
diffusers is 0.14.0
huggingface hub is 0.11.1

**Comment by eaidova** [comment]
@alberxualberxu  it seems that requirements on transformers library in diffusers was updated. Please try to upgrade transformers  on 4.25.1 version

**Comment by alberxualberxu** [comment]
@eaidova should i update requirement file and then pip install to update transformers' version?

**Comment by alberxualberxu** [comment]
@eaidova update TF version to 4.25.1 and issue fixed, this open can be closed, thank you
