### ISSUE TITLE
example URL in 231 is block in PRC

### ISSUE THREAD

**Issue by OpenVINO-dev-contest** [openvinotoolkit/openvino_notebooks#887]
Could we switch the link to a local file, or a link in github ?

https://ichef.bbci.co.uk/news/976/cpsprodpb/3970/production/_108240741_beatles-abbeyroad-square-reuters-applecorps.jpg

<img width="847" alt="image" src="https://user-images.githubusercontent.com/91237924/223056715-bca16cd4-7b88-49f0-922d-17a8841c2723.png">

**Comment by andrei-kochin** [comment]
Internal ref CVS-105407
