### ISSUE TITLE
import cv2 on codespaces

### ISSUE THREAD

**Issue by fajemila** [openvinotoolkit/openvino_notebooks#892]
importing the cv2 throws
`ImportError: libGL.so.1: cannot open shared object file: No such file or directory`, 
when I started working on notebooks/201-vision-monodepth/201-vision-monodepth.ipynb
I was able to solve this by installing `opencv-python-headless`. Although I was using the GitHub codespace im not sure if that is the reason, so just wanted to report this. I followed the installation guide  [Ubuntu](https://github.com/openvinotoolkit/openvino_notebooks/wiki/Ubuntu)

**Comment by hbalasu1** [comment]
Hi @fajemila 

Is your issue resolved?

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and ask additional questions related to this topic.
