### ISSUE TITLE
Broken links in CONTRIBUTING.md

### ISSUE THREAD

**Issue by blaz-r** [openvinotoolkit/openvino_notebooks#899]
Hello,

while working on a prerequisite task for GSoC, I found some links in CONTRIBUTING.md file that don't work:

Section:
https://github.com/openvinotoolkit/openvino_notebooks/blob/main/CONTRIBUTING.md#jupyterlab-code-formatter
Link:
https://jupyterlab-code-formatter.readthedocs.io/en/latest/
I think that documentation was moved to:
https://ryantam626.github.io/jupyterlab_code_formatter/index.html

There is also a problem with the link to Binder which points to a part of repo that doesn't exist:
Section:
https://github.com/openvinotoolkit/openvino_notebooks/blob/main/CONTRIBUTING.md#getting-started
Link:
https://github.com/openvinotoolkit/openvino_notebooks/blob/main/Binder

**Comment by adrianboguszewski** [comment]
Great points. Could you please create a PR fixing these links?

**Comment by blaz-r** [comment]
Yes, I'll fix that and double check that others work as well.

**Comment by blaz-r** [comment]
Closing with #919
