### ISSUE TITLE
230-yolov8-optimization-benchmark

### ISSUE THREAD

**Issue by af-doom** [openvinotoolkit/openvino_notebooks#909]
After the YOLOv8 model is converted to openvino, is the input image size dynamic? When testing, the inference speed is related to the input image size

**Comment by eaidova** [comment]
@af-doom yes, we are export model with dynamic input shape, for benchmarking we are use `benchmark_app` which allow to specify target input size for benchmarking (by default we are use 640x640)

**Comment by af-doom** [comment]
> @af-doom yes, we are export model with dynamic input shape, for benchmarking we are using `benchmark_app` which allows to specify the target input size for benchmarking (by default we are using 640x640)
Thank you for your quick reply, but the detection time is related to the image size. How should I set the detection input to (640x640)

**Comment by eaidova** [comment]
Do you mean in benchmark app or here?

**Comment by eaidova** [comment]
inside notebook, benchmarking called by this comand:
```
benchmark_app -m $int8_model_det_path -d $device -api async -shape "[1,3,640,640]" -t 15
```
shape parameter declares input data shape for benchmarking,
more details about benchmark_app parameters can be found in [documentation](https://docs.openvino.ai/latest/openvino_inference_engine_tools_benchmark_tool_README.html)

**Comment by af-doom** [comment]
Sorry, no, it's openvino

**Comment by af-doom** [comment]
> Do you mean in benchmark app or here?
Sorry, no, it's openvino

**Comment by eaidova** [comment]
@af-doom  could you please provide more context, what you trying to run?
benchmark_app is openvino component, it is tool used for performance openvino model, so it is also run openvino.
Regarding just running inference using API, dynamic shapes mean that model accepts data of different input size, you need just provide data of shape what you need (resize image to specific size for example using preprocessing)

**Comment by af-doom** [comment]
> @af-doom could you please provide more context, what you trying to run?
> benchmark_app is openvino component, it is tool used for performance measurement of openvino model, so it is also run openvino.
> Regarding just running inference using API, dynamic shapes mean that model accepts data of different input size, you need just provide data of shape what you need (resize image to specific size for example using preprocessing)

Thank you very much for your reply
