### ISSUE TITLE
FP32 to INT8 conversion

### ISSUE THREAD

**Issue by swe-cognitica** [openvinotoolkit/openvino_notebooks#911]
I want to convert a custom model from FP32 to INT8. I referred the following link: https://docs.openvino.ai/2020.4/pot_README.html.

But the specified path to the "/deployment_tools/open_model_zoo/tools/accuracy_checker" and the "/deployment_tools/tools/post_training_optimization_toolkit" does not exist. There is a folder in the name of accuracy_checker and pot but those doesn't contain setup file to install. 

I also tried using DL workbench in which when I try to upload the dataset (annotated using roboflow) it is not showing. I tried in pascal voc and coco format but I'm unable to upload. 

Please suggest a way to convert. 

Details:
-- Openvino 2022.1
-- Ubuntu 20.04 

I'm using 2 models to attain inference and I want to improve the FPS so I want to try with INT8.

**Comment by eaidova** [comment]
@swe-cognitica documentation link which you provide correspond to openvino 2020.4 (released in 2020 year), a lot of new great features was delivered by openvino from time when it was published and the structure of the package also has changed.

Actual low-precision optimization guide can be found here: 
the latest release: https://docs.openvino.ai/latest/openvino_docs_model_optimization_guide.html
openvino 2022.1 (package what you use as I understand) https://docs.openvino.ai/2022.1/openvino_docs_model_optimization_guide.html

I also recommend trying the new NNCF Post Traning Optimization API as the most user-friendly way to get the int8 model with openvino (however, it will require to update openvino package to have 2022.3)
https://docs.openvino.ai/latest/nncf_ptq_introduction.html#doxid-nncf-ptq-introduction
You can also find tutorials for using both POT and NNCF quantization in this repository.

**Comment by swe-cognitica** [comment]
Thank you! In the link I mentioned I tried to change the version but it lead to Error page and its mentioned as "for version more than 2020". Is there any way to use the DL workbench as in "https://docs.openvino.ai/2021.3/workbench_docs_Workbench_DG_Int_8_Quantization.html"?

**Comment by eaidova** [comment]
@swe-cognitica please check this sample, it includes quantization tutorial  for Workbench https://docs.openvino.ai/latest/workbench_docs_Workbench_DG_Tutorial_Semantic_Segmentation.html

**Comment by swe-cognitica** [comment]
Thank you
