### ISSUE TITLE
Error on 230-yolov8-optimization with custom image size model

### ISSUE THREAD

**Issue by MattVAD** [openvinotoolkit/openvino_notebooks#921]
Hi @eaidova ! And big thanks for your work on the notebook, it's very useful !

In order to get more context, I trained using yolov8 repository a custom yolov8n model on 1 class with a modified image size at 416,416. 

I have already executed your notebook with a yolov8n custom model with traditional image size at 640,640 and it works fine !

This problem occurs on when i'm using the resize model. 
Here is what happening : 
when I tried to get the validation values using the command : 
`fp_det_stats = test(det_ov_model, core, tqdm(det_data_loader), det_validator) `

I get this runtime error : 
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/48956156/225399086-67068c67-c1a3-469c-9f32-872178720e75.png">

Have you any idea on how to resolve this ? 

Thanks in advance, 

Matthew

**Comment by eaidova** [comment]
@MattVAD do you made any modifications in the notebook according to your changes in dataset and input size?
I believe preprocessing code and dataset configuration should be adjusted by your usecase

**Comment by MattVAD** [comment]
Hi @eaidova, yes ! I used the get_cfg method from ultralytics repo and I updated the args.imgsz to 416. It's probably a dataloader problem that's not well resizing my data during the loading step.

**Comment by MattVAD** [comment]
Hello, it's solved now. The yolo dataloader forced the images to be in 640p. I just overwrite the default.yaml config file because it's called at every step of dataloading. thx @eaidova for your time !

**Comment by yash-khurana** [comment]
> Hello, it's solved now. The yolo dataloader forced the images to be in 640p. I just overwrite the default.yaml config file because it's called at every step of dataloading. thx @eaidova for your time !

Hello, I'm facing the same issue when doing it on imgsz=416. Can you elaborate on how you fixed it? Where did you make the change?
