### ISSUE TITLE
【PaddlePaddle Hackathon 4】RFC of Task 205 Portrait segmentation and Background replacement

### ISSUE THREAD

**Issue by unseenme** [openvinotoolkit/openvino_notebooks#932]
# RFC of PaddlePaddle Hackathon 4 Task 205

## Solution Name

Portrait segmentation and Background replacement

## Description

This notebook shows how to do Portrait segmentation and Background replacement with OpenVINO Runtime and PaddlePaddle model.

## Workflow

![workflow](https://user-images.githubusercontent.com/41909825/226219079-54d73500-4752-47d1-9d6f-153f2fd5b5ff.png)

## Models

 - portrait_pp_humansegv2_lite

This model is supported by OpenVINO.
The result of benchmark:

    ...
    [Step 11/11] Dumping statistics report
    [ INFO ] Count:            55304 iterations
    [ INFO ] Duration:         60008.95 ms
    [ INFO ] Latency:
    [ INFO ]    Median:        4.32 ms
    [ INFO ]    Average:       4.29 ms
    [ INFO ]    Min:           2.97 ms
    [ INFO ]    Max:           35.24 ms
    [ INFO ] Throughput:   921.60 FPS

## Results Visualizing

![input](https://user-images.githubusercontent.com/41909825/226219145-5105867f-c96c-428a-a595-6ebfc2110474.png)![bg_remove](https://user-images.githubusercontent.com/41909825/226219168-d9b363b2-ce3e-4c7f-afc8-8bec77d927d9.png)![bg_replace](https://user-images.githubusercontent.com/41909825/226219179-06a4d429-c727-4852-a166-fecdcc964743.png)

## Project Timeline

3/20 Submitting RFC
3/31 Creating PR
4/15 Merging PR

## My Experience in ML and DL

I'm a PPDE, and I completed three OpenVINO tasks in the first PaddlePaddle Hackathon:
Task 88 https://github.com/openvinotoolkit/openvino/issues/7615
Task 91 https://github.com/openvinotoolkit/openvino/issues/7612
Task 92 https://github.com/openvinotoolkit/openvino/issues/7611

**Comment by unseenme** [comment]
@zhuo-yoyowz Sorry in your busy schedule. Can this RFC document be passed?

**Comment by OpenVINO-dev-contest** [comment]
Sorry for late reply. From my perspective, I saw a current [notebook](https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/205-vision-background-removal) and your RFC are a little duplicated, could help to explain more about the difference between them. 

Meanwhile we still would like to collect more RFC by the deadline of submission, and then select 2 best one from them.

**Comment by zhuo-yoyowz** [comment]
Yes, I agree with @OpenVINO-dev-contest. New notebooks should be different in the specific use case scenario, DL frameworks, or showing significant improvement over current notebooks, etc. Thanks~
