### ISSUE TITLE
004-hello_detection can't work on the raspberry

### ISSUE THREAD

**Issue by pzchu** [openvinotoolkit/openvino_notebooks#951]
**Describe the bug**
Raspberry 4 B, OS:debian 11, this demo runs error.

**Screenshots**

**Traceback (most recent call last):
  File "/home/pi/Desktop/notebooks/004-hello-detection/helloDetection.py", line 9, in <module>
    compiled_model = ie.compile_model(model=model, device_name="CPU")
  File "/opt/intel/openvino_2022.3.0/python/python3.9/openvino/runtime/ie_api.py", line 399, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: Check 'get_output_size() == 1' failed at src/core/src/node.cpp:432:
While validating node 'v5::NonMaxSuppression 1411 (1385[0]:f32[1,2641,4], 1401[0]:f32[1,1,2641], 1411/Reshape_1D_2[0]:i64[1], 1411/Reshape_1D_3[0]:f32[1], 1411/Reshape_1D_4[0]:f32[1]) -> (i64[..100,3], f32[..100,3], i64[1])' with friendly_name '1411':
get_shape() must be called on a node with exactly one output**

**Comment by eaidova** [comment]
@pzchu  thank you that you let us know, it is expected behaviour, model contains layers that required dynamic shapes support. Currently, ARM-based cpu openvino plugin does not support dynamic shapes, so it is the reason why it does not work
