### ISSUE TITLE
[GSoC] Prerequisite task: An issue with the Model's source code (ESPNet)

### ISSUE THREAD

**Issue by Nouran-Muhammad** [openvinotoolkit/openvino_notebooks#958]
Hi, 
I have been working on ESPNet model. There is a problem with the authors code regarding loading models on GPU and openvino works on CPU and i need your opinion on what to do so that i can finish the task and make the pull request.
The code provided by the authors implements 2 versions of ESPNet as 2 **classes** in Model.py file:
1- ESPNet_encoder: encoder that outputs segmentation mask with dimensions 1/8 the original image, so the mask is upsampled
2- ESPNet: encoder+decoder where the decoder's output is the segmented mask with the image's original dimensions
 
I was supposed to work on both versions, run inference on them and convert them to openvino IR.
I imported the 2 classes in my notebook:     from Model import ESPNet, ESPNet_encoder

Then i wanted to make 2 models (instances) of the 2 classes:
ESPNet_encoder = ESPNet_encoder()   then load the pretrained weights for model
ESPNet = ESPNet() and here comes the problem

In ESPNet class, the encoder part is defined and the pretrained weights for it are loaded automatically using the line of code:
model.load_state_dict( torch.load(pretrained_weights) ),  this line forces pytorch to use GPU which can't be done in openvino environment. As a result, it gives error and i can't create the model and as far as i know, i shouldn't modify the this line in the Model.py file to put the parameter: map_location=torch.device('cpu'), right? And i tried many different tricks including environment variables to shut the use of GPU but nothing worked.

The net result is that i can't use the ESPNet version due to this problem. Do you have a solution for this? is it a must that my notebook works on both variants or can i work on ESPNet_encoder version only and my pull request can be accepted?
Thanks

**Comment by blaz-r** [comment]
Hello,
I'm not sure what exactly the issue is, but I think one way to work around this is to not specify path to encoder weights. If you check the code:
```python
if encoderFile != None:
    self.encoder.load_state_dict(torch.load(encoderFile))
    print('Encoder loaded!')
```
so maybe don't pass encoderFile, leave it as None, and then manually do 
```python
model.encoder.load_state_dict(torch.load(encoderFile, map_location=torch.device("cpu")))
```
Hope this helps.

**Comment by Nouran-Muhammad** [comment]
Hi, thank you for your reply.
I did try this 
`encoderFile = '../pretrained/encoder/espnet_p_2_q_3.pth'
model = ESPNet(p=2, q=3)
model.encoder.load_state_dict(torch.load(encoderFile, map_location=torch.device("cpu")))
model.load_state_dict(torch.load('../pretrained/decoder/espnet_p_2_q_3.pth', map_location=torch.device('cpu'))) # to load decoder pretrained weights`

and it worked well (all keys matched successfully) .
But when i try to export the model to onnx:
`dummy_input = torch.randn(1, 3, 512, 1024)
torch.onnx.export(
            model,
            dummy_input,
            f = 'model.onnx',
            verbose = True,
        )`
I get this error: TypeError: 'list' object is not callable
The export works well with the another version of the model (ESPNet_encoder), so that means there is still a problem with the model ESPNet but i can't get what is it.

**Comment by blaz-r** [comment]
Hello,
good to hear that fix worked. As for your new error, I cant really tell what the problem is from just that error, if you could please post a bit more of error printout.

**Comment by Nouran-Muhammad** [comment]
The error log is big, so i will post a screenshot for part of it and try to explain. If you still need the whole log, it is okay i will post it in 2 or 3 screenshots.
As you can see: model.modules has a problem, i think it doesn't see the model as a pytorch model but a list instead.


![image](https://user-images.githubusercontent.com/61350907/228206795-8d40acf5-b90a-4db6-bf35-e874638122dc.png)

**Comment by blaz-r** [comment]
I think the problem arises because inside ESPnet, they do `self.modules = []` and this overrides modules() function, because of the way python works.

I'm not sure how to fix this without changing name of this variable in source though.

**Comment by Nouran-Muhammad** [comment]
Exatly. That's my problem. Whatever fix I can find, I need to change something in the source and i am not supposed to do this. So, i don't know if i should drop that version and just work with ESPNet_encoder and if that is acceptable or do what?
