### ISSUE TITLE
【PaddlePaddle Hackathon 4】No.205 Notebook RFC -Make the photo move

### ISSUE THREAD

**Issue by ziyuanji** [openvinotoolkit/openvino_notebooks#967]
**Solution Name**
    Animation of generating smiling faces in photos
 **Description**
    Recently, there have been numerous AI applications emerging that are dazzling. Among them, the application of AI that makes old people "move" in old photos is particularly eye-catching, allowing the characters in old photos to perform any prescribed actions, helping people see photos of past loved ones from a new perspective~
    And among them, the PaddleGAN model is used to transfer the expression of character A in the video to the face of character B in the picture, completing the expression "smiley face"~to achieve "old friend laughing"

**Workflow**
![流程图](https://github.com/openvinotoolkit/openvino_notebooks/assets/125521589/8f9790e6-0944-4636-9c13-d13628635c42)

 **Models**
    PaddleGAN

**Results Visualizing **
![src](https://github.com/openvinotoolkit/openvino_notebooks/assets/125521589/5715f649-9276-47f9-a22e-09364d8667ed)
![tag](https://github.com/openvinotoolkit/openvino_notebooks/assets/125521589/d4055df4-677f-41d7-9321-5b130afcfd12)

**Project Timeline**
    3/31 Submitting RFC
    4/10 Creating PR
    4/30 Merging PR

**Comment by OpenVINO-dev-contest** [comment]
Hi @ziyuanji great thanks for your RFC, and it looks very interesting. Could you help to put more comments to explain more on the function or scenario of this use case ?  My understanding is it can change the type of people's hair, am I right ? does it have any further features ?
BTW, you should be very careful on using a sample picture of a real person, and we have to get permission before start with it.

**Comment by zhuo-yoyowz** [comment]
Also want to know more about this RFC. Is it only for changing hair style, or only on portrait? or can be extended to anything? 

Features involving human face does raise a lot of concerns in AI ethics, especially for portraits of celebrities. Should be careful on this.

**Comment by ziyuanji** [comment]
hello everyone! Have you noticed that many hair changing software nowadays can only cover the original hairstyle with a layer of hair, either changing the face or body, without the function of cutting the hair short or shaving the head? In real life, many people want to cut their hair short or shave their hair, but they are afraid that the effect of cutting it will be ugly, but if their hair is cut short or trimmed, it will not be able to grow back for a while and a half, and their hearts are very troubled, How good is it that deep learning can help solve their problems

**Comment by ziyuanji** [comment]
hello everyone! Have you noticed that many hair changing software nowadays can only cover the original hairstyle with a layer of hair, either changing the face or body, without the function of cutting the hair short or shaving the head? In real life, many people want to cut their hair short or shave their hair, but they are afraid that the effect of cutting it will be ugly, but if their hair is cut short or trimmed, it will not be able to grow back for a while and a half, and their hearts are very troubled, How good is it that deep learning can help solve their problems




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openvinotoolkit/openvino_notebooks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月31日(星期五) 中午12:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openvinotoolkit/openvino_notebooks] RFC of PaddlePaddle Hackathon 4 Task 205 (Issue #967)





 
Also want to know more about this RFC. Is it only for changing hair style, or only on portrait? or can be extended to anything?
 
Features involving human face does raise a lot of concerns in AI ethics, especially for portraits of celebrities. Should be careful on this.

**Comment by OpenVINO-dev-contest** [comment]
Hi @ziyuanji Can you clarify more on whats the inputs and outputs in this workflow, Does the inputs include some text prompt ? or just a raw image.

**Comment by ziyuanji** [comment]
The input is the original image (with hair), and the output image (without hair) after entering the model processing

**Comment by ziyuanji** [comment]
The input is the original image (with hair), and the output image (without hair) after entering the model processing




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openvinotoolkit/openvino_notebooks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月31日(星期五) 中午12:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openvinotoolkit/openvino_notebooks] RFC of PaddlePaddle Hackathon 4 Task 205 (Issue #967)





 
Also want to know more about this RFC. Is it only for changing hair style, or only on portrait? or can be extended to anything?
 
Features involving human face does raise a lot of concerns in AI ethics, especially for portraits of celebrities. Should be careful on this.

**Comment by ziyuanji** [comment]
hello everyone! Have you noticed that many hair changing software nowadays can only cover the original hairstyle with a layer of hair, either changing the face or body, without the function of cutting the hair short or shaving the head? In real life, many people want to cut their hair short or shave their hair, but they are afraid that the effect of cutting it will be ugly, but if their hair is cut short or trimmed, it will not be able to grow back for a while and a half, and their hearts are very troubled, How good is it that deep learning can help solve their problems




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openvinotoolkit/openvino_notebooks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月31日(星期五) 上午10:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openvinotoolkit/openvino_notebooks] RFC of PaddlePaddle Hackathon 4 Task 205 (Issue #967)





 
Hi @ziyuanji great thanks for your RFC, and it looks very interesting. Could you help to put more comments to explain more on the function or scenario of this use case ?  My understanding is it can change the type of people's hair, am I right ? does it have any further features ?
 BTW, you should be very careful on using a sample picture of a real person, and we have to get permission before start with it.

**Comment by ziyuanji** [comment]
Hello, OpenVINO dev content, zhuo yoyowz! How to improve RFC

**Comment by OpenVINO-dev-contest** [comment]
i dont think this topic is a typical and highly-demand use case for business, cuz it just remove the hair from your head. My suggestion is you can replace the topic of this RFC with a more common or interesting use case, for example generating an animation of smiling face from a photo.

**Comment by ziyuanji** [comment]
Ok, thank you OpenVINO dev content

**Comment by ziyuanji** [comment]
Hello OpenVINO dev content! Is this instance okay

**Comment by ziyuanji** [comment]
Hello @OpenVINO-dev-contest ! ! Is this instance okay

**Comment by OpenVINO-dev-contest** [comment]
Yes the result looks good to me, but you have to make sure these model can be deployed by openvino.
BTW, since your code have been merged by the end of May, I dont think we have enough time to include it in Paddle Hackathon's result.

**Comment by OpenVINO-dev-contest** [comment]
> Yes the result looks good to me, but you have to make sure these model can be deployed by openvino. BTW, since your code have been merged by the end of May, I dont think we have enough time to include it in Paddle Hackathon's result, but we still welcome to see your contribution.

**Comment by ziyuanji** [comment]
Ok, openvino has good performance. I must convert the model to onnx format to facilitate openvino deployment
